### ISSUE TITLE
Implement Page/Chapter Tracking

### ISSUE THREAD

**Issue by seniorm0ment** [bookwyrm-social/bookwyrm#1013]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to my knowledge to set where you are in the book, such as page number, or chapter. 
This would be beneficial as it could allow you to keep track of stuff you are reading better, however it also can play a role in the social aspect as it can allow users to better understand any reviews you give, in the cases you may not have completed a book.

This could also pair nicely with #963 

**Describe the solution you'd like**
Implement the ability to track page/chapter progress.
I also suggest adding re-read count ("User read this X times"). If they're re-reading they can just make a new shelf called "re-reading" or place it back in "currently reading", whichever they fancy.

**Comment by mouse-reeve** [comment]
Tracking your page/percent through the book is already a feature 🙂 . When you have started reading a book, you can update your progress, and you can indicate your progress in the book along with a comment. You can also add read dates from the book page, and add progress updates there.

From your suggested books panel:
<img width="408" alt="Screen Shot 2021-04-28 at 1 35 38 PM" src="https://user-images.githubusercontent.com/1807695/116469196-ab3c2000-a826-11eb-9916-52f17be45f48.png">

With a comment:
<img width="392" alt="Screen Shot 2021-04-28 at 1 34 24 PM" src="https://user-images.githubusercontent.com/1807695/116469215-b4c58800-a826-11eb-8f04-7b381554f6f8.png">

From the book page
<img width="961" alt="Screen Shot 2021-04-28 at 1 34 39 PM" src="https://user-images.githubusercontent.com/1807695/116469241-babb6900-a826-11eb-9922-05e31961b506.png">

**Comment by seniorm0ment** [comment]
Ok, been playing with it a little. It's a bit confusing the way it's setup, and nestled away it seems there are some issues with getting that page prompt to appear.

Firstly, I think It should offer the ability to input reading progress when you first start reading progress on a book. Currently it seems you have to start reading, enter the dates, click save, then click enter again to add the pages.
As for the issues I mention for getting it to appear:

**Issues**

- This seems to only apply to books if you have it under your "Currently reading" shelf? 
This is kinda restrictive in my opinion. If I want to have two different lists for "Currently reading" (for example slower reading stuff can be put in another shelf if the user wishes), it makes it impossible to only track one of those shelf.

- Another issue seems to be that if you have the book on the "Currently reading" shelf, as well as a custom shelf, it refuses to show the reading dialog. This seems like a big issue.
I'm assuming it's set on the back-end in a way that custom shelves are different than the 3 default shelves, as I notice I cannot rename the default shelves as well. So I assume this plays a role in this issue.

- It doesn't let you add page progress if you input no dates. This makes it not possible to add page progress for books you may have started quite some time ago, and not know the exact dates. Otherwise you have to set random dates, not ideal.

**Comment by seniorm0ment** [comment]
Would you like me to open a new issue for the issues I have presented above?

**Comment by mouse-reeve** [comment]
Yes. The last one is going to be a won't-fix for me, though -- I think page progress without dates is too far an edge case to support, since the confusion and potential for error it adds to the UI feels higher than the reward.

**Comment by seniorm0ment** [comment]
Will open them when I get a chance, thank you.

>since the confusion and potential for error it adds to the UI feels higher than the reward.

Could 00/00/0000 be offered as a selectable date, then just have it display "Unknown date" or something along those lines?
Imo it does kinda suck to add dates that aren't the actual dates when you started a book.

**Comment by Ryuno-Ki** [comment]
@seniorm0ment Could you link the issues if you came around to open them?

I'm looking into #963 shortly.
