### ISSUE TITLE
Set Started/Finished Dates As "Unknown" or "In The Past"

### ISSUE THREAD

**Issue by seniorm0ment** [bookwyrm-social/bookwyrm#1014]
**Is your feature request related to a problem? Please describe.**
For books users wish to add that they have read in the past, they may not know the dates they started if they have been reading for a while, or the started/finish dates if they have already read the book.

**Describe the solution you'd like**
Currently you can set nothing as a date, however under "your books" it shows a blank space.
Instead of showing a blank space, I think it should offer an option to set as "unknown" or "in the past" or something similar.

**Comment by mouse-reeve** [comment]
I'm not totally sure what your ask is here - is it that the table in the "Your books" view have filler text instead of blanks when the reading dates aren't set?

**Comment by seniorm0ment** [comment]
**Steps to produce**
1. Go add a book to "currently reading"
2. When the prompt shows "started reading", click the x to clear the date.
3. Upon clicking the x, the date shows `mm/dd/yyyy`
4. Go to https://bookwyrm.social/user/username/books
5. See blank spaces under Started and Finished (expected)

**My Suggestion**
At step 3, offer the ability to set dates as "unknown" or "started in the past" for books that people may have started in the past, but not know the dates. This would then appear as "unknown"/"started in the past" under the "Started and Finished" tables at step 5.

**Comment by mouse-reeve** [comment]
I think that adding the option to set why a book's read dates are unset is an unnecessary level of specificity which will make the UI and the data model more complex than it needs to be, without providing very much information to the user in return. If a book has been read, it can reasonably be assumed that it was read in the past, and if the date is unset, it can be reasonably assumed that the date is unknown (or not of sufficient interest to the user to enter).

**Comment by seniorm0ment** [comment]
Understandable.
Please note however, there are currently issues with the date system, causing issues with the page counter to not show up when the date fields are set empty-as referenced in #1013.
Thank you.
