### ISSUE TITLE
Reduce detail level of timestamp on posts

### ISSUE THREAD

**Issue by tofuwabohu** [bookwyrm-social/bookwyrm#1029]
**Is your feature request related to a problem? Please describe.**
I think the time when a post was posted is a tad too detailed. For posts in the last 24h, it changes every time you refresh.
![image](https://user-images.githubusercontent.com/66644064/116756620-b355b480-aa0c-11eb-98de-e77ec1c4b2f2.png)

**Describe the solution you'd like**
I think the firstmost unit would be enough.

Also, after a few days (I suggest 3), the date (Apr 28) rather than "2 weeks(, 4 days in the current version)" seems a bit more helpful. After 1 year, the date could be shown in "Apr 2021",

This is subjective of course, but imho Bookwyrm is a platform where the "when" doesn't really matter (in comparison to e.g. Mastodon where many are posting news and other stuff where the temporal context is more important). 

**Describe alternatives you've considered**
Hovering over the time could show the exact time as a tooltip. I think of this rather as an addition than an alternative and think both would complement each other.

**Comment by mouse-reeve** [comment]
super agree! I originally wrote an ultra-concise version of this based on Mastodon (which uses "23s" "17m" "3h" "5d" "Apr 12"), but I didn't think about internationalization at the time, so the quick fix was to sub in this built-in and already translated filter.

It would be very possible to update that old filter or write a new one that is translated, in whatever format makes the most sense.
