### ISSUE TITLE
Date pickers display incorrectly to screen readers

### ISSUE THREAD

**Issue by Flameborn** [bookwyrm-social/bookwyrm#1039]
When using a screen reader, such as VoiceOver under MacOS, the date pickers do not display as an editable spin control, but as a group when using the *tab* key.

When navigating via the arrow keys, the date displays as text, and there's no feedback when changing the value, either via *up/down* or by typing in a new value.

This can be seen when adding a new reading progress for a book.

Tested via VoiceOver/Safari, using b3e369cdba823413b81fec0b4f506a1909520a09

**Comment by mouse-reeve** [comment]
I'm using the html `date` input field (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) without anything else added to it, I'll have to figure out what the best practice here is 🤔
