### ISSUE TITLE
Finish date does not appear when adding a new reading progress for a book

### ISSUE THREAD

**Issue by Flameborn** [bookwyrm-social/bookwyrm#1040]
If there's an existing book with reading progress added, upon adding a new reading progress, only the start date is displayed, rather than the start/finish dates similarly to the previous, existing reading progress.

The added finish date seems to be saved though.

**Comment by mouse-reeve** [comment]
I'm trying to replicate this and I think I'm doing something differently than you are, can you step me through what you're seeing at each step in a little more detail (what page you're on, what data is saved, and what data is displaying)?

**Comment by Flameborn** [comment]
I've imported a book from Goodreads which had an existing reading progress.

On the book's page, I've clicked on the *Add read dates* button, and filled in the start/finish dates.

After clicking save, I am not seeing the finish date for the newly added progress, only the start date is displayed.

The book can be found here: https://bookwyrm.tardis.pw/book/876

**Comment by mouse-reeve** [comment]
Reading progress is only visible to the user, so here's a screenshot of what I'm doing to try to replicate this:

After clicking "Add read dates":
<img width="707" alt="Screen Shot 2021-05-02 at 8 42 39 AM" src="https://user-images.githubusercontent.com/1807695/116818887-754ab480-ab22-11eb-8873-18cad430cb63.png">

Entering dates:
<img width="713" alt="Screen Shot 2021-05-02 at 8 42 54 AM" src="https://user-images.githubusercontent.com/1807695/116818917-9ad7be00-ab22-11eb-9943-edbadb3ede9f.png">

After saving:
<img width="708" alt="Screen Shot 2021-05-02 at 8 43 03 AM" src="https://user-images.githubusercontent.com/1807695/116818935-ac20ca80-ab22-11eb-8196-14baa1aff49c.png">

Do these steps look the same as what you're doing?

**Comment by Flameborn** [comment]
Yes, these are the steps I use to reproduce as well.

I've just examined how the date picker works and what values it sends exactly, and it seems that if the delete key is pressed in Safari or in Brave, Brave sends a negative value, while Safari does the same, but it conveys the current date to VoiceOver.

This is exactly what's happening here, in my BW database, the finish date is empty, this is why it is not showing up via the UI, but this was not the value that VoiceOver announces, even when editing those dates.

I am closing this, as this is clearly a browser specific issue with its date picker. I'm very sorry about the confusion.

One positive aspect is that now we can leave the finish date empty, in case of a reread.
