### ISSUE TITLE
First published date cannot be empty

### ISSUE THREAD

**Issue by Flameborn** [bookwyrm-social/bookwyrm#1042]
When adding/editing a book, the *First Published* field is always filled in. This is mainly because when values via the new date picker are erased, the current year/month/day gets selected instead. This is great, for example, when adding a new reading progress, however, in this case it is making it impossible to leave this field empty.

**Comment by mouse-reeve** [comment]
This sounds like browser-specific handling from the date tag - I think this will have the same fix as #1039, getting a different system in place for date fields.

**Comment by Flameborn** [comment]
As I found out via https://github.com/bookwyrm-social/bookwyrm/issues/1040, the date field is in fact empty, but it misleadingly shows up incorrectly via VoiceOver in Safari as the current date. In practice, the field remains empty.
