### ISSUE TITLE
Add load from cover URL feature to the new book creation page

### ISSUE THREAD

**Issue by Flameborn** [bookwyrm-social/bookwyrm#1043]
Currently, when creating a new book, covers can be only uploaded. Later on, when a book is edited, or the *Add Cover* button is used on a book's page, a cover can be loaded from a URL as well.

It would be amazing if one could specify a cover URL straight away when creating a book, so no extra editing step would be necessary.

**Comment by joachimesque** [comment]
@mouse-reeve I think this feature is now implemented. Should this issue be closed?

**Comment by mouse-reeve** [comment]
Yes!
