### ISSUE TITLE
Signup without e-mail

### ISSUE THREAD

**Issue by TomasEkeli** [bookwyrm-social/bookwyrm#1054]
**Is your feature request related to a problem? Please describe.**
i do not like giving away my e-mail address to sites on the internet, and services that do not actually need it should not gather such personal information. 

**Describe the solution you'd like**
i would like to be able to start using bookwyrm without giving away my e-mail address, and only add it later if needed. maybe i want to give a different kind of address instead (like a mastodon account or something) later instead of e-mail.

**Describe alternatives you've considered**
i could have made a transient e-mail address

**Additional context**
unverified accounts could be "sandboxed" away from the instance's verified accounts to combat spurious account registrations and spam.

**Comment by mouse-reeve** [comment]
Hi! Thanks for raising this -- in all honestly it's probably not something I'll do, but hopefully I can explain a little bit of context for why.

At the moment, there are a few reasons that it's important to have an email associated with an account: it helps prevent spam, it's how invites are distributed, and some features in the application (password reset) rely on the user having a working email address. It would be impractical, at least with the development capacity currently, to support services besides email acting as account verifications.

It's possible that a system could be put in place where for an instance, email is made optional and the admins manually verify accounts, but a feature like that would, realistically, be a long ways away on the roadmap.
