### ISSUE TITLE
Additional data fields for author

### ISSUE THREAD

**Issue by cats-shadow** [bookwyrm-social/bookwyrm#1057]
It would be nice if authors had "pseudonym" or "AKA" fields.
This would allow you to find works by the same author written under different pseudonyms.

**Comment by mouse-reeve** [comment]
Yes! This field exists in the database but not in the UI. I think it would be straightforward and useful to display it and make it editable, and include it in the fields that search looks at

**Comment by cats-shadow** [comment]
> I think it would be straightforward and useful to display it and make it editable, and include it in the fields that search looks at.

It would be the best solution!
