### ISSUE TITLE
Clarify language of editions and works

### ISSUE THREAD

**Issue by cats-shadow** [bookwyrm-social/bookwyrm#1059]
Depending on the translation (or even the edition), some works may be called differently while still being the same.
So can the same work in different languages.
It would be nice to have a field "title in the original language" as well as additional fields for other title variants.
This would avoid duplication.
It would also be nice to have "original language", "language of this variant" fields when specifying an additional variant title.

**Comment by mouse-reeve** [comment]
Agreed! Some of this data may already be available, it's just not being displayed.

**Comment by mouse-reeve** [comment]
I'm going through and closing old issues that seem stale or out of date - feel free to reopen with a comment adding some updated context if you feel like it still needs to be addressed ❤️
