### ISSUE TITLE
Book information fields

### ISSUE THREAD

**Issue by cats-shadow** [bookwyrm-social/bookwyrm#1077]
There is a suggestion to convert some fields of information about the book from a text field to selectable from a list.
For example, it would be convenient in the "format" field (Physical Properties).
This would avoid accidental typos, because there aren't many book formats. In any case, new formats can always be added.

The "Series" and "Publisher" fields should be checked for uniqueness, just like the "Authors" and "Title" fields. Again, this is to avoid accidental typos.

**Comment by cats-shadow** [comment]
>We would lose some nuance - mass market paperback vs trade paperback, audio CD vs audio cassette

Why lose the nuances?
You can always enter extra lines for Audio CD, Audio cassette, vinyl record, can't you?
Just like for mass market paperback and trade paperback.

**Comment by cats-shadow** [comment]
![2021-05-11_23-59-52](https://user-images.githubusercontent.com/16667173/117884754-b034b100-b2b5-11eb-9f29-adc93460764a.png)

**Comment by cats-shadow** [comment]
Additional question.
How to fill fields, selected by arrows on screenshot manually?
![2021-05-11_23-59-52](https://user-images.githubusercontent.com/16667173/117884879-cf334300-b2b5-11eb-9a2d-68a5f6f239b0.png)

**Comment by mouse-reeve** [comment]
Right now, they aren't editable. The ticket tracking that is #740
