### ISSUE TITLE
The license is not open-source as the page footer claims

### ISSUE THREAD

**Issue by Minoru** [bookwyrm-social/bookwyrm#1083]
**Describe the bug**
At the bottom of every page there is [a sentence saying](https://github.com/bookwyrm-social/bookwyrm/blob/e011fe6f88c207a20207da650b121f74fb6a9dfe/bookwyrm/templates/layout.html#L217) that "BookWyrm is open source software". However, Clause 2 of BookWyrm's license withholds permissions from e.g. for-profit organizations. This violates Clauses 5 and 6 of [The Open Source Definition](https://opensource.org/osd), which say:

> ### 5. No Discrimination Against Persons or Groups
>
> The license must not discriminate against any person or group of persons.
>
> ### 6. No Discrimination Against Fields of Endeavor
>
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

**Expected behavior**
I see the intent behind BookWyrm's license, and I don't think it can be reconciled with OSD. I think BookWyrm's HTML template should stop saying that the software is open source.

**Additional context**
I am truly sorry to be "that guy", but I like BookWyrm's idea and I like open source, so I feel that this stuff *has* to be sorted out.

**Comment by mouse-reeve** [comment]
Good catch, thanks!
