### ISSUE TITLE
Not clear what the license means by "an individual person, laboring for themselves"

### ISSUE THREAD

**Issue by Minoru** [bookwyrm-social/bookwyrm#1084]
**Describe the bug**
BookWyrm's license uses this set of words which I can't quite understand: "laboring for themselves". I looked it up, but it doesn't seem to be a legal term or anything well-defined. Specifically, it's not clear to me if this wording includes:

1. a self-employed person (I guess it does)
2. a person who coasts on their savings (I guess it doesn't, since the person is currently not labouring for anyone I guess?)
3. a person who is earning their living by working for someone else (I guess it doesn't: even though the person gets their income via their labour, they also enrich their boss, meaning they don't labour for *just* themselves — this strays a bit off the wording the license uses, but seem to be in line with its general intent)
4. a person who gets their income from investments like shares, or from renting their property like flats and cars (I guess it doesn't, because the income is derived from what the person already owns, not the labour of finding renters)

I understand that "asking the author" is not the correct way to shake out legal imperfections, but I just want to get your view on this because I can't abide by the license I don't understand.

**Additional context**
I'm not a native English speaker, but the tests I did about five years ago put me into Upper-Intermediate category, so I doubt my lack of understanding is caused by a language barrier.

**Comment by mouse-reeve** [comment]
Hi! My view is that this definitely includes a self-employed person, and it isn't related to other, outside sources of wealth or income such as someone's unrelated day job, inheritance, etc. So, for example, someone who works for a corporation is not forbidden or discouraged from running a bookwyrm instance for their friends in their free time, but they cannot run a bookwyrm instance owned by the corporation they work for as part of their job.

Does that answer your question?

**Comment by Minoru** [comment]
Ah, so the license is not conditioned on who the User *is* (e.g. an individual/not-for-profit/cooperative), it's conditioned on the *context* in which the licensed permissions are used (e.g. as an individual/as part of not-for-profit work/as part of paid job when working for a cooperative). The current text does not convey this nuance to me at all, with phrasing like "if the User is an organization with owners".

This does answer my question, but I hope the wording will be improved somehow to make all this clearer from the license itself. I'm sorry I don't have specific suggestions here; it feels like the last three clauses will have to be rewritten to talk about context rather than the user's affiliation, and I'm not up for that.

Thanks for the explanation!
