### ISSUE TITLE
Redis Broker Unreachable if Password Contains Characters That Need URL Encoding

### ISSUE THREAD

**Issue by bcj** [bookwyrm-social/bookwyrm#1098]
**Describe the bug**
The `CELERY_BROKER` and `CELERY_RESULT_BACKEND` environment variables use the redis broker password without urlencoding it, so any unsafe characters will result in the broker being unreachable (and may erroneously be listed as IPv6 errors by flower)

**To Reproduce**
1. set the redis broker password to something including a `:`
2. attempt to create a new server using the production instructions
3. See errors when running `./bw-dev up`

**Expected behavior**
No errors occur and everything works as accepted (or: note in .env.prd.example that the password needs to only use `[A-Za-z0-9~._-]`.

**Screenshots**

**Desktop (please complete the following information):**
    - OS: macOS Big Sur
    - Browser N/A
    - Version `production`

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bcj** [comment]
sorry for the slightly rushed issue info.
I can tackle this later this week, In all the python code it should be easy to construct the URL manually and safely from port and password, need to check on how it will be easiest on the flower service

**Comment by tofuwabohu** [comment]
This is probably related: When the smtp password contains such characters and is not set in `""`, `bw-dev update` will fail. However, when the passwort is set in `""`, emails can't be sent. Currently I switch this back and forth at every update and it's not too bad, but it may be the same thing?
