### ISSUE TITLE
Remove user information from "Yours books" page

### ISSUE THREAD

**Issue by cats-shadow** [bookwyrm-social/bookwyrm#1099]
The "yours books" page displays the same userinfo just like the user profile. But the user already knows everything about himself (he filled out a profile). :) 
As a result, to access their "shelves" every time you have to scroll down the page, which is inconvenient. 
In the screenshot the information that is offered to be removed is framed.

![2021-05-19_17-24-12](https://user-images.githubusercontent.com/16667173/118830035-4e80d200-b8c7-11eb-805a-36447a15db4b.png)

**Comment by mouse-reeve** [comment]
Ah yeah, this really makes a big difference for people with long profiles. I think there does need to be a clear indication of who's books page is being shown, since this same view is used to show any users' shelves, not just your own. But it certainly doesn't need to be the entire profile and bio!

**Comment by cats-shadow** [comment]
Perhaps it makes sense to show this in the header?
I mean, instead of "Yours books", in my example, a link to the user's profile "<a href='https://books.cats-home.net/user/cats-shadow'>Michael [Кошак] Skolsky</a> books", that would save space without losing information.

**Comment by shilpeePrasad** [comment]
Hi, I would like to work on this issue. Thanks

**Comment by mouse-reeve** [comment]
Go for it @shilpeePrasad 😊

**Comment by shilpeePrasad** [comment]
> Go for it @shilpeePrasad 😊

Hi could you please let me know the file that I should refer for removing the bio.

**Comment by mouse-reeve** [comment]
This is the template for the shelf page: https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/templates/user/shelf/shelf.html

It uses a user page layout (https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/templates/user/layout.html#L23), which contains the bio. Since a number of pages where it does make sense to show the bio all use that template, it might make sense to use the base template (https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/templates/layout.html) for the shelf page instead.

**Comment by shilpeePrasad** [comment]
> This is the template for the shelf page: https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/templates/user/shelf/shelf.html
> 
> It uses a user page layout (https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/templates/user/layout.html#L23), which contains the bio. Since a number of pages where it does make sense to show the bio all use that template, it might make sense to use the base template (https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/templates/layout.html) for the shelf page instead.

Thanks !

**Comment by shilpeePrasad** [comment]
Hi, could you please provide list of books available in the database or way to get the list of books. Thanks

**Comment by mouse-reeve** [comment]
If you're in the python shell (`./bw-dev shell` if you're running the app with docker) you can execute database commands using the Django queryset syntax (https://docs.djangoproject.com/en/3.2/ref/models/querysets/). To get all books (both works and editions) in the database, you can run:

```python
from bookwyrm import models
models.Book.objects.all()
```

Or to get just editions, `models.Edition.objects.all()`

**Comment by shilpeePrasad** [comment]
Hi, I have executed above code but its giving output as <InheritanceQuerySet []> and not list of books. could you please help.
Following is the code executed.
>>> from bookwyrm import models
>>> models.Book.objects.all()
<InheritanceQuerySet []>

**Comment by mouse-reeve** [comment]
it looks like there might not be books on your instance? When a new instance is created, there isn't any data present, so you'll have to search for a book and import it for there do be books in your instance.

**Comment by binyamin** [comment]
@mouse-reeve I know @shilpeePrasad already opened a PR for this, but I have another suggestion. My bio is not long at all, and I'd expect it to be there, if the rest of my profile info is there. How about adding a "read-more" button for text which is too long? Or, use [the details element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details).

![profile picture with long bio, but part of bio is hidden](https://user-images.githubusercontent.com/39805353/123022648-1546f080-d3a4-11eb-9a0f-269f02ce184e.png)

**Comment by mouse-reeve** [comment]
I was envisioning removing the user info entirely:
<img width="1201" alt="Screen Shot 2021-06-27 at 4 43 01 PM" src="https://user-images.githubusercontent.com/1807695/123562983-d8457a00-d766-11eb-88f8-9091dcdfc50b.png">

So not just removing the bio.

**Comment by mouse-reeve** [comment]
Fixed
