### ISSUE TITLE
Dates are not pre-selected on editing announcements

### ISSUE THREAD

**Issue by tofuwabohu** [bookwyrm-social/bookwyrm#1117]
**Describe the bug**
When I edit an existing announcement, the datpickers don't use the formerly defined dates but default back to `mm / dd / yyyy`

**To Reproduce**
1. Create and save an announcement with set dates
2. Edit the existing announcement

The new feature is great, thanks! :)

**Comment by mouse-reeve** [comment]
I had the same realization: #1115 :)
