### ISSUE TITLE
Implement Username Change Ability

### ISSUE THREAD

**Issue by seniorm0ment** [bookwyrm-social/bookwyrm#1124]
**Is your feature request related to a problem? Please describe.**
The inability to change usernames.

**Describe the solution you'd like**
The ability to change usernames.

**Describe alternatives you've considered**
Changing display name is possible, however the username is not. This is not ideal.

**Additional context**
The ability to change the username would be an appreciated feature if possible. There are many reasons for this, but from a privacy perspective, if someone uses a username that may be identifiable to them, or isn't at the time of creation but may become identifiable to them, they have the ability to change their username to help attempt negate that if they wish. While there may be other identifiable factors of course, it is always nice to have the option to change the username.
There are also other reasons a user may want to change his username which should be reasonably obvious.

This would be an appreciated feature. Otherwise the user would have to export their profile, create a new account, and delete their old account, just to get a new username. This is both tedious, and the ability to change the username would solve this.

**Comment by mouse-reeve** [comment]
I agree that this would be a helpful feature, but the reason I haven't added it is for compatibility with Mastodon. From what I've read, it doesn't sound like there's any plans to change how this works on Mastodon, unfortunately, so for now, migrating accounts will have to be the feature that accomplishes this. 

Sorry not to have a more helpful response!
