### ISSUE TITLE
Inventaire integration

### ISSUE THREAD

**Issue by xplosionmind** [bookwyrm-social/bookwyrm#1128]
**Is your feature request related to a problem? Please describe.**
It would be great if a user could:
- directly import data from their own Inventaire account
- synchronise the the books added to Inventaire and vice-versa
- Linking the same individual’s Bookwyrm and Inventaire profiles so that, until the features in #1127 are implemented, a user could make use on Inventaire of the features missing on Bookwyrm.

**Describe the solution you'd like**
Doing all of the above via the GUI without having to download, tweak in order to maximize compatibility and then re-upload exported data.

**Describe alternatives you've considered**
Doing all of the above manually.

**Additional context**
none

**Comment by mouse-reeve** [comment]
Depending on how/if Inventaire implements ActivityPub, interoperability may also been an alternative path to syncing accounts (https://github.com/inventaire/inventaire/issues/187)
