### ISSUE TITLE
Started/finished reading: use “yes” or “no”

### ISSUE THREAD

**Issue by xplosionmind** [bookwyrm-social/bookwyrm#1129]
**Is your feature request related to a problem? Please describe.**
It is not.

<br>

**Describe the solution you'd like**
As of right now, only a date could be entered to mark when a user started or finished reading a specific book.  Nevertheless, I could be reading the endless [*Count of Monte Cristo*](https://openlibrary.org/works/OL15197048W/Le_comte_de_Monte-Cristo 'Count of Monte Cristo on Open Library') for so long that I do not remember the date when I started it. At the same time, I may have read [*The Little Prince*](https://openlibrary.org/works/OL10264W/Le_petit_prince 'Le petit prince on Wikipedia') when I was little, and naturally I cannot remember the date of when I finished it.

Hence, it would be great if it could be logged not a date but a `true` or `false` statement regarding the `started reading` and `finished reading` parameters.

<br>

**Describe alternatives you've considered**
Using a symbolic date for dates I do not remember.

<br>

**Additional context**
none.

**Comment by Flameborn** [comment]
Currently, a book can be moved to your *read* self, indicating that a book is read.

The start/finish dates can be, I believe, optional.

Thus, to achieve what you've given as an example case, you can move both books to your *read* self, and leave the start/finish dates blank respectively, in case you don't remember them.

**Comment by mouse-reeve** [comment]
Yep, the start and finished dates are optional - a book will be presented as "read" if you have it on your read shelf.

**Comment by xplosionmind** [comment]
I am sorry. My bad, I missed the "read" shelf option.

Nevertheless, I think the issue is still relevant for what concerns books which I started a looooong time ago and I never finished.

**Comment by Flameborn** [comment]
This is why start/finish read dates are optional ☺️

Specify a start or a read date (or both if you know them), move your book to your *read* shelf, and you are all good. The book will have a read status, and optionally a start/finish date which you specified.

If you are still reading a book, add it to your *currently reading* shelf, so you can mark it as finished later. At that point, simply don't specify the start date, when asked.

**Comment by xplosionmind** [comment]
Thank you very much
