### ISSUE TITLE
Remote Follow on Profile Pages

### ISSUE THREAD

**Issue by TomatDividedBy0** [bookwyrm-social/bookwyrm#1139]
Remote follow is one of the advantages of the Fediverse, and a button to remote follow a profile for both logged-in and logged-out profiles would make it easier for people to realize they can follow an account from Mastodon/Pleroma/wherever without necessarily needing to create a Bookwyrm account.

**Comment by hughrun** [comment]
I'm working on a PR for this. Stay tuned.

**Comment by hughrun** [comment]
Okey dokey, **seeking feedback on #1635.** I still need to do a little bit of cleanup and testing but it's close to complete and proven to work, at least with Mastodon. This should work with any other ActivityPub service that uses the ostatus 'subscribe' protocol. That definitely includes Mastodon and Pleroma, not sure if any others do the same.

**Follow a bookwyrm user from remote server**

1. Click new button on user profile page, regardless of whether or not you are logged in. Happy to adjust this button including the wording.

![follow_button](https://user-images.githubusercontent.com/17669239/143765372-cf40ad38-60db-48de-b2e3-c06419c937d7.png)

2. a new window pops up (non-javascript fallback will own in new window/tab - happy to receive advice on the most accessible way to indicate that this happens in a new window). Enter the handle you wish to follow from.

![follow_form](https://user-images.githubusercontent.com/17669239/143765385-e67573c6-20f1-4f97-a1e4-dda6c80188e4.png)
 
3. User is redirected to their "home" server to complete the follow activity using their own ostatus subscribe template

![redirect_mastodon](https://user-images.githubusercontent.com/17669239/143765464-6b9cb226-07af-42fa-a291-171be95773db.png)

4. Follow completed

![proof](https://user-images.githubusercontent.com/17669239/143765562-85e2d062-9a3d-48cf-932f-255227b127a6.png)

 **Follow remote user from bookwyrm account**

1. Click on follow button on Mastodon whilst logged out, window pops up asking for remote user handle.

![follow_masto_from_bookwyrm](https://user-images.githubusercontent.com/17669239/143765517-fb9db0fd-5ce1-4d3c-8654-fcf400d9edd3.png)

2. User is redirected to Bookwyrm ostatus subscribe template to complete follow

![redirect_to_bookwyrm](https://user-images.githubusercontent.com/17669239/143765544-ebfe60c8-0402-458f-943d-af77b1212f49.png)

3. Once we reach this point it's just a normal Bookwyrm follow, and the user is presented with a success page (still WIP to get it to look right, but functionality is fine).

**Comment by mouse-reeve** [comment]
Fixed by #1635
