### ISSUE TITLE
Maintain the Privacy Setting when switching between Review/Comment/Quote Panes

### ISSUE THREAD

**Issue by bcj** [bookwyrm-social/bookwyrm#1140]
**Is your feature request related to a problem? Please describe.**
Sometimes I switch the privacy settings of a post before remembering to switch from `Review` to `Comment`/`Quote` when making a post.
Because I've already set the privacy, I don't think to check it before hitting post.
At which point I've made a post public even though I'd really like all of my posts to be private.

**Describe the solution you'd like**
When switching between post types, common settings (CW, post privacy) should persist across types.

I guess this might require moving the CW input to have it persist but I also think having the input appear below the quote input in the `Quote` pane makes it unclear whether the entire post will be CWed or just your comment.

**Describe alternatives you've considered**
would be less of a problem if #253 gets solved because the inputs would already be set to my default privacy

**Additional context**

**Comment by mouse-reeve** [comment]
I'm marking this as closed by #1248 but feel free to reopen if it needs additional attention
