### ISSUE TITLE
"discover" page

### ISSUE THREAD

**Issue by binyamin** [bookwyrm-social/bookwyrm#1144]
> Lists feel more social to me than "Your Books" because lists are about the curation of books by people in your network, and I envision it having more interactivity in the future. (@mouse-reeve, https://github.com/bookwyrm-social/bookwyrm/pull/1070#issuecomment-846582779)

How about an "explore" or "discover" page? Besides for people's lists, it might display various popular books along with a couple comments and ratings. I specifically chose a vague name for this page, since that would provide plenty of room for adding stuff. Opportunity to expand.

**Comment by mouse-reeve** [comment]
Yeah, I think there's a lot of potential cool stuff with this! There technically is a discover page (https://bookwyrm.social/discover) which displays recently-reviewed books, but obviously it's very limited and it isn't shown anywhere except as the landing page for logged out users.
