### ISSUE TITLE
Define Workflow for locales and naming strings

### ISSUE THREAD

**Issue by arkhi** [bookwyrm-social/bookwyrm#1149]
> > ? Another thing that can be part of this PR: _Ouverte_ should be _Ouvrir_ on [line 1370](https://github.com/bookwyrm-social/bookwyrm/blob/c7b59f8653e93b23d1e5c13aba03a2644308e6d2/locale/fr_FR/LC_MESSAGES/django.po#L1370).
> 
> There's a problem for these. "Open" can be a verb or a state, and is used as both in the app, with only one translation key. What's the best way to handle it?
> 
> ### "Open" as a state, « Ouverte »
> 
> ![image](https://user-images.githubusercontent.com/1781070/119673406-9eb5e200-be3b-11eb-9ac5-8cdbeb7685cd.png)
> 
> ### "Open" as an action, should be « Ouvrir »
> 
> ![image](https://user-images.githubusercontent.com/1781070/119673818-fa806b00-be3b-11eb-9847-4911f488ab70.png)
> 
> _Originally posted by @joachimesque in https://github.com/bookwyrm-social/bookwyrm/issues/1125#issuecomment-848797849_

In some cases, making sure i18n strings are not ambiguous might be helfpful.

One way to help would be to use strings like `action_read` and `status_read`, for example.

Anybody has a better option?

**Comment by mouse-reeve** [comment]
This is a good idea - I think it will help keep display consistency as well (using the same terminology and capitalization across the app, for example).

**Comment by mouse-reeve** [comment]
I did some investigation and using context markers in the `trans` tags seems to be the best way to do this. If there are particular items that need context, flag 'em in crowdin <3
