### ISSUE TITLE
Long titles do not fit in the "Want to read" box

### ISSUE THREAD

**Issue by LongJohn-Silver** [bookwyrm-social/bookwyrm#1150]
**Describe the bug**
When the title of a book is too long, and you add it to your "To read" shelf, it doesn't show entirely.

**To Reproduce**
1. Go to a book with a long title.
2. Click on "To read" button.
3. Wait for  the box/dialog to appear.
4. See error.

**Expected behavior**
The title should fit perfectly within the box, maybe showing it as two lines would work?

**Screenshots**
![image](https://user-images.githubusercontent.com/63723030/119751861-76ee6a80-be8b-11eb-9e9c-931f759abf3b.png)

**Desktop (please complete the following information):**
    - OS: Irrelevant.
    - Browser: Firefox Nightly
    - Version: 90.0a1

**Smartphone (please complete the following information):**
    - Device: N/A
    - OS: N/A
    - Browser: N/A
    - Version: N/A

**Additional context**
N/A

**Comment by mariusz79** [comment]
Setting flex-shrink to unset in modal-card-title class could fix the bug.
![Untitled](https://user-images.githubusercontent.com/39931044/120086312-3898bb80-c0d6-11eb-8fe0-20b4e5917c54.png)
