### ISSUE TITLE
Querying Book Data From Remote Catalogues Causes Slowdown

### ISSUE THREAD

**Issue by TomatDividedBy0** [bookwyrm-social/bookwyrm#1151]
Currently, requesting book data from remote catalogues (a rather common occurrence considering the size of the local library) causes the site to grind to a halt for all users, especially when done multiple times in a row. Seeing as new users would want to add all their books at once, this isn't that rare of an issue.

On the issue, @mouse-reeve had the following to say:
> oh shoot I've been meaning to fix that. The problem is that as your instance federates, it adds more and more search endpoints, and ends up making more and more http requests every time there's a search. If one of the other instances is slow to respond, the whole thing waits on that. A temporary fix is to go into the connectors admin panel (/admin/bookwyrm/connector/) and unchecked the option for all the connectors besides openlibrary and inventaire
you'll still be sharing data with other servers, just not querying them for search

**Comment by TomatDividedBy0** [comment]
Some of the potential solutions that I came up with off the top of my head are:

- Having a time limit on the request itself, in which it would stop if waiting for the endpoints takes too long. It'd probably work short-term but I'd imagine this wouldn't solve the issue of the amount of requests scaling exponentially with the network.
- Splitting up the buttons as one for querying Inventaire/OpenLibrary and one for other instances, since most people use the button to access the former. It'd help but I imagine it'd lead users to neglect the other instances' data which kind of defeats the purpose of federation. 
- Maybe some sort of instance following system so instance admins can decide which other instances to query data from? Would require instance administrators to take the initiative though and would probably be a lot of work to implement.

**Comment by mouse-reeve** [comment]
> * Maybe some sort of instance following system so instance admins can decide which other instances to query data from? Would require instance administrators to take the initiative though and would probably be a lot of work to implement.

This does currently exist (/admin/bookwyrm/connector/), but it's a hassle to use - it's a temporary fix right now, but not _the_ solution

**Comment by mouse-reeve** [comment]
The solution I'm leaning towards is to have only inventaire, openlibrary, and bookwyrm search by default, and let admins optionally enable search to other instances. So new instances wouldn't be automatically added as search connectors, which is what's causing this problem.

To be clear, books will still federate between instances when users' posts reach other instances, so it wouldn't cut off federation overall. I do agree that it makes less use of the neatness of federating book data, though!

**Comment by TomatDividedBy0** [comment]
Could we possibly have it as a setting during the instance setup, maybe with a disclaimer regarding network speeds? I think that would strike a good balance,
