### ISSUE TITLE
Alternative installation guide

### ISSUE THREAD

**Issue by Amolith** [bookwyrm-social/bookwyrm#1156]
## Is your feature request related to a problem? Please describe.
I run all of my applications and services inside [LXC](https://linuxcontainers.org/). At the moment, the only supported installation method for BookWyrm is through Docker. With my architecture, this would require installing the whole Docker stack in a container in order to run a single Docker container inside the first container. In my opinion, this is incredibly inefficient; it would be better to provide a "manual" or "advanced" installation guide that describes the setup process for individuals like myself with different architectural needs.

## Describe the solution you'd like
I would simply like documentation that guides potential hosts through the process of setting BookWyrm up without relying solely on Docker. I would be more than happy to write and maintain such documentation as well as support individuals who installed BookWyrm by following it. If this is a welcome contribution, I would also ask that future release notes describe architectural changes made to the Docker-related files so that "manual" hosts can see updates via RSS and easily modify their setup accordingly.

## Describe alternatives you've considered
It's certainly possible to dissect the Docker(-compose) files and manually get a functional stack set up but dissecting those files and working out the architectural differences between them for every release and then applying those changes locally would make upgrades prohibitively time-consuming and difficult.

**Comment by mouse-reeve** [comment]
This would be a super welcome contribution! I know you're not alone in wanting to run the system without Docker. You're also welcome to join the matrix chat (https://app.element.io/#/room/#bookwyrm:matrix.org), which is handy for quick questions

**Comment by Amolith** [comment]
\o/

Should be able to start working on it sometime tomorrow morning/afternoon. Once I have an instance set up on [nixnet.services](https://nixnet.services), I'll be adding it to the public list as well :ok_hand:

**Comment by WesleyAC** [comment]
Closing, since this was completed in https://github.com/bookwyrm-social/documentation/pull/77

[Docs for Dockerless installation](https://docs.joinbookwyrm.com/install-prod-dockerless.html)
