### ISSUE TITLE
The pop up window when adding a book to the 'to-read' list wouldn't go away

### ISSUE THREAD

**Issue by oragegu** [bookwyrm-social/bookwyrm#1178]
**Describe the bug**
After ./bw-dev update, when loading the book from other catalogues and adding the book to the to-read list. 

It is worth noting that when clicking on the 'I want to read' button, the generated link has a question mark at the end.
From "website.com/book/1461", it becomes: "website.com/reading-status/want/1461?"

**To Reproduce**
1. Update with the command "./bw-dev update"
2. Go and search for a book that doesn't exist in the current catalogue
3. Load the book from other catalogues and add it to the local catalogue
4. At this stage one should be landed at something like "website.com/book/1461"
5. Click on the "I want to read" and the link becomes "website.com/reading-status/want/1461?".
6. Click on the green botton 'I want to read', but the pop up doesn't go away. One is stuck.
![image](https://user-images.githubusercontent.com/78921858/121981100-6431cc00-cd8d-11eb-86c6-33886610866d.png)

**Expected behavior**
After clicking on the 'I want to read' botton, the pop up should go away, and one is landed on the bookwyrm instance timeline stream.

**Comment by mouse-reeve** [comment]
Part of this is a caching problem - there was a javascript update, and you have to hard refresh (cmd-shift-R for chromium) to clear the cache. That will stop it from redirecting you to the other url. That state is intended to only load when users have javascript disabled, or it's not loading for whatever reason. 

But it shouldn't leave you stuck! I'll fix that. In the short term, a hard refresh should have it working again.

**Comment by oragegu** [comment]
Thank you! 

After updating, the problem is gone.
