### ISSUE TITLE
Cannot interact with mastodon instances that have activated 'secure mode'

### ISSUE THREAD

**Issue by oragegu** [bookwyrm-social/bookwyrm#1179]
**Describe the bug**
Accounts from instances activated secure mode cannot subscribe to any bookwyrm account. They can interact (comment and favourite) a bookwyrm post if that post is forwarded to them from other mastodon instances, but the bookwyrm account will not receive any notifications about these intereactions.

**To Reproduce**
1. Go to a mastodon instance with secure mode on
2. Subscribe to a bookwyrm account
3. Publish something with the bookwyrm account
4. The publication does not appear on the mastodon side
5. The subscription does not appear on the bookwyrm side
6. Boost a bookwyrm post with another mastodon account that is followed by the "secure mode account"
7. Comment and boost the bookwyrm post with the "secure mode account"
8. Nothing is shown on the bookwyrm stream and no notification

**Expected behavior**
Stream and notifications should be updated on both sides when intereacting.

**Remark**
I have tested this on two bookwyrm instances. Both have this problem.

**Comment by mouse-reeve** [comment]
I believe this code is related: https://github.com/bookwyrm-social/bookwyrm/pull/427

**Comment by mouse-reeve** [comment]
Re-opening this because the work isn't done yet!

**Comment by tofuwabohu** [comment]
I believe rage.love (hometown fork) also has "secure mode" activated and I've had similar problems in the beginning but there was a fix in the meantime. I can follow bw users from r.l and get the subscription notification and also get the bw content shown in my r.l tl, I also boosted a bw status on r.l. I will keep an eye on it.

**Comment by anantshri** [comment]
Is there anything that can be done to prioritize this issue. This is stoping me from connecting with bookwyrm instances as i run a mastodon secure equivalent server. people should not be required to reduce security settings to be able to talk to each other IMHO.

**Comment by mouse-reeve** [comment]
You're right, this needs to be one of the top priority issues, especially since there's already code that was written for it
