### ISSUE TITLE
“Added by”-hyperlink in lists links to the wrong account

### ISSUE THREAD

**Issue by tastytea** [bookwyrm-social/bookwyrm#1185]
**Describe the bug**
The hyperlink in “Added by […]” in lists links to the wrong account. When I'm logged in, it links to my profile page. When I'm logged out, it links to nothing (`""`).

**To Reproduce**
1. Go to <https://bookwyrm.social/list/61>
2. Scroll to “Scheidelinien by Anja Meulenbelt”
3. Click on user name in “Added by […]” line

**Expected behavior**
I expect that the hyperlink takes me to the account that is specified in the text.

**Screenshots**
![screenshot_2021-06-18T20:46:51](https://user-images.githubusercontent.com/3681516/122604874-ef091400-d076-11eb-8a2e-90c393c5d94b.png)

![screenshot_2021-06-18T20:54:07](https://user-images.githubusercontent.com/3681516/122605152-58892280-d077-11eb-9c6a-ba4a2023acd1.png)

**Additional context**
I'm also the creator of the list, so I don't know if it links to the creator or the logged-in person.

**Comment by mouse-reeve** [comment]
woops! thank you
