### ISSUE TITLE
Quotes with page numbers

### ISSUE THREAD

**Issue by bluebirch** [bookwyrm-social/bookwyrm#1189]
When I add a quote, I would like to be able to add page number(s).

I tried adding it to the quote itself, then to the comment, but none of it looks good. Example:

![Quote with page number added as comment.](https://user-images.githubusercontent.com/4832639/122663986-cb40ed80-d19e-11eb-8efb-246bc058a18d.png)

I would like the page number to be part of the source reference, like this:

> — In Our Clients' Shoes by Stephen E. Finn (p. 20)

**Comment by mouse-reeve** [comment]
This should be straightforward, but it makes sense to wait until #1092 is merged, just because of what a headache the merge conflicts would be
