### ISSUE TITLE
Potential bug in getting users json feed?

### ISSUE THREAD

**Issue by carbontwelve** [bookwyrm-social/bookwyrm#1198]
**Describe the bug**
When looking at the routes I can see on [line 196 of urls.py](https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/urls.py#L196) that https://bookwyrm.social/user/carbontwelve.json should return the same as https://bookwyrm.social/user/carbontwelve except I would imagine the former returns a json representation of my feed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://bookwyrm.social/user/carbontwelve.json
2. See 404 error

**Expected behaviour**
From looking at the source code I would expect the .json suffixed url to return the users page as .json or at least return the same as the non json suffixed as both routes appear to go to the same [User class](https://github.com/bookwyrm-social/bookwyrm/blob/ae1d0343baea0383d3db6496f72b1c331fde239c/bookwyrm/views/user.py).

Looking at a status works in this way, for example https://bookwyrm.social/user/carbontwelve/review/30416 returns the html view and https://bookwyrm.social/user/carbontwelve/review/30416.json returns the Activity Stream json. 

**Additional context**
What I am actually interested isn't directly related to the Activity Stream and I know requesting https://bookwyrm.social/user/carbontwelve with `Accept: application/json` will return the correct Person activity stream object. I'm really looking for a json representation of the Atom feed https://bookwyrm.social/user/carbontwelve/rss which I would have assumed be published at https://bookwyrm.social/user/carbontwelve.json.

What I am attempting to do is hook up my statically generated blog so that each time it publishes it can grab my book feed and list my recent reviews. At the moment I am fetching https://bookwyrm.social/user/carbontwelve/rss and parse that for links containing `/review/` and then suffixing the links with .json in order to fetch the book cover image url.

**Comment by mouse-reeve** [comment]
Ah yeah, the `.json` links shouldn't produce a 404! Thank you for reporting. For a workaround in the meantime, you can fetch the regular url with the `Accept: application/json` header to get the json version of the views.
