### ISSUE TITLE
Better UI pattern for form elements that store multiple values

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1203]
There are a handful of fields that store arrays or multiple foreign keys. Right now, the user is expected to enter a comma separated list of values, which is parsed into an array and, if it's a foreign key, matched with existing entries. It's cumbersome!

Examples include:
 - Authors' aliases
 - Books' authors
 - Books' languages

I think it would be good for there to be javascript which enhances this pattern, but it should still work, even if it's less convenient, without javascript.

**Comment by hughrun** [comment]
I can look into this. Seems like a text field that creates camouflaged checkboxes might be a solution.

**Comment by mouse-reeve** [comment]
This is related, although I absolutely tanked the PR by moving files around (sorry @bibliotechy): https://github.com/bookwyrm-social/bookwyrm/pull/1481

**Comment by hughrun** [comment]
Ooh I think maybe like that better than what I was thinking. Maybe I'll put together a little demo and you can see which approach might work best.

**Comment by mouse-reeve** [comment]
Fixed by #1481
