### ISSUE TITLE
[Feature Request] Implement Forums For Discussions

### ISSUE THREAD

**Issue by seniorm0ment** [bookwyrm-social/bookwyrm#1209]
Suggesting adding forums for users to create topics and have discussions, discover new books, etc.

**Comment by mouse-reeve** [comment]
Unfortunately, this is out of scope for the project.

**Comment by kopischke** [comment]
I’m frightfully sorry for jumping into a closed issue, but how about activating the [Discussions feature](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions)? That works for any GH repo, has zero extra software overhead and helps keeping snowballing discussions out of issue management?
