### ISSUE TITLE
Import floods the federated feed with a bunch of old reviews

### ISSUE THREAD

**Issue by cincodenada** [bookwyrm-social/bookwyrm#1210]
**Describe the bug**
When importing (from Goodreads in this example), the feed as shown on Mastodon is flooded with a bunch of old reviews, all in a row. The dates on the posts are old (and probably correct), but their position on the feed seems to be all at the time of the import.

**To Reproduce**
1. Import a Goodreads export with old reviews
2. View the user the books were imported into in a non-Bookwyrm client (e.g. Mastodon)
3. Notice that a bunch of reviews from the import were posted all very recently in the timeline

**Expected behavior**
I would expect the old reviews to not federate at all, I think - I doubt there's a way to, like, rewrite history and put the posts in an old timeline.

**Screenshots**
![Screenshot_2021-07-03 Cybrespace](https://user-images.githubusercontent.com/479715/124366442-cf402700-dc04-11eb-9806-a8907e64669d.png)

The first post is legit and was posted in real time, the next two (and the hundred or so after that, by my count, I think [this post](https://bookwyrm.cincodenada.com/user/cincodenada/reviewrating/1081) is the next legit one) resulted from the import.

**Instance**
bookwyrm.cincodenada.com (running latest main)

---

**Desktop (please complete the following information):**
    - OS: Ubuntu Linux
    - Browser Firefox
    - Version 86.0

**Comment by wakest** [comment]
If they dont get "posted to the feed" none of the people following you will have them in your "collection" there is also a plus side to all the old stuff being added. I think as a compromise it would make sense to post them "unlisted" so they are still in the remote followers collections but that they dont make it to anyones timelines without an intentional reshare

**Comment by mouse-reeve** [comment]
I think they could also federate to bookwyrm instances only, where they are posted based on publication date rather than created date

**Comment by wakest** [comment]
by federating out tho then others are able to comment on them, if they are not announced to outside instances then it makes interacting with the posts really difficult

**Comment by mouse-reeve** [comment]
My assumption is that for Mastodon and other non-bookwyrm services, getting years-old reviews is not going to be useful to them (plus I don't know if it's possible to back-date them). They can still be loaded by searching for the url for the review. Whereas for other bookwyrm instances, they posts are added to timelines retroactively, and there's a benefit to getting old reviews.

**Comment by cincodenada** [comment]
Yeah, for me my intent when importing 100 book starts/reviews/etc spread out over the last decade, my intent is not for everyone in my federated feed to be able to interact with them (especially not all at once!), it's to have them in my Bookwyrm history, certainly locally and optimally in other Bookwyrm instances as well.

If I do want to surface a review or something for interaction, I can always boost it or what have you, but I can't imagine a scenario where it's useful to throw 100+ posts into my timeline externally. If it were possible to quietly add those to my timeline as visible from non-Bookwyrm clients in a consistent way maybe, but it sounds like that's not an option.
