### ISSUE TITLE
Potential bug in outbox pagination

### ISSUE THREAD

**Issue by carbontwelve** [bookwyrm-social/bookwyrm#1214]
**Describe the bug**
When I visit https://bookwyrm.social/user/carbontwelve/outbox I see that there are 21 items over two pages; however it seems both pages are returning the same `orderedItems` list. Additionally visiting a page three that shouldn't exist results in the same results as page one instead of an empty list.

**To Reproduce**
1. Go to https://bookwyrm.social/user/carbontwelve/outbox
2. Click on https://bookwyrm.social/user/carbontwelve/outbox?page=1 and https://bookwyrm.social/user/carbontwelve/outbox?page=2
3. See that `orderedItems` are apparently identical
4. See that the `next` url on page two isn't `null` and points to itself (i'd assume it `null` if last page, or the `next` property to not exist)

**Expected behavior**
There are 15 items per page and I would expect to see page one return 15 items and page two return 6 items. Page two appears to return the same 15 items as page one.

**Screenshots**
![image](https://user-images.githubusercontent.com/464699/124572118-4e6d6f00-de40-11eb-8391-5ce0c6316d07.png)
![image](https://user-images.githubusercontent.com/464699/124572258-6c3ad400-de40-11eb-910c-77029e5d082f.png)
![image](https://user-images.githubusercontent.com/464699/124572299-752ba580-de40-11eb-83a6-2d0366ed1235.png)

**Instance**
https://bookwyrm.social/

**Comment by mouse-reeve** [comment]
good catch, thank you!
