### ISSUE TITLE
Error to build the db

### ISSUE THREAD

**Issue by CysteineOmni** [bookwyrm-social/bookwyrm#1218]
I've got an error when I try to run `docker-compose up --build`
Same when I run `docker-compose build db`

Step 10/12 : RUN awk '$0 ~ /^\t_main "\$@"$/ { print "\tif [[ $1 == cron ]]; then\n\t\tservice cron start\n\t\tshift\n\tfi" }{ print }' docker-entrypoint.sh > bookwyrm-entrypoint.sh
 ---> Running in ab462753ce9a
awk: cannot open docker-entrypoint.sh (No such file or directory)
The command '/bin/sh -c awk '$0 ~ /^\t_main "\$@"$/ { print "\tif [[ $1 == cron ]]; then\n\t\tservice cron start\n\t\tshift\n\tfi" }{ print }' docker-entrypoint.sh > bookwyrm-entrypoint.sh' returned a non-zero code: 2
ERROR: Service 'db' failed to build : Build failed

This is my first issue in GIT, so tell me if you want more details =)

**Comment by mouse-reeve** [comment]
This seems to be the line that is failing: https://github.com/bookwyrm-social/bookwyrm/blob/production/postgres-docker/Dockerfile#L18

**Comment by mouse-reeve** [comment]
This should be resolved by setting the version number for postgres. Let me know if you continue to have issues!

**Comment by CysteineOmni** [comment]
@mouse-reeve Thanks, it works, I can continue the install =)
