### ISSUE TITLE
Allow mark as read without date

### ISSUE THREAD

**Issue by aclezotte** [bookwyrm-social/bookwyrm#1222]
**Is your feature request related to a problem? Please describe.**
I often know I have read a book many years ago but don't remember when

**Describe the solution you'd like**
I would like the ability to mark books as read without a finish date

**Describe alternatives you've considered**
I know I could approximate but often I really have no idea when it was that I read it

**Comment by mouse-reeve** [comment]
You can already do this! When you're on the "finish reading" modal, you can set the date to empty. You can also move books to the "read" shelf from the "Your books" view.
