### ISSUE TITLE
Use a font that displays Roman numerals coherently

### ISSUE THREAD

**Issue by LongJohn-Silver** [bookwyrm-social/bookwyrm#1223]
**Is your feature request related to a problem? Please describe.**
Books have formed part of our culture for a long time, therefore a lot of them (mostly old ones, but there are obviously more contemporary cases, too) use Roman numerals as a way to catalogue them in a hierarchical way. A good example of this is the ten books that compose Plato's Republic.

**Describe the solution you'd like**
Using a font that displays them in a way that an uppercase "I" can be distinguishable from a lowercase "L", and that displays Roman numerals as they usually are writen.

Example:
![Screenshot from 2021-07-15 12-58-20](https://user-images.githubusercontent.com/63723030/125819310-cada59f1-84b9-41e5-b924-aa97db623507.png)

**Describe alternatives you've considered**
None.

**Additional context**
Maybe this can be applied only to relevant book's metadata, since it's probably where it's going to be used, but not on the rest of the web site, since these kind of fonts tend to look less modern and it could drastically change the aesthetics of the project. Using a copylefted font would also be preferable, since it adds to the ideals of BookWyrm.

Now the important question is, which font should we use?

**Comment by mouse-reeve** [comment]
I'm closing this since themes are now available, and changing the font would be something that can be done in a custom theme
