### ISSUE TITLE
[Bug] Linebreak Not Recognized In Bio

### ISSUE THREAD

**Issue by seniorm0ment** [bookwyrm-social/bookwyrm#1225]
Single linebreaks are not recognized in profile descriptions, and acts as one paragraph.
If the user double linebreaks, it shows up as a double line break (as exoected).

**Comment by mouse-reeve** [comment]
Statuses and bios are formatted with markdown, which treats single line breaks as ignorable whitespace, and double line breaks as paragraph breaks. I think this can be fixed by changing how css handles whitespace for the element.
