### ISSUE TITLE
[Feature] Directly Input Classifications/Identifiers, and search Editions

### ISSUE THREAD

**Issue by seniorm0ment** [bookwyrm-social/bookwyrm#1228]
Requesting the ability to directly query classifications and identifiers such as ISBN 10/13, numbers, OpenLibrary (or other) entry identifiers, etc.
It already seems like this might be possible, however when searching, the results don't show the identifier you searched, just the name and author so it's not always clear.

Furthermore, I suggest being able to search when viewing editions. It's pretty much impossible to find editions when there's like 300 editions for a book. Especially because some have similar covers or may be old books with lots of translations.

**Comment by mouse-reeve** [comment]
Search already matches identifiers directly - it only defaults to a title/author search if there isn't an identifier match. Searching within editions is a good idea; at the moment, you can filter by a couple attributes.
