### ISSUE TITLE
External Storage: images not displayed in local search results

### ISSUE THREAD

**Issue by joachimesque** [bookwyrm-social/bookwyrm#1245]
In the local search results, if your images are stored externally, the covers don't show up. (it doesn't concern images that have been saved before migration to S3 and not deleted since). This is due to the local Connector using `DOMAIN` in the value for `covers_url`.

As it is set during the `initdb` sequence, it has to be fixed afterwards. This is how I did it in my local environment:

```python
from bookwyrm.settings import DOMAIN, MEDIA_URL
c = models.Connector.objects.get(identifier=DOMAIN)
c.covers_url = MEDIA_URL
c.save()
```

Which would be the best way to be sure it's updated when external storage is set up ?

- having the admin run this code in the shell
- having a management command (yet another, for a very narrow use case)
- having it automated at app start

**Comment by mouse-reeve** [comment]
Now that the local connector no longer exists, and the `book_search` doesn't rely on `DOMAIN`, I think that has been fixed. Please re-open if not!
