### ISSUE TITLE
“Show more” reveal shows duplicate text in reviews

### ISSUE THREAD

**Issue by kopischke** [bookwyrm-social/bookwyrm#1284]
**Describe the bug**
When selecting “Show more” on a truncated review text in the feed, the expanded text repeats the already visible part.

**To Reproduce**
Hard to reproduce, as the example I have is on my feed, but see screenshots.

**Expected behavior**
Expanding should only show the full text.

**Screenshots**

![Truncated review](https://user-images.githubusercontent.com/80906/129076451-50037632-770d-4ced-a4ba-cc792eaed852.png)

![Fully expanded review](https://user-images.githubusercontent.com/80906/129076542-15337f5f-83c0-4381-9d03-e64a49d148f2.png)

**Instance**
bookwyrm.social

---

**Tablet:**
    - Device: iPad Pro 12.9
    - OS: iOS 14.7
    - Browser: stock Safari
    - Version: N/A

**Comment by mouse-reeve** [comment]
I believe this is a problem with your browser caching outdated javascript. If you hard refresh (cmd-shift-r for chromium, [this looks like a way to do it in ios(https://vanja.gavric.org/blog/how-to-perform-force-refresh-in-ios-11-safari/)) the problem should be resolved.

**Comment by kopischke** [comment]
Ah, thanks for the quick answer; for any body stumbling on this, the workaround still works on iOS 14, but, at least on iPad, you need to “Reload without content blockers” from the site options menu (long pressing Reload will do diddly-squat).
