### ISSUE TITLE
very minor issue on mobile

### ISSUE THREAD

**Issue by quaayd** [bookwyrm-social/bookwyrm#1288]
on my mobile device, the drop down menu in the upper right corner doesn't function.
clicking on it, the box is highlighted, but menu does not appear.

iphone 11 pro max
ios 14.7.1
safari

![72BYzCWnRHaO4sN%Fg8C%A_thumb_46ef](https://user-images.githubusercontent.com/63938514/129265328-b0c936dc-d5a7-4520-a1b4-8effde59cd4e.jpg)

**Comment by mouse-reeve** [comment]
I suspect this is a caching problem (#1285) and I think the fix is the same as in #1284. Lemme know if that doesn't fix it!

**Comment by quaayd** [comment]
Hi, no, sadly did not solve the issue. tried loading with firefox on my phone, had the same issue.

**Comment by mouse-reeve** [comment]
I see the issue -- thanks for checking

**Comment by quaayd** [comment]
thank YOU! 

fwiw i love the new interface. Home and Book feeds is a simple, elegant solution.

**Comment by mouse-reeve** [comment]
aww thank you!!
