### ISSUE TITLE
Unread statuses notification is often wrong

### ISSUE THREAD

**Issue by tastytea** [bookwyrm-social/bookwyrm#1293]
**Describe the bug**
In the home feed, It said that there are 9 unread statuses but there were only 2.

**To Reproduce**
1. https://bookwyrm.social/
2. Log in
3. Wait a few hours
4. Check back and see if the reported number matches with the actual number of statuses

**Expected behavior**
The right number in the notification.

**Instance**
bookwyrm.social

**Additional context**
There was at least 1 suspend + resume in between my 2 visits to the site.

---

**Desktop:**
    - OS: Gentoo Linux
    - Browser Firefox
    - Version 78.12.0esr (gentoo 1.0)

**Comment by mouse-reeve** [comment]
This is so interesting, the first thing I thought of was that imports might be increasing the unread count but be too far backdated to appear on the timeline. Another low hanging fruit could be users composing and then deleting statuses.

**Comment by mouse-reeve** [comment]
Oh you know what, it may be including every save action on a status, which happens multiple times when a statuses is created for complicated reasons

**Comment by tastytea** [comment]
It got worse. 😄 (There was no new status)

![screenshot: load 85 unread statuses](https://user-images.githubusercontent.com/3681516/129952293-dff34e24-1daa-41fe-a1bf-07e17fe820a9.png)

**Comment by mouse-reeve** [comment]
okay that must have been an import! but big hmmm about this feature for sure; I'll try and get it working better
