### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by SrEstegosaurio** [bookwyrm-social/bookwyrm#1295]
**Is your feature request related to a problem? Please describe.**
I noticed that their onboarding page is only disponible in 2 lenguajes. It can be a difficulty to some users.

**Describe the solution you'd like**
Make the community able to help with the translations. It would be cool to contribute.

**Comment by mouse-reeve** [comment]
We do accept community translations, and it's actually 3 translation as of a few minutes ago 😊. The application itself is translated into French, Spanish, German, and Traditional and Simplified Chinese. There is documentation on how to contribute translations here: https://docs.joinbookwyrm.com/translations.html

At this point it is definitely still a bit technically involved, so while I'm not sure what the tools out there are like, I'm interested in options that have a lower barrier to entry for folks not used to software environments.

**Comment by mouse-reeve** [comment]
I'm going through and closing old issues that seem stale or out of date - feel free to reopen with a comment adding some updated context if you feel like it still needs to be addressed ❤️
