### ISSUE TITLE
'bookwyrm.social' vs. 'www.bookwyrm.social' login status

### ISSUE THREAD

**Issue by bnewbold** [bookwyrm-social/bookwyrm#1300]
**Describe the bug**

It seems that logins to base domain (eg, `bookwyrm.social`) do not have cookies or apply to the www sub-domain (eg, `www.bookwyrm.social`). When not logged in, I ended up with a bunch of www tabs open. After logging in, I refreshed these tabs but was still not logged in.

I'm not totally sure what The Right Thing To Do is in this case, but it might be to HTTP redirect all www URLs to the bare domain? This would also result in "canonical" URLs for each page, might help with "SEO", etc.

**To Reproduce**

Log in to service, then compare views of a URL with/without `www` sub-domain, eg:

- https://bookwyrm.social/book/8138
- https://www.bookwyrm.social/book/8138

**Expected behavior**
Either logins work across the www sub-domain and not, or have www redirect to the base domain.

**Instance**
bookwyrm.social

**Desktop (please complete the following information):**
    - OS: Debian Linux
    - Browser: Chromium (Version 90.0.4430.212 (Developer Build) built on Debian 10.9, running on Debian 10.10 (64-bit))

----

Thank you for maintaining BookWyrm!

**Comment by mouse-reeve** [comment]
Thank you! I think treating a url as canonical makes the most sense - it also clarifies identifiers in the federation process.
