### ISSUE TITLE
Author Pages don't list books by the Author

### ISSUE THREAD

**Issue by DeadSuperHero** [bookwyrm-social/bookwyrm#1302]
I've been adding a fair amount of book entries to bookwyrm.social, in the hopes of making imports go a bit more smoothly for new people, and improving discovery of other books by a given author. This has involved adding lots of metadata and publicly-available information from places like OpenLibrary and Wikipedia.

However, as I filled out various information for authors, I've noticed that their books do not appear on their profiles, despite there being a dedicated section for it. Is this a bug, or is the behavior simply not implemented yet?

A few examples:
https://bookwyrm.social/author/845
https://bookwyrm.social/author/1585

This seems to be the case for all authors. It would be really awesome to see the thumbnails and titles of books on the author pages!

**Comment by mouse-reeve** [comment]
Oh dear, that's a recent bug -- luckily easy to fix. Thanks for reporting!
