### ISSUE TITLE
Post button not appearing for finish book popup on mobile browser

### ISSUE THREAD

**Issue by Danie10** [bookwyrm-social/bookwyrm#1312]
**Describe the bug**
Post button not appearing for finish book popup on iOS mobile browser

**To Reproduce**
1. Go to Finish book
2. Scroll down to view as Public etc
3. Cannot see Post button

**Expected behavior**
Expected it to scroll down

**Screenshots**
None

**Instance**
Bookwyrm.social

**Additional context**
Tried with Safari and Brave browsers on iOS. Tried to scroll, and also tried zooming out. It appears that when scrolling, it is in fact scrolling the background page below the popup window. On desktop it works fine.

---

**Smartphone (please complete the following information):**
    - Device: iPhone 12 Pro
    - OS: ios 15 Public Beta 4
    - Browser Safari and Brave
    - Version

**Comment by mouse-reeve** [comment]
Yikes! workin' on it

**Comment by mouse-reeve** [comment]
this should be fixed now - let me know if you continue to have any issues with it and thank you for reporting!

**Comment by Danie10** [comment]
Seems not as doing the same on Safari and Brave still - here is a video of what I see when I click on Finish and try scroll down to see the Post button. You can see the background scrolling under the window. Yet I can fill in the fields fine, just can't scroll down to the Post button to actually post it. See https://photos.app.goo.gl/2exDWxWfBfD3x7DY7

**Comment by mouse-reeve** [comment]
I'm finding that if I place my finger on the body of the modal, the scroll works normally, but if I'm on the header, the scroll is triggered on the background. If you start in that region are you able to scroll down to the button?

**Comment by Danie10** [comment]
Yes thank you, tested it now and is scrolling up fine to see the post button. We can close for now then. Thanks for feedback.
