### ISSUE TITLE
add ability to delete a list

### ISSUE THREAD

**Issue by hughrun** [bookwyrm-social/bookwyrm#1317]
**Is your feature request related to a problem? Please describe.**
There does not appear to be any way to delete a list once it is created, even if it's a brand new, empty list.

**Describe the solution you'd like**
A button in the "Edit list" modal that allows the list owner to delete a list, with some kind of confirmation step to avoid accidentally deleting lists.

Ideally this would be allowed for any list, but one possible extra safety mechanism would be to force users to remove everything from the list before allowing the list itself to be deleted.

**Describe alternatives you've considered**
It's possible this feature already exists and I just can't find it, as I'm quite new to Bookwyrm.

**Additional context**

**Comment by mouse-reeve** [comment]
oh yeah I meant to add this feature and completely forgot! thank you for raising.
