### ISSUE TITLE
Bad Gateway errors when trying to use lists

### ISSUE THREAD

**Issue by lissertations** [bookwyrm-social/bookwyrm#1319]
**Describe the bug**
I am having the same issue as #885  - every time I try to view or otherwise interact with lists, I get a 502 Bad Gateway error. I have tried multiple browsers and instances and this problem recurs. It is very frustrating.

**To Reproduce**
1. Go to https://bookwyrm.social/list/130
2. See `502 Bad Gateway`

**Expected behavior**
A list of books

**Screenshots**
See console details below (idk what these mean, I am only a vaguely technical person)
![image](https://user-images.githubusercontent.com/22556371/130312949-108ec0f6-cb41-4e1d-b269-08c5716cbd75.png)

**Instance**
I had this problem on both bookwyrm.social and cutebook.club.

---

**Desktop (please complete the following information):**
    - OS: macOS 10.14.5 Mojave
    - Browser: Chrome 91.0.4472.164 *and* Firefox 91.0

**Comment by mouse-reeve** [comment]
Usually, gateway errors mean the site is down and aren't related to the specific page you're trying to access. We did have a couple hours of downtime yesterday, unfortunately. Are you still having trouble loading the page if you try it now? I was able to access it alright this morning

**Comment by charlag** [comment]
I just signed up for flagship and every single list times out

**Comment by mouse-reeve** [comment]
ah I'm sorry, how frustrating! @charlag are you also seeing the 502 error message?

**Comment by mouse-reeve** [comment]
I'm having trouble figuring out what's going on because I haven't yet been able to reproduce the error, and nothing in the logs or error reporting indicates an issue. It's odd that this issue would be particular to lists, which are pretty anodyne views.

**Comment by charlag** [comment]
@mouse-reeve no need to be!
Yes, I get 502 from Nginx after some time

**Comment by lissertations** [comment]
I tried again just now and am still getting 502 errors.

**Comment by mouse-reeve** [comment]
Okay, I'm seeing the timeout in the logs:
```
web_1             | [2021-08-22 02:24:18 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:6)
web_1             | [2021-08-22 02:24:19 +0000] [6] [INFO] Worker exiting (pid: 6)
web_1             | [2021-08-22 02:24:20 +0000] [49] [INFO] Booting worker with pid: 49
```

Is this only happening with lists, and are you doing any activities (creating a list, adding books, editing, anything else), or just viewing?

**Comment by lissertations** [comment]
It also happens when I create a list - the list is successfully created, but I still get the 502 error. Same with adding a book to a list.

I haven't experienced it yet with any other areas of the site.

**Comment by meunierd** [comment]
I just wanted to chime in and say I'm also experiencing 502s for all lists that I've tried. Absolutely love the project!

**Comment by meunierd** [comment]
One more clue: this actually works fine when I'm not signed in. It's only when I'm authenticated that I get 502s.

**Comment by mouse-reeve** [comment]
Hm, that is helpful info! I'll take another look at the queries that go into generating that page and see if I can suss out what's going on.

**Comment by mouse-reeve** [comment]
I think the problem here is with the query that determines which lists user are authorized to view, in particular, the part that checks followers-only content to see if the viewer is a follower of the user that created the list. If it's not possible to make that query more performant, I can use a redis activitystream for lists in the same way I do for the status updates feeds.

Thank you all for being patient with me on this!

**Comment by amwelles** [comment]
Wanted to check in here. I’m still experiencing this on bookwyrm.social. I was able to create lists, but unable to view them.

**Comment by mouse-reeve** [comment]
I just had a gateway error on an admin page -- I think there's a performance issue application-wide on bookwyrm.social right now

**Comment by amwelles** [comment]
Things appear to be working more smoothly today!
