### ISSUE TITLE
413 Request Entity Too Large error when creating book

### ISSUE THREAD

**Issue by lissertations** [bookwyrm-social/bookwyrm#1323]
**Describe the bug**
Sorry for being a repeat bug-submitter: I get a 413 Request Entity Too Large error when creating a new record for a book (that is, no record is available for import). 

I thought it could be related to having copypasted a summary from the publisher's website into the Description field (is there a character limit? If so, it's not specified on the page) but I tried again with no summary and it didn't work either.

The book is ['The maddest place on earth'](https://scholarly.info/book/the-maddest-place-on-earth/) by Jill Giese.

**To Reproduce**
1. Go to https://bookwyrm.social/create-book
2. Add some metadata
3. Click Save
4. Admire error

**Expected behavior**
A new record for a book, I guess

**Instance**
bookwyrm.social

---

**Desktop (please complete the following information):**
    - OS: macOS 10.14 Mojave
    - Browser: Chrome 92.0.4515.159

**Comment by mouse-reeve** [comment]
wow this is another one that's totally baffling me! I'm sorry you keep running into these. The description shouldn't be an issue, did you attach a cover? That's a common suspect.

**Comment by mouse-reeve** [comment]
I was able to create the book, so the create flow itself doesn't seem to be broken in every case (https://bookwyrm.social/book/187089). It sounds like the error is being sent by nginx, since django would be serving a 500 error.

**Comment by lissertations** [comment]
Yeah I did attach a cover - I didn't think to test without it, so good to see your test worked.

**Comment by reesporte** [comment]
@lissertations did you ever test without the cover / do you know how big the cover file was? i think mouse is right that it's an nginx error, because there's a [default](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) max file upload size of 1 MB and pictures can get big

**Comment by lissertations** [comment]
The cover is 1.2 MB, so that might have been it.

**Comment by mouse-reeve** [comment]
I heard from another user who hit a 413 when trying to import a 2.4 MB csv file
