### ISSUE TITLE
status not showing up in my timeline

### ISSUE THREAD

**Issue by quaayd** [bookwyrm-social/bookwyrm#1325]
not sure if this is an issue, but a status didn't show up in my timeline.

This status showed up in my timeline:

<img width="1186" alt="yes" src="https://user-images.githubusercontent.com/63938514/130379395-3a2ee8cc-b4db-4be4-86e8-f01fc35aa0e6.png">

but not this one:

<img width="1195" alt="no" src="https://user-images.githubusercontent.com/63938514/130379412-4facf7a0-1837-4982-a93a-44407fe0d5ed.png">

it was the same on chrome and firefox, mac laptop and iphone.

i noticed this post on my oulipo mastadon instance on tusky. it was of particular interest because of my mild obsession with biblical history, so I went to read it on my laptop. but it was not on my timeline. it was on user's (mouse) profile page, which is were i got the image.

**Comment by mouse-reeve** [comment]
whew good catch! this was an obvious bug in retrospect but it would have taken me ages to notice
