### ISSUE TITLE
After Setting up the S3 Storage, Impossible to Upload Custom Logo

### ISSUE THREAD

**Issue by oragegu** [bookwyrm-social/bookwyrm#1347]
**Describe the bug**
After Setting up the S3 Storage, Impossible to Upload Custom Logo

**To Reproduce**
1. Setting up the S3 options
2. bw-dev CROS all the remote images
3. Upload a big custom logo to the server

By F12 the page one would see that the address of the logo image is not from the S3 cloud but a local address, which is invalid.
![image](https://user-images.githubusercontent.com/78921858/131894286-f11887fe-1a00-45c0-9b8b-73dbbea4edab.png)

**Expected behavior**
After uploading the logo it should have shown on the registration page.

**Instance**
This problem is encountered while setting up a brand new instance (the yyyyy.club instance). The big logo image is uploaded to the S3 bucket without any problem, but the about page doesn’t fetch from the S3 for the logo image. 

For the moment the workaround we found is to change the default big logo.png on the vps.

**Comment by mouse-reeve** [comment]
Oops! Sorry about that, luckily it should be a quick fix
