### ISSUE TITLE
Users from blocked federated instances still show up in "Who to follow" Home widget

### ISSUE THREAD

**Issue by IcedEagle** [bookwyrm-social/bookwyrm#1364]
**Describe the bug**
Apologies if what I'm doing is against fediverse etiquette first of all... I got a personal bookwyrm instance stood up for my house, and decided to block the default bookwyrm.social federation so we could use the software and be on our own island for now as we play with the software. However, the users that were automatically selected for "Who to follow" remain on our home page, even though you can't access those accounts anymore. Expectation is that only valid active users would remain here.

**To Reproduce**
1. Go to Home Timeline and scroll down to see "Who to follow"
2. Note the instances those users are on
2. Go to the Admin Portal for an instance
3. Block the instance those users are on
4. Go back to the Home page

**Expected behavior**
The "Who to follow" widget shows only users that are accessible to the instance. Any changes to federated instance status would have relevant widgets refresh at the appropriate time.

**Screenshots**
![image](https://user-images.githubusercontent.com/934801/132164898-e7e059fb-971f-4032-bbdf-9612b80e7326.png)

![image](https://user-images.githubusercontent.com/934801/132164868-0cc744ef-e7ac-416f-8061-8ef23536909e.png)

**Instance**
My local bookwyrm instance

**Additional context**
I tried to delete these users using the admin dashboard, but that threw a lot of users that it couldn't delete the users without deleting a bunch of other objects, so I don't think that was the right approach and didn't investigate further.

---

**Desktop (please complete the following information):**
    - OS: Pop OS 21.04
    - Browser: Firefox
    - Version: 92

**Comment by IcedEagle** [comment]
Actually, this may have been because some of the Celery jobs were failing? I saw in one of the logs that some jobs were failing to update. Unfortunately by me attempting to fix it by exposing and changing the ports used in the env file, I broke Redis connection auth and can't get it working again so I have to figure out how to fix that tomorrow...

**Comment by mouse-reeve** [comment]
Whew thank you! I accounted for users blocking one another and for individual deactivation, which in theory ought to account for domain-level blocks. I'll take a look and see if it's a task issue or something I missed in the implementation
