### ISSUE TITLE
Import from Goodreads doesn't work correctly

### ISSUE THREAD

**Issue by RedwanFox** [bookwyrm-social/bookwyrm#1370]
**Describe the bug**

Import  from goodreads csv imports only first line of csv and stops with 'success' status. If user tries to reimport same csv again importer takes the same first imported line yet again. 

Broken import examples https://bookwyrm.social/import/775 https://bookwyrm.social/import/776

**Expected behavior**
Importer correctly imports all lines of csv or returns error message to user

**Comment by mouse-reeve** [comment]
How frustrating! Would you be able to upload the csv here? that way I can test against it locally.

**Comment by Raineer** [comment]
My issues with Goodreads import is that it isn't a CSV. This was the first time I requested a data export. It took the service a full day to send it (all of 57KB) - and it was a ZIP file filled with JSONs. Was this a policy change on Goodreads' behalf to act against Bookwyrm (and the like)? 

See the attached image for what was received. I went back to their Data Export page today and there is no option to receive data in any different formats.

![Goodrads Data Dump](https://user-images.githubusercontent.com/6374644/132385798-30c81a01-9f05-44c9-89fa-9131ec01a2db.png)

**Comment by mouse-reeve** [comment]
@RedwanFox I think I figured out the issue for you - it seems like you may have hit a database validation constraint around read dates. I can fix it shortly

@Raineer I need to clarify this in the ui! There are two ways to export data from GoodReads -- there's a full user data download, which is what you did, and there's a csv export, which is what you need to do the import. You can download the csv here: https://www.goodreads.com/review/import and it should only take a few minutes. Thanks for raising - I know you're not the only one who has ended up with the wrong type of export.

**Comment by Raineer** [comment]
@mouse-reeve I had deleted my comment because I figured it out and felt dumb... but yes this was the exact issue. Once I exported from the right section, the import worked correctly. Thank you greatly for all the hard work.

**Comment by mouse-reeve** [comment]
Not dumb at all! It's really non-obvious and I think a little info on the import page would help a lot

**Comment by RedwanFox** [comment]
[goodreads_library_export.csv](https://github.com/bookwyrm-social/bookwyrm/files/7123574/goodreads_library_export.csv)

@mouse-reeve  thanks for fast response. Here is my csv. Even though you have found source of problem, I think this data can be used in test suites.

**Comment by mouse-reeve** [comment]
Should be fixed on bookwyrm.social -- let me know if you have any other issues ❤️
