### ISSUE TITLE
New lines are not displayed for book descriptions

### ISSUE THREAD

**Issue by IcedEagle** [bookwyrm-social/bookwyrm#1380]
**Describe the bug**
When there are new lines in book descriptions, whether imported from OpenLibrary or Inventaire, or manually put into a book's description, new lines are removed, or at least not rendered. This puts everything in a single paragraph, which for large descriptions is difficult to read.

**To Reproduce**
1. Go to any book you have
2. Edit it
3. For the description, put any text and use multiple paragraphs
4. Save it and refresh to see the book details you just saved.

**Expected behavior**
Formatting is exactly as I entered for book details.

**Screenshots**
![image](https://user-images.githubusercontent.com/934801/132469792-eb6241c5-4e61-458c-8a4a-f3e30e751c72.png)

**Instance**
Personal instance

**Additional context**
Looking at the generated HTML, I don't see any line breaks visually, so presumably it's removed when submitting the text into the database or something similarly? Verified on Edge and Firefox that no newlines are displayed.

---

**Desktop (please complete the following information):**
    - OS: Windows 11
    - Browser Firefox, Edge
    - Version 94, 95

**Comment by mouse-reeve** [comment]
This is displaying correctly for me - is it possible your local instance is using an older version of the codebase? I fixed a bug causing this behavior recently - #1095

**Comment by IcedEagle** [comment]
Interesting, I'll double check that tonight. I used the production branch, but I'll make sure it's actually up to date.

**Comment by mouse-reeve** [comment]
Thank you! For reference for what I'm seeing on b.s: https://bookwyrm.social/book/206605

**Comment by IcedEagle** [comment]
Yup, my instance was out of date somehow. Good catch! I'm up to date and I have newlines, hooray!
