### ISSUE TITLE
Better support for abandoning a book

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1385]
Currently, if you are reading a book and decide you aren't going to finish it, there is an option in the pulldown menu to "Remove from Currently Reading", which removes the book from your "reading" shelf. It doesn't change anything about the current read-through (if one exists), or mark the book as abandoned. 

It would be useful to hear from people what behavior you'd like to have when you abandon a book -- should it be marked as abandoned? should the button be labelled differently? et cetera

**Comment by tastytea** [comment]
I would find it useful to know if I abandoned a book before. I'm pretty sure I won't remember it anymore in a year. :sweat_smile: 

Where does the book go currently? Back to the “To Read” shelf?

**Comment by mouse-reeve** [comment]
It is removed from the shelf and not added anywhere else. When you encountered the book again, it would show the "Want to read" button, as if it was a book you hadn't interacted with before

**Comment by maxheadroom** [comment]
When this happens to me, I would have at least read a certain percentage of the book. Which I'd like to still track as progress. Even though I haven't finished the book. I'd also love to keep it in my shelfs as I do with physical books. I don't throw away abandoned books as I might come back to them later. 
So for me the flow would rather be: "Currently reading" shelf -> "To Read" or "Abandoned". Like keeping them somewhere to come back and maybe finish them later.

**Comment by bcj** [comment]
I think I would not use a setting to keep a book in a abandoned state (If I abandoned it I'd rather just forget about it completely). If that was the default and I had to do another step to go from abandoned to "never happened" that would be fine too

**Comment by loppear** [comment]
Echoing above, I have two uses:
1. Not actually going to read, "Remove from My Books". This should take it off my shelves, and may as well delete any open read-through.
2. DNF or On Hiatus. I want it out of my Currently Reading, but keep my history (and show me I tried it if I stumble back on it. On GR I handle this with separate exclusionary shelves (a bigger-effort answer for more user-defined flows - I have both "on-hiatus" and "parked-aka-abandoned"), direct support for one "Not Currently Reading" would be fine.

**Comment by mouse-reeve** [comment]
Followup question for @bcj and @loppear: does the existing functionality for removing a book from your shelves fit your use case? Is it even clear that that functionality exists?

**Comment by hughrun** [comment]
I agree with what @bcj and @loppear are saying: anything around this needs to be optional because everyone has different preferences and not always consistently!

I think it might be helpful to have something like this:

1. A new drop-down option in a book that is currently being read, called something like `Abandon reading`
2. If you choose that, it goes into a default (i.e. like `Read` and `To Read`) shelf called something like `Abandoned` but retains the read-through information i.e. the "started reading" date isn't changed.
3. If you choose `Remove from Currently Reading` instead, the current behaviour remains.

As I understand it people could manually create such a workflow now, like @loppear has, but as you note it's not necessarily obvious. Making it "official" would also potentially support features like being able to share on your timeline that you abandoned reading a book, if you're particularly disappointed with it 😆

**Comment by mouse-reeve** [comment]
Thanks all! I think your suggestion seems like a good solution, @hughrun.

It's been interesting to see a split in people for whom abandoning a book is a rejection of the book, and people for whom it connotes setting the book aside for later. If anyone has a suggestion for a word that has a more neutral connotation than "abandon" but it still concise and clear enough for a button, I'd be interested to hear it.

**Comment by hughrun** [comment]
Maybe just "Stop Reading"? i.e. you either "Finish Reading" the book, or you "Stop reading" it, and the shelf could be "Stopped" or "Stopped Reading"

**Comment by loppear** [comment]
1. I hadn't noticed the current "Remove from Currently Reading" (it's not a common use case for me!), it meets use 1 for me, though to this issue's point I'd like to see it as "Remove from My Books" ("Remove" is fine on the book Move menu) and remove open read-through too.
2. My use 2 (captured in @hughrun's suggested two flows) requires some support for an additional status shelf to have it in the "Move" menu. But I also don't particularly curate my To Read, and could start to use a List for books-i'm-coming-back-to, so I'm very ok dropping that idea out. I should use Lists more.
3. +1 "Stopped" +- "Rage Quit" ~ "Set Aside"

**Comment by rkingett** [comment]
I'd want a feature for abandoned reading, but keep the current remove book from bookshelf as is, with the main points for each.

Official abandon shelf.

1. Make this option available when updating a books status and on book pages.
2. when click, it puts it in a DNF or abandon shelf while maintaining reading progress.
3. This way, when readers visit the book again, they can see how long they tried it, etc.
That being said, I'd actually like the remove from shelves feature to be updated a bit to do the following.

1. I'd like some way to completely delete all traces of the book, so to speak, including what shelf it's on, and the progress read. Not sure about comments yet.
2. Have an option to remove the book completely, and all traces of it, from your profile, including comments and reviews so you could probably try again later.
But I agree with some of the suggestions above as well, I'd just like an official DNF option in some way.

**Comment by hughrun** [comment]
> Maybe just "Stop Reading"? i.e. you either "Finish Reading" the book, or you "Stop reading" it, and the shelf could be "Stopped" or "Stopped Reading"

Or perhaps "pause reading" is better.

**Comment by quaayd** [comment]
(borrowing a lot from previous comments)

Reasons to stop reading a book:

1 Book is awful, you can't read another word, never want to see it again

2 book is too intense, complex, requires special attention and you don't have the time or headspace to devote at the moment.

3 another book comes along that had a time pressure. like a library book that needs to be returned, so must be read first.

4 another book comes along that really captures your attention, is amazing or timely and needs to be read immediately.

i can't think of any more at the moment.

for number one i think i'd like an abandoned shelf that doesn't eliminate the book completely, i like to own my mistakes, or maybe i'd have change of heart. either way, i'd like to remember i'd encountered the book.

for the rest i think some variation of pause would be good, or set aside or to be continued.

i have an attention deficit issue, so i rarely read just one book beginning to end. usually i'm bouncing around several at a time. I also reread parts of books, sometimes returning to parts multiple times. if a book can be read straight through i kind of feel like it's not worth reading. there are a lot of books in my currently reading list.

**Comment by joachimesque** [comment]
I like the idea of a dedicated shelf for "Abandonned" (or "Stopped") books. I already use one for the books I don't want to forget I started, and I think it would be great to have the setting in the dropdown menu, along with the "Remove from currently reading", which is for another use case (the books I want to forget I started).

**Comment by wakest** [comment]
I have recently had an issue where I was staying at my fathers house and started a few books there. And then I was staying with some friends and started reading a few books. It would feel weird to list those as “abandoned” per se, I will probably come back to them next time I am in a place that those books physically exist. It’s more like “don’t currently have access to copies of these books I started reading but would finish them if I did” a bit too long for a menu item though :)

**Comment by Tak** [comment]
+1 for an abandoned shelf

**Comment by tversteeg** [comment]
I would suggest naming the shelf "Partially Read", which I feel is a better fit than "Abandoned". "Partially Read" just states that the book isn't currently being read and that it isn't finished yet, without implying any reason for not currently finishing the book. I also feel this fits nice with the rest of the default shelves:

![image](https://user-images.githubusercontent.com/2574730/152329728-543441d8-8dd5-47c4-9244-95254a0916d4.png)
