### ISSUE TITLE
One Email Address Spam-registered in an instance I help co-admining

### ISSUE THREAD

**Issue by oragegu** [bookwyrm-social/bookwyrm#1387]
**Is your feature request related to a problem? Please describe.**
I have noticed that one particular email address has registered many accounts on an instance I help adminstering.
![image](https://user-images.githubusercontent.com/78921858/132580680-e92c41f8-da12-481a-9d37-e7d469aedd02.png)
I looked aroud a bit and didn't find any way to block spam based on email addresses.

**Describe the solution you'd like**
A way to block registration from certain email addresses.

**Describe alternatives you've considered**
We could make the instance 'invite-only', but that's sort of our last resort.

**Comment by mouse-reeve** [comment]
Ah yeah I can add this asap. Is it the same domain name, or is it the full address? For example, every spam user is using `<username>@spamdomain.com`, or are they using `sameusername+<spam>@gmail.com`?

Also if they do anything besides make profiles, can you let me know? I haven't had any spam accounts locally to my knowledge so I haven't seen what behavior their doing

**Comment by oragegu** [comment]
Thank you for the quick reply!

> Is it the same domain name, or is it the full address? For example, every spam user is using `<username>@spamdomain.com`, or are they using `sameusername+<spam>@gmail.com`?

They all came from the same gmail account, as in "sameusername@gmail.com". Normally it's one email address per account, but since the spammer never bothered to validate and confirm their email address, and instead just kept registrating new accounts, this person managed to flood the admin->user panel with his spam accounts.

I noticed this spam behaviour because there was a sudden deluge of failed mail delivery since yesterday/two days ago, and on clicking open one delivery status message, it read: '4.2.1 The user you are trying to contact is receiving mail at a rate that 4.2.1 prevents additional messages from being delivered. Please resend your 4.2.1 message at a later time. If the user is able to receive mail at that 4.2.1 time, your message will be delivered.'

**Comment by mouse-reeve** [comment]
Huh thank you!

**Comment by mouse-reeve** [comment]
The PR above will let you block email domains, I'll work additionally on not letting people multi-register email. It should be possible

**Comment by mouse-reeve** [comment]
Are they the exact same email? There's a uniqueness constraint in the database that should prevent that

**Comment by oragegu** [comment]
> Are they the exact same email? There's a uniqueness constraint in the database that should prevent that

After diving further into the spam log, no actually there are several spam email addresses, all from gmail. 

Though this looks very unusual. Normally the spam emails should be `sameusername+<spam>@gmail.com` as you have suggested, but there is no particular pattern among the usernames of the gmail addresses with a '4.2.1' delivery status message.

**Comment by mouse-reeve** [comment]
Alright, that's a relief from a database standpoint, but frustrating from an anti-spam standpoint, since it doesn't make sense to block all gmail accounts. 

The delivery status message sounds like it's coming from your email provider putting a rate limit on how many messages you send per hour. I ran into this a couple days ago on bookwyrm.social when hella people registered via the hacker news post, since my mailgun account only allows 100 messages per hour. 

Aside from the high volume of registrations, is it the username pattern that is indicating to you that they're spam?

**Comment by oragegu** [comment]
> The delivery status message sounds like it's coming from your email provider putting a rate limit on how many messages you send per hour. I ran into this a couple days ago on bookwyrm.social when hella people registered via the hacker news post, since my mailgun account only allows 100 messages per hour.

> ...it read: '4.2.1 The user you are trying to contact is receiving mail at a rate that 4.2.1 prevents additional messages from being delivered. Please resend your 4.2.1 message at a later time. If the user is able to receive mail at that 4.2.1 time, your message will be delivered.'

I understood it more as the gmail side has received way too many mails that the rate limit is reached. Besides, yyyyy.read is a small instance, and its mail sending rate has never passed 20/hour yet
![image](https://user-images.githubusercontent.com/78921858/132597140-7cfb4adc-d31c-4c98-88c6-a5ceb13ed7db.png)


> Aside from the high volume of registrations, is it the username pattern that is indicating to you that they're spam?

Indeed. The usernames from these 4.2.1 email addresses are all gibberish.

**Comment by mouse-reeve** [comment]
Yeah you're right, it sounds like the gmail account causing the problem. 

I'm not sure how to filter these out, since I can't see how to identify the email addresses themselves as spam. I guess the good news is that the email confirmation process is preventing them from activating their accounts, but it's frustrating that they're registering to many.

**Comment by oragegu** [comment]
> I'm not sure how to filter these out, since I can't see how to identify the email addresses themselves as spam. I guess the good news is that the email confirmation process is preventing them from activating their accounts, but it's frustrating that they're registering to many.

💔

What do you think of this: to be able to ban one particular email address?

**Comment by mouse-reeve** [comment]
It would be hard to prevent a user with a specific email address from registering, but you can currently disable accounts for active users, and I can expand the user admin controls to let you ban users who haven't confirmed their email addresses. Does that work for you?

**Comment by oragegu** [comment]
> It would be hard to prevent a user with a specific email address from registering, but you can currently disable accounts for active users, and I can expand the user admin controls to let you ban users who haven't confirmed their email addresses. Does that work for you?

Sounds great, thank you!

**Comment by mouse-reeve** [comment]
The changes are available in the production branch. For a user that hasn't confirmed their email, I think it's better just to suspend rather than fully delete - deletion will send out a broadcast activity to other instances, which is only necessary if the user has been able to do anything.

**Comment by oragegu** [comment]
@mouse-reeve 
> I think it's better just to suspend rather than fully delete - deletion will send out a broadcast activity to other instances, which is only necessary if the user has been able to do anything.

Yeah I agree. I think it is the best option we have to just suspend them.

I git pulled the code. When I tried to delete a spam account, the password of the user-to-be-deleted is demanded. 

In the end because most of the spam accounts come from big email providers like gmail and yahoo, I can't really just block these domains from registeration :(, so the workaround for the moment is to "Allow invitation demand", and before sending an invite link, I check with spam blacklists email addresses databases to make sure it's a genuine person behind the email address.
![image](https://user-images.githubusercontent.com/78921858/132895693-971521d6-3155-4545-9a2e-ca34df2bbe37.png)

**Comment by mouse-reeve** [comment]
I should have made the UI clearer - it's asking for your password, not the user's password. It's just a precaution since deletions are permanent.

I'm sorry you're having such a spam problem! If you have ideas about how to identify this type of spam I'm more than happy to work on that, but I'm not coming up with anything clever at the moment.

**Comment by oragegu** [comment]
> I should have made the UI clearer - it's asking for your password, not the user's password. It's just a precaution since deletions are permanent.

Nono, it was perfectly clear the UI you made. I at first thought it was asking for my password, but since that didn't work, I assumed it was asking for the user's password.

> I'm sorry you're having such a spam problem! If you have ideas about how to identify this type of spam I'm more than happy to work on that, but I'm not coming up with anything clever at the moment.

Guess we are just unlucky. For the moment we are just doing the manual email check-up. The service I am using is: https://cleantalk.org/price-database-api.

**Comment by mouse-reeve** [comment]
Oh it didn't work! Lemme take a look.

**Comment by mouse-reeve** [comment]
Hm, I just tried it in my test instance and it worked for me. Is it giving you an error that your password is incorrect, or is it a different error?

**Comment by oragegu** [comment]
> Hm, I just tried it in my test instance and it worked for me. Is it giving you an error that your password is incorrect, or is it a different error?

OH!!

My Bad!

I have been inputting the wrong password all along!

I am soso sorry for wasting your time on my mistake!

It works perfectly!

**Comment by mouse-reeve** [comment]
No trouble at all! Glad it's working :)

**Comment by mouse-reeve** [comment]
Would blocking an IP address or IP range help with this?

**Comment by oragegu** [comment]
> Would blocking an IP address or IP range help with this?

It would definitely help!

I think there might be a way to do it with nginx, but my limited nginx knowledge doesn’t allow me to find the way.

**Comment by mouse-reeve** [comment]
I opened an issue for that #1414
