### ISSUE TITLE
After updating to latest production branch, Home and Discover tab streams no longer populate

### ISSUE THREAD

**Issue by IcedEagle** [bookwyrm-social/bookwyrm#1393]
**Describe the bug**
After updating to the latest production branch of bookwyrm (commit 4c5f5d90ba56e096552833a446c8a94ac2a66ce6), I did a db migration, redis stream populate and things seemed fine at first glance. I then noticed after I deleted a post that things weren't updating correctly. Namely commenting on a book, reviews, quotation, reading goals or other actions you can take on the home tab. Upon deleting the streams and repopulating them, I can't get the streams to populate correctly, nor can I find any errors.

Similarly, the Discover tab is now empty of all activity. Even after re-enabling federation to bookwyrm.social and doing a stream repopulate to see if that helps.

If I go to my user page, I can see all of my user actions properly on there (and I went so far as to verify in postgre SQL that changes were committed), it's only the Home and Discover tab streams that are empty as far as I can tell.

I'm not super familiar with Celery, Flower, Redis, but looking at the logs I see the newer CELERY_BROKER_URL present, and Celery says it can connect to Redis. Flower shows Celery as online as well and I occasionally see tasks queued in it so that part seems to be working...?

I've deleted the stream, remade it, deleted the redis docker volumes, remade streams, etc. I can't get the streams to show up, nor find anything complaining of errors so I'm a bit lost unfortunately... Any direction of where to look would be greatly appreciated!

**To Reproduce**
1. Sync'd local instance to latest Production branch, commit 4c5f5d90ba56e096552833a446c8a94ac2a66ce6
2. Update containers, do db migration, do stream populate
3. Observed that the activites weren't being properly refreshed on the home screen
4. Deleted streams and attempted to remake them

**Expected behavior**
If I had bad stream data, repopulating them would either make the streams again, or show me an error if one is happening

**Screenshots**
Home tab
![image](https://user-images.githubusercontent.com/934801/132808625-79d8904e-4b32-45cd-865c-5b26b4eb77a6.png)

User tab showing activity that should be on the Home tab
![image](https://user-images.githubusercontent.com/934801/132809667-3eadaa47-24b6-4eb8-92fc-d1e5392b408d.png)

**Instance**
Local instance

**Additional context**

---

**Desktop (please complete the following information):**
    - OS: Pop OS
    - Browser Firefox
    - Version 93

**Comment by IcedEagle** [comment]
Anndddd of course as my last resort of just deleting absolutely everything except the database and trying everything again it works fine.

Docker shenanigans? Gremlins? Who can say. I used the same env, docker compose and nginx files and it works now regardless. Now to clean up all my test messages...

**Comment by IcedEagle** [comment]
Ah! I found my problem. The docker-compose was updated because of changes to celery queues. I was foolishly just keeping my same docker-compose file. I remade my compose file using the newly checked in one, and all seems fixed. Fingers crossed. I really should figure out a better way to handle this...

**Comment by mouse-reeve** [comment]
Ah yeah I added prioritized queues! Let me know if there's a way I can make supporting variations in docker-compose easier for you

**Comment by categulario** [comment]
I faced this when upgrading from `0.6.3` to `0.6.4`. Checking the differences between those tags and applying them worked for statuses posted _after_ the migration but I didn't recover the statuses _before_ the migration both in the Home and Discover sections.

did you manage to restore them @IcedEagle ?
