### ISSUE TITLE
Unable to post review in Safari on iPadOS

### ISSUE THREAD

**Issue by kopischke** [bookwyrm-social/bookwyrm#1407]
**Describe the bug**
When trying to post a long-ish review in Safari on iPadOS (desktop mode, content blockers disabled), the post button shows the spinner introduced with #1388, but the posting never concludes.

**To Reproduce**
1. Get an iPad pro 13.9” running iPadOS 14.7.1
2. Open your bookwyrm.social account in Safari, ensuring it runs in desktop mode and content blockers are disabled
3. Write a review of at least 2700 chars
4. Try to post it

**Expected behavior**
After some spinning, the review appears on your feed.

**Instance**
bookwyrm.social

**Extra context**
[Book I’m trying to review](https://bookwyrm.social/book/214201).

---

**Device Info:**
    - Device: iPad pro 2nd gen 13.9”
    - OS: iPadOS 14.7.1
    - Browser: Safari
    - Version N/A

**Comment by mouse-reeve** [comment]
Yikes, thank you for opening an issue! You're the second iOS user to report this problem. It's working fine for me on my Android phone and I don't have any iOS devices, so it's going to be a bit challenging for me to test this directly.

From what you're describing - it sounds like this is where it's hanging: https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/static/js/status_cache.js#L72. There doesn't appear to be any compatibility issues with the fetch function (https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#browser_compatibility).

Would it be possible for you to check the javascript console for an error (https://www.lifewire.com/activate-the-debug-console-in-safari-445798)? Having an error message would make it a lot easier to figure out where things are going awry.

**Comment by kopischke** [comment]
Thanks for the pointer, I think I have found the issue: the console complains that `undefined is not an object` on [the line you identified](https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/static/js/status_cache.js#L72), which can only mean that `trigger` is  undefined. As it turns out, Safari (desktop and iOS) does not support [`SubmitEvent`](http://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent), so, yeah, this can’t work on Safari. At all.

**Comment by kopischke** [comment]
(which is a pity, because the spinner and LocalStorage cached drafts are a huge step forward UX-wise)

**Comment by mouse-reeve** [comment]
Ah thank you so much! I should be able to have the form submit in the traditional way if the event trigger is populated correctly. I do have safari, happily, so I can properly debug this :)

**Comment by mouse-reeve** [comment]
This is live on b.s - let me know if you run into any more issues

**Comment by kopischke** [comment]
Can confirm this is fixed; [my review](https://bookwyrm.social/user/kopischke/review/51818) just went through. Thanks for the quick turnaround!
