### ISSUE TITLE
Block registration based on IP

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1414]
To avoid spam, let admins block IP ranges from registering new accounts. I'm not sure how to interface with nginx from the application admin panel, but I'm sure it can be done some way or another

**Comment by oragegu** [comment]
What do you think of a little Human-Friendly Bot-Unfriendly Test Question? Something like “why do you want to join this instance?”, or “what do you plan to do  on this instance?”

**Comment by mouse-reeve** [comment]
Yeah - that sounds super doable. Can you tell me more about how you're picturing this? Would you want that to be part of requesting an invitation, so that you can decide whether to approve it, or part of open registration, so you can verify afterwards? Or both?

**Comment by oragegu** [comment]
> Would you want that to be part of requesting an invitation, so that you can decide whether to approve it, or part of open registration, so you can verify afterwards? Or both?

I am thinking about both. And the question can be customised.

**Comment by oragegu** [comment]
Speaking of "requesting an invitation": I once tried to register an account at bookwyrm.social, but got intimidated by the "ask for an invitation" email form (at that time bookwyrm was very very young and it wasn't open registration).

I for some reason thought that by filling the form, it would send an email to the admin's email address, then the admin would reply to me and perhaps give me an invitation link. 

Of course after setting up my own instance, I realised that it was done automatically.

Do you think if there is the need to change the presentation of the invitation request a bit?

**Comment by oragegu** [comment]
But maybe it's just my brain being weird and misinterpret it.

**Comment by mouse-reeve** [comment]
I agree the wording could be clearer there - can you open a separate issue for it?

**Comment by oragegu** [comment]
Of course!

**Comment by oragegu** [comment]
Done!

And the IP blocking functions with no problems!
