### ISSUE TITLE
Admin dashboard stat doesn't zoom out properly

### ISSUE THREAD

**Issue by oragegu** [bookwyrm-social/bookwyrm#1432]
**Describe the bug**
When the ratio of number of active users : number of total users is too low, the stat graph doesn't zoom out properly

**To Reproduce**
1. Go to the Admin Dashboard of an instance with a low ratio
2. See error

**Expected behavior**
The graph should have zoomed out.

**Screenshots**
![](https://media.discordapp.net/attachments/794607556441931807/889170978662387732/IMG_3088.PNG)

In comparison to:

![](https://media.discordapp.net/attachments/794607556441931807/889171312398991420/IMG_3089.PNG)

**Instance**
https://yyyyy.club

**Additional context**

---

**Desktop (please complete the following information):**
    - OS: Windows
    - Browser: Firefox

**Smartphone (please complete the following information):**
    - Device: iPhone 11
    - Browser Safari

**Comment by mouse-reeve** [comment]
wonderful, thanks for the update!
