### ISSUE TITLE
not able to search for a user un-logged in

### ISSUE THREAD

**Issue by wakest** [bookwyrm-social/bookwyrm#1434]
No option to search for a user without being logged in even though it says books or users in the non logged in search field 

**Screenshots**
![B1B1BF6E-685C-4981-AC1C-FD393FC5DCDA](https://user-images.githubusercontent.com/7890201/134020800-b1b6b514-35a4-4afa-829f-652d6a7028ae.png)
![C1878A19-8A29-48BC-9993-3E105F743301](https://user-images.githubusercontent.com/7890201/134020810-e0d4dfc0-ce11-44e8-b01c-f939d8146b80.png)

**Instance**
bookwyrm.social

---

**Desktop (please complete the following information):**
iOS 12, Firefox

**Comment by mouse-reeve** [comment]
Thank you -- either that language should change, or logged out user search should be enabled. I made user search logged-in-only out of a general sense of user privacy, but I'd be interested to know if that's more of a hassle than a benefit.

**Comment by Flameborn** [comment]
I personally like it the way it works currently, it makes sense for small communities where members are trusted over non-members.

On the other hand, I can certainly see the benefits for large, or more open instances, where being able to find someone is preferred.

As a compromise, I can imagine a global and a per user setting to override it. This way, administrator(s) could decide whether users show up in public searches, while users could decide to accept this or go with the opposite respectively.

**Comment by mouse-reeve** [comment]
For now, since no one was expressed a desire to search for users while logged out, I'll just change the wording in the search box. But it's open to reevaluate in the future :)

**Comment by mouse-reeve** [comment]
Thank you! Your use case makes a lot of sense, and I'm totally happy to re-open this
