### ISSUE TITLE
Interface language picklist

### ISSUE THREAD

**Issue by Guanchishan** [bookwyrm-social/bookwyrm#1437]
BookWyrm is a great project, but here I would like to make a suggestion.

**Is your feature request related to a problem? Please describe.**
Users cannot choose the language of the interface they want.

**Describe the solution you'd like**
The settings page allows the user to select their desired interface language.

**Describe alternatives you've considered**
Use the mechanical translation that comes with users' own browser.

**Additional context**
At Mastodon, users can freely choose the language of the interface.
![image](https://user-images.githubusercontent.com/30859354/134042275-5248b1de-05ce-41d4-869a-b7300a5960ff.png)

**Comment by mouse-reeve** [comment]
Yes! Thank you, I have been vaguely meaning to do this for ages and just haven't yet.

**Comment by Guanchishan** [comment]
It looks like this issue is similar to #1025
