### ISSUE TITLE
Refactor about page

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1438]
Right now, the instance "about" page (for example, https://bookwyrm.social/about) shows the instance description and logo, a registration box (or your user profile if you're logged in), and then the code of conduct and privacy policy. It ends up being a wall of text, and while both those documents are important, they're a hard to scan and don't tell you a lot about an instance at a glance. 

I'd like to use this space to give more information about an instance that can be parsed more easily, and let users (and prospective users) drill down into the detailed policies when they are interested in that information.

Some general thoughts:
 - Emphasize the interpersonal relationship between the admins, mods, and users. A fundamental difference between bookwyrm and corporate social media is that bw is designed to be human-scale, and the site should make that clear.
 - Understanding how moderation works - when you report something, who sees it (this can be determined by user permissions, so these users can be displayed automatically) and what kind of actions will they take. 
 - Get a sense of "local flavor" - this may already be addressed by the instance description, but it's good to have space for an instance to communicate what it's about and what the vibe is.
 - Opening the door for users to participate in decision making for the project - I'd like users to feel like they have a say in how the project progresses, and feel heard about what works and doesn't work. And it's a huge help when people feel like they can and should report bugs or frustrations with the software. Right now these conversations are often on GitHub, which is a barrier to people who aren't coders. 
 - Users shouldn't have to understand (or care) about the technical concepts and jargon around federation and decentralization.

Specific thoughts:
 - Show the profile previews of the people who have moderation and administration perms
 - Add a panel about communication with admins (not just for reporting) with some pre-set content and some customizable content
 - Include some general, instance-non-specific information about what bookwyrm is
 - Move the code of conduct and privacy policy to respective pages

**Comment by mouse-reeve** [comment]
As always, I'd love to hear from any @bookwyrm-social/instance-admins who have thoughts ❤️

**Comment by oragegu** [comment]
> Specific thoughts:
> 
> * Show the profile previews of the people who have moderation and administration perms

Something like a little text section saying “This instance is administered with love by [x] and [y], moderated with care by [z] and [α]”, and [x] [y] [z] [α] links to the relevant profile pages? 

I think it would be nice. 

> * Include some general, instance-non-specific information about what bookwyrm is

How about putting this piece of information at bookwyrm.social instead? I find it making more sense to be on the most probable first landing page of a potential new user. 

> * Move the code of conduct and privacy policy to respective pages

What do you think of making them collapsible?


> *panel

Could you give some examples? I fail to picture in my head this panel.

**Comment by mouse-reeve** [comment]
Thank you for the feedback! Once I mock up some examples I'll post screenshots, it's still taking shape in my head too :)

> How about putting this piece of information at bookwyrm.social instead? I find it making more sense to be on the most probable first landing page of a potential new user.

The reason I was thinking of generalizing this was so that individual instances would be more legible to brand new users, in order to make bookwyrm.social less centralized to the network. But I definitely don't want to overload each instance with redundant information where it isn't helpful to the user or doesn't feel right to the admins.

> What do you think of making them collapsible?

My one concern is that this would make it harder to link to them and find them again.

**Comment by oragegu** [comment]
> Thank you for the feedback! Once I mock up some examples I'll post screenshots, it's still taking shape in my head too :)
> 
> > How about putting this piece of information at bookwyrm.social instead? I find it making more sense to be on the most probable first landing page of a potential new user.
> 
Sorry I wasn’t being clear. I meant putting this piece of info at your.bookwyrm.site, since this is where brand new users first land. Not all read the about page.

**Comment by mouse-reeve** [comment]
Oh thank you! I see now, and yeah, I think that's a good idea.

**Comment by oragegu** [comment]
> My one concern is that this would make it harder to link to them and find them again.

True. In this case your suggestion of having separate pages for them is definitely better.
