### ISSUE TITLE
upload cover from url when manually adding a book

### ISSUE THREAD

**Issue by wakest** [bookwyrm-social/bookwyrm#1443]
since you can upload a book cover from URL after a book has been created manually it would make sense to have the same feature before the book has been saved. also might be good to make some indication that there is no cover currently, even just an empty box with a x through it where the cover would go would do.

this is where the feature is missing
![image](https://user-images.githubusercontent.com/7890201/134197336-f910836b-5f5f-4e9a-809d-6cb67873ce36.png)

this is what it looks like when you click add cover from the book page after the book has been created (much better!)
![image](https://user-images.githubusercontent.com/7890201/134198997-efcc9743-d57c-45d8-8455-9f93f3d3fc07.png)

**Instance**
BookWyrm.social

**Comment by mouse-reeve** [comment]
Fixes by #1456
