### ISSUE TITLE
cover image fails to upload from url but works when downloading and reuploading same image

### ISSUE THREAD

**Issue by wakest** [bookwyrm-social/bookwyrm#1444]
**Describe the bug**
I was able to add this image
https://xexoxial.org/is/sites/default/files/imagecache/product_full/libraries_front_cover_sm.jpg
to this book https://bookwyrm.social/book/222875 but only by downloading it first and then reuploading

when I try to upload from URL for this image (seemed to happen with a few images from this domain) it says in little red text "failed to upload"

this is all on bookwyrm.social

**Comment by mouse-reeve** [comment]
That domain is returning an HTTP 406 response when it's queried programmatically, but a 200 when accessed directly. I tried setting different `Accept` headers to no avail, so it may be that the server doesn't want to serve images to programmatic services. If you're seeing this across more domains, please let me know, but I think this is just The Way It Is for that site.
