### ISSUE TITLE
Rereading Books Fails When You've Read the Book Within the Last 2 Days

### ISSUE THREAD

**Issue by bcj** [bookwyrm-social/bookwyrm#1472]
**Describe the bug**
If you have finished a book in the last 2 days (or possibly longer? also possibly only an issue if the start date is in the last 2 days), then clicking `Finish Reading` will attempt to adjust the read dates of your last read instead of creating a new entry

**To Reproduce**
1. Add start/finish reading dates for a book that are within the last 2 days
2. Click `Start Reading` on that book and select today as the start date.
3. Click `Finish Reading`. The listed start date will be from the previous read. Confirming will replace the read dates from the previous read.

**Expected behavior**
The two reads are treated separately. It is up to my friends on BookWyrm to stop me from endlessly rereading a book and not the site itself.

**Screenshots**
N/A (or available on request?)

**Instance**
BookWyrm.social

**Additional context**
I am sorry

---

**Desktop (please complete the following information):**
    - OS: macOS
    - Browser: Firefox
    - Version : 93.0b9

**Comment by mouse-reeve** [comment]
bcj, thank you for your weird reading habits.

**Comment by mouse-reeve** [comment]
I think this will be fixed by: https://github.com/bookwyrm-social/bookwyrm/pull/1455, which I will deploy today

**Comment by bcj** [comment]
Oh, nice. I can confirm later today then. Always glad to help

**Comment by mouse-reeve** [comment]
Just deployed

**Comment by bcj** [comment]
I've confirmed #1455 has fixed it. I'll go ahead and close. Thanks mouse!
