### ISSUE TITLE
Book search results are limited to 10 entries

### ISSUE THREAD

**Issue by Tak** [bookwyrm-social/bookwyrm#1479]
**Describe the bug**
When searching for a book, the results for the local instance seem to be truncated at ten entries, with no way to load more results.

**To Reproduce**
Enter a query with lots of results (in my case, "Adrian Tchaikovsky") into the global search bar

**Expected behavior**
Either all applicable results load, or some results load with a way to load more

**Actual behavior**
Maximum ten results are loaded, with "Load results from other catalogues" and disabled "Previous" and "Next" buttons

**Instance**
https://reading.taks.garden (`production` `cfc6528d0cddd72fa3a46568f4f60ccebaaec49f`)

---

**Smartphone (please complete the following information):**
    - Device: Pixel 2 XL
    - OS: Android 11
    - Browser: Firefox
    - Version: 92.1.1

**Comment by mouse-reeve** [comment]
Looks like this was fixes by #1413 and #1494

**Comment by Tak** [comment]
Nice! 🙂
