### ISSUE TITLE
Markdown paragraphs not respected in author descriptions

### ISSUE THREAD

**Issue by kopischke** [bookwyrm-social/bookwyrm#1482]
**Describe the bug**
Paragraph breaks in the Markdown for author descriptions are transformed into line breaks when displayed. This is inconsistent with how MD paras are displayed in book descriptions, with the latter being closer to expected behaviour in my, er, book (sorry).

**To Reproduce**
1. Go to [this author page](https://bookwyrm.social/author/33299)
2. Observe the lack of discernible paragraph breaks, despite two of them being present in the Markdown source.

**Expected behavior**
Paras display as paras.

**Instance**
bookwyrm.social

**Additional context**
I did the cache busting and reload dance, to no avail.

---

**Smartphone (please complete the following information):**
    - Device: iPad Pro 13.9”
    - OS: iOS 14.8
    - Browser: Safari
    - Version: N/A

**Comment by mouse-reeve** [comment]
Thank you! The wrapping element just needs the `content` class added.
