### ISSUE TITLE
French translation suggestion

### ISSUE THREAD

**Issue by oragegu** [bookwyrm-social/bookwyrm#1488]
**Describe the bug**
It’s not precisely a bug, more like a translation suggestion 

**To Reproduce**
1. Go search for a book that is not in the database
2. Add the book manually 
3. See the current translation 

**Expected behavior**
Instead of « série », wouldn’t « Collection » be more appropriate?

I am also having doubts for « première date de publication ». « Publication », isn’t this a bit anglicisme ? How about « première parution » and « parution »? 

**Screenshots**
![F8DF6281-3A7B-430C-8AB2-EF8638B9D53D](https://user-images.githubusercontent.com/78921858/135736383-73f4c782-3609-4036-9bec-1b966254a283.png)

—-
Edit:
Also for isbn, EAN13/EAN10; for description, résumé. 

If everyone is ok with it, I can create a pull request.

**Comment by mouse-reeve** [comment]
Thank you! Tagging in @joachimesque and @arkhi

**Comment by joachimesque** [comment]
From what I've seen on Bookwyrm, the field “Series” is specifically for books published as a series: the _Lord of the Rings_ series for example has _The Fellowship of the Ring_, _The Two Towers_ and _The Return of the King_. It wouldn't fit with the concept of a publisher's editorial collection (like _Tracts_, or Gallimard's _Collection Blanche_)… though in the english-speaking word, the term “series” is often used for editorial collections:

> A collection generally using distinctive, common formats and features. The title of a collection can be accompanied by the term "series" or its equivalents in other languages,[2] such as in the English-speaking world, for example, the Bibliothèque de la Pléiade, Découvertes Gallimard and Que sais-je ? are all termed book series instead of collections. 

https://en.wikipedia.org/wiki/Collection_(publishing)

For the term “Publication”, it's true that in French the word is more often associated with newspapers and magazines (https://www.larousse.fr/dictionnaires/francais/publication/64958). « _Parution_ » is a good alternative. « _Résumé_ » is also better than “Description”.

As for ISBN/EAN, I don't have an opinion, technically it looks every kind of good can carry an EAN13, but only books can carry an ISBN. I don't know what's the best choice.

**Comment by arkhi** [comment]
Hello…

Ditto for _Collection_ vs. _Série_; they are not the same thing in French. A _Série_ also has a specific order whereas a _Collection_ is more of an unordered group of works.

About _[Publication](https://www.cnrtl.fr/etymologie/publication)_ vs. _[Parution](https://www.cnrtl.fr/etymologie/parution)_, I understand from the CNTRL that the former (1840) has been used before the latter (1907) in French. The added benefit is that even English‑speaking people can understand both at the moment. The two being synonymous, I have zero preference though.

I don’t necessarily agree about _résumé_ being better than _description_; it depends on the intent. I personnaly feel _description_ is better as it can include a _résumé_ (a summary) whereas using _résumé_ would prevent describing other things that would not be the story itself, like what the book looks like, the process used to create the object or the content, etc.

_ISBN_ is internationally recognized for books so I would not touch that, but if there are better arguments than _let it be_, I’m all ears. :)

**Comment by arkhi** [comment]
All that being said, I agree the collection of a book would be nice information to add. That involves coding more than translating though.

**Comment by oragegu** [comment]
> I don’t necessarily agree about _résumé_ being better than _description_; it depends on the intent. I personnaly feel _description_ is better as it can include a _résumé_ (a summary) whereas using _résumé_ would prevent describing other things that would not be the story itself, like what the book looks like, the process used to create the object or the content, etc.

@mouse-reeve How about having two separate fields for résumé and description? One summarises the book, the other one other stuff. Other stuff as in « oh this book has won this and this award, oooh it’s critically acclaimed by this and this review/newspaper ».

**Comment by arkhi** [comment]
If we’re talking awards, it would be nice to have a dedicated field so that books can be sorted by awards and years. :)

**Comment by mouse-reeve** [comment]
Given the way the data is structured in the data sources, it would be challenging to separate out promotional material about awards and acclaim from promotional material that summarizes the book. Since it's written out rather than structured data, and it could be in any language, it wouldn't be feasible to create those fields automatically, and if it's added by users, I think @arkhi is right that having structured fields to show awards would be a simpler approach.

**Comment by oragegu** [comment]
Changed. As discussed, the only change is the parution one. Happy discussing with you all.
