### ISSUE TITLE
celery_worker can't connect to redis_broker (AUTH <password> called without any password configured for the default user)

### ISSUE THREAD

**Issue by airdogvan** [bookwyrm-social/bookwyrm#1509]
everything else seems to run without errors on docker-compose up except the one mentioned.

My .env file is exactly a copy/paste of the .env.prod.example file with the single difference that domain=my_domain.com .

The whole error message reads as follows:
celery_worker_1   | [2021-10-05 22:49:24,364: ERROR/MainProcess] consumer: Cannot connect to redis://:**@redis_broker:6379/0: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?.

So it doesn't seem to be a connection problem in the sense that celery apparently can find the redis_broker port but doesn't pass a password.  
As said the password is present in the .env file and that file is in the docker-compose:
  celery_worker:
    env_file: .env

Any help appreciated.  I'm probably missing something very obvious here but after quite a bit of research can't find it.

**Comment by mouse-reeve** [comment]
Huh! It does sound like the redis broker password isn't getting loaded properly in celery. A few things to check:
1. Are you on the `production` branch?
2. Is `REDIS_BROKER_PASSWORD` set? (it sounds like it is, just double-checking)
3. Does putting quotes around the `REDIS_BROKER_PASSWORD` help? In the past, there are have been character encoding weirdness with that

**Comment by mouse-reeve** [comment]
The compose file you sent me looks to the one on the `main` branch, not the `production` branch. There are a number of differences, but of particular importance for this is how the redis broker is run:

In the developer version on the `main` branch:
``` bash
command: ["redis-server", "--appendonly", "yes"]
```

Versus on the `production` branch:
``` bash
command: redis-server --requirepass ${REDIS_BROKER_PASSWORD} --appendonly yes --port ${REDIS_BROKER_PORT}
```

If you're on the production branch, I wonder if you may have accidentally copies the `main` version of the compose file while modifying it?

**Comment by airdogvan** [comment]
ok for the moment github can't connect so can't clone and start over.

So I'll have to wait till it becomes available...

**Comment by airdogvan** [comment]
that's what I did.
Anyway deleted everything and waiting for git to be available again.

**Comment by mouse-reeve** [comment]
Okay, let me know how it goes!

**Comment by mouse-reeve** [comment]
We resolved this configuration issue via email ❤️

**Comment by cdrum** [comment]
Darn. now I'm getting the same issue. was the config issue simple to fix?
