### ISSUE TITLE
User interface for adding translations

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1513]
I'd like to make translation more accessible to people who aren't familiar with git/command line (and less of a hassle for those that are). It looks like self-hosting [Weblate](https://weblate.org/) is the thing one can do at reasonable cost, and it should allow anyone who wants to keep directly editing .po files in git to do so. Does anyone have feelings or preferences on this? (@bookwyrm-social/translators)

**Comment by bayocr** [comment]
In the past I used [Crowdin](https://crowdin.com/), have you seen it?. I think they're good and they  have a plan for open source projects

**Comment by mouse-reeve** [comment]
Approved! I'm really excited about this
