### ISSUE TITLE
Delete and redraft doesn’t cache the deleted text properly 

### ISSUE THREAD

**Issue by oragegu** [bookwyrm-social/bookwyrm#1522]
**Describe the bug**
After clicking delete and redraft, the text box doesn’t contain the correct text

**To Reproduce**
1. Write a critique or reply to a bookwyrm status
2. Click on 'delete and redraft’

**Expected behavior**
The text body should be the one that was just deleted 

**Instance**
book.dansmonorage.blue

**Additional context**
When publishing a critique, the title is correctly preserved.

**Comment by mouse-reeve** [comment]
When you say the text is incorrect, do you mean because it was restyled with html? It should definitely save in the original format is was composed in, but if that's the extent of the problem, this issue is similar to #1141

**Comment by kopischke** [comment]
I think OP means “doesn’t contain the original review text at all”, because _that_ is a bug I have been experiencing (didn’t get around to reporting it yesterday), and I would be very surprised if there were two subtly different issues so similar.

**Comment by oragegu** [comment]
> When you say the text is incorrect, do you mean because it was restyled with html? It should definitely save in the original format is was composed in, but if that's the extent of the problem, this issue is similar to #1141

When I said text being in correct, I meant the brute pure text body. The format was correct.

**Comment by mouse-reeve** [comment]
Got it, thank you for the clarification!
