### ISSUE TITLE
Track Book Progress Out of Order

### ISSUE THREAD

**Issue by seniorm0ment** [bookwyrm-social/bookwyrm#1583]
Requesting a way to track book progress out of order.
Many books are books one wouldn't or may not want to read front to back, so they may hop around. Examples can be reference books, books with short stories, and so on.
This would allow the user to track the parts they have read, and have not.

Maybe merge the results as they progress. For example if they make an entry that they read Pages 50-60, then later they read 80-90, then they read 20-49 (as 3 different entries).
the list would update and say they read 49-60; 80-90.  Maybe the ability for a custom entry name so if they are names of short stories it will show "Story 1, Story 3" with the page numbers.

**Comment by hughrun** [comment]
Good idea. Also related to #1133

**Comment by mouse-reeve** [comment]
As far as I know you can already do this. Here's an example I tested locally -- the dates are all "today" but they're displaying in the order I created the updates:
<img width="705" alt="Screen Shot 2021-11-16 at 9 33 57 AM" src="https://user-images.githubusercontent.com/1807695/142036442-71ff3b1c-55d1-4e82-94ed-16e375ea8f32.png">

Am I misunderstanding the request?

**Comment by mouse-reeve** [comment]
I'm closing this since I think the existing behavior largely meets the request in the issue. Please feel free to re-open with clarification if there are additional changed needed. Thanks!
