### ISSUE TITLE
Make Page Title Match Shelf Name

### ISSUE THREAD

**Issue by TomatDividedBy0** [bookwyrm-social/bookwyrm#1586]
Rather minor suggestion, but it came to my attention when I was managing three of my shelves (To Read, Currently Reading, Audiobooks) across multiple tabs. In this screenshot I have each of the three open in separate tabs but they're indistinguishable. 

![image](https://user-images.githubusercontent.com/25469801/140374971-0e85db4e-1226-4a41-a2ec-ac0171e3f70e.png)

All of the page titles say "Your Books" when I think it'd make more sense to have it be the shelf title so people can identify tabs easier.

**Comment by mouse-reeve** [comment]
Thank you for the excellent suggestion, @TomatDividedBy0, and for the quick fix @hughrun. I appreciate you all very much ❤️
