### ISSUE TITLE
Lists not loading when logged in to bookwyrm.social

### ISSUE THREAD

**Issue by xthursdayx** [bookwyrm-social/bookwyrm#1587]
**Describe the bug**
I'm not sure if this should be posted as an issue here or not, but I've found that I am unable to view lists when logged into my account on bookwyrm.social. However I am able to view the same lists while logged out if I use the direct URL. I've tried both Firefox and Chromium and found the same issue with both. 

**To Reproduce**
1. Log into bookwyrm.social
2. Click on 'Lists'
3. Choose a list to view and click it.
4. See 502 Bad Gateway error. 

**Expected behavior**
I expected to be able to view the lists while logged in, since they're visible when not logged in. 

**Instance**
On bookwyrm.social. I am also self-hosting an instance, but do not currently have any lists on it, nor other local users with lists to try viewing. 

---

**Desktop (please complete the following information):**
    - OS: MacOS
    - Browser: Firefox & Ungoogled Chromium
    - Version: All up to date.

**Comment by hughrun** [comment]
This looks like another example of #1319

**Comment by xthursdayx** [comment]
> This looks like another example of #1319

Ah yes, I didn't see that issue for whatever reason when searching the existing issues. I'll close it. Thanks for the heads-up.

**Comment by hughrun** [comment]
@xthursdayx good to get another confirmation of the problem!
