### ISSUE TITLE
Timelines seemingly not updated 

### ISSUE THREAD

**Issue by Llaverac** [bookwyrm-social/bookwyrm#1590]
**Describe the bug**
When I’m logged on my account (Llaverac), on desktop or on mobile, I don’t see any new status past November 4th. In the Discover timeline for instance, the latest status displayed is this one: https://bookwyrm.social/user/Ri/comment/61388#anchor-61388 

**Instance**
bookwyrm.social

**Comment by mouse-reeve** [comment]
Thank you for reporting! I restarted celery which solved the problem in the short term, but leave this open while I try to add some bigger-picture/preventative fixes to reduce the risk of it getting stuck.

**Comment by mouse-reeve** [comment]
Should be fixed by #1600
