### ISSUE TITLE
List Followers You Know When Looking at User's Follower List

### ISSUE THREAD

**Issue by bcj** [bookwyrm-social/bookwyrm#1609]
**Is your feature request related to a problem? Please describe.**
When you look at a user's profile, the link to the user's followers will be titled 'X followers you follow', but the followers list is supplied in reverse-chronological order by date followed, with followers in common given no priority.
When trying to decide how to handle a follow request, seeing what people we both know is the most relevant information to me.

**Describe the solution you'd like**
Sort followers that I know (follow) ahead of all other followers when showing a users Followers list (honestly, sorting the Following list this way would be nice too)

**Describe alternatives you've considered**
Have a separate view for 'Followers you know' (and rename the link to the Followers list if it doesn't point to that list)

**Additional context**
Hi mouse

**Comment by mouse-reeve** [comment]
Yeah! I think the right approach is to add an annotation indicating the presence of a relationship to the queryset and then sort by the annotation + follow date in the view
