### ISSUE TITLE
`shelve_button` wipes out `disabled` state in shelf list dropdown

### ISSUE THREAD

**Issue by hughrun** [bookwyrm-social/bookwyrm#1626]
**Describe the bug**
If you add a shelf or change the read status by using the `read_status` button, only the new read status shelf is disabled regardless of whether the book is also shelved on them.

**To Reproduce**
1. Add a book to an editable (custom) shelf
2. Go to the book page
3. Click on the dropdown arrow and notice that your custom shelf is disabled
4. Click on 'Want to Read'
5. Click on dropdown arrow and notice that the custom shelf is no longer disabled

**Expected behavior**
Shelves the book is shelved on should persist their disabled state when reading status is changed.

**Instance**
Bookwyrm.social and `main`.

**Additional context**
I can't even work out what is causing this, but somewhere in `status_cache.js` seems like the most likely culprit.

---

**Desktop (please complete the following information):**
    - OS: Mac
    - Browser: Firefox, Chrome

**Comment by mouse-reeve** [comment]
Oh I bet it's the stuff around line 189 in that javascript file in `cycleShelveButtons`... my bad

**Comment by mouse-reeve** [comment]
I'm closing this because it is very old! I hope it's not still broken?
