### ISSUE TITLE
Some translation strings missing/not applied

### ISSUE THREAD

**Issue by nycterent** [bookwyrm-social/bookwyrm#1637]
**Describe the bug**
Some translations are not being applied.

**To Reproduce**

change Bookwyrm language to other than English (tested with Lithuanian)

https://ziurkes.group.lt/user/athinkingmeat/books/read
https://ziurkes.group.lt/user/athinkingmeat/books/reading
https://ziurkes.group.lt/user/athinkingmeat/books/to-read

**Expected behavior**
All these links should have "read", "currently reading" and "to read" strings translated, but they are shown in English

**Screenshots**

![image](https://user-images.githubusercontent.com/81133/143778383-c5e6f8b2-4925-4060-a886-e40b9b6361fb.png)

![image](https://user-images.githubusercontent.com/81133/143778390-5ba3cc06-6744-4a60-a855-27fb3202f690.png)

![image](https://user-images.githubusercontent.com/81133/143778375-e799c900-1737-4025-8d1e-80ea99b3df81.png)

**Instance**

https://ziurkes.group.lt/

**Additional context**
Probably is a problem with other languages as well

**Comment by hughrun** [comment]
This looks like the bug reported in #1566 and fixed in #1572.

This fix was pulled into the `production` branch on 25 October so if `ziurkes.group.lt` hasn't been updated since then, doing an update to the latest production branch code should fix the issue.

**Comment by nycterent** [comment]
i am tracking production branch and i can see i have these files in my
instance

maybe some cache might interfere?

m

**Comment by hughrun** [comment]
It's not your cache, this is happening because of the way the shelf template is set up interacting with default shelf names. I'll take a look, we had to fix this in some other places as well.
