### ISSUE TITLE
Certbot image not renewing automatically

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1641]
The certbot renewal process should be running regularly, but it is not. Running `docker-compose run certbot` does work correctly, it just isn't running automatically.

**Comment by hughrun** [comment]
I've had this issue on my Mastodon server - could be to do with cron user permissions or environment params.

**Comment by hughrun** [comment]
@mouse-reeve what is the mechanism for actually running the `renew` command? I see there is a cron setup for postgres backups, is there one for certbot renewals as well? The certbot container would normally just run once when you `--build` and then shut itself down, from what I understand.

**Comment by mouse-reeve** [comment]
I think at some point, at least in theory, it was intended to keep the image running, and certbot would periodically re-try the renew command. At this point, I think there fully is no mechanism to schedule the renewals, and you're correct that it just runs once and then shuts itself down

**Comment by hughrun** [comment]
I've had a bit of a read and it looks to me like the best mechanism would be to set up a cron in the host machine to activate the container and run the renew command. If `docker-compose run certbot` already works without causing any port conflicts then I think it should be as simple as a cron job on the host machine to just run that every day:
```
5 0 * * * docker-compose run certbot renew --webroot --webroot-path /var/www/certbot
```

**Comment by mouse-reeve** [comment]
Agreed! I think adding that to the documentation is the fix.

**Comment by hughrun** [comment]
ping @mouse-reeve is the proposed documentation fix ok?

**Comment by mouse-reeve** [comment]
woops thank you! I'm neglecting this poor repo. I actually only have to run `docker-compose run --rm certbot` and the `renew --webroot --webroot-path /var/www/certbot` part is in the docker-compose file
