### ISSUE TITLE
Give users the option to embed lists in other websites

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1646]
Similar to how spotify playlists can be embedded in websites, it would be cool for users to be able to embed a list in their own blog or website.

I think this is pretty straightforward, and would entail:
1. Creating an alternate list view that uses the same Django view with a simplified template designed to look nice in an embed
2. Generating an iframe html that can be copied and pasted

(suggested by Erik Kemp on matrix)

**Comment by joachimesque** [comment]
If nobody's taken it I'll give it a try!

**Comment by mouse-reeve** [comment]
go for it :)

**Comment by hhofner** [comment]
Is there anyway to get an embed for "Currently Reading"?
