### ISSUE TITLE
Update developer instructions

### ISSUE THREAD

**Issue by seedlingattempt** [bookwyrm-social/bookwyrm#1665]
**Describe the bug**
Following the developer instructions point by point is going to lead a new contributor to experience some things that appear to be genuine errors but are just an effect of instructions being unclear. The developer is instructed open up the `http://localhost:1333` server before doing `./bw-dev collectstatic` which makes the nginx respond with `404` to all requests made to `/static/` and `/images/`.

Another point of pain for developers and users alike is the lack of a clear way to create a superadmin user without an email setup. This could potentially hurt new contributors and hopeful instance admins alike due to inherent clunkiness of email in general. Since that is a bigger issue not only concerning developers it will be left to another issue.

**To Reproduce**
1. Go to https://docs.joinbookwyrm.com/developer-environment.html
2. Follow the instructions on a completely clean docker setup (no previous volumes)
3. When build is done, follow the instructions and go to `http://localhost:1333`
4. See visual errors (missing images and styling) as well as console errors (404 for all static resources and images)

**Expected behavior**
A chronological instruction which tells you to go to the localhost only when the above mentioned resources are actually populated using the `collectstatic` script.

**Comment by cincodenada** [comment]
>Another point of pain for developers and users alike is the lack of a clear way to create a superadmin user without an email setup. This could potentially hurt new contributors and hopeful instance admins alike due to inherent clunkiness of email in general. Since that is a bigger issue not only concerning developers it will be left to another issue.

So to make sure I'm understanding this correctly: is this mainly about superusers, or about creating users without an email? There are instructions on how to create a superuser here, that could probably be added/referenced in the developer setup as well:
https://docs.joinbookwyrm.com/installing-in-production.html#configure_your_instance

But that still requires signing up with the regular UI, which I think still requires an email - I don't remember how I initially got my user set up in local dev. Is that something that exists?

**Comment by seedlingattempt** [comment]
> So to make sure I'm understanding this correctly: is this part mainly about superusers, or about creating users without an email? 

It's mainly about creating users without an email setup. The idea would be to maybe have a script that can fetch and print the validation code for a user, so that you can validate them without an existing email setup, because I believe that that part is a big step that makes it harder for people to setup their own instances. (At least it was for me)

In the current validation paradigm however it might not be a very good idea to allow for people to run instances without an email-setup which handles all of this. I just think that right now, at this stage in the projects life, it could benefit from having a lot of people trying to setup their own instances and mail-setups is one of the bigger hurdles in my opinion 🙂

**Comment by mouse-reeve** [comment]
@cincodenada you probably set it up before that feature existed!

Requiring an email confirmation to create a user can be disabled in the site settings. Right now, it's enabled by default, which, as you point out @seedlingattempt, is good for production (although creating the superuser without it would probably be helpful), but a huge hassle for development.

**Comment by viviicat** [comment]
Would there be any easy way to make the email confirmation setting a docker env var (email confirmation on by default of course)? IMO that would make the initial dev setup simpler.

**Comment by mouse-reeve** [comment]
I'm adding a UI-based flow to create the initial admin user, which circumvents the email confirmation, and also gives some helpful feedback on the state of the install in #1949. I really appreciate yall flagging this, it's a major pain point in settings up a dev instance
