### ISSUE TITLE
[Bug] Shelves and remove from things are... weird?

### ISSUE THREAD

**Issue by nerdteacher** [bookwyrm-social/bookwyrm#1693]
Sorry, I have no idea how to make a title, and I didn't see this listed? (But it might have been, and I apologise if I overlooked it.)

But when you click 'move book', there's some wild stuff happening? And all of my books have multiple "Remove book from..." entries that I don't quite understand. This is the most egregious example, but pretty much every book I looked at is uh... full of "Remove book from Read."

Just a head's up! If it wasn't known. If not, just an accidental new post.

![image](https://user-images.githubusercontent.com/77229429/146966246-e460794c-e112-4387-ad46-080d001b2cee.png)

**Comment by mouse-reeve** [comment]
oh no! This is a known bug (#1643), but wow you sure are taking the brunt of it, sorry about that.

**Comment by nerdteacher** [comment]
Haha, it's no worries! But thanks for letting me know it's a known bug, too. (And yes, it's uh... most of them are between 3-6 "Remove from" entries, but this one was absolutely wild... I'm also super confused about the "Remove from Gustav..." one because... that is not a shelf I have or have ever had, ahahaha).

Good luck and good work! <3
