### ISSUE TITLE
OpenLibrary imports don't work on bookwyrm.social

### ISSUE THREAD

**Issue by tastytea** [bookwyrm-social/bookwyrm#1694]
**Describe the bug**
I'm getting HTTP error 500 when I try to import a book from OL or update the metadata of a book from OL. Searching by OL-ID doesn't work.

**To Reproduce**
1. Search for [OL35718808M](https://openlibrary.org/books/OL35718808M/Warden)
2. Nothing is found
3. Search for [9780241402450](https://openlibrary.org/books/OL32732512M/The_Dawn_of_Everything)
4. The book is found, but importing doesn't work

**Instance**
bookwyrm.social

---

**Desktop (please complete the following information):**
    - OS: Gentoo Linux
    - Browser Firefox 
    - Version 91.3.0esr

**Comment by xplosionmind** [comment]
Same here.

---

MacOS  12.1
Firefox 95.0.2

**Comment by mouse-reeve** [comment]
This should be fixed by https://github.com/bookwyrm-social/bookwyrm/commit/09f5218f9cd0e070ae3eec0c8263580642005f4a, and is live now. I tested a couple places and it seems to be working correctly now. Thank you both for reporting!
