### ISSUE TITLE
WARNING: The REDIS_ACTIVITY_PASSWORD variable is not set. Defaulting to a blank string

### ISSUE THREAD

**Issue by oragegu** [bookwyrm-social/bookwyrm#1696]
**Describe the bug**
While updating, when I docker build the following warnings are shown:
```bash
WARNING: The REDIS_ACTIVITY_PASSWORD variable is not set. Defaulting to a blank string.

WARNING: The REDIS_ACTIVITY_PORT variable is not set. Defaulting to a blank string.                                   

WARNING: The REDIS_BROKER_PASSWORD variable is not set. Defaulting to a blank string.                                   

WARNING: The REDIS_BROKER_PORT variable is not set. Defaulting to a blank string.
```

But these parameters are well present in `.env`.

**To Reproduce**
1. git pull
2. docker build

**Expected behavior**
No warning should be shown

**Screenshots**

**Comment by mouse-reeve** [comment]
Is this on the production branch?

**Comment by oragegu** [comment]
> Is this on the production branch?

yes it is.

**Comment by oragegu** [comment]
Guess it’s just a glitch. After restarting the containers everything is fine

**Comment by mouse-reeve** [comment]
Thanks for following up on this! I'm glad it's working now, even if the cause remains mysterious.
