### ISSUE TITLE
Can longer delete book reviews/comments on iPhone 

### ISSUE THREAD

**Issue by oragegu** [bookwyrm-social/bookwyrm#1697]
**Describe the bug**
A few collapsible buttons the collapsed menus of which are not shown

**To Reproduce**
1. Go to the home feed of bookwyrm
2. Click on ‘more options’ of a book review 

**Expected behavior**
When clicking on ‘more options’ of a book review/comment, the collapsed options should be shown. 

**Screenshots**

The clicked and the not-yet-clicked ‘more options’ button look almost identical. 
![37C88C7B-51C5-4CD2-9290-D794D844AFF6](https://user-images.githubusercontent.com/78921858/147167236-4dc6aca0-40cf-419f-be58-d4710be4791d.png)

![7FA7FFEE-6270-40F5-B265-EC7429046DB3](https://user-images.githubusercontent.com/78921858/147167226-4cd60cf2-c47b-43a5-9bcd-c5b8cbf1abff.png)

**Smartphone (please complete the following information):**
    - Device: iPhone X
    - OS: newest 
    - Browser safari

**Comment by mouse-reeve** [comment]
I think that this will be fixed by https://github.com/bookwyrm-social/bookwyrm/pull/1689 -- thank you so much for reporting

**Comment by mouse-reeve** [comment]
This should be working (it is for me in safari on my laptop) but please let me know if you're still having issues on your phone. Thank you!
