### ISSUE TITLE
Order not kept between pages in a pagination

### ISSUE THREAD

**Issue by joachimesque** [bookwyrm-social/bookwyrm#1713]
## Describe the bug

When look at my books, the `read` shelf ;
I sort them by Rating ;
Then I click on the second page ;
Some common books appear on both pages.

As you can see on the screenshots, the first and last  books on page 1 (Seveneves, local id: 650, and Ministry for the Future, local id: 58) are found on page 2 in position 3 and 6.

## Expected behavior

Each book appear only once in all the pagination.

### Page 1

![image](https://user-images.githubusercontent.com/1781070/147603892-b2df1423-1683-4af5-b015-65121e50b333.png)
https://lire.boitam.eu/user/joachim/books/read?sort=-rating&page=1

### Page 2

![image](https://user-images.githubusercontent.com/1781070/147603925-70689aff-4a05-48fc-a108-e2151d1d44c8.png)
https://lire.boitam.eu/user/joachim/books/read?sort=-rating&page=2

### Page 3

![image](https://user-images.githubusercontent.com/1781070/147604011-ab960044-a15c-4c07-8fbc-3946512b1b62.png)
https://lire.boitam.eu/user/joachim/books/read?sort=-rating&page=3

**Comment by mouse-reeve** [comment]
This is so weird; the does seem to be being applied on each page. I wonder if it's related to #1643?

**Comment by hughrun** [comment]
@joachimesque Couple of questions to help debug this:

1. does this also happen when you sort in other ways (e.g. start, finish, shelved)?
2. is it possible that you rated these books on two separate occasions?

**Comment by cincodenada** [comment]
I wonder if this is because we're sorting by rating, and a bunch of the ratings are the same, so we're not guaranteed an ordering between pages? I'm not 100% sure how Postgres behaves in that situation, but it might be worth adding a second sort field (probably title?) so we have a stable sort and see if that fixes it? I haven't been able to reproduce this locally yet.

**Comment by mouse-reeve** [comment]
@joachimesque Are you still seeing this now that #1740 is live?

**Comment by joachimesque** [comment]
I don't see it anymore, thank you!
