### ISSUE TITLE
Inconsistent Cover Scaling on Recap Page

### ISSUE THREAD

**Issue by TomatDividedBy0** [bookwyrm-social/bookwyrm#1731]
Seems that with certain numbers of qualifying books (such as 3) that covers scale inconsistently. Seems that covers get larger if there's less books, but honestly I think it'd just be fine if the size was the same irrespective of book count.  Either way here's an image and the corresponding link.

![image](https://user-images.githubusercontent.com/25469801/147711660-9998d2dc-9370-4bd6-b8ad-eb826994bfc7.png)
http://bookwyrm.social/user/SolidusSnake/2021-in-the-books?key=0356629e30524da2ae025964c2726e7f

**Comment by cincodenada** [comment]
It looks like the issue here is that the width/height isn't specified at all for that row, so we're at the mercy of the size of the original images here. I'll dig in here and see if I can throw some limits on there :)

**Comment by cincodenada** [comment]
Okay, I was incorrect here, the CSS grid is constraining things for us just fine, more or less - what you're seeing here is that books you rated 5 stars are rendered twice as big as the rest, which is a nice effect if you have more books to fill the grid, but as-is with smaller numbers of books it can look a little funky. I don't know what would be better to do here though - we could disable the 5-stars-is-bigger functionality below a certain threshold of books I suppose?

Here's an example of my page with more books, to show what the intention is: http://bookwyrm.cincodenada.com/user/cincodenada/2021-in-the-books?key=87a84f24b9244e53882cb45248d38036

**Comment by joachimesque** [comment]
You're right, the handling of that grid is not ideal.

The idea of disabling the 5-stars-is-bigger functionality below, let's say, 10 books (2 lines on the widest desktop screen), is good for a start.

I'm also thinking of densifying the grid a little bit, to have 6 columns on the widest desktop screen. That should cause less problems with big covers filling some columns and leaving some others empty

**Comment by joachimesque** [comment]
Here's what it looks like with a six-column grid and less white space around the "big" covers: http://lire.boitam.eu/user/joachim/2021-in-the-books?key=2f0c38451e69471bb186707b4af996eb

**Comment by TomatDividedBy0** [comment]
Seems like it's still bugged, this time with alignment issues. Profile is the same as the one I linked in the OP.

![image](https://user-images.githubusercontent.com/25469801/150467290-3471703c-750e-4972-851a-23afd28d0adb.png)
