### ISSUE TITLE
Receive '403: forbidden' when registering new account

### ISSUE THREAD

**Issue by jaqarrick** [bookwyrm-social/bookwyrm#1777]
**Describe the bug**
When attempting to register a new account I receive a `403` status from the `/register` endpoint. 

*Full message:*
> 
> CSRF verification failed. Request aborted.
> 
> You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.
> 
> If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for “same-origin” requests.
> 

A friend reported this to me and I was able to reproduce. Cookies are not disabled on my browser. 

**To Reproduce**
1. Go to https://bookwyrm.social/
2. Fill in new user form and click "Sign Up"
3. Observe failed request and 403 response. 

**Expected behavior**

**Screenshots**
<img width="798" alt="Screen Shot 2022-01-06 at 2 35 53 PM" src="https://user-images.githubusercontent.com/32184074/148462597-dead2839-f237-4523-b821-bb0f3055214e.png">
<img width="819" alt="Screen Shot 2022-01-06 at 2 34 21 PM" src="https://user-images.githubusercontent.com/32184074/148462625-136f0f46-4fd9-48a9-a02c-df628225c87e.png">

**Instance**
bookwyrm.social

---

**Desktop (please complete the following information):**
    - OS: macOS 12.1
    - Chrome Version 96.0.4664.110

**Comment by hughrun** [comment]
I can replicate this too. On a fresh dev install my first user goes through but the second one in a brand new incognito window gets this error. @mouse-reeve could this be something to do with the new caching setup?

**Comment by mouse-reeve** [comment]
Thank you so much for reporting this promptly @jaqarrick and for fixing just as quickly @hughrun!

**Comment by mouse-reeve** [comment]
Frustratingly, this is going to also effect all the other template caches I did. I can replace them with query caches though. Nothing reveals bugs like pushing to production :)

**Comment by JigmeDatse** [comment]
I'm not sure it's the same bug, or a different bug, but something very similar is happening for me on ramblingreaders.org on logging in.  It doesn't seem that it's preventing the login, but on logging in after having been logged out I get a similar (though I don't think identical) error about CSRF verification failed.  Do they need to update?  Or is there something about what's going on here something on my end (client)...

**Comment by mouse-reeve** [comment]
That sounds like an unrelated issue, I wonder if it's as simple as a form missing a csrf token. Can you open a new issue for this?
