### ISSUE TITLE
I want to be able to set the log level independently of prod/dev

### ISSUE THREAD

**Issue by cincodenada** [bookwyrm-social/bookwyrm#1787]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to be able to turn on more verbose logging in production to track down an issue. I'd like to be able to do that via an environment variable

**Describe the solution you'd like**
I'd like a `LOG_LEVEL` environment variable or similar in `.env` that adjusts what types of messages are logged.

**Describe alternatives you've considered**
I think the main alternative is the current setup, where there are (I think?) different logging levels in dev/prod, which makes it hard to track down production issues

**Additional context**
[Matrix conversation](https://matrix.to/#/!zoxBMxLlvIyeEKkHuB:matrix.org/$yBr16_gvZ6pHHhFDUsDArypuxjR7E5qOuV1OgROLQS4?via=matrix.org&via=tchncs.de&via=privacytools.io)

(this is a note-to-self, I literally have an implementation of this sitting around uncommitted on my server, so _definitely_ ping me if I don't get it up as a PR this weekend)

**Comment by mouse-reeve** [comment]
Fixed by #1802
