### ISSUE TITLE
Let admins set default interface language

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1791]
Right now, BookWyrm's interface language is determined by, in order of preference:
1. The language selected in the user's settings
2. The language requested by the browser, if it's available in the app
3. English

Admin should be able to set the default display language of the interface for logged out viewers and users that don't have a preference saved.

**Comment by hughrun** [comment]
Does `DEFAULT_LANGUAGE` from `.env` not do this already? And regardless of that, would it be preferable to set the default language from the admin web interface rather than `.env`?

**Comment by mouse-reeve** [comment]
Nope, all that does is prefer that the default edition of a book be in the provided language -- which is super non-obvious from context. Also it assumes the language field on the book is in English. Not one of the most fleshed out options 😬 

And yeah agreed, having an option in the admin panel to set language would be the best solution.

**Comment by mouse-reeve** [comment]
Based on https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#how-django-discovers-language-preference it sounds like it will only be practical to set language code in the `.env` file, rather than the site settings interface. The alternative appears to be writing custom locale middleware, which I don't think has benefits that outweigh how much hassle that would be.
