### ISSUE TITLE
User confirmation

### ISSUE THREAD

**Issue by joachimesque** [bookwyrm-social/bookwyrm#1806]
**Describe the bug**

When a new user has not yet confirmed their email address, if the site settings change to disable email address confirmation, the user's status stays inactive and the code doesn't work.

**To Reproduce**

1. Site settings: email confirmation ON
2. Register new user
3. Do not confirm their email with `confirmation_link` or confirmation code
4. Site settings: email confirmation OFF
5. user is inactive
6. `confirmation_link` or confirmation code seem not to work

**Expected behavior**

User confirmation should work even when the setting for email confirmation is off

**Comment by hughrun** [comment]
This would be awesome because I make this mistake every single time I am testing something on a fresh dev instance 🤣
