### ISSUE TITLE
Make Book Title a Link in Activity Pub Posts

### ISSUE THREAD

**Issue by bcj** [bookwyrm-social/bookwyrm#1813]
**Is your feature request related to a problem? Please describe.**
On BookWyrm, the title of a book is a link to that book's listings in both reviews and "want to read" posts. When viewing those posts on Mastodon (and presumably other ActivityPub sites), "want to read" links the book but reviews don't. I'll often read BookWyrm posts from another account and it would be nice to need one fewer click to add a book to my reading list.

**Describe the solution you'd like**
I would like the quoted title of a book at the beginning of a review to be a link to that book's page.

**Describe alternatives you've considered**
Add a "want to read" button on review posts (honestly, I like the idea of both of these happening. I assume this one is slightly more work)

**Additional context**
BookWyrm is good I like it.

**Comment by mouse-reeve** [comment]
It turns out the `name` field does't support html, so for reviews, the link should be added to the body, instead of the header

**Comment by mouse-reeve** [comment]
Since this is a constraint on how Articles work, I'm going to close this as just too hard to address. Sorry bcj!
