### ISSUE TITLE
Logo in onboarding dialog is not being size-limited

### ISSUE THREAD

**Issue by cincodenada** [bookwyrm-social/bookwyrm#1839]
**Describe the bug**
There appears to be no size-limiting on the onboarding dialog, as a large logo image is being rendered apparently full-size:

**To Reproduce**
1. Set the logo image to a high-resolution/large image
2. Go through the onboarding process
2. Look at the header of the dialog

**Expected behavior**
The logo is limited to a couple line's worth of text or so in height

**Screenshots**
![biglogo](https://user-images.githubusercontent.com/479715/149884096-182fb903-f8c7-40c8-8fc3-a26a4d6cc475.png)

**Instance**
https://ziurkes.group.lt

---

**Desktop (please complete the following information):**
    - OS: Xubuntu, I think, 20.04
    - Browser Firefox
    - Version 94

**Comment by officialkzhang** [comment]
Hello! I'm a student in an Intro to SWE class, and I was looking for an issue for a "first contribution" assignment. Can I attempt this issue, and would you say it's beginner-friendly?

**Comment by mouse-reeve** [comment]
Yes! Please do -- it should be a matter of adding the right class the HTML element in the template. Let me know if I can help point you to the right places

**Comment by officialkzhang** [comment]
Hello! So I've found a working class for the image HTML element that will allow the image to be a reasonable size, however, I can't seem to locate where to add this class? Is there a JavaScript file that I could locate when exactly the onboarding logo would be produced, and therefore add the class? Or does the usage of Bulma prohibit directly adding classes to a CSS element?

**Comment by mouse-reeve** [comment]
Ah, you've run afoul of the arcane templating system! It's all rendered in Python using Django templates, which live in `bookwyrm/templates/` -- this is the spot you're looking for: https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/templates/get_started/layout.html#L15

**Comment by mouse-reeve** [comment]
Fixed by #1872
