### ISSUE TITLE
Server error on adding read start date

### ISSUE THREAD

**Issue by tonzyl** [bookwyrm-social/bookwyrm#1842]
**Describe the bug**
Over the past days I get a server error when setting a read start date.

**To Reproduce**
1. Go to ['book page'](https://bookwyrm.social/book/111431)
2. Click on +Add read dates, set start date
3. See server error when loading https://bookwyrm.social/create-readthrough

**Expected behavior**
Start date saved and book visibile in current reading list.

**Instance**
bookwyrm.social

**Additional context**

---

**Desktop (please complete the following information):**
    - OS: MacOS 11.2.3
    - Browser Firefox 95.0.2

**Comment by mouse-reeve** [comment]
I believe this will be fixed by #1838
