### ISSUE TITLE
Your books: All books: shelved date is incorrect

### ISSUE THREAD

**Issue by coffeeshopped** [bookwyrm-social/bookwyrm#1846]
**Describe the bug**

I just started using Bookwyrm, and added 4 books as "To Read". On my "All Books" page, the "Shelved" dates for 3 of those books are incorrect. https://bookwyrm.social/user/chorist/books

If I click over to my "To Read" page however, the Shelved dates are all correct (all showing "today").

**Screenshots**

<img width="1181" alt="Screen Shot 2022-01-18 at 4 52 23 PM" src="https://user-images.githubusercontent.com/557851/150031715-652dc082-a45a-4e71-af7f-efc34dfb0de9.png">

**Instance**
bookwyrm.social

**Desktop (please complete the following information):**
    - OS: MacOS
    - Browser: Safari
    - Version 15.2

**Comment by mouse-reeve** [comment]
Oh thank you! I think this is an unintended side effect of #1740 -- this view actually isn't getting the shelve date so it's displaying some nonsense value there, when it should just not try to show that columns.

**Comment by cincodenada** [comment]
Ah shoot, I thought about this when looking at that PR but forgot to mention it. I wonder if we could show an Added Date here instead - which would I guess be the earliest date the book was shelved in any shelf, I guess? I'd have to dig in to see if that's feasible with how we're doing the query building and things.
