### ISSUE TITLE
Allow adding a short description for each book in a list, prefereably with some markup (links) allowed

### ISSUE THREAD

**Issue by cincodenada** [bookwyrm-social/bookwyrm#1863]
**Is your feature request related to a problem? Please describe.**
For many lists, I would like to add a short blurb about the book, and why I added it to the list - in the motivating case I'd also like to include an external link to more info for each book.

**Describe the solution you'd like**
When adding a book to a list, have an optional text box to add a short description for each book, specific to the list it is being added to.

**Describe alternatives you've considered**
You could, like, add a list of the books to the list description with small descriptions there, but that seems like a pain to maintain and use.

**Comment by mouse-reeve** [comment]
Oh yes! I've been meaning to do this. It should be quite straightforward

**Comment by mouse-reeve** [comment]
Hilariously, there's actually already a field in the database for this, just no UI for it
