### ISSUE TITLE
Improve bot management with robots.txt

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1871]
Looking at traffic to bookwyrm.social, there is a huge amount of traffic coming in from various bots. Adding politeness settings for them could help reduce load.

Top bots:
1. AhrefsBot/7.0; +http://ahrefs.com/robot/
2. SemrushBot/7~bl; +http://www.semrush.com/bot.html
3. DotBot/1.2; +https://opensiteexplorer.org/dotbot
4. BLEXBot/1.0; +http://webmeup-crawler.com/
5. MJ12bot/v1.4.8; http://mj12bot.com/
6. PetalBot;+https://webmaster.petalsearch.com/site/petalbot

**Comment by willhoh** [comment]
I'm new to contributing on github and also relatively new to web programming. However, I would take this task to also learn about SEO and more about django. Would that be ok?

**Comment by mouse-reeve** [comment]
Sure thing! The robots.txt file can be found: https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/templates/robots.txt.

**Comment by willhoh** [comment]
Thanks. I already did some research and would ask if I should realize this with the robots.txt or **django-robots** app?

Should I also try to delay the requests up to 10 seconds (some bots allow this) or completely disallow the crawl?

**Comment by mouse-reeve** [comment]
The way you approached it in your PR looks correct - use robots.txt and a crawl delay, rather that disallowing crawling entirely. Thank you for your work on this!
