### ISSUE TITLE
Split `web` container into two images

### ISSUE THREAD

**Issue by cincodenada** [bookwyrm-social/bookwyrm#1896]
**Is your feature request related to a problem? Please describe.**
Right now the `web` container has two main roles: running the Django webserver, and running tools like linting that are auxiliary to the webapp, but use the same codebase. Because it's the same container with the same requirements, this means that running `./bw-dev black`, for instance, requires that a database and redis instances and such are running, which means we spend unnecessary time spinning up dependent containers sometimes.

**Describe the solution you'd like**
It would be nice to be able to run just the web container for these auxiliary tasks - I think it makes sense to have a `tools` or `dev` image that's separate from the `web` image, which would not depend on any other images, and thus be faster to spin up and down to run linting and the like.

This would also allow us to theoretically only include the dev dependencies (such as `black`) in the `tools` image, which would help make progress towards #1858, since much of the remaining difference between production and main right now is the extra dependencies, which could just be moved into the new image.

**Describe alternatives you've considered**
We could use `exec` to run these, but that assumes a running web container, which just kind of sidesteps the problem and still requires spinning up a full container if one isn't running.

We could also look into using `--no-deps` with the existing web container, which would solve the dependent containers issue, but doesn't address the python deps problem.

This issue was spawned out of #1785, but is separate enough to warrant its own issue.

**Comment by mouse-reeve** [comment]
I love this! `black` and `prettier` are clear fits. There are also a handful of dev-only management commands that might be worth moving as well, although they do use the app which might over-complicate the image:
 - `makemessages`
 - `compilemessages`
 - `update_locales`
 - `makemigrations`
