### ISSUE TITLE
Translation string for the name of the Swedish language is backwards

### ISSUE THREAD

**Issue by cincodenada** [bookwyrm-social/bookwyrm#1902]
**Describe the bug**
All other languages in the list are of the form "Name in Original Language (Name in Translated Langauge)" e.g. "Español (Spanish)" for listing Spanish in the en-US locale, but Swedish is backwards: "Swedish (Svenska)".

**To Reproduce**
1. Go to Settings -> Display Preferences
2. Open the "Language" dropdown
3. Notice that Swedish doesn't match the format of the others

**Expected behavior**
It should be "Svenska (Swedish)" to match all the others.

**Screenshots**
<img width="391" alt="Screen Shot 2022-02-02 at 11 43 16 AM" src="https://user-images.githubusercontent.com/479715/152225435-6f3ac6d8-6188-4383-b7e8-af0e67f887d8.png">

**Instance**
bookwrym.social

**Additional context**
We should make sure to change the translation string itself, so that this doesn't continue to propagate as languages are added.

**Comment by mouse-reeve** [comment]
Fixed by #1901
