### ISSUE TITLE
Some follow requests fail 

### ISSUE THREAD

**Issue by nycterent** [bookwyrm-social/bookwyrm#1923]
**Describe the bug**

When trying to follow a user via suggestion box I get this:

```
db_1              | 2022-02-05 06:27:41.846 UTC [43264] ERROR:  duplicate key value violates unique constraint "userfollowrequest_unique"
db_1              | 2022-02-05 06:27:41.846 UTC [43264] DETAIL:  Key (user_subject_id, user_object_id)=(1, 3) already exists.
db_1              | 2022-02-05 06:27:41.846 UTC [43264] STATEMENT:  INSERT INTO "bookwyrm_userfollowrequest" ("created_date", "updated_date", "remote_id", "user_subject_id", "user_object_id") VALUES ('2022-02-05T06:27:41.843902+00:00'::timestamptz, '2022-02-05T06:27:41.843933+00:00'::timestamptz, NULL, 1, 3) RETURNING "bookwyrm_userfollowrequest"."id"
```

it does not happen for all the users, just for some of them. might be related that it is not the first time i am trying to follow the user and remote instance was not accessible or malfunctioned

**Expected behavior**
User gets a follow request

**Comment by mouse-reeve** [comment]
I think this will fix the issue, but please reopen if you're still running into issues with remote follows even after this gets merged into prod later today
