### ISSUE TITLE
Searching for ISBN with dashes (as seen on some books) does not show the same results as without dashes

### ISSUE THREAD

**Issue by viviicat** [bookwyrm-social/bookwyrm#1931]
**Describe the bug**
When using the search, if you type the ISBN in a format as seen on some books, (978-1-78330-350-2) you will get results from Inventaire that contain some of the sub-numbers (e.g. "350 Arbres et arbustes" is the first result in this case). If you expand OpenLibrary you can see the correct book but it is less clear.

This is inconsistent with typing the ISBN as an un-dashed list of numbers, in which case you clearly see a single book matching the description.

**To Reproduce**
1. Type an ISBN containing dashes, e.g. 978-1-78330-350-2 into the search bar.
2. Hit Search.
3. Note many results from Inventaire, all of which do not contain the target book.
4. Expand OpenLibrary results and note the correct book is present there.

**Expected behavior**
When a number matching an ISBN dash-included format (seems there are a few variations of this?) is entered, it should be parsed as an ISBN and sent as a flat number to the search engines, so that only the correct book is shown. Users may not realize that removing the dashes from their search would help them find their book.

**Screenshots**
![image](https://user-images.githubusercontent.com/287339/153527587-418810b5-2cb8-4915-ba6b-f2088a5a2b3b.png)
![image](https://user-images.githubusercontent.com/287339/153527620-c5049ba8-77bf-4a2b-a027-e811aeed7a52.png)

**Instance**
My instance https://books.solarpunk.moe

---

**Desktop (please complete the following information):**
    - OS: Windows
    - Browser Firefox
    - Version 97

**Comment by willhoh** [comment]
Hi, I would love to work out a solution for this. I have already done some research and found 2 algorithms to check if they are ISBN numbers. Unfortunately I'm stuck on the realization of the search and where/how to include such helper functions. Would it be possible to give me some tips for this?

I have already added a few tests to check if ISBNs are really recognized.
