### ISSUE TITLE
There is no password length check at signup

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [bookwyrm-social/bookwyrm#1945]
You can create a password with a length greater that 100, but you can't log in with that same password. The signup should have a check for password length and not allow the creation of an account with a greater length than the maximum.

**Comment by mouse-reeve** [comment]
Hm, the password management is handled completely by Django's built in authenticate system (https://docs.djangoproject.com/en/3.2/topics/auth/passwords/). I was able to log in without issue on my dev instance using a 120 character long password. Is it possible that a different issue could be at play for why the login failed?

**Comment by mouse-reeve** [comment]
I'm closing this because I can't seem to replicate it. Please feel very free to re-open with additional context and thank you for reporting
