### ISSUE TITLE
Add book title or author name to url

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1947]
It would be great if urls were more human readable, by including the book title in book urls and author name in author urls. This field should be optional and non-determing, so if you enter a url without the name, or with the wrong name, it should resolve to the correct name. When the title or name changes, the url should reflect that change.

For example:
`https://bookwyrm.social/book/304370` or `https://bookwyrm.social/book/304370/sdkjhfjksdf`

Would redirect to:
`https://bookwyrm.social/book/304370/oldest-cuisine-in-the-world`

**Comment by viviicat** [comment]
I have been looking into this.
