### ISSUE TITLE
Selective Federation

### ISSUE THREAD

**Issue by sofia-columbidae** [bookwyrm-social/bookwyrm#1964]
**Describe the bug**
Bookwyrm instance is selectively federating. A few users from several Bookwyrm and Mastodon instances are showing up under "Users," but Mastodon and Bookwyrm users for the most part cannot view each other or have follow requests recognized from either side.

**To Reproduce**
1. Build Bookwyrm instance in Production
2. Make an account
3. Attempt to look up/follow/view an account on another instance; alternatively, attempt to follow a Bookwyrm account from Mastodon
4. Experience federation problems

**Expected behavior**
Clear, unhindered federation with instances added to the "Federated Instances" list, including viewing profiles and recognized follow requests.

**Instance**
https://tankie.ml

**Comment by sofia-columbidae** [comment]
I've noticed a lot of similarities between what I'm experiencing and this issue: https://github.com/bookwyrm-social/bookwyrm/issues/1928

However, I've attempted to follow the steps that led to this issue resolving and was left in the same predicament.

**Comment by mouse-reeve** [comment]
Can you give me more details about what the failure looks like? When you say users can't view each other, do you mean that if you search for a user by their username on your bookwyrm instance, there are no results? Are there any errors?

When federation is silently failing, it often is because of problems with authentication -- for #1928, the problem was that there was a mismatch between the expected user identifier and the actual user identifier. It's possible that something like that is happening for you but for different reasons. 

Do you have an example of a Mastodon user and a user on your instance that aren't able to interact that you'd feel comofortable sharing?

**Comment by sofia-columbidae** [comment]
> When you say users can't view each other, do you mean that if you search for a user by their username on your bookwyrm instance, there are no results? Are there any errors?

Yes, this is what I mean. I haven't seen any errors, but that doesn't necessarily mean there aren't any -- how would I check that?

For example, my Mastodon account (@columbidae@monads.online) can look up my Bookwyrm account (@columbidae@tankie.ml) but it cant see any posts. I can click the button that says it sends a follow request, but the follow request does not show up o Bookwyrm's end. If I search for the Mastodon account on Bookwyrm, it says the user doesn't exist.

**Comment by sofia-columbidae** [comment]
Another instance (egirls.gay, which uses Misskey) is having 401 unauthorized errors when they try to send activities to my instance, if this helps

**Comment by sofia-columbidae** [comment]
It appears that Bookwyrm isn't signing its requests, according to the logs on the Misskey instance, meaning it gets locked out at auth fetch. How would I go about fixing this?

**Comment by realityfabric** [comment]
To see the Bookwyrm posts on Mastodon you have to search for the post url (on Mastodon) unless someone on your instance is following your Bookwyrm account. But I also have the same issue where attempting to follow Bookwyrm users tells me it sent a request, but the request never shows up for the Bookwyrm user.

**Comment by sofia-columbidae** [comment]
I've also discovered that replies and comments from Mastodon also do not appear in Bookwyrm

**Comment by realityfabric** [comment]
That depends on the instance, I've been able to interact with Mastodon users on some instances and not others. Same with notifications, some instances likes and boosts show up in my notifs and some instances they don't. But the instances that don't propagate interactions are also ones where I can search for posts and accounts from that instance, but can't do so from BookWyrm.

**Comment by realityfabric** [comment]
Is this issue connected to issue #1179?

**Comment by mouse-reeve** [comment]
> Is this issue connected to issue #1179?

I believe it's the same issue

**Comment by WesleyAC** [comment]
Sounds like this should be fixed by #2613, so I'm going to go ahead and close this.
