### ISSUE TITLE
Create dark mode theme

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1972]
BookWyrm is close to being theme-able, and it would be nice to ship with a dark mode theme by default. I made a basic version but it would be great if someone who is excited about specific shades were to apply their artist vision to this.

The current super-top-secret dark mode theme is here: https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/static/css/themes/dark.scss and can be activated by editing the main scss file here: https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/static/css/bookwyrm.scss#L4 to be "dark.scss" instead of "light.scss"

Another option for someone who prefers not to set up a developer environment would be to provide an example image of the colors would look and a list of their hex values, and I can make the theme file

**Comment by viviicat** [comment]
I'm seeing if I can make use of the Dark Reader-generated theme as a reference for this.
