### ISSUE TITLE
A couple small things missing from dark mode theme

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#2019]
Content warnings:
<img width="767" alt="Screen Shot 2022-03-14 at 1 13 30 PM" src="https://user-images.githubusercontent.com/1807695/158253830-fcbb0d6a-6abf-4f60-91f8-b8ff19a7d72c.png">

Sucess notice:
<img width="898" alt="Screen Shot 2022-03-14 at 1 14 09 PM" src="https://user-images.githubusercontent.com/1807695/158253709-60269f05-ea43-4f68-9df7-26e571d9ec02.png">

**Comment by viviicat** [comment]
Getting to work on this, now.
