### ISSUE TITLE
Re-send confirmation page shows 404

### ISSUE THREAD

**Issue by MaybeThisIsRu** [bookwyrm-social/bookwyrm#2022]
**Describe the bug**
I signed up on bookwyrm.social, but didn't get my confirmation code over email. I requested it again on the confirmation page (had to write my email), and it went to https://bookwyrm.social/resend-link with a 404 page displaying instead.

**Expected behavior**
If I wrote an invalid email, tell me that. Otherwise the 404 page doesn't make much sense.

**Instance**
bookwyrm.social

---

**Desktop (please complete the following information):**
    - OS: macOS 12.3
    - Browser Firefox 98.0.1

**Comment by MaybeThisIsRu** [comment]
The culprit here is probably this:

https://github.com/bookwyrm-social/bookwyrm/blob/35e27a44434c5825072f32ef23a98a75a239ff13/bookwyrm/views/landing/register.py#L136

> user = get_object_or_404(models.User, email=email)

Entering a wrong email immediately equals a 404 with no helpful message.

**Comment by MaybeThisIsRu** [comment]
Off-topic: finally received the email at 2:33AM (so about a few hours late).

**Comment by mouse-reeve** [comment]
The delayed email is because of #2030
