### ISSUE TITLE
Confirmation code page is not tablet friendly

### ISSUE THREAD

**Issue by MaybeThisIsRu** [bookwyrm-social/bookwyrm#2023]
![image](https://user-images.githubusercontent.com/3974019/158655808-3fa795e4-7d87-44af-8733-ee8a4c9ae10a.png)

I will PR this sometime in the next few days.

**Comment by bSolt** [comment]
I'll take a look at this later. More reactive html is right up my alley

**Comment by bSolt** [comment]
Hm would just making the image smaller at this width be best?

**Comment by bSolt** [comment]
Or it could be hidden like at narrower widths

![image](https://github.com/bookwyrm-social/bookwyrm/assets/36494925/0d5e8db3-b0da-4d9b-a974-bfe6bf22a372)

**Comment by bSolt** [comment]
I'm not so confident in these solutions because this element is also used in other places I'll have to check

**Comment by bSolt** [comment]
I probably like this best, just make the first part full width then stack the second with the image

![image](https://github.com/bookwyrm-social/bookwyrm/assets/36494925/a2c1654c-2a36-411a-9b4f-2f2746c40a4e)

This should probably apply to some other pages with similar layouts like /invite/... and possible /login. I'll work on a PR

**Comment by bSolt** [comment]
@mouse-reeve @hughrun any preference on the layout solution? I am thinking either make the form column full width except on desktop, or use a smaller logo image in all cases (maybe "md"). Also I have determined that this same issue applies to the invite page, login/reactivate (without registrations enabled), and password reset pages.

**Comment by mouse-reeve** [comment]
I think the full-width solution seems the nicest, since it prioritizes and gives more space to the thing that people are on the page to actually use

**Comment by mouse-reeve** [comment]
Fixed by #3260
