### ISSUE TITLE
Pre-set user's timezone

### ISSUE THREAD

**Issue by MaybeThisIsRu** [bookwyrm-social/bookwyrm#2024]
**Is your feature request related to a problem? Please describe.**
I signed up and saw you can set a timezone. It was set to UTC by default.

**Describe the solution you'd like**
JavaScript has an Internationalization API that returns timezones. At attempt should be made to pre-set this for less friction.

```
const x = new Intl.DateTimeFormat()
x.resolvedOptions().timeZone
// => "Asia/Kolkata"
```

Reading:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/resolvedOptions

**Comment by mouse-reeve** [comment]
Almost every thing is done in Django, so JavaScript may not be able to help here, but I think Django can make a decent guess at timezones based on request headers

**Comment by redshiftss** [comment]
On a related note, I was looking into fixing this and it seems like bookwyrm still uses pytz, but zoneinfo was made the official timezone implementation in django according to this (https://docs.djangoproject.com/en/4.1/topics/i18n/timezones/). Should we switch to zoneinfo or continue using pytz?

**Comment by mouse-reeve** [comment]
It would be good to switch to zoneinfo -- we're still using Django 3, which is why pytz is in use, but I'd like to get to Django 4 and that would be a helpful step towards it.

**Comment by redshiftss** [comment]
I've been having a look at this - two things : it seems like django does a very bad job at guessing - it just defaults to UTC (which isn't any better than what it currently is doing...) and headers don't seem to be useful, but I'll try and implement something with hidden fields like @MaybeThisIsRu suggested, I think that will work
