### ISSUE TITLE
edit book shows 500 error

### ISSUE THREAD

**Issue by SouthFox-D** [bookwyrm-social/bookwyrm#2039]
**Describe the bug**
Updating my instance to v0.3.4 after , edit book show 500 error.

**To Reproduce**
1. Go to `website`
2. Click one `book`
3. Click one `edit`

**Additional context**
logs:
> web_1             | [2022-03-18 13:45:57 +0000] [1] [INFO] Handling signal: term
web_1             | [2022-03-18 13:45:57 +0000] [7] [INFO] Worker exiting (pid: 7)
web_1             | [2022-03-18 13:45:58 +0000] [1] [INFO] Shutting down: Master
web_1             | [2022-03-18 13:46:08 +0000] [1] [INFO] Starting gunicorn 20.0.4
web_1             | [2022-03-18 13:46:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
web_1             | [2022-03-18 13:46:08 +0000] [1] [INFO] Using worker: sync
web_1             | [2022-03-18 13:46:09 +0000] [9] [INFO] Booting worker with pid: 9
web_1             | [2022-03-18 13:47:33 +0000] [1] [INFO] Handling signal: term
web_1             | [2022-03-18 13:47:33 +0000] [9] [INFO] Worker exiting (pid: 9)
web_1             | [2022-03-18 13:47:34 +0000] [1] [INFO] Shutting down: Master
web_1             | [2022-03-18 13:47:39 +0000] [1] [INFO] Starting gunicorn 20.0.4
web_1             | [2022-03-18 13:47:39 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
web_1             | [2022-03-18 13:47:39 +0000] [1] [INFO] Using worker: sync
web_1             | [2022-03-18 13:47:39 +0000] [8] [INFO] Booting worker with pid: 8
web_1             | Not Found: /api/v1/streaming/
web_1             | Internal Server Error: /book/505/edit
web_1             | Traceback (most recent call last):
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1             |     response = get_response(request)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
web_1             |     response = response.render()
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
web_1             |     self.content = self.rendered_content
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
web_1             |     return template.render(context, self._request)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
web_1             |     return self.template.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 170, in render
web_1             |     return self._render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
web_1             |     return self.nodelist.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
web_1             |     bit = node.render_annotated(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_1             |     return self.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
web_1             |     return compiled_parent._render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
web_1             |     return self.nodelist.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
web_1             |     bit = node.render_annotated(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_1             |     return self.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
web_1             |     result = block.nodelist.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
web_1             |     bit = node.render_annotated(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_1             |     return self.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 519, in render
web_1             |     return self.nodelist.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
web_1             |     bit = node.render_annotated(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_1             |     return self.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
web_1             |     result = block.nodelist.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
web_1             |     bit = node.render_annotated(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_1             |     return self.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 195, in render
web_1             |     return template.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 172, in render
web_1             |     return self._render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
web_1             |     return self.nodelist.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
web_1             |     bit = node.render_annotated(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_1             |     return self.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 315, in render
web_1             |     return nodelist.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
web_1             |     bit = node.render_annotated(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_1             |     return self.render(context)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 170, in render
web_1             |     values = list(values)
web_1             | TypeError: 'ManyRelatedManager' object is not iterable

---

**Desktop (please complete the following information):**
    - OS: [Manjaro]
    - Browser [Firefox]
    - Version [98.0.1]

**Comment by mouse-reeve** [comment]
Thanks for reporting!
