### ISSUE TITLE
More natural reading post updates

### ISSUE THREAD

**Issue by MaybeThisIsRu** [bookwyrm-social/bookwyrm#2047]
**Is your feature request related to a problem? Please describe.**
Reading updates don't have a very appropriate text. If you look at the post, the display name is already available. There's no need to repeat it as "Name started reading X."

**Describe the solution you'd like**
Use first-person and say: "I started reading X."

**Additional context**

<img width="602" alt="image" src="https://user-images.githubusercontent.com/3974019/159158166-d299c50b-1bc7-4e74-898a-c60240d68b9f.png">

**Comment by mouse-reeve** [comment]
I'm open to changing how this works for sure, but I'm reluctant to use the first person for an app-generate message. It feels presumptuous to me if a program writes a sentence for me as if I said it, if that makes sense?

**Comment by MaybeThisIsRu** [comment]
That makes sense. Not sure what to do haha. I guess you could close this issue since I don't have any ideas and from the looks of it, there isn't much to pick from.

**Comment by mouse-reeve** [comment]
Thanks -- I'll close for now as part of my futile attempt to keep the issue queue manageable, but feel free to re-open if you have other ideas :)
