### ISSUE TITLE
Give users control of how CSV headers are mapped before import

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#2050]
I'd like to give users an option to see and change what import item fields are matched with the columns in their csv. This would allow any arbitrary CSV to be imported, so long as the user is willing to do a bit of checking.

I did some of the groundwork for this in #1600, so it isn't as major an overhaul as it might appear from the outside

**Comment by DougNix** [comment]
Perhaps merge this issue with #2411

**Comment by mouse-reeve** [comment]
Good idea to merge them, thank you!
