### ISSUE TITLE
Create a walkthrough for new users

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#2052]
It would be great to give new users who want it a "guided tour" of the application.

**Comment by hughrun** [comment]
I'm not promising to do it right now but I would like to volunteer to look into this. It's difficult to get your head around all the concepts at first.

**Comment by hughrun** [comment]
I'm working on this now, using Shepherd.

**Comment by hughrun** [comment]
whoops @mouse-reeve I must have forgotten to trigger an auto-close for this.
