### ISSUE TITLE
end reading but not read

### ISSUE THREAD

**Issue by tnntwister** [bookwyrm-social/bookwyrm#2060]
Hi !

Owning a lot of books and ebooks, i just don't see the interest of forcing myself to end a book that didn't awake smth during the first pages. So i have some books that are marked as begun reading, but that i don't want to tag as read, because i just quit reading, my reading isn't finished. 

It would be nice when clicking on "read" status to be able to say where we have stopped reading. (always this bookmark idea... ;)). and thus i would be able to hide quit books from my reading list. 

Hope it's little clear... :'s

**Comment by mouse-reeve** [comment]
That's in the pipeline! PR: #2035. I'm going to close this issue since it's a duplicate #1385 -- but this is a good reminder to finish up the last couple things on that PR :)
