### ISSUE TITLE
User account menu does not behave properly with the keyboard

### ISSUE THREAD

**Issue by rkingett** [bookwyrm-social/bookwyrm#2071]
The user account menu button drop down menu at the top of all pages, containing the label, avatar for USER, is not behaving as it should using the keyboard.

When a keyboard user attempts to open the menu button with the keyboard and expand the menu, a new HTML page loads, but then the menu button is expanded after the page loads. 

Ideally, this menu button should expand without refreshing the page or loading a new HTML page.

The menu button directs users to their profile  page.

**To Reproduce**

1. Use the keyboard to tab to the user account menu button after logging into any Bookwyrm instance. It appears, in tab order, after the Discover  link.
2. press space, or enter, to expand the menu for links such as account settings and more.
3. observe how, after pressing enter, your profile page loads and then the menu is expanded after the page loads.

**Expected behavior**

Ideally, this menu button should expand without refreshing the page or loading a new HTML page.

**Instance**

Bookwyrm.social

**Additional context**

This happens no matter what browser I am using. 

---

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by mouse-reeve** [comment]
Thank you for opening an issue for this and reminding me, I'll make this my priority. It was working as of a few weeks ago, right?

**Comment by mouse-reeve** [comment]
On my computer I'm able to tab through the menu options (as long as I don't press enter when I get to the menu), but the `aria-expanded` value stays set to false, which might be part of the problem.

**Comment by rkingett** [comment]
Correct! It appears to not open for me if the screen reader interacts directly with the browser. Like, if I bypass the screen reader virtual buffer and tab to the menu, it appears to not expand. Perhaps VoiceOver just automatically does it on macs?

**Comment by mouse-reeve** [comment]
I finally caught a break in my wedding cake making to address this! It looks good on my machine and uses the same pattern that other menus on the site use, so hopefully it works well for you too. It's live on bookwyrm.social, so let me know if it doesn't work or could be improved form your perspective.

**Comment by rkingett** [comment]
It works! You can close this issue.
