### ISSUE TITLE
order reviews on book page based on social relevance

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#208]
ie, friends, then people on your instance, then anyone

**Comment by arkhi** [comment]
Do you imagine this as an option or an enforced algorithm?

I think a disabled option would offer people more exposure to things they would not read by default, hence more diversity of opinions.

**Comment by mouse-reeve** [comment]
As an option. When I'm looking at book reviews myself, I'm much more interested in the opinions of people I know, but yeah, there's no reason to make that mandatory for people who want a broader exposure

**Comment by mouse-reeve** [comment]
I'm going through and closing old issues that seem stale or out of date - feel free to reopen with a comment adding some updated context if you feel like it still needs to be addressed ❤️
