### ISSUE TITLE
Instance /about/ page not localized

### ISSUE THREAD

**Issue by Stoori** [bookwyrm-social/bookwyrm#2081]
**Describe the bug**
When a translated locale is used, about ~everything shows right in the locale language except the instance /about/ page, which stays in English.

**To Reproduce**
1. Change your preferred language to some other than English.
2. Go to instance /about/ page.
3. See error

**Expected behavior**
/about/ page should be in the selected translated locale.

**Instance**
https://kirja.casa
- also reports from at least one other instance.

---

**Desktop (please complete the following information):**
    - OS: macOS Monterey
    - Browser: Vivaldi
    - Version: 5.2.2623.24

**Comment by mouse-reeve** [comment]
This seems to be the same issue we've seen pop up where the compiled locales aren't complete. In the short term, re-compiling the locale should fix this. I wonder if there's something off in the command I use to bulk update the locales?

**Comment by mouse-reeve** [comment]
I'm going to close this because it's gotten old, but please re-open if it happens again?
