### ISSUE TITLE
no update from federated sites?

### ISSUE THREAD

**Issue by airdogvan** [bookwyrm-social/bookwyrm#2094]
Not totally sure if it is a bug or not.

After first install and until I updated the version I daily received books added and/or reviewed from other sites.

Since the version I updated to, it's extremely rare that I get updates (I think in the last few months I got 2).

It's possible that nobody is using the other instances anymore but I rather doubt it especially since the updates ceased (but again not totally) right after upgrade.

Sorry not sure how to find out which version I'm running.

**Comment by mouse-reeve** [comment]
You can find out which version your running on the about page (`/about`, for example: https://bookwyrm.social/about) or the `nodeinfo` (`/nodeinfo/2.0`, for example: https://bookwyrm.social/nodeinfo/2.0). 

There isn't any intentional reason why you wouldn't get statuses federated from other instances, so it sounds like something has gone awry. Are you able to follow and receive follow requests from other instances?

**Comment by airdogvan** [comment]
I already went to the about page and cannot find the info version.

I followed a few profiles and that's why I was receiving updates before upgrading, but as said only rarely now.  A few of these profiles were quite active but nothing anymore.

As said maybe they have ceased using it, not sure.

I can browse other profiles in the directory, no problem there...

As for the node, seems to me I would first need to know wether I'm using 1.x or 2.x to use that method, no?

If I just use bookwyrm.x/nodeinfo it tells me page not found.

**Comment by mouse-reeve** [comment]
The url includes the 2.0, it's not related to the version number of the app itself. if you go to `bookwyrm.x/nodeinfo/2.0`, you should get a json blob that includes the version number. If the version number isn't present on your about page, you're probably running a pretty out of date version, so the problem may be resolved by updating to the latest.

If you can check the logs, you might find illuminating errors there. `docker-compose logs --tail=50 web` or `docker-compose logs --tail=50 celery_worker` might have stack traces if there are errors.

**Comment by airdogvan** [comment]
Version 0.1.0.

Celery log showed no errors,
Web log:
ESC[36mweb_1             |ESC[0m   File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
ESC[36mweb_1             |ESC[0m     return self.sslsocket_class._create(
ESC[36mweb_1             |ESC[0m   File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
ESC[36mweb_1             |ESC[0m     self.do_handshake()                                                     ESC[36mweb_1             |ESC[0m   File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
ESC[36mweb_1             |ESC[0m     self._sslobj.do_handshake()
ESC[36mweb_1             |ESC[0m ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1129)
ESC[36mweb_1             |ESC[0m
ESC[36mweb_1             |ESC[0m During handling of the above exception, another exception occurred:         ESC[36mweb_1             |ESC[0m
ESC[36mweb_1             |ESC[0m Traceback (most recent call last):
ESC[36mweb_1             |ESC[0m   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
ESC[36mweb_1             |ESC[0m     resp = conn.urlopen(
ESC[36mweb_1             |ESC[0m   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
ESC[36mweb_1             |ESC[0m     retries = retries.increment(
ESC[36mweb_1             |ESC[0m   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 446, in increment                                                                                            ESC[36mweb_1             |ESC[0m     raise MaxRetryError(_pool, url, error or ResponseError(cause))
ESC[36mweb_1             |ESC[0m urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bookwyrm.spaceling.sh', port=443): Max retries exceeded with url: /search?q=beautiful%20world%20where%20are%20you (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1129)')))


Please disregard the ESC s these are the results of screen copy from terminal.

**Comment by airdogvan** [comment]
Version 0.1.0.

Celery log showed no errors,
Web log:
ESC[36mweb_1             |ESC[0m   File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
ESC[36mweb_1             |ESC[0m     return self.sslsocket_class._create(
ESC[36mweb_1             |ESC[0m   File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
ESC[36mweb_1             |ESC[0m     self.do_handshake()                                                     ESC[36mweb_1             |ESC[0m   File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
ESC[36mweb_1             |ESC[0m     self._sslobj.do_handshake()
ESC[36mweb_1             |ESC[0m ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1129)
ESC[36mweb_1             |ESC[0m
ESC[36mweb_1             |ESC[0m During handling of the above exception, another exception occurred:         ESC[36mweb_1             |ESC[0m
ESC[36mweb_1             |ESC[0m Traceback (most recent call last):
ESC[36mweb_1             |ESC[0m   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
ESC[36mweb_1             |ESC[0m     resp = conn.urlopen(
ESC[36mweb_1             |ESC[0m   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
ESC[36mweb_1             |ESC[0m     retries = retries.increment(
ESC[36mweb_1             |ESC[0m   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 446, in increment                                                                                            ESC[36mweb_1             |ESC[0m     raise MaxRetryError(_pool, url, error or ResponseError(cause))
ESC[36mweb_1             |ESC[0m urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bookwyrm.spaceling.sh', port=443): Max retries exceeded with url: /search?q=beautiful%20world%20where%20are%20you (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1129)')))


Please disregard the ESC s these are the results of screen copy from terminal.

But I know I'm due for an update anyway so I'll do it soon.  Probably Monday.

**Comment by mouse-reeve** [comment]
Thank you - I think that error is unrelated to your federation issues. Let's prioritize getting you updated and then see how things are working. I'm happy to help if you have hiccups in the update process, and the [Matrix chat](https://app.element.io/#/room/#bookwyrm:matrix.org) would be a great place to get support

**Comment by airdogvan** [comment]
update finished with following error:
found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 8.5.5 -> 8.8.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.8.0>
npm notice Run `npm install -g npm@8.8.0` to update!
npm notice 
Removing intermediate container d0db2f18a4d1
 ---> 15a3b23e44f5
Successfully built 15a3b23e44f5
Successfully tagged bookwyrm_dev-tools:latest
+ docker-compose exec web python manage.py migrate
ERROR: No container found for web_1

Don't forget I modified my docker-compose because I don't need nginx.

The last update didn't pose any problems though...

**Comment by mouse-reeve** [comment]
You will need to use the current `docker-compose` file and update it according to your setup -- there have been changes since version 0.1.0.

Can you tell what is triggering the `docker-compose exec web python manage.py migrate`? It probably ought to be doing `docker-compose run --rn web python manage.py migrate`.

**Comment by airdogvan** [comment]
OK, modified my docker-compose with the changes in the new one.
Restarted and now it's up but the page displays errors:

Server Error
Something went wrong! Sorry about that.
Successfully posted status
Error posting status

And also looks like a web page that couldn't read it's css file.

Sorry no idea what you're talking about with the python stuff.  Started update with ./bw-dev update and copied the last few lines showing the error in previous comment.

**Comment by mouse-reeve** [comment]
If the only problem is missing css, you can fix that by running `./bw-dev collectstatic` from the command line. But that should have run during the update command, so there is probably a separate, underlying issue.

We need to do some diagnostics -- first, use `docker-compose ps` to see what images are running. Since the site is loading, web is probably running but unable to connect to another image. Try restarting the web image (`docker-compose restart web`) and checking its logs (docker-compose logs --tail=50 web).

**Comment by airdogvan** [comment]
docker-compose ps shows all services are up and running.

here is the log, copied the first few lines, hope it's enough:

web_1             | LINE 1: ..._key" AS Col9, "bookwyrm_book"."bnf_id" AS Col10, "bookwyrm_...
web_1             |                                                              ^
web_1             | 
web_1             | 
web_1             | The above exception was the direct cause of the following exception:
web_1             | 
web_1             | Traceback (most recent call last):
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1             |     response = get_response(request)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_1             |     response = wrapped_callback(request, *callback_args, **callback_kwargs)

**Comment by mouse-reeve** [comment]
That looks like it might be a migrations issue. Try running `./bw-dev migrate` and let me know what the output is?

**Comment by airdogvan** [comment]
that did it.  Now running version "0.3.4".

So what happened?

Anyway thanks for the fix.  Much appreciated as usual.

**Comment by mouse-reeve** [comment]
It looks like in your first round of updating, the migrate command failed because it was trying to use a web image that wasn't running. I'm not 100% sure why, but in previous versions of the application the `exec` docker command was used rather than `run`, so it may have been trying to run an older script.

**Comment by airdogvan** [comment]
that did it.  Now running version "0.3.4".

So what happened?

Anyway thanks for the fix.  Much appreciated as usual.

**Comment by airdogvan** [comment]
Just wanted to let you know that I'm getting updates almost daily now... :)
