### ISSUE TITLE
Profile link on user menu incorrect if currently on another user’s profile

### ISSUE THREAD

**Issue by denmch** [bookwyrm-social/bookwyrm#2096]
https://github.com/bookwyrm-social/bookwyrm/blob/e0fa0b859aa16a15ee82c496f938c92daee3141c/bookwyrm/templates/user_menu.html#L24

The profile link works as expected unless I’m on someone else’s profile and then use the user menu to try to navigate back to my own. At a glance, I suspect we need `request.user.localname` here as in the link for My Books.

Does that seem right?

**Comment by mouse-reeve** [comment]
yep! thank you for catching this
