### ISSUE TITLE
Django Debug Toolbar

### ISSUE THREAD

**Issue by Ryuno-Ki** [bookwyrm-social/bookwyrm#2101]
**Is your feature request related to a problem? Please describe.**
During running a local development environment I noticed a sluggish experience.

**Describe the solution you'd like**
In order to proper investigate, Django Debug Toolbar is a popular tool.
I spent some time (and got help on Mastodon) to get a setup running:

https://github.com/bookwyrm-social/bookwyrm/compare/main...Ryuno-Ki:django-debug-toolbar?expand=1

Note, that this must not be merged! For one, it is not designed for production usage. But it also circumvents some security measures.
However, for contributors it might help get it up fast.

Keep in mind, that you will also need to run the [whole build-setup-up cycle](https://docs.joinbookwyrm.com/developer-environment.html) again, to make Docker take note.

**Comment by mouse-reeve** [comment]
I did the same thing -- I think the issue here is it should be documented. https://github.com/bookwyrm-social/bookwyrm/tree/debug-toolbar

**Comment by mouse-reeve** [comment]
I'm considering this fixed with the new documentation page, but please let me know if you think this needs additional attention. We did our respective branches a little differently as well, so if you think there are ways the local branch should change I'd be grateful for that feedback as well.

**Comment by Ryuno-Ki** [comment]
I wasn't aware that there is another repository. My bad.
https://docs.joinbookwyrm.com/debug_toolbar.html is fine.
