### ISSUE TITLE
When adding multiple authors to one book, only the first is added

### ISSUE THREAD

**Issue by joachimesque** [bookwyrm-social/bookwyrm#2108]
**Describe the bug**

I would like to add multiple authors to a book (it's an anthology). When I add multiple authors to the book, via the "Add Another Author" button, only the first one is added.

**To Reproduce**

1. Edit book
2. Fill the info for one author (Charlie Jane Anders) in the input
3. Click "Add Another Author"
4. Fill the info for the new author in the second input
5. Click "Add Another Author"
6. Fill the info for that new author in that third input
7. Save book
8. The interface shows the message _Is "Charlie Jane Anders" one of these authors?_
9. Select one of the choices
10. Only Charlie Jane Anders has been added, the other authors don't show up.

**Expected behavior**

I would like to see all authors added, and the interface for selecting the right author (ie. _Is "Charlie Jane Anders" one of these authors?_) should show the choices for all the authors I add.

**Screenshots**

**Instance**

boitam.eu (I expect this problem to be global)

**Comment by chris-y** [comment]
I can confirm this was also happening to me when adding and also editing books, on wyrms.de a couple of weeks ago (not sure if the instance has had an update in the meantime)

**Comment by stopregionblocking** [comment]
i had this same issue on the main instance (bookwyrm.social) less than 4 days ago.

**Comment by mouse-reeve** [comment]
Sorry for the confusion -- I haven't put the fix in production yet, but the issues are closed automatically when the PR is merged, so in this case there's a gap between the issue being closed and the feature going live. I should have it up Monday latest.

**Comment by stopregionblocking** [comment]
> Sorry for the confusion -- I haven't put the fix in production yet, but the issues are closed automatically when the PR is merged, so in this case there's a gap between the issue being closed and the feature going live. I should have it up Monday latest.

sure, thanks for clarifying. will give it a week or so
