### ISSUE TITLE
Cannot add book

### ISSUE THREAD

**Issue by airdogvan** [bookwyrm-social/bookwyrm#2121]
When I try to add a book I get error message from the web page.

Docker logs show the following error:

[error] 30#30: *112520 directory index of "/app/static/" is forbidden

Running version "0.3.4

I noticed that in the docker-compose the volume is mapped as:
static_volume:/app/static

but there is no static_volume in my file structure.

**Comment by mouse-reeve** [comment]
It's normal that there isn't a `static_volume` in your file structure, since it's a docker volume rather than a directory. When you create a book it should be saving the cover to `media`, not `static`, which is for assets that are part of the app, not user -generated content. Is there anything you've changed in your `.env` file or `docker-compose` file that might be related to that?

**Comment by mouse-reeve** [comment]
And, does creating a book work when there is no cover image?

**Comment by airdogvan** [comment]
Of course, I haven't really written a docker-compose for a while so I forgot the volume is kept in /var/lib/docker/volumes...

And no the absence of cover image leads to the same result.  

Didn't have this problem in previous versions by the way.

**Comment by mouse-reeve** [comment]
Can you give me more details about how you're adding a book? For example, are you adding a new book via the link in the search results, or adding another edition to an existing work via the "editions" page? I'm having trouble replicating this error locally (although I did find a logic problem with the add book flow, fixed by #2127

**Comment by Neriderc** [comment]
Can I chime in here and say I'm having the same issue, with only one book in particular.

I search for a book, and then try to import the book from the search results. The book in question is this one: https://bookwyrm.social/book/282741/s/guards-guards

I've added a dozen others the same way without issue.

I get a very similar error to the original author:
`[error] 31#31: *683 directory index of "/app/static/" is forbidden`

**Comment by mouse-reeve** [comment]
@Neriderc #2133 may help with your issue (maybe?), but I don't expect it to help at all with @airdogvan's issue.

**Comment by mouse-reeve** [comment]
What operating system are you using? A similar issue came up in the matrix chat and the problem seemed to be present on Debian and not on Ubuntu

**Comment by airdogvan** [comment]
The host OS is Ubuntu 20.04 LTS.  But please don't forget that I'm running the docker version.

About docker, I'm running docker rootless which can sometimes create access rights problems.

But I didn't see any indication of that in the docker logs.  And as a reminder I added many books (both import and manual add) in previous versions without any issues.

**Comment by mouse-reeve** [comment]
It sounds like it's a problem with docker permissions, and I'll be honest, I have no clue how to debug it. You can try in the matrix chat room and see if anyone else has ideas. Sorry not to be more help!

**Comment by airdogvan** [comment]
Ok then why would it happen now and not before?

And as said I've had permission problems in docker before but they always clearly show up in the logs with something such as " could not access file xx" or " permission denied".

But in this case nothing even close.

**Comment by mouse-reeve** [comment]
It's very odd! I truly have no idea, and I was referring to docker permissions very loosely, I didn't mean to imply you were using it incorrectly.

**Comment by airdogvan** [comment]
I'm curious.  Can you reproduce the problem? Trying to manually add the book with the author and title I've given you? 

Can you add that book without any problems?

**Comment by mouse-reeve** [comment]
Yes, I've tried to replicate it using you data and it's worked for me. I also haven't seen any errors similar to this on b.s's Sentry, which is why I was asking about Docker configuration and operating system -- it doesn't seem to be happening consistent across instances

**Comment by airdogvan** [comment]
Can't find it when I do a search...

**Comment by mouse-reeve** [comment]
I tried it on my local test instance. I'll add it on b.s now

**Comment by mouse-reeve** [comment]
I was able to import it from OpenLibrary: https://bookwyrm.social/book/442597/s/la-rage

**Comment by airdogvan** [comment]
Ok found it and was able to add without problems.  Strange!!!
Thanks for the dedication, much appreciated.
No time today but tomorrow I'll try to manually add another one to see what happens.  Will let you know.

**Comment by mouse-reeve** [comment]
I would be surprised if it was related to the content of the data; there are lots of books and authors in various character sets.

**Comment by airdogvan** [comment]
so would I.  So this particular case is going to remain a mystery!!!!
Again thanks for your help and dedication, once again very much appreciated when a developer stands behind his work like you do.
And also would like to say that this site is important to me as I read regularly and was looking for a viable alternative to goodreads.  
I still register my read books on goodreads (just in case) but only review them on my site.
Kudos and thanks to you!!!

**Comment by airdogvan** [comment]
I was thinking, is it possible that when adding a book your software does some kind of check on spelling for the author's name and if the spelling is incorrect (which it was in my case with the wrong "l") it issues an error?
That would explain why I was able to add a book by an non existing author (airdog van) for which the correctness of the name could not be verified but not one by an existing author whose name was not written correctly.
Long shot, but just a thought.

**Comment by mouse-reeve** [comment]
There isn't really a way to spell check names, because they're so free-form. There is a check that tries to find existing similar authors, and authors in the ISNI database, which can help avoid mistakes like that.

**Comment by airdogvan** [comment]
But I was right there is a check.  And what does it do when if finds similar author? Displays list of possible authors?

I've been at software ( producer and user) for a long time and developed some kind of sixth sense.
This tells me that the error is not related to docker and probably occurs during some kind of checking.

Of course I could be wrong...

**Comment by mouse-reeve** [comment]
When you create a new book, it should take you to a confirmation page that shows you existing author matches (and existing works); for example:

<img width="1194" alt="Screen Shot 2022-05-31 at 1 27 22 PM" src="https://user-images.githubusercontent.com/1807695/171278834-781cd6e5-8f5e-4f52-a156-aa59f1ce0607.png">
