### ISSUE TITLE
Cannot edit author page

### ISSUE THREAD

**Issue by kopischke** [bookwyrm-social/bookwyrm#2123]
**Describe the bug**
Editing [this author page](https://bookwyrm.social/author/2536/edit) on bookwyrm.social fails: saving the edit reproducibly loads a page stating that I have required a non-existent page (bw.social’s 404 page? The message is localised, which means I am working off the German translation here). The author data never gets updated, though I can navigate back to the cached edit.

**To Reproduce**
1. Go to [this author page](https://bookwyrm.social/author/2536).
2. Click on ‘Edit author’.
3. Correct the birth date (June 14th, 1972, according to Wikipedia). Save your edit.
4. See error.

**Expected behavior**
Author data updated.

**Instance**
bookwyrm.social

---

**Platform / Device info:**
    - Device: iPad Pro 13”
    - OS: iPadOS 15.5
    - Browser: Safari
    - Version: N/A

**Comment by mouse-reeve** [comment]
I bet this is the same as #2040
