### ISSUE TITLE
Unable to edit book - leads to Page Not Found

### ISSUE THREAD

**Issue by chris-y** [bookwyrm-social/bookwyrm#2124]
**Describe the bug**
Unable to edit a book, the "Save" button on the edit page leads to a 404 error. 

**To Reproduce**
1. Go to https://wyrms.de/book/28/edit
2. Change some details
3. Click on 'Save'
4. Browser ends up at https://wyrms.de/book/28/s/dispossessed/edit showing "Not Found".

**Expected behavior**
The edited details are saved, or at least a proper error page is displayed describing why they can't be (permissions, etc)

**Screenshots**
![image](https://user-images.githubusercontent.com/1818803/169873968-9fe5c0c8-70b4-4859-85f5-1640c2a666f4.png)

**Instance**
wyrms.de

**Additional context**
I managed to add a scan of the cover successfully from the book page (before entering edit mode).
I was trying to correct the title and some other details, it looks like the current ones have been imported from OpenLibrary but don't match the copy I have here with the same ISBN.
I tried editing both on desktop and phone with the same result.
I have previously edited books I've added with no issues, but not sure if the instance has been updated since then.

---

**Desktop (please complete the following information):**
    - OS: Raspberry Pi OS
    - Chrome
    - 101.0.4951.57

**Smartphone (please complete the following information):**
    - Device: Moto G200
    - OS: Android 12
    - Browser Chrome
    - Version 101.0.4951.61

**Comment by mouse-reeve** [comment]
Shoot, I wrote this fix (#2040 ) but haven't deployed it yet. I'll do that now and consider this closed.

**Comment by mouse-reeve** [comment]
Oh I should have read more carefully - it's deployed on b.s, wyrms.de will need to update to get this fix @tofuwabohu

**Comment by coffeverton** [comment]
@mouse-reeve I'm also running another bookwyrm instance. Should I wait for a new release, or is it safe to do a git-pull and docker-compose up --build?

**Comment by mouse-reeve** [comment]
You can update now, but I suggest using `./bw-dev update`, which does a handful of update tasks like migrating that may be necessary depending on what's in the update

**Comment by tofuwabohu** [comment]
Thank you for the fix! I updated wyrms.de so it should work now.

**Comment by chris-y** [comment]
I've tested and it is now working, thank you!
