### ISSUE TITLE
authors discarded if multiple added during merge phase

### ISSUE THREAD

**Issue by jzacsh** [bookwyrm-social/bookwyrm#2135]
**Describe the bug**
Edits silently discarded: adding multiple authors doesn't work; only the first is accepted and the rest are silently dropped.

**To Reproduce**
1. Go to a book's edit page that has an author already
2. Add five new authors (say this is a short story collection)
3. Save your edit
4. See edit page re-render with confirmation flow to reduplicate authors mentioned
5. Note: you're only seeing dedupe of one author, but okay maybe only one already exists in bookworm.
6. Confirm
7. See view-book page render with your edits
8. **Bug**: only the first author of the five (in step 2) is present. It seems to consistently be the one in step 5.
9. Try again (steps 1-8) this time with 4 authors: same results (first author is only one deduped and only one saved, the rest are silently dropped)

**Expected behavior**

**Screenshots**

- **before** here's a screenshot of the edit page where I'd entered all these authors:
![af417fde-ba72-4b14-9d71-9c3d63a2d71f](https://user-images.githubusercontent.com/156228/170724643-a32968c9-5ea8-4e27-a4e8-9d1885c82fba.png)

- **after** here's a screenshot of the edit page (after it asked me to merge just the first author in my edit's list of new authors, seemed to save successfully, loaded the view page of the book with only one new author showing, so I clicked through to edit page again via edit icon):
![ea10fd95-e689-41c8-a58d-4e0ecdd55105](https://user-images.githubusercontent.com/156228/170724697-bfc5ae26-adf8-49ac-9c87-a6c3dd7a6f55.png)

**Instance**

> On which BookWyrm instance did you encounter this problem.

bookwyrm.social

**Additional context**

> Add any other context about the problem here.

In case it helps, here's the actual book I was editing: 

---

**Smartphone (please complete the following information):**
    - Device: pixel 5
    - OS: Android 12
    - Browser: chrome

**Comment by mouse-reeve** [comment]
Thank you! This is fixed by #2108, which has been merged but not deployed yet

**Comment by jzacsh** [comment]
Doh, I searched the issues before posting, but clearly didn't search well enough. Thanks!
