### ISSUE TITLE
Page number not always shown with comments

### ISSUE THREAD

**Issue by chris-y** [bookwyrm-social/bookwyrm#2136]
**Describe the bug**
The page number relating to a comment is not shown in certain circumstances.

**To Reproduce**
1. Go to a book you are reading
2. Click on the arrow and "update progress"
3. Enter a page number and a comment
4. Click post
5. View the "Discover" page or look at the comment as viewed from a Mastodon instance 

**Expected behavior**
The page number is shown alongside the comment.

**Screenshots**
Correct (viewing comment on Bookwyrm):
![Screenshot_20220527-180307-166.png](https://user-images.githubusercontent.com/1818803/170748383-0d33f111-811e-4ab7-b494-2399351e096f.png)

Incorrect (viewing the comment in the context of the Discover page):
![Screenshot_20220527-180242-788.png](https://user-images.githubusercontent.com/1818803/170748863-505229a4-3631-4fa6-805e-f9e51d514c87.png)

Incorrect (viewing the comment via Mastodon):
![Screenshot_20220527-180339-895.png](https://user-images.githubusercontent.com/1818803/170749250-d2b13ede-3168-4ec7-a8a8-3b2199e137f1.png)

**Instance**
wyrms.de

**Additional context**
This is just an inconsistency on Bookwyrm (only noticed it on the discover page), but the federation to Mastodon is probably that this is extra metadata which Mastodon doesn't recognise? Not sure if federation Bookwyrm - Bookwyrm keeps the page number, I suspect it does.
I note that reviews have some text on Mastodon and just a link to the review, which differs from how it displays on Bookwyrm, so adding extra context ahead of the comment might be a solution?

**Comment by chris-y** [comment]
There appears to be a similar issue with quotes. Quotes on Bookwyrm end "by {author} (Page NN)". This section is missing from the end of the Mastodon federated quote.

**Comment by hughrun** [comment]
I think it's arguable how much value adding the author name provides, given there is a link to the book in each post. 

I'm going to create a PR which adds the page numbers in explore (for comments) and ActivityPub posts (for comments and quotes)

**Comment by mouse-reeve** [comment]
I believe this is closed by #2148
