### ISSUE TITLE
Creating a new book with multiple authors doesn't work correctly

### ISSUE THREAD

**Issue by lucianak** [bookwyrm-social/bookwyrm#2147]
**Describe the bug**
When I created a new book with multiple authors, after inputting all the authors in separate fields and saving only the first author was shown in the newly created book page. When I retried editing the book information and adding the missing authors, again only the first of the newly added authors was added to the book information. This happened independently if I confirmed that this author was an existing one after saving the book information or if I selected that the author was a new author. I had to edit the book information once for every author I wanted to add. 

**To Reproduce**
1. Create a new book entry with multiple authors
2. Save the book information
3. Confirm the author or create a new author, for me it didn't change the behaviour
4. Check the created entry if all authors are there or if only the first author is shown 

**Expected behavior**
I would expect all authors that are added while creating or editing book information to be added after saving. 

**Screenshots**
No screenshot, but the concerned book is this one: https://book.dansmonorage.blue/book/57341

**Instance**
https://book.dansmonorage.blue/

**Additional context**
Please let me know if additional context is needed, I can't think of anything relevant right now. 

---

**Desktop (please complete the following information):**
    - OS: Linux Manjaro with Gnome
    - Browser Firefox
    - Version 101.0

**Comment by coffeverton** [comment]
Hi, looks like your server is using the version 0.3.4.
They fixed it about a week ago, so you must update your server to fix this issue.

**Comment by lucianak** [comment]
Hi, thanks for the answer and sorry for not having checked the solved issues. I'm not running the server so will have to wait for the admins :)
