### ISSUE TITLE
Questionable license

### ISSUE THREAD

**Issue by Moogly** [bookwyrm-social/bookwyrm#2152]
> This is anti-capitalist software, released for free use by individuals and organizations that do not operate by capitalist principles.

So do I need to quit my job to use this thing? Why not use a non-commercial license that has been standardized? If you want to limit commercial usage I recommend AGPL, I avoid it like the plague at my job.

**Comment by mouse-reeve** [comment]
The license is only about how you use bookwyrm, not what you do in your life. So it's no issue to have a job at a for-profit company, for example, it would only be an issue if you were running bookwyrm as part of that job.

I'm happy to clarify questions about the license, and if you're curious about the philosophy there's a lot of great info on its [website](https://anticapitalist.software/). But the license itself isn't up for discussion -- I hear that that's frustrating, and I think we're both trying to build towards a healthier software ecosystem, while disagreeing on the approach. So I appreciate your care about this, but I'm not looking to change it at this time.
