### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [bookwyrm-social/bookwyrm#2158]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@vovikhangcdv) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by mouse-reeve** [comment]
Hi thank you! I'll do that. In the mean time, mousereeve@riseup.net is a good place to send it

**Comment by JamieSlome** [comment]
@mouse-reeve - appreciate your response and diligence 👍 

I've opened up https://github.com/bookwyrm-social/bookwyrm/pull/2159 to help you out :)
