### ISSUE TITLE
Private lists appear on Lists page

### ISSUE THREAD

**Issue by hughrun** [bookwyrm-social/bookwyrm#2162]
**Describe the bug**
When I go to `/list` and see the "All lists" tab, I can see the list name, cover images, and "Created and curated by" name for lists that are private. When clicking on the title, appropriately it returns a 404 as I should not be able to access these lists.

It seems to me that private lists should not be visible at all to anyone other than the list owner.

**To Reproduce**
1. Go to `/lists` when logged in to bookwyrm.social
2. Observe that you can see lists with an envelope icon indicating they are private
3. Click on the name of one of these lists
4. See a 404 page

**Expected behavior**
I would expect private lists to be, well, private. Therefore they should not appear at all in the public Lists discovery page.

**Screenshots**
![Screen Shot 2022-07-02 at 6 36 45 pm](https://user-images.githubusercontent.com/17669239/176993299-7dfe388b-b1c2-4522-adc0-4f61afeb5f72.png)

**Instance**
bookwyrm.social

**Additional context**

---

**Desktop (please complete the following information):**
    n/a

**Comment by mouse-reeve** [comment]
Oh I wrote a fix for this but haven't gotten the tests set for it -- the list of lists isn't being updated properly when a list's privacy is edited. https://github.com/bookwyrm-social/bookwyrm/pull/2057
