### ISSUE TITLE
Menus don't fully close on mobile when updating reading progress

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#2178]
On my phone, when I open a reading progress modal from a menu, the menu stays open and on top of the modal.

![Screenshot_20220704-094332](https://user-images.githubusercontent.com/1807695/177230313-2ce2099c-4140-4bef-bec0-da2eca49f218.jpg)

---
**Smartphone (please complete the following information):**
    - Device: Android
    - Browser Chromium

**Comment by obrenckle** [comment]
Hi @mouse-reeve, and thank you for your work with bookwyrm !
I investigated this issue and I think I found two causes:
- the drop-down menu's z-index is set to 100 on a phone (20 on desktop), while the modals all default to a z-index of 40
- the drop-down menu isn't closed when one if its item is selected

The first part could be solved by setting the drop-down z-index to 35, below modals, but above the navbar (z-index 30). That could be a quick but partial fix to this issue.

For the second part, a solution could be to add an optional call back function parameter to the handleModalButton function, and use it to handle closing the drop-down menu, for modals activated from a drop-down menu.

I'm not exactly a javascript developper, but I could try to come up with Pull Requests if these solutions sound good to you.
