### ISSUE TITLE
No check if finish date has not happened yet

### ISSUE THREAD

**Issue by joelchrono12** [bookwyrm-social/bookwyrm#2191]
**Describe the bug**
There is no check to avoid finishing a book in a date that still has not happened

**To Reproduce**
1. On a currently reading book, click on "Finish reading"
2. Set a finish date in the future
3. Click "Post"
4. There is nothing stopping you to do it

**Expected behavior**
The Post button should be disabled until a valid finish date is chosen 

**Screenshots**
As you see, the Post button is pretty easy to click here :P  
![image](https://user-images.githubusercontent.com/18448587/177686213-f904f303-575d-456e-a3d8-789a2876da54.png)

**Instance**
https://bookrastinating.com

---

**Desktop (please complete the following information):**
    - OS: Fedora
    - Browser Firefox
    - Version 102

**Comment by hughrun** [comment]
@mouse-reeve we can close this issue now?

**Comment by mouse-reeve** [comment]
Yes!
