### ISSUE TITLE
Adding a space after typing a username will not show that user in the search results

### ISSUE THREAD

**Issue by joelchrono12** [bookwyrm-social/bookwyrm#2205]
**Describe the bug**
When I search for "@user@example.com" it won't work if the input has a space at the end ("@user@example.com ")
It may work if the user has already been searched for before though. 

**To Reproduce**
1. search a user you don't currently follow
2. add a space at the end
3. the user won't be found

**Expected behavior**
spaces should be ignored when looking for usernames

**Instance**
On which BookWyrm instance did you encounter this problem.

**Additional context**
Bookrastinating.com

---

**Desktop**
    - OS: Fedora
    - Browser Firefox
    - Version 102

**Comment by hughrun** [comment]
I'd love to fix this but I don't seem to be able to replicate it in a dev environment. Searching for a fediverse user not yet known on the bookwyrm server seems to come up with no result, whereas if the user is known to the server, spaces don't seem to make any difference. @mouse-reeve is there anything additional I might need to switch on in the config?
