### ISSUE TITLE
Move 3-dot menu items to the right side/center of the screen for accesibility

### ISSUE THREAD

**Issue by joelchrono12** [bookwyrm-social/bookwyrm#2209]
**Is your feature request related to a problem? Please describe.**
When using the mobile version of Bookwyrm, the menu items are hidden in a 3-dot menu. This is fine, by tapping it it expands and shows the  Feed Lists and Discover items. Tapping on the profile pic opens yet another menu to access Your Books and the rest of elements

The titles of these elements are on the left. Thankfully, you don't need to specifically tap the title, but the region itself works as a link. This is still kinda confusing though.

**Describe the solution you'd like**
Move these links to the left or center of the screen, and if possible, position them near the bottom of the screen.

**Describe alternatives you've considered**
Emm, I guess I could just keep using it since its not the end of the world, but still

**Additional context**
![image](https://user-images.githubusercontent.com/18448587/178121094-7ad1e59e-3781-441c-bdca-6218e20cabb4.png)

**Comment by lodenrogue** [comment]
The reasoning for the suggestion is that it will be easier for users to reach? What about users that can't reach the right side of the screen?

**Comment by joelchrono12** [comment]
Perhaps doing it like protonmail does with some of its elements (at the center of the screen, vertically and horizontally) is a better approach then :P

**Comment by martispyc** [comment]
Moving the items to the right would be better for right-hand dominant individuals (around 90%) but a good alternative is to center the items. The only downside is that it would look messy.

**Comment by hughrun** [comment]
Running the menu down the right side and right-aligning the text does seem like it would be more intuitive, given the trigger to open this menu is in the top right corner, hence the menu will "drop down" like the user menu on larger screens.
