### ISSUE TITLE
2FA Support

### ISSUE THREAD

**Issue by SrEstegosaurio** [bookwyrm-social/bookwyrm#2250]
Having suppart for 2FA would be an amazing security improvement for everyone. That's it. :D

Btw: thanks for working on this amazing project. <3

**Comment by SrEstegosaurio** [comment]
Something important that sometimes I see neglected on other projects are the **recovery codes**. Those need to be provided at 2FA activation time to act as a backup in case of not having acces to the codes. 

I say this because I lost a few accounts already due to them not providing recovery codes. :/

Anyways, a lot of thanks for reading my previous issue. (:

**Comment by hughrun** [comment]
This would be cool.

We could probably use [pyOTP](https://pyauth.github.io/pyotp/) and [qrcode.js](http://davidshimjs.github.io/qrcodejs/)

TOTP for the standard 2FA
HOTP for backup codes

**Comment by hughrun** [comment]
I'm working this now.

**Comment by mouse-reeve** [comment]
We have thisnow ! Thank you Hugh!!
