### ISSUE TITLE
Delete Notifications button should not appear if there are no notifications to delete

### ISSUE THREAD

**Issue by hughrun** [bookwyrm-social/bookwyrm#2264]
**Describe the bug**
The `X Delete notifications` button always appears on the page at `/notifications`.

**To Reproduce**
1. Go to `/notifications`
2. Click on `X Delete notifications`
3. Notice that button remains on screen even if there are not any notifications to delete

**Expected behavior**
It seems more logical that this button would only be visible if there are notifications to be deleted.

**Screenshots**
![Screen Shot 2022-08-09 at 8 47 09 pm](https://user-images.githubusercontent.com/17669239/183630196-565636e7-4015-4fcc-a111-1ec9c037178f.png)
![Screen Shot 2022-08-09 at 8 46 46 pm](https://user-images.githubusercontent.com/17669239/183630220-0df22ef2-aa19-4324-b5c6-d04b1feaf4a1.png)

**Instance**
bookwyrm.social

**Additional context**
I'm guessing it would be easier to simply not show the button on page load if there are not any notifications, whereas "disappearing" it after clearing notifications is likely going to require JS.

---

**Desktop (please complete the following information):**
    - OS: MacOS
    - Browser Firefox
    - Version 103.0.1

**Smartphone (please complete the following information):**
    - Device: iPhone

**Comment by mooseyboots** [comment]
@mouse-reeve does this just need an if statement in the notifications html file? like so: https://github.com/mooseyboots/bookwyrm/commit/b4cc9f5753da56551a8958255bb59111b086ecf7.

i tried it in a dev env, but was unable to test it when i *did* have notifications, as private messaging myself did not generate any. adding a second account requires an email invite, which i figure a dev env cannot send.

**Comment by mooseyboots** [comment]
@hughrun thanks a lot,  that works!

so the button appears when there are new notifications, does not appear when there are none, and disappears when the page is reloaded by clicking on it.

seems good.

**Comment by mouse-reeve** [comment]
This looks good! Open a PR for it :)
