### ISSUE TITLE
Ignore missing leading zeros when searching ISBN

### ISSUE THREAD

**Issue by jfinkhaeuser** [bookwyrm-social/bookwyrm#2269]
**Is your feature request related to a problem? Please describe.**
Many older books have an ISBN (ISBN-10 to be precise), but omit any leading zeroes.

**Describe the solution you'd like**
When searching ISBNs, permit leading zeroes to be omitted. As it stands, matches are precise, so without the leading zeroes, nothing is found.

**Comment by hughrun** [comment]
@jfinkhaeuser can you explain a little more about the use case here? Typically an ISBN-10 would be printed including any leading zeroes, are you suggesting this sometimes doesn't happen, or that users may erroneously omit them, or something else?

**Comment by jfinkhaeuser** [comment]
I have plenty of older books where leading zeros are NOT printed. These predate barcodes, but already have ISBN-10.

**Comment by hughrun** [comment]
@jfinkhaeuser this should be fixed by #2282, just waiting on feedback on my latest update to that.

**Comment by Te-k** [comment]
Thank you for fixing that bug <3
