### ISSUE TITLE
resetdb doesn't work

### ISSUE THREAD

**Issue by hughrun** [bookwyrm-social/bookwyrm#2276]
**Describe the bug**
`./bw-dev resetdb` fails with the following error message:

```
dropdb: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
```

**To Reproduce**
1. run command
2. see error
3. database is not dropped

**Expected behavior**
Dev database is wiped and docker build process is restarted

**Screenshots**

**Instance**
n/a

**Additional context**

---

**Desktop (please complete the following information):**
    - OS: MacOS
    - Browser [n/a
    - Version `main` 

**Smartphone (please complete the following information):**

**Comment by mouse-reeve** [comment]
I wonder if this command should be jettisoned in favor a command that removes the docker images 🤔

**Comment by hughrun** [comment]
I can see two distinct but related use cases, that probably calls for two different commands or maybe one command with an optional flag.

1. remove bookwyrm docker _images_ (maybe you were fiddling with the build and want to pretend it never happened)
2. remove all bookwyrm _volumes_ (your ngrok URL changed or something and you need to wipe the database)

I'd quite liked the convenience of having a command that wipes everything _and_ rebuilds the image _and_ runs migrations and setup. But, I may be an edge case.

**Comment by mouse-reeve** [comment]
I don't think you're an edge case, I wipe everything and rebuild pretty often -- that was what I originally meant for the command to do.
