### ISSUE TITLE
Certbot failed to authenticate some domains

### ISSUE THREAD

**Issue by Zagur** [bookwyrm-social/bookwyrm#2302]
**Describe the bug**
I am following the instructions in the documentation to install a new instance but after running `docker-compose up --build` to see that everything is up correctly, I see the following error:

```
certbot_1         | Account registered.
certbot_1         | Requesting a certificate for mydomain.com
certbot_1         | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot_1         | Some challenges have failed.
certbot_1         | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
certbot_1         | 
certbot_1         | Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
certbot_1         |   Domain: mydomain.com
certbot_1         |   Type:   connection
certbot_1         |   Detail: xxx.xxx.xxx.xxx: Fetching http://mydomain.com/.well-known/acme-challenge/qBf8kLzp72uS7asSdPDimS6m-afoFmcfdEGGlhFxzw8: Connection refused
certbot_1         | 
certbot_1         | Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.
certbot_1         | 
```

I have hidden my domain and IP from my server, but this domain responds correctly to ping.

**To Reproduce**
1. https://docs.joinbookwyrm.com/install-prod.html
2. Step: "Run the application (this should also set up a Certbot ssl cert for your domain) with docker-compose up --build, and make sure all the images build successfully"

**Expected behavior**
Create SSL certificate.

**Instance**
In one that is in process.

---

**Desktop (please complete the following information):**
    - OS: Ubuntu 22.04

**Comment by mouse-reeve** [comment]
Is you `nginx.conf` set up to serve the acme challenge file? It should look something like:

```nginx
include /etc/nginx/conf.d/server_config;

upstream web {
    server web:8000;
}

server {
    listen [::]:80;
    listen 80;

    server_name your-domain.com www.your-domain.com;

    location ~ /.well-known/acme-challenge {
        allow all;
        root /var/www/certbot;
    }

}
```

It might also be worth running the nginx validator using `docker-compose run --rm nginx nginx -t` to make sure there aren't any issues with the file.

**Comment by Zagur** [comment]
> It might also be worth running the nginx validator using `docker-compose run --rm nginx nginx -t` to make sure there aren't any issues with the file.

Nginx configuration is correct:

```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

In nginx.conf everything is correct, it is the file that is already in the repository, I only modify the value for my domain.

Regards
Zagur

**Comment by Zagur** [comment]
I just found out what the problem was. It was related to the Firewall. Fixed it.
