### ISSUE TITLE
Add a Reviews and Comment tab users profile

### ISSUE THREAD

**Issue by edmael** [bookwyrm-social/bookwyrm#2306]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a user-related feed of reviews and comments made by them.
Right now there's no way to filter out comments/reviews from "wants to read"/"finished reading" making it a bit more difficult to create a discussion/engage with a user.
Adding a "Reviews and Comment" tab in a user profile would help engagement and discussions between users.

**Additional context**
I've added a simple image to show a bit better what I mean with this feature request.
![immagine](https://user-images.githubusercontent.com/1659050/192251346-30fab5cf-b0b2-488f-92e9-afa8ebee4cbf.png)

**Comment by placoderm** [comment]
This makes a lot of sense and seems like a natural feature for a social book network.
