### ISSUE TITLE
Merge individual book entries to editions of one and the same book entry

### ISSUE THREAD

**Issue by Cs137** [bookwyrm-social/bookwyrm#2307]
**Is your feature request related to a problem? Please describe.**
Since many books are existing a couple of times, it would be handy to merge them to one entry and define them as new editions.

**Describe the solution you'd like**
Option to search for book within entry editor and checkbox to define currently editing entry as version of book found via the onpage search.

**Comment by nichobi** [comment]
Duplicate of #562 (though the title is a little hard to search for)

**Comment by mouse-reeve** [comment]
Closing this as a duplicate of #2664
