### ISSUE TITLE
Additional metadata field for translator(s) in book entry

### ISSUE THREAD

**Issue by Cs137** [bookwyrm-social/bookwyrm#2308]
**Is your feature request related to a problem? Please describe.**
For translated version of books, it would be handy to assign translator(s) to the entry.

**Describe the solution you'd like**
List of objects comparable to the author(s).

**Comment by franbarra** [comment]
Hello! This issue of multiple types of authors was discussed in #1120.

**Comment by mouse-reeve** [comment]
Closing this as a duplicate of #1120 ❤️
