### ISSUE TITLE
Add review count to book search listing to concentrate reviews

### ISSUE THREAD

**Issue by cblgh** [bookwyrm-social/bookwyrm#2317]
Often when I'm searching for a book to e.g. mark as having started reading, or to figure out if any other wyrms have reviewed it, I'll have more than one search result. 

![image](https://user-images.githubusercontent.com/3862362/196053166-f31dc917-15d7-411e-8249-97706cdb5869.png)
_two results for wayfarer no 2_

I typically don't really care so much about reviewing a given edition (I read a lot of non-scholarly ebooks). So instead of finding a particular edition, I want to find the one that has been reviewed by people I follow & whose judgement I trust. Similarly, I'd want to contribute _my_ review to that growing pile of context around a given book.

To aid this, I suggest adding some light information markers to the search results. # of reviews would be one concrete suggestions, another would be to display which ones people I'm following have reviewed. Basically use whatever makes sense from a fast query perspective imo :)

Thanks again for bookwyrm! It's a delightful space and I've found _so_ many books over the soon-to-be 2 years since I joined!! u rok

**Comment by mouse-reeve** [comment]
This is such a good idea! Thank you

**Comment by cblgh** [comment]
yooo nice, thanks based dev @mouse-reeve 😍
