### ISSUE TITLE
Searching "Being and Time" Returns 502 Error

### ISSUE THREAD

**Issue by TomatDividedBy0** [bookwyrm-social/bookwyrm#2318]
Other functions and searches on BookWyrm seem to work, but consistently over a period of weeks, whenever I search "Being and Time" in the catalog, I'm met with a 502 error. Not sure at all what would possibly cause this.

**Comment by mouse-reeve** [comment]
This may have been resolved by #2385 -- are you still seeing this behavior?

**Comment by TomatDividedBy0** [comment]
> This may have been resolved by #2385 -- are you still seeing this behavior?

Nope, looks good now.
