### ISSUE TITLE
Announcements bar at the top takes up space even if dismissed

### ISSUE THREAD

**Issue by viviicat** [bookwyrm-social/bookwyrm#2319]
**Describe the bug**
[this is extremely minor]

If there is at least one active Announcement published, it takes up space at the top of the page, even if the user has dismissed it. This wastes a small amount of vertical screen space.

**To Reproduce**
1. Add an Announcement.
2. Dismiss announcement.
3. Notice the announcement `<div>` is taking up space even though it has no visible content.

**Expected behavior**
Dismissed announcements do not take up space.

**Screenshots**
![Screenshot from 2022-10-19 13-43-10](https://user-images.githubusercontent.com/287339/196800330-5ae16ed2-1f33-4e18-87c9-a7ff297d58cf.png)
![Screenshot from 2022-10-19 13-43-24](https://user-images.githubusercontent.com/287339/196800335-038e8e25-f6cb-4a20-b8dc-bf141e52b906.png)

**Instance**
https://books.solarpunk.moe

---

**Desktop (please complete the following information):**
    - OS: Linux
    - Browser Firefox
    - Version 105

**Comment by mouse-reeve** [comment]
I love an easy problem to fix :)
