### ISSUE TITLE
How hard would it be to track science articles using DOIs?

### ISSUE THREAD

**Issue by darachm** [bookwyrm-social/bookwyrm#2334]
**Is your feature request related to a problem? Please describe.**
No problem! Just trying to understand if a thing is feasible, before getting too into the idea for advancing scientific discourse into the fediverse.

**Describe the solution you'd like**
Is it be possible for BookWyrm to support tracking scientific articles using DOIs?

Many scientists are trying to move off Twitter. This opens up new opportunities for how folks were talking about articles, especially what they thought in detail about articles. It sounds like BookWyrm is a fantastic fit for this kind of work. It seems like if articles could be added just like books are, then accounts in BookWrym servers could indicate reading and reviewing articles and that those are then visible on a causal chatter network like Mastodon. Or just stay on BookWyrm in the future so you only need one account!

It does not seem like I can add articles to write about them in BookWyrm. For example this one: https://elifesciences.org/articles/83907 . A convienent and pretty authoritative way to reference science articles, datasets, just about everything is with a DOI. [These](https://doi.org) are the way we track just about everything you could cite or talk about. Preprints, articles, datasets. Services like the non-profit crossref have APIs to resolve that to metadata:  https://api.crossref.org/works/10.7554/eLife.83907 , [more deets here](https://www.crossref.org/documentation/retrieve-metadata/rest-api/a-non-technical-introduction-to-our-api/). If I search for the title or the DOI of that in BookWyrm, I don't see anything.

Is it possible to modify BookWyrm to permit adding articles as "books" using the DOI system (see above for DOI to metadata API)?
Would it be better to fork BookWyrm for that functionality, or for books to just reference books and articles?
Is this an easy lift, or is this something that an agency or non-profit publisher like PLoS or eLife could fund a grant for developing?

What would this look like, roughly, to do?
Do you have suggestions for parts of the code to look at for understanding the underlying databases and how it's all wired?
Do I just write a connector like [here](https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/connectors/abstract_connector.py) ?

**Describe alternatives you've considered**
There are silo'd version of this kind of thing, platforms for discussing articles. I do not know of one that runs ActivityPub. Please correct me if anyone knows!

Forgive me if this is out-of-band or out-of-scope, I'm just excited that sceince twitter seems to be finally leaving twitter, and excited for what new opportunities we have now.

**Comment by darachm** [comment]
Wow this is cool! Got dev setup, and trying to modify it now. This whole docker/django/etc setup is neato

I put a DOI `CharField` in the `models/book.py`, and I think that then means everything from that model then has a DOI. This might suggest that a more ontologically clean version of what I'm thinking about would be writing my own darn models thata are "objects" or the like, but for now it doesn't seem to error out when I use the handy `bw-dev makemigrations` then `migrate` then `up`. That seems to get a DOI field in there okay so I can edt a book and add it and see it, but it's kinda hacky.
All that is here 
https://github.com/bookwyrm-social/bookwyrm/compare/main...darachm:bookwyrm-doi:crossref

The trickier bit that I can't quite figure out is how the connectors are fitting together... I've started by copying the openlibrary one and trying to modify it to map from the JSON returned by crossref to the internal data, but I've got to stop there for today.

Am I on the right track?

**Comment by mouse-reeve** [comment]
Although I've had some trepidation about expanding bookwyrm outside of books, I do think academic articles are an interesting use case and I'm interested in supporting them. (I think I talked about this with @hughrun at one point? Am I misremembering?)

I'd need to think a little deeper about how to structure the models, and right now there are unfortunately like 10 other things on fire and I have too few neurons left. I'd be super happy at a calmer time to talk more about it and help clarify how the connects work (that is the right place for adding external data).

**Comment by darachm** [comment]
Okay I'm looking in the right place and will keep poking at it, see if I can't understand it and get a demo of it up and then re-think with yall how it should be done for real (with proper style and all).

Will update here any progress, in case anyone else is curious about it.

Sounds like the fediverse is firing on all cylinders, so good times and thanks for the work yall are doing and what it took to get here.

**Comment by darachm** [comment]
I'm interested in it as a demo of what postpub peer review could look like, with the vague hope that someone like CSHL or PLoS or eLife would want to plunk down some cash grant for a proper fork. This is a vague speculative dream, expecially because I keep bumping this to the next todo list week after week!

One day I'll have time, I swear, but I started a few tweaks in the above linked branch of a fork. It has a field for DOI, and  next needs to have a connector that makes the DOI info request from CrossRef.

**Comment by mouse-reeve** [comment]
I'm closing this so that #1607 can be the canonical issue for this topic
