### ISSUE TITLE
413 Request Entity Too Large on import - no UI warning + possible to bypass

### ISSUE THREAD

**Issue by msub2** [bookwyrm-social/bookwyrm#2340]
**Describe the bug**
A user recently reported to me that they received a 413 - Request Entity Too Large error when attempting to import a file larger than 2MB. While I don't have the exact file they used, I was able to replicate the behavior by attempting to upload a shortcut file that pointed to a larger exe. This was not caught by the size checker. Additionally, when directly choosing a file over the size limit there is no visual indicator other than the import button being disabled, although I can see in code that there is supposed to be.

**To Reproduce**
1. Go to https://books.theunseen.city/import
2. Click on Browse
3. Select a file over 2 MB large.
4. See that there is no visual feedback other than the disabled import button.

OR

3. Select a shortcut to a file over 2 MB large.
4. Receive a 413 error on submit

**Expected behavior**
User should be shown clear feedback that the file they have selected is too large.

**Screenshots**

**Instance**
https://books.theunseen.city/

**Additional context**
The primary issue for the user here is moreso that they need a higher file size limit to import their data, the lack of warnings is essentially a secondary issue I noticed when checking myself.

---

**Desktop (please complete the following information):**
    - OS: Windows 10
    - Browser: Firefox
    - Version: 106

**Comment by msub2** [comment]
The bypass issue could probably be solved just by restricting the filepicker to .csv files, since those are the only kinds listed as being valid for import.

**Comment by mouse-reeve** [comment]
TSV is also a valid format, but you're right that it ought to check
