### ISSUE TITLE
Non Docker-Version

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2342]
**Is your feature request related to a problem? Please describe.**
My problem is that I have a nice server running but for reasons I am not able to run Docker. If I look back in history the last three places where I had my things running were not able to run Docker (like, uberspace e.g. gives me a shell and I can install tools and everything but I can not get a chroot which docker needs)

**Describe the solution you'd like**
I would like a "de-docker-fied" possibility in the docs tu run it on a server.

**Describe alternatives you've considered**
Alternative would be to rent another server just for bookwyrm. Which I will not do.

thanks for considering.

**Comment by mouse-reeve** [comment]
Good question! We actually do have dockerless install instructions and I completely forgot to update the docs to display them. I fixed that and you can now find that here: https://docs.joinbookwyrm.com/install-prod-dockerless.html
