### ISSUE TITLE
Error in plain text verify Email

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2343]
**Describe the bug**
I joined a bookwyrm instance
I got an email to verify my emailadresse.
The email was read in plain text mode.
the email has HTML Tags in plain text. 

**To Reproduce**
1. Do what I have done

**Expected behavior**
I expect no HTML tags in a plain text email.

**Screenshots**
<img width="1069" alt="Bildschirm­foto 2022-11-10 um 21 31 56" src="https://user-images.githubusercontent.com/2017105/201203418-444e5a39-522c-4d57-a5da-9e23bbc17373.png">

**Instance**
Unseen City

---

**Desktop (please complete the following information):**
    - thundebrird 102.4.2

**Comment by mouse-reeve** [comment]
It looks like this was an error in the German locale -- I've fixed it over at [translate.joinbookwyrm.com](https://translate.joinbookwyrm.com/translate/bookwyrm/1553/en-de#40731)
