### ISSUE TITLE
an API for adding a single book?

### ISSUE THREAD

**Issue by puntomaupunto** [bookwyrm-social/bookwyrm#2354]
Importing my library from Goodreads resulted in more that half titles unknown (or which matched "Les Misérables" :-) ) Importing a .tsv from LibraryThing results in a server error.

I understand that I have many Italian books, which are not present in OpenLibrary or inventaire.io; but I thought that the data present in my imported file should be sufficient to create a record, even if partial (for example, there would be no cover). A workaround for this would be to have an API which let us add a single book to the database in a specifica format; it would be up to us to convert our databases in that format. Is that viable?

**Comment by mouse-reeve** [comment]
We don't have API access at this point, although servers are sharing book data via ActivityPub, which is a way new books are added programmatically. 

One feature I've been meaning to add for a while but haven't gotten to yet is to allow users to create a new book based on a CSV/TSV import entry that failed to match. I wonder if that would also help for your use case?

Regarding Librarything, that sounds like a separate issue!

**Comment by puntomaupunto** [comment]
Yes, I think that if I could create books based on a CSV import I would eventually be able to massage my data to have it work :-)

**Comment by mouse-reeve** [comment]
I'm closing this because I think it's covered by https://github.com/bookwyrm-social/bookwyrm/issues/1820 and https://github.com/bookwyrm-social/bookwyrm/issues/785
