### ISSUE TITLE
Need for an extra page Legal/Impressum

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2363]
**Is your feature request related to a problem? Please describe.**
In Germany (and Austria as well, I do not know for other countries) I need to have some legal notes present (it is called Impressum) which needs to be reachable via a link from the entry page. 
 
**Describe the solution you'd like**
A menu point at "instance settings" gives the opportunity to add at least one extra site and specify the title and content of the site. 

**Describe alternatives you've considered**
Hack something into the code

**Comment by jaschaurbach** [comment]
Yes, so basically I need links on the front-page: Privacy and Legal/Impressum

**Comment by marcusyoung** [comment]
Along the same lines, there is also the pesky cookie consent issue for EU and UK. I don't know whether it can be argued that the ‘strictly necessary’ exemption applies. If not, users need to give a clear and positive action to give consent to the use of cookies.

**Comment by jaschaurbach** [comment]
the user needs to be informed about cookies, what they are used for, which information they store and how long the cookie persists. If the cookie is relevant that the site works proper, there is only need to show that this cookies are used.

I was going to file another request regarding this issue as this needs some more work done...

**Comment by mouse-reeve** [comment]
We do only use "strictly necessary" cookies are far as I understand it -- cookies handle user authentication sessions as built in to Django, and the only custom cookie sets language preference.

**Comment by jaschaurbach** [comment]
And how long do these cookies stay? (sorry, Europe and GDPR - for me as a European it is pain)

**Comment by mouse-reeve** [comment]
Two weeks, [via the Django defaults](https://docs.djangoproject.com/en/4.1/ref/settings/#session-cookie-age)

**Comment by hueyy** [comment]
Linking a relevant discussion on Mastodon with respect to cookie banners: https://github.com/mastodon/mastodon/issues/19679#issuecomment-1321118272
