### ISSUE TITLE
fetichign remote_id not present sometimes lead to 502

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2372]
**Describe the bug**
I klicken on a link leading somewhere on own instance gives a 502

**To Reproduce**
This somtimes happens a remote ID can not be fetched. from STDERR

```
2022-11-15 14:18:19,504 DEBG 'bookwyrm' stderr output:
Could not connect to host for remote_id: https://mastodon.social/users/ScottScribe
Traceback (most recent call last):
  File "/home/wyrm/bookwyrm/bookwyrm/activitypub/base_activity.py", line 272, in resolve_remote_id
    data = get_data(remote_id)
  File "/home/wyrm/bookwyrm/bookwyrm/connectors/abstract_connector.py", line 247, in get_data
    raise ConnectorException()
bookwyrm.connectors.connector_manager.ConnectorException
```

**Expected behavior**
The link opens up, the background task does not affect anything

**Screenshots**

**Instance**
books.jascha.wtf

**Additional context**

---

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by jaschaurbach** [comment]
I am not running behind nginx, it is behind an apache. 

Nope, it happens randomly :(

**Comment by mouse-reeve** [comment]
I see! I think the best next step would be to check your apache logs and see if you can find an error in those logs that correspond to the link that you were trying to click. The web server logs probably won't have anything helpful, since the connection isn't going through.

**Comment by jaschaurbach** [comment]
I will activate the login and go through the logs (yes, I do not log per default unless needed)

**Comment by jaschaurbach** [comment]
This can be closed as the 502 was not created by my first thoughts.
