### ISSUE TITLE
Larger, extendable, or configurable character limit for invite request text response

### ISSUE THREAD

**Issue by viviicat** [bookwyrm-social/bookwyrm#2377]
**Is your feature request related to a problem? Please describe.**
When requesting an invite, some users complain that 50 characters is not enough to answer the question. In our case the question is "How do your interests overlap with the concept of Solarpunk?"

**Describe the solution you'd like**
I would like one of the following, if possible:
- Configurable length for the invite request response in the settings form
- Longer length (100-150 would probably suffice)
- Selection of type of response (short versus long text,  this is how Funkwhale does it)

**Describe alternatives you've considered**
Cannot think of an alternative other than patching the code.

**Additional context**
Here is Funkwhale's solution to this problem:
![image](https://user-images.githubusercontent.com/287339/202022345-93a741a3-717d-4961-ad34-da2906285fed.png)

**Comment by mouse-reeve** [comment]
The simplest fix would just be to [expand the character limit in the database](https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/models/site.py#L184) to something more sensible.
