### ISSUE TITLE
Dark theme is incompatible with 2FA

### ISSUE THREAD

**Issue by viviicat** [bookwyrm-social/bookwyrm#2386]
**Describe the bug**
When using 2FA, the generated QR code does not have a white backdrop.

**To Reproduce**
1. Enable the Dark theme
2. Set up two-factor authentication until you observe a bar code to scan
3. Attempt to scan with Google Authenticator or similar, and note that it has a lot of trouble with the reduced contrast.

**Expected behavior**
2FA works for dark theme.

**Instance**
Solarpunk.moe

---

**Desktop (please complete the following information):**
    - OS: Gentoo Linux
    - Browser: Firefox
    - Version 106.0.5

**Comment by hughrun** [comment]
ugh sorry this was a QA fail, I thought I'd tested it with dark mode but must have subsequently changed something — I just noticed exactly this problem myself in production.

@mouse-reeve please assign to me.
