### ISSUE TITLE
2FA signup should present the code as well as the QR image.

### ISSUE THREAD

**Issue by moopet** [bookwyrm-social/bookwyrm#2389]
2FA currently assumes a phone with a camera is going to be the 2FA device, but this isn't always the case. Presenting the TOTP authenticator key would allow a wider range of 2FA devices to be used.

**Comment by hughrun** [comment]
oh lol sorry I assumed this was brand new and didn't see @jaschaurbach's PR.

@mouse-reeve I'm going to revert this re showing the code, Jascha's is better.
