### ISSUE TITLE
Autors do not update in list

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2391]
**Describe the bug**
I have a list (https://books.jascha.wtf/list/1/s/queerwelten) with some books. Later, I added some authors to books. In the list they are still missing (Example book: https://books.jascha.wtf/book/51)
 
**To Reproduce**
1. Create a list
2. Add a book
3. Later, add more authors to the books
4.I the list overview they are not updated

**Expected behavior**

**Screenshots**

**Instance**
books.jascha.wtf
**Additional context**

**Comment by marcusyoung** [comment]
Looks ok to me: 3 authors and "3 others"?
At a guess there was some caching going on.

**Comment by jaschaurbach** [comment]
Question is: where? Because I still get it like described.
<img width="1293" alt="Bildschirm­foto 2022-11-16 um 20 36 18" src="https://user-images.githubusercontent.com/2017105/202277486-ff0201c1-0aff-42bb-947d-1a0f7f7dbf6c.png">

**Comment by marcusyoung** [comment]
Just to check, are we looking at same thing?
![image](https://user-images.githubusercontent.com/10391966/202277821-4d096fb5-081b-4311-8742-e85437800ec7.png)

**Comment by jaschaurbach** [comment]
Looks like my list. But logged out in a new private browser window on safari and in a new private browser window it is the same as with my first screen shot

**Comment by marcusyoung** [comment]
The caching is quite aggressive for some elements, part of redis. You can clear the cache with `redis-cli flushall`. After that have to re-create the timelines. There's a discussion on Matrix from a few days ago. Don't know if that is your problem but worth seeing?

**Comment by jaschaurbach** [comment]
OMG, what an aggressive caching :D This solved it. Thank you for helping out!
