### ISSUE TITLE
Missing js/css Files

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2403]
**Describe the bug**
I created a list and wanted to embed it on my website. It looked quite ugly and I was looking what is happening. `static/css/bookwyrm.css` is missing as well as `static/css/vendor/bulma.min.css` are missing. 

**To Reproduce**
I just was not sure if it is my setup or not. I cloned the bookwyrm repository and just started the it with `./bw-dev up`
I created a list and put a book on it. 
I copied the embedding code, pasted it into a new HTML got the same issue

**Expected behavior**
Both files exist and the page looks nice :) 

**Screenshots**
<img width="1233" alt="Bildschirm­foto 2022-11-17 um 22 07 43" src="https://user-images.githubusercontent.com/2017105/202561369-a5b0f52f-7c4d-407f-951b-c2b929f5cf99.png">

**Instance**
books.jascha.wtf, local instance

**Comment by mouse-reeve** [comment]
I can replicate this locally. The problem seems to be that the embed is using the wrong path (the old css files rather than the new theme files)
