### ISSUE TITLE
GDPR requires data to be deleted on request

### ISSUE THREAD

**Issue by marcusyoung** [bookwyrm-social/bookwyrm#2420]
GDPR requires that user data is deleted on request or on withdrawal of consent (inferred by a user deleting their account). However, the delete option only marks an account as deleted and as far as I can tell retains all the data for that user in the database. This needs to be addressed to be compliant with GDPR in EU/UK.

**Comment by jaschaurbach** [comment]
I just checked what we can keep: 

* username
* E-Mail
DSGVO 6, lit b,f

**Comment by jaschaurbach** [comment]
#2510 deletes Avatar when user is deleting themselves or is banned from instance
