### ISSUE TITLE
Let Books have release date give only by month an year or only year

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2422]
**Is your feature request related to a problem? Please describe.**
I read a Zine and wanted to add it to my reading list. The Zine was released in August 2022, no day given.
To add it to BookWyrm, I had to make up a day to enter it.

**Describe the solution you'd like**
I would like to set the release date only to a year or a month and a year. To avoid mistakes by just forgetting the values user should explizit tick a box "Date and/or month unknown". 

**Describe alternatives you've considered**
Coming up with a day (or months) which leads to false data or not entering the date at all.

**Comment by marcusyoung** [comment]
See #743 for open issue on this. Related to the Postgresql fieldtype used.

**Comment by jaschaurbach** [comment]
Oh! Oversaw this. Will close this one.
