### ISSUE TITLE
Improve contrast for dark mode

### ISSUE THREAD

**Issue by placoderm** [bookwyrm-social/bookwyrm#2425]
**Describe the bug**
The difference between the card background and site background is much too small

**To Reproduce**
Go to the feed in darkmode.
![2022-11-19 09_11_33-_ Untitled -1 0 (RGB color 8-bit gamma integer, GIMP built-in sRGB, 5 layers) 89](https://user-images.githubusercontent.com/31570884/202955582-201022c8-c07b-4d6a-9d2c-7135d48ed79c.png)

**Expected behavior**
Changing the site background to full black improves the situation. But I'm sure there are other ways.

![2022-11-19 09_11_59-_ Untitled -1 0 (RGB color 8-bit gamma integer, GIMP built-in sRGB, 5 layers) 89](https://user-images.githubusercontent.com/31570884/202955645-50b984ae-038c-4106-afbe-e131dbf42181.png)

**Instance**
https://bookrastinating.com

**Desktop (please complete the following information):**
    - OS: Windows
    - Browser Firefox

**Comment by mouse-reeve** [comment]
Thank you! Tagging in @viviicat as well -- do you have feelings on this?

**Comment by placoderm** [comment]
Oh, wow! It's Mouse! Thanks so much for making this platform. I really hope it succeeds.

**Comment by viviicat** [comment]
I don't feel strongly about keeping the existing color--I agree that the difference in color is very subtle, so it makes sense to make it more distinct as suggested.

**Comment by placoderm** [comment]
Another option would be to put a border line around cards.

**Comment by mouse-reeve** [comment]
I am willing to bet that there would be surprising and frustrating challenges with adding a border, but I think changing the background color is a simple and effective solution.

**Comment by viviicat** [comment]
![image](https://user-images.githubusercontent.com/287339/203857739-ebc56267-32a6-4010-afa5-793e6800f963.png)

After fiddling a bit with the inspector, I am kind of digging this color scheme. Thoughts/feedback? It's really just a tweak of some of the core colors, nothing major. I also kind of like how the header pops out a bit.

The only thing that IMO needs tweaking is the shadow, probably just needs to be a bit smaller because there's some color banding.

**Comment by placoderm** [comment]
To my eyes, the contrast between the middle of the cards (between header and footer) is still so close to the page background colour that it's hard to see the card as a single entity. But maybe I've just gotten too old to be using a dark theme.

Thanks for working on it!

**Comment by viviicat** [comment]
Further darkened -- thoughts on the contrast in #2459 ?
