### ISSUE TITLE
Admin determined limit on max import size

### ISSUE THREAD

**Issue by marcusyoung** [bookwyrm-social/bookwyrm#2429]
I'd like to be able determine the maximum import size a user can make. I had a user that imported 4000 books. I want to control that as you can all of a sudden have a huge increase in disk space usage, especially once the edition collation has taken place also.

**Comment by Giebisch** [comment]
I will get to work on it

**Comment by marcusyoung** [comment]
Probably needs some discussion about what form this feature would take. Is it just going to be a per instance and per import limit, in which case a user could just split up the CSV and do multiple imports to overcome the limit, or something more sophisticated. E.g. limit maximum import per user per day or per week. I'm sure there are many potential ways to take this.

**Comment by Giebisch** [comment]
> Probably needs some discussion about what form this feature would take. Is it just going to be a per instance and per import limit, in which case a user could just split up the CSV and do multiple imports to overcome the limit, or something more sophisticated. E.g. limit maximum import per user per day or per week. I'm sure there are many potential ways to take this.

That's actually true, I didn't think of that. How about providing _two_ fields for the administrator to set the maximum number of books per import, and the number of days between imports? This seems like a reasonable solution for all different sizes of communities.

**Comment by marcusyoung** [comment]
I'm not sure if I'd want to stop users doing several small imports close together. That's something a new user might want to do. Well, I would, as I'd test with a few books first and then do the main import, for example. You could have it as days before "import allowance" is reset perhaps? So you are allowed any number of imports up to the maximum limit. Once that is reached you can't import again until after x days when your import count is set back to zero. This does make it more complex to implement though.

**Comment by Giebisch** [comment]
So you mean three fields, one for # of books per import, # of allowed imports, timeframe of the imports (in days) ?

**Comment by Giebisch** [comment]
Ah, now I see what you mean. Yes, that definitely sounds reasonable, I'll see what I can do!

**Comment by Giebisch** [comment]
This is how it looks like at the moment. The admin can set a limit and the user can see how many book imports he has left. The import button is disabled when there are no more imports remaining. There are still a few bugs, so the PR will probably come next week.

**Admin view**

![import_limit](https://user-images.githubusercontent.com/39874595/206691119-8972a4af-e653-4adc-af68-93b5febb0cd0.PNG)

**User view**

![allowed_imports](https://user-images.githubusercontent.com/39874595/206691114-0efdadb9-167b-4085-937e-296fd002610c.PNG)

Feedback welcome
