### ISSUE TITLE
Issue with CSV Export delimitation

### ISSUE THREAD

**Issue by marcusyoung** [bookwyrm-social/bookwyrm#2432]
**Describe the bug**
I exported my books as a test, and there is an issue with delimitation of the CSV file, with contents not matching the columns for some books. Screen shot of section of file below, see item 41.

![image](https://user-images.githubusercontent.com/10391966/203294417-534b8103-3cfb-4eb0-9ebd-550172e85218.png)

**Comment by cincodenada** [comment]
Can you show the text content of the CSV? It looks to me like the export is correct, and whatever application you're using to open the CSV isn't correctly handling quoted fields.

`41,Walking the Literary Landscape,"Hamilton, Ian"` is three correctly-delimited fields in CSV, but if your settings about quoted fields aren't correct you'll end up with four columns.

**Comment by marcusyoung** [comment]
Thanks. Yes, it looks like the software got confused because only a single column is quoted rather than none of them or all of them. Can be fixed with tweaking of settings.
