### ISSUE TITLE
2FA setup QR code not readable with bookwyrm-dark theme

### ISSUE THREAD

**Issue by 4U6U57** [bookwyrm-social/bookwyrm#2434]
**Describe the bug**
2FA setup QR code not readable with bookwyrm-dark theme, with QR code rendered black on gray (see screenshot)

**To Reproduce**
1. Go to the profile edit page https://bookwyrm.social/preferences/profile
2. Change theme to BookWyrm Dark and apply
3. Now go to the 2FA setup page and authenticate. If 2FA is enabled, disable it.
4. Attempt to set up 2FA by scanning the QR code with a TOTP application on your mobile device (such as Google Authenticator, Authy). It will most likely not scan, since the code is black while the background is dark gray.

**Expected behavior**
QR code should be readable by a QR code scanner, with the black QR code contrasted by a bright (like white) background

**Screenshots**
![image](https://user-images.githubusercontent.com/4676561/203448057-16e98653-c957-4ba5-9c70-0edbd0a83042.png)

_In case anyone is worried for me, I did not set up my 2FA with the displayed token, I generated a new one with light theme enabled_

**Instance**
https://bookwyrm.social

**Additional context**

---

**Desktop (please complete the following information):**
    - OS: Ubuntu Linux
    - Browser: Microsoft Edge
    - Version 107.0.1418.42 

**Smartphone (please complete the following information):**
    - Device: Google Pixel 6
    - OS: Android 13
    - Browser: N/A
    - 2FA App: Bitwarden
    - Version: 2022.10.0

**Comment by mouse-reeve** [comment]
This has been fixed by #2407 but hasn't been released yet. Thank you so much for filing!

**Comment by 4U6U57** [comment]
Oops, I think I searched existing issues for 2FA, but must've had it filtering out closed issues. Thanks for the response, and the fix!
