### ISSUE TITLE
drop down for languages

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2435]
**Is your feature request related to a problem? Please describe.**
The language field of an edition is plain text - it would be nice to have a drop down that gives the languages in the locale while it is saved in English

If I would write "Deutsch" in the database is written "German" and if a French speaking instance sees it it is "Allemand". Furthermore it would help if a language setting is imported from OL or wherever, as their "Deutsch" transforms to "German" as well. Now I have t"German-sprachig" everywhere and this looks just wrong.

Furthermore, the language setting "German" in .env would not match Deutsch.

**Describe the solution you'd like**
Make a drop down, allow to add several languages but all with a drop-down. Allow a free field for those languages who are not in the list. 

**Describe alternatives you've considered**
Have it in different languages.

**Comment by mouse-reeve** [comment]
Agreed! There's a further discussion on that here: #2309, so I'm closing this as a duplicate
