### ISSUE TITLE
Inconsistent Capitalization in Feed on Edited Titles

### ISSUE THREAD

**Issue by TomatDividedBy0** [bookwyrm-social/bookwyrm#2439]
Editing a title for a book which has just been imported is possible, as should be. Issue is that it leads to inconsistent capitalization in the feeds, either due to keeping the old title or just something capitlalization-related. Attached images should show what I mean. Clicking the book page will give the edited, proper capitalization of the title.

![image](https://user-images.githubusercontent.com/25469801/203642722-8517f29e-6df2-4933-a359-e55e216c2f5e.png)

![image](https://user-images.githubusercontent.com/25469801/203642816-9456c01f-a50e-45af-af6b-cca5b2836d13.png)

**Comment by mouse-reeve** [comment]
This is because of caching! I think the preview is cached for a certain amount of time, even if the data is changed

**Comment by TomatDividedBy0** [comment]
> This is because of caching! I think the preview is cached for a certain amount of time, even if the data is changed

Still there, after 18 days. Are you sure this is because of caching, and if so, isn't 18 days quite a long time?

**Comment by chdorner** [comment]
I believe this should be fixed with #2529

**Comment by TomatDividedBy0** [comment]
Doesn't seem like it, although I wonder if it just doesn't retroactively apply to previous statuses.

![image](https://user-images.githubusercontent.com/25469801/209194968-2b52e516-71ef-47b4-b938-18f0be9c5470.png)

**Comment by mouse-reeve** [comment]
I haven't deployed that yet! Sorry for the confusion -- things are happening at a different pace because of the holidays
