### ISSUE TITLE
Delete Avatar when User closes account/gets banned

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2453]
**Is your feature request related to a problem? Please describe.**
When a user deletes their account we keep the avatar in the database.  I need to clarify why I need to store this data after an account is closed. I seen no reason to keep an avatar.

**Describe the solution you'd like**
The avatar gets deleted after an account is closed (for whichever reason).

**Describe alternatives you've considered**
Deleting it from the database by hand.

**Additional context**
GDPR can be pain. This is part of the pain.

**Comment by marcusyoung** [comment]
Can this be merged with #2420?

**Comment by jaschaurbach** [comment]
Oh yes, please. I will close this one.
