### ISSUE TITLE
Move Book dropdowns do not function correctly

### ISSUE THREAD

**Issue by marcusyoung** [bookwyrm-social/bookwyrm#2472]
**Describe the bug**
v0.5.2

The move book dropdowns that are available on a book page and next to each book on a shelf do not function correctly. When an option is clicked the scroll bar for the page disappears and then nothing happens. It will hang like this and the modal will never show until you click to open up the drop down again. Then the relevant model is presented.

Note that this only seems to occur when a modal needs to be shown. When books are moved to custom shelves the move functions correctly. Also changing status in Lists and using the drop down underneath the book cover works correctly.

**Comment by marcusyoung** [comment]
This appears to be the same issue as #2356, but additional info provided here with the page scroll bar disappearing and that this only occurs when using the built-in locations (that have a modal associated with them).

**Comment by placoderm** [comment]
Maybe you could add that info in the other issue and then delete this one? It would save the dev's work I think.

**Comment by marcusyoung** [comment]
Closing but referencing in #2356
