### ISSUE TITLE
Strange Password behavior

### ISSUE THREAD

**Issue by nosilam** [bookwyrm-social/bookwyrm#2475]
**Describe the bug**
Everytime my Browser log me out i cant log in with my saved credentials for bookwyrm.social so i have to renew my password, set on the same password and everything is fine except for the next time my browser logged me out.

**Instance**
bookwyrm.social

---

**Desktop (please complete the following information):**
    - OS: Linux
    - Browser: Firefox Beta
    - Version: various versions

**Smartphone (please complete the following information):**
    - Device: Google Pixel 4 5G
    - OS: Android 12
    - Browser: Chrome

**Comment by mouse-reeve** [comment]
Are you still experiencing this issue? I haven't heard other reports of this issue, so I'm going to close it just as cleanup, but please re-open if I can still help with this
