### ISSUE TITLE
Make goodreads ID for books available to edit 

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2487]
It is just missing in the frontend.

this request is a reminder for me.

**Comment by jzacsh** [comment]
What is this new ID in the UI? Is it the first digits in the last page-path of the work? Eg `3899622` for the edition URL `https://www.goodreads.com/book/show/3899622-hands-of-my-father` perhaps?

**Comment by jaschaurbach** [comment]
Yes, because `https://www.goodreads.com/book/show/3899622` will be forwarded to the URL from your comment. They add the name for SEO reasons.
