### ISSUE TITLE
AASIN and isfdb not editable

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2500]
Somehow during the merge some code most be gone lost because...

<img width="640" alt="Bildschirm­foto 2022-12-11 um 21 29 47" src="https://user-images.githubusercontent.com/2017105/206927195-f9b27bcc-2f3a-46eb-ab1d-84340e5fa061.png">

**Comment by mouse-reeve** [comment]
Oh dear! I know exactly what happened, it was a merge weirdness with another PR of mine; I'll fix it momentarily
