### ISSUE TITLE
let user set default post privacy

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#253]
Right now, a user can set the privacy level of a status when they post the status. The user should also be able to set their preferred default post privacy in the user settings (this is the same as the edit profile page for now).

What I think this will ential:
 - adding a default post privacy setting to the User model (there's already an enum defined with the options in `bookwyrm/models/base_model.py`), with the default value to `Public`
- in the status creation template, make the default post privacy setting the correct one for the user (`bookwyrm/templates/snippets/create_status.html`)
- when privacy isn't set explicitly in a template (boosts, generated statuses come to mind), pass along the user's default

**Comment by ibrand** [comment]
I'd love to work on this one!

**Comment by mouse-reeve** [comment]
yay yes! go for it
