### ISSUE TITLE
Database backup script via cron doesn't have environment variables

### ISSUE THREAD

**Issue by chdorner** [bookwyrm-social/bookwyrm#2546]
Bug report from https://github.com/bookwyrm-social/bookwyrm/discussions/2541

**Describe the bug**
The [database backup script](https://github.com/bookwyrm-social/bookwyrm/blob/production/postgres-docker/backup.sh) relies on the `POSTGRES_DB` environment variable, however in the context of the cron execution this env variable is not set.

**To Reproduce**
1. Follow the production setup instructions, make sure to set the `POSTGRES_DB` env variable to something else than the default
2. Wait for the backup cron to be scheduled and see that 

or, another way to test this without waiting:
1. Add `* * * * * env > /var/log/env.log` to `postgres-docker/cronfile`
2. Follow the production setup instructions, make sure to set the `POSTGRES_DB` env variable to something else than the default
3. After about a minute check the content of that log file to see what's in the environment: `docker-compose exec db cat /var/log/env.log`
The environment is:
```
HOME=/root
LOGNAME=root
PATH=/usr/bin:/bin
SHELL=/bin/sh
PWD=/root
```
Missing the `POSTGRES_DB` variable which the backup script refers to, resulting in always empty backups because the `bookwyrm` default database doesn't exist.

**Expected behavior**
The backup script should be able to backup the database configured in the `POSTGRES_DB` env var in the `.env` file.

**Comment by mouse-reeve** [comment]
I believe this was fixed by #2548
