### ISSUE TITLE
RSS Feed only for reviews

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2556]
I would love to get an RSS-Feed with only the _reviews_ of a user.

**Comment by Giebisch** [comment]
I like this idea and am willing to work on it. How do you envision this being displayed on the profile, a second link to an RSS feed right next to the other?

**Comment by chdorner** [comment]
Might be interesting to make this more generic and have different rss feeds for the different content types. I'm sure someone else will want a quotes feed or a comments feed fairly soon 😊

**Comment by jaschaurbach** [comment]
> I like this idea and am willing to work on it. How do you envision this being displayed on the profile, a second link to an RSS feed right next to the other?

I can imagine the RSS logo in a dropdown. if you just click the logo you get the full feed, in the dropdown you chose which "subfeed" you want (incorporates the remark of @chdorner).

But in the end I am no UI-person and do not care as in "I have no fracking idea"

**Comment by Giebisch** [comment]
> if you just click the logo you get the full feed, in the dropdown you chose which "subfeed" you want

Yes, I have already thought of that as well. I'll play around with it for a bit, let's see what I can come up with. If there is a UI/UX professional, I am of course open for help.

**Comment by Giebisch** [comment]
Yea I think a dropdown works quite well. What do you think ? :)

![rss-feeds](https://user-images.githubusercontent.com/39874595/211503693-51320169-0698-441c-9cbd-59da7933b2ea.PNG)

**Comment by mouse-reeve** [comment]
I like the drop-down a lot!

**Comment by Giebisch** [comment]
I'm glad you like it. Copying to the clipboard would imo be the neatest solution. But I understand that BookWyrm generally tries to use as little JavaScript as possible, so I would be fine with regular links. Maybe in the future we can make a case distinction for users with and without JS.

**Comment by mouse-reeve** [comment]
If the HTML element that the javascript is applied to is a regular link, both use cases will be supported, because if javascript is unavailable, the link will work as written. So it shouldn't be in conflict at all, just a note on implementation :)

**Comment by hughrun** [comment]
Merged, thanks @Giebisch!
