### ISSUE TITLE
Please make it so we can add the site to our iOS Home Screen - progressive web app 

### ISSUE THREAD

**Issue by shaunrobinson** [bookwyrm-social/bookwyrm#2558]
In the absence of any apps for Bookwyrm, I’d like to add it to my iOS home screen and for it to launch on its own (not in safari). 

This can be done for e.g Mastodon, but cannot currently be done for bookwyrm. Please add this feature so I don’t have to keep using safari.

**Comment by cincodenada** [comment]
Yes! Having Bookwyrm as a PWA has long been on my wishlist, thanks for adding this as an issue.

For just the "not have to go through Safari" bit, does [Add to Home Screen](https://www.howtogeek.com/667910/how-to-add-a-website-to-your-iphone-or-ipad-home-screen/) in the Share menu satisfy your needs? It looks similar to the functionality I'm familiar with in Android. It's still using your browser under the hood, but that's the case with a full-blown PWA like Mastodon as well.

Enabling a proper PWA is a much larger endeavor that involves adding a layer to support offline use that syncs back up to the website when you're back online, which is definitely something I'd like to see, but there's not a quick fix for.

**Comment by shaunrobinson** [comment]
No, when you add a home screen icon all it does is launch the bookmark in Safari when you tap it - not ideal. 

I don’t think it’s that complicated to make it stay in its own “app”, you don’t need to make a full blown PWA to do that (it’s just a few lines of HTML, I’ve done it before myself with sites)

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by bahuma20** [comment]
The requirements to be an installable PWA are actually quite low.

A manifest file and a service worker with no logic is enough: https://web.dev/install-criteria/

**Comment by pabloscloud** [comment]
> For just the "not have to go through Safari" bit, does [Add to Home Screen](https://www.howtogeek.com/667910/how-to-add-a-website-to-your-iphone-or-ipad-home-screen/) in the Share menu satisfy your needs?

On iOS when adding something to the homescreen it still opens it in safari. Not so with pwa's.

**Comment by gutierri** [comment]
To be an installable PWA just a manisfest.json is enough. I made a small sketch of what a PR proposal could look like:

``` json
{
  "name": "BookWyrm",
  "short_name": "BookWyrm",
  "description": "Social network for tracking your reading",
  "start_url": "/",
  "display": "fullscreen",
  "dir": "auto",
  "orientation": "portrait",
  "icons": [
    {
      "src": "/static/images/logo-24x24.png",
      "sizes": "24x24",
      "type": "image/png"
    },
   [...]
  ]
}
```

But as mentioned in PR #2564, it would be interesting to have a space for customizing these settings. But with the basic standards of the project, we managed to start something.

I'm using Android with a local instance. It would be interesting to have this functionality.
