### ISSUE TITLE
Goodreads reading dates failed to import.

### ISSUE THREAD

**Issue by snaggen** [bookwyrm-social/bookwyrm#2561]
**Describe the bug**
When I imported my Goodreads data, it only imported one book with my reading start/stop date. The dates that failed to import was set in Goodreads with only year and month. 

So, I assume the issue is to allow only year and month to be used for read start/stop datesm

**To Reproduce**
1. In Goodreads, set a start / stop reading date with only year and month.
2. Export Goodreads data
3. Import the Goodreads data 
4. Check the reading dates on the imported entries.

**Expected behavior**
The dates should be imported

**Instance**
ramblingreaders.org

---

**Smartphone (please complete the following information):**
    - Device: OnePlus 8T
    - OS: Android 12
    - Browser: Firefox Android 
    - Version 108.1.0

**Comment by Giebisch** [comment]
Can you check if the exported data from Goodreads actually contain these dates ? Can't really replicate this.

**Comment by snaggen** [comment]
It seems that even though Goodreads can handle read dates of just year and month, they are not exported. So, this is not an issue with bookwyrm.
