### ISSUE TITLE
Add magazines

### ISSUE THREAD

**Issue by eszter007** [bookwyrm-social/bookwyrm#2567]
I love reading magazines and I also would like to track them, discuss and recommend issues with the community. It would be amazing if this gets added as a new media type. Goodreads and any other platform I know don't have it which is a shame.

Maybe they can get handled a bit differently then books. I can imagine a magazine page that lists all belonging issues, so they are easier to find and also clutter the site less.

What do you all think?

**Comment by jaschaurbach** [comment]
For this I would suggest just to use the series field and give correct numbering - I do not find the issue but somewhere someone wanted to make series clickable and show all elements belonging to a series. That would work for magazines as well.

**Comment by eszter007** [comment]
> For this I would suggest just to use the series field and give correct numbering - I do not find the issue but somewhere someone wanted to make series clickable and show all elements belonging to a series. That would work for magazines as well. 

Yes, making the series clickable and showing all elements is a good solution. It would be good though if magazines get an additional type in the format dropdown then 😊

**Comment by hughrun** [comment]
Related to #1607

**Comment by mouse-reeve** [comment]
I'm closing this so that #1607 can be the canonical issue for this topic
