### ISSUE TITLE
Publication of rating adds half a star to said rating

### ISSUE THREAD

**Issue by mjeammet** [bookwyrm-social/bookwyrm#2568]
# Hi, 👋🏾 

**Describe the bug**
Something weird is happening around rating and publication; books rated 3 stars seem to be rated 3.5 when coming back to the page. 4 stars seems to become 4.5 and so one.

**To Reproduce**
1. Go to a book's page 
2. Click on a rating, select a privacy and click Rate
3. Navigate to the book's page again
4. Displayed rating seems to be your rating + half a star

**Expected behavior**
Same rating selection, publication and display.

**Screenshots**
![image](https://user-images.githubusercontent.com/30848497/210286323-2e0a468a-9bef-437e-a6be-d1ccb5f29224.png)

**Instance**
+ [Diaspodon](https://bw.diaspodon.fr) 
+ https://bookwyrm.social/

---

**Desktop (please complete the following information):**
    - OS: Ubuntu 
    - Browser: Firefox 
    - Version: 108.0 (64-bit)

**Comment by Giebisch** [comment]
I'll give it a try, let's see if I can find the problem ;)
