### ISSUE TITLE
When validating the form for adding book manually, some fields are emptied if a field is not valid

### ISSUE THREAD

**Issue by iGormilhit** [bookwyrm-social/bookwyrm#2571]
**Describe the bug**
When adding manually an item (book), if a field is not valid, after hitting enter some fields are emptied (values removed), such as the author, the subject, the cover, etc.

1. Add manually a book.
2. Fill the form with a publication date having only the year.
3. Add an author, subjects and a cover.
4. Save the form.
5. See the emptied fields.

**Expected behavior**
All filled in fields should keep their value after validating the form.

**Instance**
https://bw.diaspodon.fr

**Additional context**

---

**Desktop (please complete the following information):**
    - OS: Archlinux
    - Browser: Firefox
    - Version: 108

**Comment by chdorner** [comment]
For the cover file select field this is related to #2421

**Comment by chdorner** [comment]
Did a bit more manual testing on this:

When form submit returns with a validation error (i.e. only selecting a publishing year, not month/day):
* Subjects field
  * Adding two subjects in the initial create form
  * on the form with validation errors: Only one subject field visible and with an empty value 
* Author field
  * Adding two authors in the initial create form
  * on the form with validation errors: Only one author field visible and with an empty value
* Load cover from url field
  * Paste image url in this field on the initial create form
  * on the form with validation errors: value is empty

When form submit ends up on the "Confirmation" screen:
* Subjects field
  * Adding two subjects in the initial create form
  * On the confirmation screen there is only one subject field with an empty value
  * When going back from the confirmation screen to the create form only the first subject appears again
  * When confirming, no subjects are stored
