### ISSUE TITLE
Open Graph tag support for lists

### ISSUE THREAD

**Issue by asmaloney** [bookwyrm-social/bookwyrm#2575]
**Is your feature request related to a problem? Please describe.**

When I add a link to [a list](https://bookwyrm.social/list/935/s/book-club-of-two) in e.g. Slack (probably Mastodon/Twitter too?) I get a generic "card" like this:

<img width="414" alt="Screen Shot 2023-01-05 at 12 15 42 PM" src="https://user-images.githubusercontent.com/391371/210841547-ad1e810e-cbd9-476a-9642-0de1670892a3.png">

**Describe the solution you'd like**

If I'm linking to a list, it would be useful to have list-specific info:
- name of the list
- description
- created/curated by
- maybe number of books?

**Comment by mouse-reeve** [comment]
This is good idea! I changed the title slightly so I'd remember what the suggestion was better
