### ISSUE TITLE
Moving books from one shelf to another

### ISSUE THREAD

**Issue by DougNix** [bookwyrm-social/bookwyrm#2582]
**Describe the bug**
I've created a number of book shelves to organize my reading. I moved some books into a couple of different folders, but then changed my mind about how I wanted to organize things. When I tried to move a book from one shelf to another, I could pull down the shelf list and tap on a different shelf, but the app flips me back to the homepage and does not move the book. 

**To Reproduce**
1. Go to any book in a users list of books
2. Click on 'Move to shelf'
3. Scroll down to the shelf you want to move it to.
4. Tap the shelf to move it to. 
5. Go to the shelf and try to move the book to a different shelf.

**Expected behavior**
Book moves to new shelf selected.

**Instance**
BookWyrm.social

---

**Desktop (please complete the following information):**
    - OS: MacOS Ventura
    - Browser Firefox, safari, Vivaldi
    - Version: current

**Smartphone (please complete the following information):**
    - Device: iPhone 11
    - Browser Firefox, safari, Vivaldi
    - Version: current

**Comment by asmaloney** [comment]
I think this is the same as #2356?

**Comment by DougNix** [comment]
Hi Andy,

Yes, I think you are correct.

--
Doug Nix
***@***.***

When you put a thing in order, and give it a name, and you are all in accord, it becomes.

From the Navajo, Masked Gods, Waters, 1950

**Comment by cincodenada** [comment]
Closing as a duplicate, thanks @asmaloney!
