### ISSUE TITLE
(List page) Book showing up twice in Add Books suggestions

### ISSUE THREAD

**Issue by asmaloney** [bookwyrm-social/bookwyrm#2584]
**Describe the bug**

When I set up a dev instance with one book, it showed up twice in the _Add Books_ suggestions on a list page:

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up a fresh dev instance & create an admin user.
2. Add a book
3. Create a new list

The _Add Books_ suggestion list shows the same book twice. These are the exact same book (not multiple editions).

**Expected behaviour**

Should only show each book once.

**Screenshots**

<img width="326" alt="Screen Shot 2023-01-09 at 21 35 50 PM" src="https://user-images.githubusercontent.com/391371/211450358-2ced1ca6-aa00-48f6-98e2-74953ecda2f9.png">

**Instance**

Dev

**Additional context**

It's this code in **views/list/list.py** (_get_list_suggestions_):

```python
    # just suggest whatever books are nearby
    suggestions = user.shelfbook_set.filter(~Q(book__in=book_list.books.all()))
    suggestions = [s.book for s in suggestions[:5]]
    if len(suggestions) < 5:
        suggestions += [
            s.default_edition
            for s in models.Work.objects.filter(
                ~Q(editions__in=book_list.books.all()),
            ).order_by("-updated_date")[: 5 - len(suggestions)]
        ]
```

I tried replacing `suggestions` (`suggestions = [`) instead of appending to it (which works for this case), but I don't know if that's correct because I don't understand what this is supposed to be doing.

Is it trying to query other editions of the same book? (If so, why?)

I'm happy to submit a PR for a fix once it's clear.

**Comment by mouse-reeve** [comment]
I think adding `.distinct()` to the end of `user.shelfbook_set.filter(~Q(book__in=book_list.books.all()))` will fix this

**Comment by asmaloney** [comment]
That's actually not the problematic query. I output the data and there is only one book in `suggestions` before the second query.

What is the second one adding to the list? I don't understand the query (I'm not a Python/Django guy).

**Comment by mouse-reeve** [comment]
Based on your PR it looks like you figured it out on your own, but the second query is just loading any book in the database to use as suggestions if the user doesn't have enough books on their shelves to populate the suggestion list
