### ISSUE TITLE
ActivityPub - (Question)

### ISSUE THREAD

**Issue by gregor2023** [bookwyrm-social/bookwyrm#2585]
Hello,

I have a question about BookWyrm. If I'm right (regarding to this documentation: [https://docs.joinbookwyrm.com/activitypub.html ](url)) is it possible to get some data (books etc.) from the user with this "_ActivityPub_" protocol?

What I want to achieve is to get some data from BookWyrm for my users on my WordPress website which they also have accounts on BookWyrm.

Thank's!

**Comment by mouse-reeve** [comment]
Yes! Try appending .json to a user url and you can see the ActivityPub data. For a book, remove `/s/...` from the URL and add .json. you can also send a request with the Accept header set to `Application/json`

**Comment by gregor2023** [comment]
Thank you for your help!
