### ISSUE TITLE
Sendind emails leads to error 502

### ISSUE THREAD

**Issue by tofuwabohu** [bookwyrm-social/bookwyrm#2595]
**Describe the bug**
When using https://wyrms.de/password-reset, bookwyrm loads a while and throws `Error 502 Bad Gateway` 

![image](https://user-images.githubusercontent.com/66644064/211934214-c02d9651-71b2-46cf-8088-bac4f4b5cd53.png)

The email is not being sent (doesn't arrive).

I also have the suspicion that the invites on invite requests are not sent out since none of them activated their account but there's no error.

**To Reproduce**
1. Go to https://wyrms.de/password-reset
2. Enter an email address (that exists on wyrms)
3. Hit Enter

**Additional context**
Using an emailaddress that doesn't exist on wyrms works as expected and leads to

>  A password reset link will be sent to madeup@email.address if there is an account using that email address. 

We used to have problems sending emails before due to some special character(s) in the SMTP password but it used to work the last months, we just reopened the instance and discovered the problem.

I just updated the instance with `bw-dev update`. Since the nginx overhaul I can't make flower accessible anymore which hinders my troubleshooting a bit, but that's another topic. The web logs show the following:

```
web_1             | [2023-01-11 22:54:20 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:18)
web_1             | [2023-01-11 22:54:20 +0000] [18] [INFO] Worker exiting (pid: 18)
web_1             | [2023-01-11 22:54:20 +0000] [21] [INFO] Booting worker with pid: 21
```

I'm not sure where to look for more context.

**Comment by mouse-reeve** [comment]
Flower got moved to your main domain and port, so if you update your nginx [configuration file](https://github.com/bookwyrm-social/bookwyrm/blob/main/nginx/production#L106) with:
```
    # monitor the celery queues with flower, no caching enabled
    location /flower/ {
       proxy_pass http://flower:8888;
       proxy_cache_bypass 1;
    }
```
 you can access flower again at `your-domain.com/flower` -- it's a lot less janky this way, but unfortunately doesn't work automatically.

But that email is being sent synchronously now, so flower shouldn't be necessary. Can you send a test email from `/settings/email-configuration`? That ought to show an error in the UI if there's one being produced in Django

**Comment by tofuwabohu** [comment]
Oh cool, didn't notice the email test thing! It leads to the 502 as well unfortunately.

I added the flower bit but still tried to connect to port 8888, it's working on default port! :tada: 
There are no failed tasks though and search for `sendmail`doesn't show anything.

**Comment by mouse-reeve** [comment]
it sounds like it's overloading the worker whenever it tries to send an email, but I don't know why that would be the case...

**Comment by tofuwabohu** [comment]
Idk how and why, but it's been working again the day after!
