### ISSUE TITLE
web ui crash on discover link

### ISSUE THREAD

**Issue by kkretsch** [bookwyrm-social/bookwyrm#2602]
**Describe the bug**
I'm loged in as admin, have my books and data and click on top menu discover.
It takes some seconds but then I get back an Ups! exception

**To Reproduce**
see above, happens always

**Expected behavior**
No crash and some content expected

**Screenshots**
![image](https://user-images.githubusercontent.com/1115638/212289185-fbe47203-a0fc-4ac8-9d08-7b2fd158780b.png)

**Instance**
On my personal, docker based, production git branch setup https://b.kretschmann.social/

**Additional context**
![image](https://user-images.githubusercontent.com/1115638/212289356-5f02b0f5-48b9-4687-b593-d352542ef4ff.png)
...
![image](https://user-images.githubusercontent.com/1115638/212289426-d76b3b0a-a949-480b-a7fb-608af934777e.png)

---

**Desktop (please complete the following information):**
    - OS: Windows 10
    - Browser: chrome
    - Version: 108

**Comment by chdorner** [comment]
#2600 fixed this and was merged onto the production branch a few hours ago. Should be getting your discover page back up and running 🤞

**Comment by kkretsch** [comment]
That was quick as hell! I updated the production git and did run all the upgrading steps. It works now.
