### ISSUE TITLE
A page range should be possible for a quote

### ISSUE THREAD

**Issue by iGormilhit** [bookwyrm-social/bookwyrm#2609]
**Is your feature request related to a problem? Please describe.**
When adding a quote to a book, it's possible to set at which page, or which percentage, the quote is situated. And for the page solution, only one integer is allowed. But, quite often, a quote is on several pages.

**Describe the solution you'd like**
It should be possible to set a page range for a quote.

**Comment by Giebisch** [comment]
I'll work on it :)

**Comment by Giebisch** [comment]
Any ideas to make it clearer to the user that you can also enter a range here ?

![page_range](https://user-images.githubusercontent.com/39874595/214946322-abf3301d-363b-4142-b97b-1f44bdd6c79f.PNG)

**Comment by mouse-reeve** [comment]
You can use a span with the class `button is-static` to add an a text element between the two number fields:
<img width="551" alt="Screen Shot 2023-02-20 at 1 19 55 PM" src="https://user-images.githubusercontent.com/1807695/220200155-20e4c873-6e07-470a-9895-e3187c365a4e.png">
