### ISSUE TITLE
HTML tags not evaluated properly

### ISSUE THREAD

**Issue by tofuwabohu** [bookwyrm-social/bookwyrm#2611]
**Describe the bug**
Some `<a>` and `<p>` tags don't get evaluated properly on wyrms.de. It seems to be user specific, on most user's profiles it's fine, but some look like this:
https://wyrms.de/user/mouse@bookwyrm.social

It also shows up in the Home Timeline when those users post something:
![image](https://user-images.githubusercontent.com/66644064/213282648-7959164b-27e7-4b05-9c40-58680cab2d85.png)

I've seen it on `finished reading`, `wants to read`, `started reading` and `set a goal to read x books in y`. So far, I've only seen it on remote instance's profiles.

**Comment by hughrun** [comment]
Is this the same as #2531 ?

**Comment by mouse-reeve** [comment]
Thank you! I'm going to close this as a duplicate of #2531
