### ISSUE TITLE
Pluralization error 

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2625]
**Describe the bug**
When I set the import limit to 200 every 1 days the string for the user looks like the following:

<img width="517" alt="Bildschirm­foto 2023-01-26 um 18 28 11" src="https://user-images.githubusercontent.com/2017105/214906784-2342bec0-3b52-4b5f-aac3-973a7500d090.png">

**Expected behavior**
I expect to read

`Currently you are allowed to import 200 books every day.`

**Instance**
All since 0.5.4.

**Comment by marcusyoung** [comment]
The easiest fix is just to change the text "days" to "day(s)" as the number of days is configurable.

**Comment by mouse-reeve** [comment]
It wouldn't be too much harder to use a `blocktrans` element that handles both singular and plural, which would be more consistent with the rest of the app

**Comment by jaschaurbach** [comment]
I agree with @mouse-reeve - it should be consistent through the whole app

**Comment by chdorner** [comment]
Just a note that this applies to both books and days:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/112063/215153448-ce31d078-96e9-4783-9474-81b8a6330308.png">
