### ISSUE TITLE
Allow for soft-blocking followers

### ISSUE THREAD

**Issue by hughrun** [bookwyrm-social/bookwyrm#2635]
**Is your feature request related to a problem? Please describe.**
(unless I've missed it) there is currently no ability to "unapprove" (remove from followers list) followers once they are following you. I'd like the option to silently remove other users from my followers, rather than having to block them. This will help with cleaning up defunct accounts, but also creates a non-confrontational and less strict way of removing followers as compared to blocking.

**Describe the solution you'd like**
At `domain.tld/user/{username}/followers` instead of the button being a follow/unfollow button, make it "remove follow" (with a confirmation screen before confirming).

**Describe alternatives you've considered**
Alternatively, the dropdown when viewing a user could have an option to "remove from followers" or similar wording.

**Additional context**
Whilst Mastodon should not be the measure of all things, this is an option available on Mastodon.

**Comment by mouse-reeve** [comment]
Relatedly, it's possible (needs investigating) that we're not properly respecting soft block requests from Mastodon -- I'm not actually sure what that activity looks like
