### ISSUE TITLE
Changes to titles not reflected in search results

### ISSUE THREAD

**Issue by ImZanna** [bookwyrm-social/bookwyrm#2643]
I noticed that, when I edit a book, in the research section it doesn't change 

It's the first time writing here so sorry if I'm doing someting wrong, but I'm on Chrome from my windows pc on Lore (part of livellosegreto, mastodont), and I enclose screenshots to make the thing more clear
 
![1](https://user-images.githubusercontent.com/124205153/216155142-ce4d7bac-3771-4370-bac3-d6858256d58f.png)
Here You can notice the fifth book title is "nell'oscutità", I spelled that wrong, it should be "nell'oscurità", so I corrected it, like below

![2](https://user-images.githubusercontent.com/124205153/216155440-15b6a470-749f-4423-9a1e-868a6aac245e.png)
But in the situation of the first photo it remains wrong and it doesn't cange

In the first picture u can notice that the last book does not have the autor, because when I created the book I forgot him, but then I added him...

![3](https://user-images.githubusercontent.com/124205153/216155749-f5ee10d2-7ac1-4a32-9ece-afcc921d6922.png)

but in the serach page it's not added... maybe it's a code problem and someone here can adjust it?

Thank you so much in advance

**Comment by hughrun** [comment]
We use caching to reduce server load, so this may simply be a cache issue. @ImZanna are you able to confirm whether the above behaviour is still the case for this item?

**Comment by hughrun** [comment]
@ImZanna Can you confirm whether these books look correct now?

I can't replicate this on a development server and I'm wondering if it's a delay either due to cache settings or something else.

**Comment by ImZanna** [comment]
Hi, no, unfortunately it's still wrong

Il sab 15 apr 2023, 08:18 Hugh Rundle ***@***.***> ha scritto:

**Comment by mouse-reeve** [comment]
This looks like a caching issue, it ought to have been fixed by https://github.com/bookwyrm-social/bookwyrm/commit/3e25b04e4a04791b39fbd259705ec48a556300ea#diff-f0fa8fcdf6cbf128af503ad8bee75ac81887ac68b5af5736f803dca22af7ebd9R8

I'm going to close this issue in the hope that the problem was a matter of getting the instance up to date with those changes. Please re-open if not!
