### ISSUE TITLE
2FA code not accepted

### ISSUE THREAD

**Issue by chris-y** [bookwyrm-social/bookwyrm#2656]
**Describe the bug**
I have 2FA set up on my account and was trying to log in but the code was not being accepted.  I've had this issue previously and tried a new code and it worked.  On this occassion I resorted to a backup code.  I disabled and re-enabled 2FA on my ccount but even the initial setup code was not being accepted.

After some head-scratching I realised that the clock on the computer I was using was out by about 1 minute.  I tried some other services which use TOTP codes and they worked OK with the incorrect clock, so I think the window of accepted codes needs to be expanded (ie. accept more codes either side of the current one).

**To Reproduce**
1. Enable 2FA
2. Set computer clock out by 1 minute
3. Try to log on.

**Expected behavior**
Bookwyrm should accept a larger range of codes.

**Instance**
wyrms.de

**Additional context**

I checked pyotp documentation:
> 
> verify(otp: [str](https://docs.python.org/3/library/stdtypes.html#str), for_time: [Optional](https://docs.python.org/3/library/typing.html#typing.Optional)[[datetime](https://docs.python.org/3/library/datetime.html#datetime.datetime)] = None, valid_window: [int](https://docs.python.org/3/library/functions.html#int) = 0) → [bool](https://docs.python.org/3/library/functions.html#bool)[[source]](https://pyauth.github.io/pyotp/_modules/pyotp/totp.html#TOTP.verify)
> Verifies the OTP passed in against the current time OTP.
> 
> Parameters:
> otp – the OTP to check against
> 
> for_time – Time to check OTP at (defaults to now)
> 
> valid_window – extends the validity to this many counter ticks before and after the current one
> 
> Returns:
> True if verification succeeded, False otherwise

It appears that setting valid_window=2 in https://github.com/bookwyrm-social/bookwyrm/blob/e88f1f0b8c2e186c350c137a957c080e012e23a0/bookwyrm/forms/landing.py#L111 should solve this issue.

---

**Desktop (please complete the following information):**
    - OS: Windows 10
    - Browser Edge
    - Version 109.0.1518.78

**Comment by marcusyoung** [comment]
Yeah, I've experienced this issue too, where a code is close to expiry and is rejected by the time I enter it.

**Comment by chdorner** [comment]
Funny coincidence, I've never seen this myself until this issue was opened, now I've already experienced it twice!

**Comment by hughrun** [comment]
This should be fixed in #2657 which defaults to a 60 second grace period but can be adjusted by server admins.
