### ISSUE TITLE
Importing book uses today's values for missing date parts

### ISSUE THREAD

**Issue by texttheater** [bookwyrm-social/bookwyrm#2660]
**Describe the bug**
When importing a book from OpenLibrary, month and day are set to today's month and day.

**To Reproduce**
1. Find a book on OpenLibary, e.g., one published in 2022
2. Import it into a BookWyrm instance, e.g., on Feb 12, 2023

**Expected behavior**
The book is shown on BookWyrm as published in 2022 (month and date unspecified)

**Actual behavior**
The book is shown on BookWyrm as published on Feb 12, 2022

**Additional context**
Related issue: #743

**Comment by chdorner** [comment]
I just [imported a book](https://secretbearlibrary.org/book/15357/s/activities-of-daily-living) today from OpenLibrary which had its published date set correctly.

Do you have a specific book that I could check this with?

**Comment by chdorner** [comment]
With the date and month yes, which is most likely related to #743. But the year is set correctly to 222, not 2023.

**Comment by texttheater** [comment]
Sorry, my mistake. Fixed the description now.

**Comment by chdorner** [comment]
Did a bit of digging, and this is where it originally happens: https://github.com/bookwyrm-social/bookwyrm/blob/2c2daf5fdf2d334a344e166eb3bfbcf375dbc4c5/bookwyrm/models/fields.py#L486

`value` is set to `"2022"` coming from OpenLibrary's API and `dateutil` automatically turns this into `datetime.datetime(2022, 2, 13, 0, 0)`.

In addition, and this is more related to #743, we would need to change how to store this data, it's currently using Django's `models.DateTimeField` which doesn't support missing day and month parts of a date.
