### ISSUE TITLE
Allow linking or merging of duplicate books and authors

### ISSUE THREAD

**Issue by rokejulianlockhart** [bookwyrm-social/bookwyrm#2664]
**Is your feature request related to a problem? Please describe.**
* [(Especially when importing, usually from external sources, such as OpenLibrary) duplicate entries are created.](https://github.com/bookwyrm-social/bookwyrm/issues/2663) No means of intelligently merging these exists.
* Different versions of the same novel may exist (different covers, but exactly same print) which have no reason to be listed entirely separately.
* Some duplicate entries cannot be deleted. This is a bug, but it's true.

**Describe the solution you'd like**
I propose that an editing user be able to designate a selected (best) version as the master, and have the other selected versions be folded into the master.

What this should actually entail is a section in the Edit page for an entry which merely allows an infinite amount of IDs to be set as children.

**Additional context**
Ultimately, this should remediate more than an abundance of unnecessarily similar or actually duplicate literature, since it should pave the way for relational mapping.

**Comment by mouse-reeve** [comment]
There are a handful of issues for this open already. I'm going to make this the canonical issue for problems around book data duplication, and change the title a little bit to reflect that. Thank you for raising this!

**Comment by mouse-reeve** [comment]
Okay I said this and then realized that there was a ton of useful conversation in #1119 so I'm going to make THAT one the canonical issue.
