### ISSUE TITLE
Create an option to import BookWyrm CSVs into a new BookWyrm account

### ISSUE THREAD

**Issue by nisemikol** [bookwyrm-social/bookwyrm#2666]
**Is your feature request related to a problem? Please describe.**
I have an old BookWyrm ID that I want to move away from for painful, personal reasons. I created a new BookWrym account (same instance, bookwyrm.social), and I'd like to import my booklist from the old account to the new one. Exporting the CSV from the old account works just fine, but when I try importing the CSV to the new account, I get a "this is not a valid CSV" error no matter which option I use (e.g., Goodreads, OpenLibrary) I've attached my CSV export for reference:
[bookwyrm-export.csv](https://github.com/bookwyrm-social/bookwyrm/files/10745520/bookwyrm-export.csv)

**Describe the solution you'd like**
An option to import BookWyrm CSVs into a BookWyrm account.

**Comment by mouse-reeve** [comment]
Yikes, thanks for flagging this and including your csv file
