### ISSUE TITLE
Search My Shelves

### ISSUE THREAD

**Issue by varanasib** [bookwyrm-social/bookwyrm#2673]
**Is your feature request related to a problem? Please describe.**
A search for a title or author returns possibly relevant books, sometimes more than one of the same book.  Yet, the search results do not indicate if I have it on any of my shelves.

**Describe the solution you'd like**
I would like to see an indication of which of my shelves a book is on, or that the book is not on any of my shelves.

**Describe alternatives you've considered**
I click on the book and look for whether I have any reading history.  (I think "reading history" really means whether I have shelved the book or not.)

**Comment by chdorner** [comment]
I'd say this is a duplicate of #2079 which already has somebody working on it 😄
