### ISSUE TITLE
Setting A Book's List Position Should Not Re-sort List

### ISSUE THREAD

**Issue by varanasib** [bookwyrm-social/bookwyrm#2677]
**Is your feature request related to a problem? Please describe.**
When adjusting the list position of books in a list, every time one hits "set," the list is immediately re-sorted by list position.  This happens even if one has set the sort order as title to assign positions on the list.  One cannot set the list position of more than one book at a time.

**Describe the solution you'd like**
When one presses "Set," the position of the book should be recorded but the list should not be immediately re-sorted.

**Describe alternatives you've considered**
Setting the position of a single book, hitting the set button, re-sorting the list manually to title, and repeating and repeating this process.

**Comment by hughrun** [comment]
@varanasib Is the functionality you're looking for here that you can change the sort order on multiple items and then press a 'save' or 'update' button which then triggers the re-sort?

Note for implementors: if we do that we'll need some kind of error management for when a user accidentally sets multiple items to the same number.

**Comment by varanasib** [comment]
Yes.  I think you've re-stated what should happen more clearly.

I am not sure that there is anything wrong with having more than one item with the same "sort order," except that bookwyrm should have a way of dealing with it, perhaps simply sorting by sort order then title order.
