### ISSUE TITLE
Feed Links Are Confusing Because Font Colors Appear Reversed

### ISSUE THREAD

**Issue by varanasib** [bookwyrm-social/bookwyrm#2697]
**Describe the bug**
When viewing a feed page, there are two "tabs."  The current feed, the one being viewed, has blue words (elsewhere in BookWyrm and generally on the web) indicating a clickable link.  The link to the other feed is in black which is typically not a clickable link.  The color of the tabs is reversed

**To Reproduce**
1. Go to Feeds page
2. Click on black "tab"
3. The other feed page loads

**Expected behavior**
Clicking on blue words should open a new link.  Clicking on black words should stay on same page.

**Instance**
ramblingreaders.org

**Additional context**
The URLS for the tabs go to an anchor link on the same page, to the very top of the feed.  This anchor is immediately below the feed selection tabs, so on almost any screen, the anchor link is not useful.  

---

**Desktop (please complete the following information):**
  -- Chrome for Linux Version 110.0.5481.177 (Official Build) (64-bit)

**Comment by varanasib** [comment]
This same problem exists with the tabs on the status posting page.

**Comment by varanasib** [comment]
Is this just a matter of switching these colors around?
```
`/* links */
$link: #3273dc;
$link-background: $link;
$link-hover: $grey-darker;
$link-focus: $grey-darker;
$link-active: $grey-darker;`
```

https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/static/css/themes/bookwyrm-light.scss

**Comment by varanasib** [comment]
Well, apparently I am wrong about the link colors being relatively standard.  Here's google translate using blue to show the language one has chosen.  There's an additional underscore, but . . . .
![Untitled](https://user-images.githubusercontent.com/17454665/221575174-3307651b-69e8-4802-98c8-664c502cc7a0.png)

**Comment by rkmdCodes** [comment]
hi @mouse-reeve @hughrun @varanasib 
I have added some CSS to interchange the color in the PR #2698 .
