### ISSUE TITLE
Servererror 500 on /discover 

### ISSUE THREAD

**Issue by nesges** [bookwyrm-social/bookwyrm#2728]
**Describe the bug**
We're seeing a servererror 500 when using the /discover page on https://buecher.pnpde.social/discover

**To Reproduce**
1. Go to https://buecher.pnpde.social/discover
2. Scroll down to 'Serverfehler'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/1583898/224309898-9d85be41-1649-4c5a-b624-7ff938a1331d.png)

**Additional context**
bookwyrm version is 0.5.4
Docker log of bookwyrm_nginx_1 shows the following:
`
192.168.112.1 - - [10/Mar/2023:11:50:41 +0000] "GET /discover HTTP/1.0" 500 9533 "https://buecher.pnpde.social/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "2003:c4:df14:8900:812:23cf:9334:5b0f"
192.168.112.1 - - [10/Mar/2023:11:50:41 +0000] "GET /static/ HTTP/1.0" 403 555 "https://buecher.pnpde.social/discover" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "2003:c4:df14:8900:812:23cf:9334:5b0f"
2023/03/10 11:50:41 [error] 28#28: *773 directory index of "/app/static/" is forbidden, client: 192.168.112.1, server: buecher.pnpde.social, request: "GET /static/ HTTP/1.0", host: "localhost:8001", referrer: "https://buecher.pnpde.social/discover"
`

**Comment by WesleyAC** [comment]
Can you post logs from the `bookwyrm_web_1` container as well? That should have the python error, which will be useful for debugging and reproducing.

**Comment by nesges** [comment]
Unfortunately there is nothing related to this error in bookwyrm_web_1's log. There are some errors, but nothing new, when refreshing the /discover page. I'm attaching the whole log though, just to be sure

[web_1.log](https://github.com/bookwyrm-social/bookwyrm/files/10943356/web_1.log)

**Comment by hughrun** [comment]
I have nothing useful to add in terms of errors but just noting that when I was working on a dev instance last week I noticed this as well - seems to be something that changed some time in the last month.

**Comment by mouse-reeve** [comment]
I checked Sentry and didn't find anything on b.s for this, unfortunately. It'll be hard to troubleshoot this without getting a stack trace or a way to replicate

**Comment by nesges** [comment]
Would setting DEBUG=true be of use here? Anything else I could provide?

**Comment by mouse-reeve** [comment]
I would not ever suggest doing that in production. You can set up error tracking like sentry, or just have Django send errors to an email address

**Comment by nesges** [comment]
`ADMINS=[("John",` "john@example.com"), ("Mary", "mary@example.com")]`
is sufficient for that? If so, I have bad news: no error report received

**Comment by nesges** [comment]
I just pulled from the production branch (git pull, bw-dev update, version is 0.5.5 now) and that solved this issue. /discover is working now :)
