### ISSUE TITLE
Typo in string "You can set a sepearate visibility level..."

### ISSUE THREAD

**Issue by MaikNog** [bookwyrm-social/bookwyrm#2771]
msgid 
"Looking for shelf privacy? You can set a sepearate visibility level for each of your shelves.  ... "

https://github.com/bookwyrm-social/bookwyrm/blob/74df7511e782ac929c14983deccd6d583113450d/locale/en_US/LC_MESSAGES/django.po#L4048

Is:                 sepearate
Should be: separate

**Comment by arkhi** [comment]
Fixed on [Main](https://github.com/bookwyrm-social/bookwyrm/blob/main/locale/en_US/LC_MESSAGES/django.po#L4048) and [Crowdin](https://crowdin.com/translate/bookwyrm/1553/en-fr#54377).
