### ISSUE TITLE
Guidance for backing up a Bookwyrm instance

### ISSUE THREAD

**Issue by futzle** [bookwyrm-social/bookwyrm#2851]
How do I correctly back up a Bookwyrm instance? What files need to be backed up in case of a total rebuild?

### Docker installation

Don't know, my installation is Dockerless.

### Dockerless installation

Assuming installed to `INSTALLDIR` (default /opt/bookwyrm).

- `$INSTALLDIR/.env` (Particularly for `SECRET_KEY`)
- `$INSTALLDIR/images/`
- `$INSTALLDIR/static/`
- The entire Postgres `bookwyrm` database.

Anything else? Does having external S3/Azure storage change this list?

**Comment by jaschaurbach** [comment]
After configuring S3/Azure as described in the docs (https://docs.joinbookwyrm.com/external-storage.html) `$INSTALLDIR/images/` and `$INSTALLDIR/static/` are now `$STORAGE/images/` and `$STORAGE/static`.

**Comment by mouse-reeve** [comment]
Is there further action needed on this issue? Please re-open if so 🙂
