### ISSUE TITLE
Review without a star rating looks like it got zero out of five

### ISSUE THREAD

**Issue by bpeel** [bookwyrm-social/bookwyrm#2856]
If you write a review and choose not to give a star rating, the review is then shown with 5 blank stars and when it is next to other reviews it looks like you have given it a rating of zero out of five. I think it would be better to not show the stars at all if the review has no star rating.

[Here is an example book](https://libroj.org/book/17020/s/rego-ubuo). If you scroll down to the reviews it looks like there is one review with 0/5 and another review with 4/5.

![image](https://github.com/bookwyrm-social/bookwyrm/assets/12873/1f5aa788-61d2-4227-95e7-84db7e42d5c9)

**Comment by hughrun** [comment]
@bpeel currently there is no distinction within the system between unrated and zero stars - i.e. it's not possible to actively give something zero stars, the lowest possible is 0.5 stars. Are you happy for this to continue to be the case when drafting/editing the review, and consider zero to equal "no rating" for display purposes?

**Comment by bpeel** [comment]
@hughrun It looks like internally in the database a review without a rating ends up with `NULL` for the rating instead of 0, or at least that’s what is stored for the example above on my server. Does that end up being 0 in the Python code when it gets interpreted through django? Either way it seems to make sense to treat 0 as “no rating”. I think that is already what happens because when the review has no rating or it’s zero, BookWyrm adds a hidden text before the stars saying “no rating” for screen readers. The guided tour says that the star rating is optional, so I think that leaving the stars blank is supposed to be interpreted as no rating and not zero. It also doesn’t seem to affect the book’s aggregated rating, which makes sense.

Maybe internally the best thing would be to change [`stars.html`](https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/templates/snippets/stars.html) so that if there is no rating then it adds a CSS class to the outermost span and then we can configure how to display it in the CSS. I think there could be a few options:

- Display nothing
- Display the empty stars greyed out so they look different from 0 stars
- Display the text “no rating”
- Something else?

I’m not sure which is best.

I can try making a PR for this to experiment.

**Comment by mouse-reeve** [comment]
+1 on all that -- I think showing "No rating" would be much clearer.
