### ISSUE TITLE
Any plans of supporting SQLite database format

### ISSUE THREAD

**Issue by anantshri** [bookwyrm-social/bookwyrm#2863]
I would love to selfhost bookwyrm instance for just myself i.e. a single user instance. It would be awesome if there could be a trimmed down version of software with lesser system resource requirements as the use-case is of single user only. 

One of the major hurdles become the database support can that be moved to sqlite3 this reduces a big overhead. similarly can redis or celery be reduced from the single user setup.

**Comment by skobkin** [comment]
Setting up a container with Postgres isn't hard if you're doing it for yourself. If you're going to allow others to register, then SQLite may take it's toll on the performance.

**Comment by hughrun** [comment]
@mouse-reeve ok if we mark this `wont-fix` and close?

**Comment by mouse-reeve** [comment]
yep, good call
