### ISSUE TITLE
Update bookwyrm display theme to change with the system theme

### ISSUE THREAD

**Issue by BenjMathis1** [bookwyrm-social/bookwyrm#2873]
It would be nice if under **Settings > Display > Theme** there was also an option to have the bookwyrm theme match the OS theme on the device.

**Comment by mouse-reeve** [comment]
Agreed! I'm going to close this as a duplicate of https://github.com/bookwyrm-social/bookwyrm/issues/2106, which also has some preliminary thoughts on how to approach it
