### ISSUE TITLE
Sending mails with SMTP does not work

### ISSUE THREAD

**Issue by saschafoerster** [bookwyrm-social/bookwyrm#2875]
In a fresh installation of Bookwyrm, I am not able to sent an test-email successfully. Bookwyrm just goes down and restarts after a while. 

Bookwyrm: docker production installation, version 1.6.3 

**To Reproduce**
1. Go to : https://URL/settings/email-config
2. Click on 'send test-email"
3. Website goes down

**Logs**
```
bookwyrm-web-1             | [2023-06-17 16:08:07 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:6)
bookwyrm-web-1             | [2023-06-17 16:08:07 +0000] [6] [INFO] Worker exiting (pid: 6)
bookwyrm-web-1             | [2023-06-17 16:08:08 +0000] [8] [INFO] Booting worker with pid: 8
```
The logs are not really showing any other significant error message. I checked several times, what happens after my clicking, but nothing more than this.

Settings: 
- django.core.mail.backends.smtp.EmailBackend
- Password has special characters. (So maybe related to #2819, #1790 and #1805? But the logs are different, I've got no redis error. 
- Debug mode is activated in .env 

**Expected behavior**
A test-e-mail should be sent. 

**Instance**
Freshly installed test-instance. 

**Additional context**
I tried to put the password in .env in '' and "", which both didn't help.

---

**Desktop (please complete the following information):**
    - OS: MacOS
    - Browser: Safari
    - Version: 13.4

**Comment by WesleyAC** [comment]
What is your `EMAIL_HOST` and `EMAIL_PORT` set to? A commercial service, or a local server? That this crashes the worker is a problem that should be fixed, but my guess is that the email settings are improperly configured, thus causing the timeout.

**Comment by saschafoerster** [comment]
> EMAIL_HOST=mail.my.server
> EMAIL_PORT=465

mail.my.server is a publicly reachable server. I also wish there were more informations in the log files, that give a hint, why this happens.

**Comment by saschafoerster** [comment]
I also check another address with another password without special signs. It is not the special signs issue. :/

**Comment by saschafoerster** [comment]
Found it: 
Had to change from:
```
EMAIL_USE_TLS=true
EMAIL_USE_SSL=false
```

```
EMAIL_USE_TLS=false
EMAIL_USE_SSL=true
```
