### ISSUE TITLE
`resetdb` throws error

### ISSUE THREAD

**Issue by hughrun** [bookwyrm-social/bookwyrm#2885]
**Describe the bug**
When I run `./bw-dev resetdb` on the latest `main` I get the following error:

```
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "bookwyrm_connector_identifier_key"
DETAIL:  Key (identifier)=(bookwyrm.social) already exists.
```
The only way to resolve this seems to be to manually stop all containers and delete all volumes.

**To Reproduce**
1. stop containers
2. run `./bw-dev resetdb`
3. See error

**Expected behavior**
It should delete all volumes, and run the setup commands as previously.

**Screenshots**
n/a

**Instance**
local dev

**Additional context**

I've been testing a new feature so it's possible something in my dev code caused this, but I don't think so.

---

**Desktop (please complete the following information):**
    - OS: MacOS
    - Browser n/a

**Comment by mouse-reeve** [comment]
I tried this just now and wasn't able to replicate it

**Comment by hughrun** [comment]
Yeah I realised after I posted this that it's probably just me: I have 2 different repositories going at the moment, on the same machine. Will check this properly later and close it if I can resolve the problem.
