### ISSUE TITLE
RSS feed does not have a pubdate field

### ISSUE THREAD

**Issue by Francois-Lu** [bookwyrm-social/bookwyrm#2888]
There is no date field in the RSS generated by appending /rss

**To Reproduce**
append /rss to your account and look at the resulting rss feed: the pubdate field is missing

**Expected behavior**
have a pubdate field for each item

**Screenshots**
![image](https://github.com/bookwyrm-social/bookwyrm/assets/85833033/d3d040ec-da93-4781-80eb-1d472c92eb52)
Reader defaults to 31 dec 1969 due to lack of pubdate field.
**Instance**
https://outside.ofa.dog/

firefox browser

**Comment by Francois-Lu** [comment]
Hello

I can't replicate the bug either (see screenshot attached).
I use my own php RSS reader - sample code attached.
I haven't made any change to my code so I guess the instance has been 
upgraded in the meantime or the bug was due to something else (???) but 
obviously you can close it.
Thanks for having a look and for bookwyrm in general :-)

Le 31/07/2023 11:14, TAKAHASHI Shuuji a écrit :

> Hello, I tried to replicate the issue but the current RSS seems to 
> return the correct <pubDate> value on the above instance: 
> https://outside.ofa.dog/user/FrankAuLux/rss
> 
> Could you still replicate the issue? Also, which RSS reader do you use?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/bookwyrm-social/bookwyrm/issues/2888#issuecomment-1657981984
[2]

**Comment by mouse-reeve** [comment]
Thanks all! Gonna go ahead and close this
