### ISSUE TITLE
API

### ISSUE THREAD

**Issue by digfish** [bookwyrm-social/bookwyrm#2889]
Does BookWyrm has an API? Doing things like updating your reading progress, adding or updating your book shelves from a 3rd part client? Can't find anything at the documentation! 

Best regards

**Comment by sleepyfran** [comment]
Take a look at #785, there's some pointers on how to do partial stuff through the ActivityPub API 😃

**Comment by mouse-reeve** [comment]
Thank you, that's correct. I'm closing this as a duplicate and pinning the older issues
