### ISSUE TITLE
UX improvement: ISBN "Copy" button and dashed formatting 

### ISSUE THREAD

**Issue by soshial** [bookwyrm-social/bookwyrm#2892]
**Describe the proposition**
1. I propose a small COPY icon button close to ISBN number to copy it (see a red area on the screenshot):
2. Also, I would love to see formatted ISBNs for easier reading. This can be [done with JavaScript](http://inventaire.github.io/isbn3/?isbn=9781781682135).

**Expected behavior**

**Screenshots**
<img width="293" alt="Screenshot 2023-07-05 at 12 48 22" src="https://github.com/bookwyrm-social/bookwyrm/assets/100644/a7278583-6e50-48d4-a4b3-afe4872da529">

**Instance**
Main instance.

**Additional context**

**Comment by mouse-reeve** [comment]
This should be in the next release! Thank you both so much :)
