### ISSUE TITLE
Prevent users from creating readthroughs that end before they start

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#291]
**Describe the bug**
Right now, a user can set any arbitrary date, past or future for the start and finish dates of a `ReadThrough`. I think future dates are fine, but that it ought to prevent you from setting the finish date as earlier than the start date. 

**Expected behavior**
The form should reject invalid dates and show error text on the page. Ideally it would check the dates before form submission, but it should also (or instead) check in the view_actions and return error text.

**Comment by wua3** [comment]
hi! could I take this?

**Comment by mouse-reeve** [comment]
yes! go for it, and let me know if you have any questions :)
