### ISSUE TITLE
Missing static css/js files - Dockerless install with external caddy reverse proxy

### ISSUE THREAD

**Issue by pm3003** [bookwyrm-social/bookwyrm#2924]
**Describe the bug**
After following the instructions for dockerless install, the site looks ugly. 

My setup: Bookwyrm on Ubuntu 22.04, LXC container.
Caddy as a reverse proxy towards port 8000, bypassing Nginx.

systemctl status bookwyrm gives gunicorn errors ending with: File not found "/static/bookwyrm.js"

Is this expected behaviour and should I just serve the static files (and the rest) through nginx? Is there somewhere I can set the root correctly for Gunicorn?

**To Reproduce**

1. Clean dockerless install
2. Caddy reverse proxy to bookwyrm on port 8000 
3. Launch browser

**Expected behavior**
Static files are served correctly through caddy.

**Screenshots**
![Screenshot_20230728-171707~2](https://github.com/bookwyrm-social/bookwyrm/assets/5320421/d962f8cf-a9bd-4d49-a04d-c3074aaec4b9)

![Screenshot_20230728-172619~2](https://github.com/bookwyrm-social/bookwyrm/assets/5320421/9653fd98-1472-42c4-9106-1dbf027db192)

**Desktop (please complete the following information):**
    - OpenSUSE
    - Browser qutebrowser, Vivaldi, Firefox

**Smartphone (please complete the following information):**
    - Device: Android
    - OS: Android 11
    - Browser Opera

**Comment by hughrun** [comment]
@pm3003 sounds like you may have missed the step where you run `collectstatic`. See [the dockerless installation instructions](https://docs.joinbookwyrm.com/install-prod-dockerless.html):

* Compile the themes by running `venv/bin/python3 manage.py compile_themes`
* Create the static files by running `venv/bin/python3 manage.py collectstatic --no-input`

**Comment by pm3003** [comment]
@hughrun Thank You for your reply. `collectstatic` was the first thing I thought of and I reran it (and `compile_themes`) in case I missed some useful error or message. The output and the generated files looked correct.

I'll try separately proxying static and get back in the next few days.

**Comment by pm3003** [comment]
In the end I passed the static files through nginx using the caddy `route` command on the reverse-proxy.
(doc here: https://caddyserver.com/docs/caddyfile/directives/route#utility)

I ran into another probem described in #2470:

> The path /var/cache/nginx does not seem to exist on a raw Debian 11 install, leading to the error:
> 
> nginx: [emerg] mkdir() "/var/cache/nginx/bookwyrm_cache" failed (2: No such file or directory)
> The solution:
> 
> # mkdir /var/cache/nginx
> # chown www-data:www-data /var/cache/nginx

The solution descrbed worked. Marking as solved.
