### ISSUE TITLE
Ratings aren't switched when switching editions

### ISSUE THREAD

**Issue by rmcminds** [bookwyrm-social/bookwyrm#2926]
I've imported many books from Goodreads, but the editions are usually wrong. When I use the 'switch to this edition' button, it correctly switches the version that's on my shelf and that has 'read dates' attached to it - but then it looks like I haven't rated it, because the rating stays with the old edition.

**Comment by joric3** [comment]
This has bothered me, too. An option to move user data (shelves, read dates, comments and reviews...) from one edition to another would be great.
