### ISSUE TITLE
Malformed Links in Profiles and Posts

### ISSUE THREAD

**Issue by sebastiansIT** [bookwyrm-social/bookwyrm#2932]
**Describe the bug**
When you write a URL at the end of a sentence in your profile or in a post, the trailing dot (.) is appended to the generated HTML anchor.

**To Reproduce**
1. Go to your profile
2. Click on 'edit profile'
3. Insert "https://github.com/bookwyrm-social/bookwyrm/issues." (with the dot at the end)
4. Click on "save"
5. Follow the Link

**Example**
https://bookwyrm.social/user/taarion

**Expected behavior**
The Link shoud be without the dot

**Instance**
bookwyrm.social i.E.

---

**Desktop (please complete the following information):**
    - OS: Windows 11
    - Browser Vivaldi
    - Version 6.1

**Comment by joachimesque** [comment]
Good catch, thanks for bringing it up!
