### ISSUE TITLE
home#feed and discover not updated

### ISSUE THREAD

**Issue by prolibre** [bookwyrm-social/bookwyrm#2939]
I come here but I'm not the admin of my instance.
What could explain the fact that my news feed and discover page have not been updated since a specific date? And this for several users of the instance?
The administrator can't see any errors in the logs.
If, on the other hand, I go directly to my account's profile (or anyone else's), the information is up to date. On the other hand, my news feed is completely frozen (as is the Discover page).

Software version :
0.6.4

**Comment by mouse-reeve** [comment]
What instance are you on? On bookwyrm.social, we had some problems with the queue that populated the feeds getting backlogged, which was fixed by https://github.com/bookwyrm-social/bookwyrm/pull/2934 and some patience. That change isn't in production yet, but I can roll it out ASAP if other admins are getting overloaded.

**Comment by prolibre** [comment]
@mouse-reeve Hello and thank you for your reply. It's on a small French instance. If a fix comes soon, it will wait until it goes into production. Thank you once again.

**Comment by prolibre** [comment]
@mouse-reeve Unfortunately the instance is broken and the administrator had no backup :-(
So I set up my own instance (bw.heraut.eu). I feel a bit lonely and I'm not sure how to federate it with others... do you have any documentation on the subject?

**Comment by mouse-reeve** [comment]
Okay, it looks like Celery is running, so the next thing to do would be to look at the celery queues and make sure the right ones exist and aren't backlogged. Do you have access to the admin panel? If so, it should be visible at https://bw.heraut.eu/settings/celery. If you can view that page, can you send me a screenshot of it?

**Comment by prolibre** [comment]
@mouse-reeve Sorry, my last message wasn't very clear. In fact, the instance where I had the problem no longer works. Since I've been on my own instance, everything works (or seems to) just fine :-)
I think that on the old instance the worker (bookwyrm-worker) was no longer in service.
Thanks for all your help.
