### ISSUE TITLE
Save-button seems unresponsive when adding a book in Firefox for Android when no sort title is given

### ISSUE THREAD

**Issue by marcnause** [bookwyrm-social/bookwyrm#2944]
**Describe the bug**
When I try to add a new book or a new edition of a book in Firefox for Android and I add no sort title, the save-button seems unresponsive. Nothing happens when I press the button.

**To Reproduce**
1. Open Firefox on an Android device.
1. Go to "Add Book" (https://bookwyrm.social/create-book on the instance I use.)
1. Add a title, don't add a sort title
1. Scroll down to the save-button
1. Press save-button
1. Nothing happens

**Expected behavior**
When I go through the steps above on my laptop, the browser scrolls to the missing field and shows a hint which data is missing. I would expect the same behavior in Firefox for Android.

**Instance**
https://bookwyrm.social/

---
**Smartphone:**
    - Device: Fairphone 4
    - OS: Android 12
    - Browser: Firefox
    - Version 116.0

**Comment by mouse-reeve** [comment]
Thank you! I think the system should probably auto-populate the sort title when none is provided

**Comment by haheute** [comment]
I had problems with that, too. The page said: "please fill in this field". 
The problem is, I don't know what a sort title is.. In the end I have copied the title into the sort title field, still not knowing what that is. Maybe a little explanation or hint would be good.

**Comment by mouse-reeve** [comment]
I think the auto-populated value will clarify it a bit, but I super agree that there should be some help text!
