### ISSUE TITLE
Question: can deleted accounts be deactivated? And if so should they?

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#2951]
I get emails quite often from people who have permanently deleted their account and would now like to un-delete it so they can use their username. I tried to make it very clear from the UI and provide deactivation as an alternative, but it still comes up quite a bit. 

My impression is that it would be effectively impossible to properly reinstate a user action a Delete activity has been broadcast, because the deletion has propagated to various instances, and any subsequent activities from that user would understandably be rejected.

But I wanted to make sure that I'm actually correct about this!

**Comment by hughrun** [comment]
I agree, [so does w3c](https://www.w3.org/wiki/ActivityPub/Primer/Delete_activity).

I feel the "delete my account" page is pretty clear about the consequences, so I'm surprised you get a lot of requests - is there any pattern in terms of why this happens? Are people confused about what "delete my account" does, or just changed their mind, or is something else going on?

I guess an alternative possibility (that may be a little complicated to set up) could be to always delay the actual delete, kind of like Twitter does. So when people delete, it actually gets deactivated for e.g. 30 days, and then if they haven't "undeleted" or reactivated it, the `Delete` activity is triggered and there's no going back.

**Comment by mouse-reeve** [comment]
Now that you mention it, I think that people may not be getting that when the account is deleted, the username is not made available again to re-register

**Comment by mouse-reeve** [comment]
Delaying deletion always felt a little sketchy to me, and I'm happy to continue letting people know they are out of luck. I'm also surprised that I still get a fair amount of emails about it, but some people may have deleted when the UI was less clear
