### ISSUE TITLE
Importing one book becomes a different book

### ISSUE THREAD

**Issue by quisquous** [bookwyrm-social/bookwyrm#2956]
**Describe the bug**
Importing one book becomes a different book (the collection it's from)

**To Reproduce**
1. Search for "A Dream of Electric Mothers" on books.theunseen.city, e.g. https://books.theunseen.city/search?q=a+dream+of+electric+mothers
2. It's not found locally, but I see it federated to https://reading.taks.garden/book/49316/s/a-dream-of-electric-mothers
3. Hit the import book button
4. It goes to https://books.theunseen.city/book/166686/s/africa-risen
5. Repeat step 1, book still not found

**Expected behavior**
I expected the book to be imported to books.theunseen.city.

**Screenshots**

**Instance**
books.theunseen.city

**Additional context**
I previously added this book to books.theunseen.city, it got federated, and then there was data loss on that site, and so I am reimporting it to books.theunseen.city. I will clearly just re-add the book which should work, but this was unexpected behavior. My suspicion is that because I listed the ISBN there's something being too smart here? This could just be a "I am holding it wrong in the case of short fiction that's part of a collection".

---

**Desktop (please complete the following information):**
    - OS: Win10
    - Browser Chrome
    - Version 115.0.5790.171

**Comment by hughrun** [comment]
The record at `taks.garden` seems to be corrupted, it's showing the cover and ISBN for _Africa Risen_ but a different title:

![taks garden](https://github.com/bookwyrm-social/bookwyrm/assets/17669239/83121bdf-aca5-4912-9ef8-cff937c103ed)

**Comment by quisquous** [comment]
> The record at `taks.garden` seems to be corrupted, it's showing the cover and ISBN for _Africa Risen_ but a different title:

No no, that's correct. As I mentioned in the original post, I added that entry. It's a story from that collection, and so I added that cover and ISBN.

(A separate issue is ... how I should be adding shorter works that are part of larger collections. I want to add just the story, because it's that story and not the collection that's nominated for a Hugo this year, and so I can add it to a list and review just that piece.)

**Comment by hughrun** [comment]
Oh I see, I misunderstood what you meant.

I think the confusion here is that the core unit within BookWyrm is a _book_, not a more generic _literary work_. Therefore the primary identifier is the ISBN (which doesn't always exist, but generally does for anything published in the last century). If you add an ISBN to a record in Bookwyrm, Bookwyrm will assume that everything with that ISBN is an edition of the same book, not just something related to or contained within the book.

_A dream of electric mothers_ appears to be a novelette contained within an anthology of short works, and from a quick search doesn't look like it was ever published as a standalone book. So the answer basically is that currently you can't add it to BookWyrm on its own, and instead should add more information to the description of the anthology. Probably what you're looking for is the feature request in #2535 with the ability to use an identifier for a particular part of an anthology separately from the whole book.

**Comment by quisquous** [comment]
Thanks, this was my suspicion. I didn't know that ISBN was being used as a primary identifier to dedup things like this. I will make sure not to list ISBN in the future to avoid this problem.
