### ISSUE TITLE
notification of invitation requests

### ISSUE THREAD

**Issue by prolibre** [bookwyrm-social/bookwyrm#2961]
**Is your feature request related to a problem? Please describe.**

My instance is open to invitations. I have to check regularly to see if I have any requests.

**Describe the solution you'd like**

It would be interesting to receive a notification (or an e-mail) when an invitation request is received. In the same way as for linked domains, for example.

Merci beaucoup / Thank you very much for your investment

**Comment by mouse-reeve** [comment]
I believe this was fixed with https://github.com/bookwyrm-social/bookwyrm/pull/3105
