### ISSUE TITLE
Admin says there is an update even when updated

### ISSUE THREAD

**Issue by ZicklePop** [bookwyrm-social/bookwyrm#2969]
**Describe the bug**

When I update Bookwyrm and go to the admin page, it says `An update is available! You're running v0.6.4 and the latest release is v0.6.5.` but I just went through the upgrade process.

**To Reproduce**
1. Go to 'Admin'
2. Click on 'Update is available' banner
3. [Follow the docs](https://docs.joinbookwyrm.com/updating.html)
4. Admin dashboard continues to say `An update is available! You're running v0.6.4 and the latest release is v0.6.5.`

**Expected behavior**
No update is available

**Screenshots**
![image](https://github.com/bookwyrm-social/bookwyrm/assets/318003/022bc0a2-eaf4-4ded-bc9e-99e933c695f3)

**Instance**
[books.nyan.lol/](https://books.nyan.lol/)

**Additional context**
I am on the `production` branch and the git commit hashes match.
`commit f0af79840852f15bd02e19586d733c3f7d79754c (HEAD -> production, tag: v0.6.5, origin/production)`

---

**Desktop (please complete the following information):**
    - OS: macOS
    - Browser: Chrome
    - Version: 116.0.5845.110 (Official Build) (arm64)

**Comment by mouse-reeve** [comment]
Sorry about that! I forgot to update the version number in the settings file 😅

**Comment by ZicklePop** [comment]
No worries! Good to know :)

**Comment by 0x29a** [comment]
@mouse-reeve @ZicklePop, there is a small PR to fix this: https://github.com/bookwyrm-social/bookwyrm/pull/2967

**Comment by jaschaurbach** [comment]
As this is already fixed I close this
