### ISSUE TITLE
Authors removed when creating a new edition

### ISSUE THREAD

**Issue by joric3** [bookwyrm-social/bookwyrm#2973]
When adding a new edition of a book, existing authors are removed even though the checkboxes for that are not marked.

**To Reproduce**
1. Go to a book, click on editions (e.g. https://buecher.pnpde.social/book/46494/editions)
2. Click to add a new edition.
3. Enter data for new edition, leave the existing authors as is, safe the entry.
4. New edition has no authors at all.

**Expected behavior**
I expect authors to be carried over, unless expressly specified to remove them.

**Screenshot**
This is what it looks like in German: Checkboxes unmarked, existing authors linked. This is what I save.
![Create-Edition-Authors](https://github.com/bookwyrm-social/bookwyrm/assets/143620816/8150d101-ab63-4b5c-b2fa-548d2bd9b1c2)

**Instance**
https://buecher.pnpde.social/about
version 0.6.4 (German localization)

**Additional context**
I tried removing them (checking the checkboxes), which works as expected: Authors are removed. (Adding a new author works, too.)
My current workaround is to create the new edition, then edit it to add the authors which had already been listed for the existing edition.

---

**Desktop (please complete the following information):**
    - OS: Windows 11
    - Browser: Firefox v. 116.0.3 (64bit)

**Comment by prolibre** [comment]
Same thing over here (latest 'production' version). It happened again yesterday when I tried to create a new edition of Trust. The author disappeared.
It seems to me that this bug is very recent.

**Comment by jderuiter** [comment]
This bug should be fixed with #2992
