### ISSUE TITLE
Creating new Edition fails

### ISSUE THREAD

**Issue by nosilam** [bookwyrm-social/bookwyrm#2978]
When creatin new edition it asks me what book is this edition for. But when there is a bunch of similar booktitles you cant link both edition. It also happened when you create a new edition from the link in the previous edition. It should automaticaly link both edition without asking because its created from the link in the edition view.

**To Reproduce**
https://bookwyrm.social/book/63057/editions
klick on create new edition
type anything in and save
there comes the question about the previous edition but only a few titles but not the real one so you cant properly link the new edition

**Expected behavior**
It should automaticaly link both edition without asking because its created from the link in the edition view.

**Instance**
bookwyrm.social

**Comment by jderuiter** [comment]
This bug should be fixed with #2992
