### ISSUE TITLE
An update is available! You're running v0.6.4 and the latest release is v0.6.5.

### ISSUE THREAD

**Issue by fofwisdom** [bookwyrm-social/bookwyrm#2984]
**Describe the bug**

**To Reproduce**
1. apt install docker.io
2. git clone https://github.com/bookwyrm-social/bookwyrm.git
3. git checkout production
4. Create your environment variables file, (.env)
5. Configure nginx (nginx/default.conf)
6. /bw-dev migrate
7. docker-compose up --build
8. Configure certbot (docker-compose.yml, nginx/default.conf)
9. ./bw-dev setup
10. docker-compose up -d
11. Create admin account.
12. Enter the Admin Dashboard

**Expected behavior**
no version update messages.

**Screenshots**
![image](https://github.com/bookwyrm-social/bookwyrm/assets/205521/acfc1e84-7cc9-4d9f-8bb4-156d1c8715e9)

**Instance**
https://reads.netsphere.pub/

**Additional context**
After deleting the docker files, I purge docker and removed all docker paths.

Next, I repeated the initial installation process to verify the reproduction.

**Comment by fofwisdom** [comment]
v0.6.5 서버가 어느 곳도 없습니다.
https://joinbookwyrm.com/instances/

**Comment by hughrun** [comment]
@fofwisdom this is the bug noted at #2969.

You're actually running v0.6.5 but the version number wasn't updated in the release.
