### ISSUE TITLE
Admins should get a notification when someone ask for an invitation

### ISSUE THREAD

**Issue by Te-k** [bookwyrm-social/bookwyrm#2994]
**Is your feature request related to a problem? Please describe.**

As an admin, I get notifications when I need to approve a new domain linked to a book, but not when someone is asking for an account. I need to go in the requests page and make sure I didn't miss any, and so sometimes, it takes a couple of days until someone get an account.

**Describe the solution you'd like**
It would be awesome to have a notification for admin when someone did a request. The notification can be the same as for linked domains.

**Describe alternatives you've considered**
I don't see any alternative here.

**Comment by hughrun** [comment]
Same as #2961 which indicates we probably should prioritise this.

**Comment by Te-k** [comment]
Ah sorry, didn't see #2961, feel free to close this ticket if not useful

**Comment by jaschaurbach** [comment]
As per request of author and as it is a duplicate I close this.
