### ISSUE TITLE
Sort Title should be an optional field

### ISSUE THREAD

**Issue by Stoori** [bookwyrm-social/bookwyrm#3014]
**Is your feature request related to a problem? Please describe.**
After the latest update there's a new obligatory field in book data, named Sort Title. Most of the time this field is identical to Title, so adding both feels unnecessary.

**Describe the solution you'd like**
If the Sort Title field is considered useful (I assume so, why else would it have been added), it should be optional. When adding a new book and the field is left empty, BookWyrm should automatically copy the contents of the Title field to Sort Title field. Or vice versa, if the user only types Sort Title field, that could be copied to the Title field.

**Additional context**
This may be a language-specific issue, and perhaps in some languages book title is indeed different from sort title. But that's not the case in every language, so the software should not force the user to do unnecessary extra work.

**Comment by hughrun** [comment]
@mouse-reeve did this get fixed in #2948 ?

**Comment by mouse-reeve** [comment]
Yes, I just haven't done a release in a while. I will do that now :)

To be clear @Stoori , the solution that I wrote will copy the sort title from the title, which it sounds like is an acceptable solution for you.
