### ISSUE TITLE
Redundant ISFDB link in author page

### ISSUE THREAD

**Issue by rexroom** [bookwyrm-social/bookwyrm#3018]
The authors pages have a listing of external links to entries in other book databases. Currently, a link to the ISFDB is produced twice in the page, although presented in different manners.

**To Reproduce**
1. Go to an author's page that has an ISFDB entry.
2. Scroll down to the 'External links' section
3. See two links to ISFDB.

**Expected behavior**
One for each database entry. I am interpreting this as a redundancy.

**Screenshots**
Attached to this report.

**Instance**
Kirjakasa (https://kirja.casa/author/20/s/johanna-sinisalo) running on Bookwyrm 0.6.4,

---
![Screenshot 2023-10-05 at 13-20-43 Kirjakasa](https://github.com/bookwyrm-social/bookwyrm/assets/4396306/a88611df-23d7-404f-9b8b-65d18f92f4d7)

**Comment by mouse-reeve** [comment]
Thank you for all these bug fixes, @dato, and for all the code review @jaschaurbach ❤️
