### ISSUE TITLE
Series with '&' in name does not show books

### ISSUE THREAD

**Issue by BasileosFelices** [bookwyrm-social/bookwyrm#3021]
**Describe the bug**
I read a book series "Lockwood & Co" and modified the books on bookrastinating to include the series name. However, whenever I try to lookup [the whole series](https://bookrastinating.com/series/by/3307?series_name=Lockwood%20&%20Co), the series is empty. I believe this is because of '&' character which stops reading the name of the series.

**To Reproduce**
I have several books with "Lockwood & Co" series name.
[Book one](https://bookrastinating.com/book/88331/s/the-screaming-staircase)
[Book two](https://bookrastinating.com/book/88334/s/the-whispering-skull)
[Book three](https://bookrastinating.com/book/88337/s/the-hollow-boy)

They should show if I click the series in the book overview. But I only get [this site](https://bookrastinating.com/series/by/3307?series_name=Lockwood%20&%20Co) for "Lockwood" series.

**Expected behavior**
"Lockwood & Co" should be a valid name that shows me the books included in the series.

**Screenshots**
![image](https://github.com/bookwyrm-social/bookwyrm/assets/106377662/907dd243-2af0-46a6-ade2-35c03af90cae)

**Instance**
bookrastinating.com

**Desktop (please complete the following information):**
    - OS: fedora station
    - Browser firefox
    - Version 0.6.1

**Comment by dato** [comment]
This should be fixed, yes; thank you for reporting.

In the meantime, if it helps, you can workaround the underlying issue by using https://bookrastinating.com/series/by/3307?series_name=Lockwood%20%26%20Co to access your series (simple `&` → `%26` substitution).

Cheers.

**Comment by BasileosFelices** [comment]
Thank you for the workaround for now.
