### ISSUE TITLE
Incorrect rendering of `(?)`

### ISSUE THREAD

**Issue by WesleyAC** [bookwyrm-social/bookwyrm#3049]
**Describe the bug**

In a comment, the text `(?)` is rendered as `()?`

**To Reproduce**

See https://bookwyrm.social/book/773954/comment for a example. When I click "edit" I see `(?)` in the box, so I didn't mis-type it, it's getting rendered wrong for some reason.

**Expected behavior**

**Screenshots**

edit box:

![2023-10-20_12 24 57_1010x257](https://github.com/bookwyrm-social/bookwyrm/assets/5001092/7f4a5932-1607-43bf-a623-38195b241865)

rendered:

![2023-10-20_12 25 18_712x47](https://github.com/bookwyrm-social/bookwyrm/assets/5001092/6b12fa96-b3bb-46b9-bfc6-ab2c31f0f827)

**Instance**
bookwyrm.social

**Comment by mouse-reeve** [comment]
I bet this is something about how links are rendered. What a weird bug!

**Comment by hughrun** [comment]
Yeah I reckon @mouse-reeve is right. It could probably be fixed along with #2993 . I put a probable fix for that in the comments but then forgot to actually fix it.
