### ISSUE TITLE
/create-book generates a "403 Forbidden" error

### ISSUE THREAD

**Issue by pymander** [bookwyrm-social/bookwyrm#3104]
**Describe the bug**
On basic user accounts, `/create-book` generates a 403 error.

**To Reproduce**
1. Log into an account with the most basic permission level.
2. Search for a book.
3. Scroll down to 'Manually add book' and click on it
4. See 403 error

**Expected behavior**
I expected to see the page for manually adding a book.

**Screenshots**
It is a plain old 403 error with no additional information.

**Instance**
https://grimoire.social

(a brand new instance)

**Additional context**

---

**Desktop (please complete the following information):**
    - OS: Linux
    - Browser: Firefox
    - Version 118.0.2

**Smartphone (please complete the following information):**

**Error log**
I also got the following trace:

```
web_1             | Forbidden (Permission denied): /create-book
web_1             | Traceback (most recent call last):
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1             |     response = get_response(request)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_1             |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
web_1             |     return self.dispatch(request, *args, **kwargs)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
web_1             |     return bound_method(*args, **kwargs)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
web_1             |     return view_func(request, *args, **kwargs)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
web_1             |     return bound_method(*args, **kwargs)
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
web_1             |     if test_func(request.user):
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 70, in check_perms
web_1             |     raise PermissionDenied
web_1             | django.core.exceptions.PermissionDenied
```

**Comment by pymander** [comment]
Oops, I see now that this was my fault. I had changed a setting on the Registration page. Mea culpa!!

**Comment by mouse-reeve** [comment]
I'm glad you solved your problem, but I don't think showing a 403 is a good behavior here. I think either the link shouldn't show up or there should be a more informative view

**Comment by hughrun** [comment]
Looks like we either need to create a custom decorator to replace [`permission_required`](https://docs.djangoproject.com/en/4.2/topics/auth/default/#django.contrib.auth.decorators.permission_required) to show some friendlier alert, or possibly just create a "you don't have permission to do that as a `name of permission level`" page, and then assign that in the `login_url` value, which redirects.

**Comment by mouse-reeve** [comment]
There are handlers in place for 404 and 500, I think 403 could follow the same pattern

**Comment by Jerry-infosecexchange** [comment]
Hello.  I am experiencing the same problem.  What setting needed to be changed on the registration page?

**Comment by hughrun** [comment]
@Jerry-infosecexchange at `/settings/site-registration-admin` there is a drop-down option labelled "Default access level". This is set to `Editor` in a fresh install, and that is the minimum permission level users need to be able to create or edit a book. If users are getting a `403`, you probably have this set to `User`.
