### ISSUE TITLE
Can we test activitypub verbs?

### ISSUE THREAD

**Issue by hughrun** [bookwyrm-social/bookwyrm#3130]
When I was working on #3124 I realised `Reject` has never been working properly, but as best I could tell we don't seem to have any tests for publishing activitypub activities as a side-effect of functions. In this case, "rejecting" a follow request passes the tests because they test to see whether the `UserFollowRequest` is deleted, but there is no test to see whether we sent a `reject` activity to the requestors server (we didn't). But I also couldn't really work out how such a test might be written.

This Issue is not specifically about that problem, but more general: did I just not see the tests? Is it impossible/very difficult to test this because it runs through the task runner? 

I'm not requesting someone else write a bunch of new tests: I'm willing to do the work to set up tests if they don't exist and are deemed useful, I'm just not sure whether this is possible or already exists or I've missed some other aspect, and would need some pointers for how it might be done.

**Comment by mouse-reeve** [comment]
You can test that an activity is going out using the broadcast mock to capture the function that would send the activity, and then check that it contains the correct object. There are some tests that do this already: https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/tests/models/test_relationship_models.py#L110

So in #124, for example, you can capture [the broadcast here](https://github.com/bookwyrm-social/bookwyrm/pull/3124/files#diff-6f36fc783d059ab0cb8f6c132d8a68b936b0365693ef53e87dfd1d9589dcfc6eR190) and
 inspect it to ensure that it 1) does get called (the mock will have a boolean `called` field), 2) gets called the number of times you expect (`mock.call_count`, and 3) contains the activitypub object in the form you want.

**Comment by hughrun** [comment]
Thanks @mouse-reeve I'll check that out and adjust #3124
