### ISSUE TITLE
Use proxy for S3 images

### ISSUE THREAD

**Issue by oculos** [bookwyrm-social/bookwyrm#3157]
I am considering to start a Bookwyrm instance, but I would like to use S3 for storage. I'd rather not have the bucket endpoint exposed, since I might relocate my storage elsewhere later.

IS it possible to use a proxy for the s3? Does Bookwyrm supports that, so that the images are served with my server's url instead of s3's? 

If not, could this be implemented later?

**Comment by hughrun** [comment]
When you set an `AWS_S3_CUSTOM_DOMAIN` (which probably should just be called `S3_CUSTOM_DOMAIN`) in your `.env` file, [this will be what is exposed as the location for images](https://github.com/bookwyrm-social/bookwyrm/blob/000e5e614532a87b79d21a3b266713dff8c186db/bookwyrm/settings.py#L374C1-L392C33). In the `settings.py` it looks like this:

```py
if USE_S3:
    # AWS settings
    ...
    AWS_S3_CUSTOM_DOMAIN = env("AWS_S3_CUSTOM_DOMAIN", None)
    AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", "")
    AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL", None)
    ...
    # S3 Static settings
    STATIC_LOCATION = "static"
    STATIC_URL = f"{PROTOCOL}://{AWS_S3_CUSTOM_DOMAIN}/{STATIC_LOCATION}/"
    ...
    # S3 Media settings
    MEDIA_LOCATION = "images"
    MEDIA_URL = f"{PROTOCOL}://{AWS_S3_CUSTOM_DOMAIN}/{MEDIA_LOCATION}/"
    MEDIA_FULL_URL = MEDIA_URL
    STATIC_FULL_URL = STATIC_URL
```
If you set `AWS_S3_CUSTOM_DOMAIN` as `s3.example.books` your images will be at `https://s3.example.books/images/`.

If you subsequently move your S3 storage service but point it to the same custom S3 domain then your external URLs shouldn't change.

This is [mentioned in the docs](https://docs.joinbookwyrm.com/external-storage.html) but it's possibly not as clear as it could be.

**Comment by oculos** [comment]
Thank you so much! Indeed, I read the documentation but wasn't very sure if this was possible. Thanks a lot!
