### ISSUE TITLE
cannot add publication years to books (entering just the year says invalid date)

### ISSUE THREAD

**Issue by mirabilos** [bookwyrm-social/bookwyrm#3161]
**Describe the bug**
I tried to add a book record with a publication year of 1983, but it didn’t save until I removed the year.

**To Reproduce**
1. Create a book record manually
2. Enter a year for publication date but do not enter a month or day
3. Try to submit

**Expected behavior**
I can enter timestamps as just the year, year+month, or year+month+day, anywhere they are required (publication dates of books, read dates, …) depending on the information precisity I have.

**Instance**
`outside.ofa.dog`

---

**Desktop (please complete the following information):**
    - OS: Debian
    - Browser: Firefox
    - Version: 115 ESR

**Comment by mouse-reeve** [comment]
This has been fixed and will be in the next release; sorry for the delay on getting that live!

**Comment by hughrun** [comment]
This is now released.
