### ISSUE TITLE
Reading progress bug

### ISSUE THREAD

**Issue by prolibre** [bookwyrm-social/bookwyrm#3164]
A small bug (minor but a little annoying). When you add a comment with a progression (for example 25% or 100 pages) it deletes the date on which you started reading. You therefore have to re-enter it later.

Bookwyrm : 0.6.6 (test with firefox)
Instance : https://bw.heraut.eu

**Comment by hughrun** [comment]
Just came to report this for "finish reading". I definitely have a readthrough with a start date but when the modal pops up only a finish date is displayed.

**Comment by dato** [comment]
@prolibre Does this bug still happen, and can you reliably reproduce it (how?)? I tried, but I failed.

To those reading along, posting progress invalidates the last_readthrough cache entry:

https://github.com/bookwyrm-social/bookwyrm/blob/7f773b3dbddd4d1dc262991bdb97f2f12d39a1f1/bookwyrm/models/readthrough.py#L46

This cache item is recomputed in templates via:

https://github.com/bookwyrm-social/bookwyrm/blob/7f773b3dbddd4d1dc262991bdb97f2f12d39a1f1/bookwyrm/templatetags/shelf_tags.py#L80-L94

So there are two possibilities to begin with (non-exhaustive): in some scenarios the cache entry is not being recreated, thus `start_date` is not available; or, perhaps, some step along the way is setting `is_active=False` in the readthrough, hence it's not retrieved.

**Comment by prolibre** [comment]
@dato Sorry

So I've just noticed this bug again on version 0.7.4 of my instance.

- I started my book on 21 July (I have the progress date indicated)
- I make a comment (just a comment, no quotes) on the book (with a percentage).
- The start date disappears. All that remains is my current progress: today: 39%.

So I have to enter my start date again. Once this has been done, both dates are shown in my progress.

Have a good day.

**Comment by dato** [comment]
@prolibre Thank you!! With your updated description I can now reproduce it.

(For those reading along: I was trying to reproduce the issue using, in the homepage carousel, the shelf selector's "update progress" item but, for this bug at least, the behaviour occurs with a Comment + Progress field. Doing some guesswork, I assume this form doesn't have a "start_date" hidden field, but it makes its way to `edit_readthrough()`, which unconditionally sets start_date from request.POST.)

https://github.com/bookwyrm-social/bookwyrm/blob/f7958bc0f309cd80927b1c5b8c2d429f44261743/bookwyrm/views/status.py#L204-L206

**Comment by prolibre** [comment]
merci @dato !
