### ISSUE TITLE
Images (covers) not being shown on federated books

### ISSUE THREAD

**Issue by oculos** [bookwyrm-social/bookwyrm#3169]
Hi,

I have deployed my instance a week ago. The main feed is now showing books of people my instance knows, but those books are without an image for the book cover. The original book posts on the remote instances do have that image.

Why is this happening? What could I check?

**Comment by mouse-reeve** [comment]
This should be fixed in the newest release, by https://github.com/bookwyrm-social/bookwyrm/pull/3039
