### ISSUE TITLE
`bw-dev build` fails 

### ISSUE THREAD

**Issue by ccamara** [bookwyrm-social/bookwyrm#3173]
**Describe the bug**
Running `bw-dev build` fails, throwing the error below

**To Reproduce**

I followed the steps on https://docs.joinbookwyrm.com/install-dev.html

1. Installed docker and docker compose
2. Clone my Forked repo
3. Edit `.env` as described
4. Run `cp nginx/development nginx/default.conf`
5. Run `./bw-dev build` and I get this error:

```
[...]

=> CANCELED [flower 6/6] RUN pip install -r requirements.txt --no-cache-dir                            45.8s

=> ERROR [dev-tools 5/6] RUN apt-get update            &&     apt-get install -y nodejs &&     pip in  44.2s

[...]

failed to solve: process "/bin/sh -c apt-get update            &&     apt-get install -y nodejs &&     pip install -r requirements.txt &&     npm install ." did not complete successfully: exit code: 127

```

It can reproduce the same in two different machines, one running KDE Neon, and another one running Mac OS

**Expected behavior**
It should correctly install all dependencies.

---

**Desktop (please complete the following information):**
    - OS: KDE Neon / Mac OS

**Comment by bernaborrero** [comment]
It looks like it can't find the `npm` command specified on dev-tools/Dockerfile.
I tried to install explicitly `npm` on the Dockerfile, just to try, and it solved the issue, but I don't know what other implications this could have.

Apparently, installing `nodejs` should include `npm`, except in old distros, but that shouldn't happen when installing using the setup script. The setup script was deprecated, and thus replaced by the apt source in `sources.list.d/` in [this commit](https://github.com/bookwyrm-social/bookwyrm/commit/1937177e1a5df853d2cea1ba1436b4baa2290e14) by @dato  as a `.sources` file. I've never used the Deb822 format, but it should do the same as before, I understand.

Lastly, when executing the command, we can see that `apt` is suggesting the installation of `npm`, but it's not installing it, so perhaps https://deb.nodesource.com/node_18.x no longer includes it?

```
> [dev-tools 5/6] RUN apt-get update            &&     apt-get install -y nodejs &&     pip install -r requirements.txt &&     npm install .:
0.725 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
0.785 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
0.787 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
0.855 Get:4 https://deb.nodesource.com/node_18.x nodistro InRelease [12.1 kB]
1.043 Get:5 http://deb.debian.org/debian bookworm/main amd64 Packages [8787 kB]
1.439 Get:6 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [12.7 kB]
1.566 Get:7 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [133 kB]
1.920 Get:8 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages [6634 B]
3.145 Fetched 9202 kB in 3s (3643 kB/s)
3.145 Reading package lists...
4.697 Reading package lists...
6.169 Building dependency tree...
6.606 Reading state information...
7.708 The following additional packages will be installed:
7.712   libc-ares2 libnode108 libuv1 node-acorn node-busboy node-cjs-module-lexer
7.714   node-undici node-xtend nodejs-doc
7.721 Suggested packages:
7.721   npm
7.878 The following NEW packages will be installed:
7.881   libc-ares2 libnode108 libuv1 node-acorn node-busboy node-cjs-module-lexer
7.883   node-undici node-xtend nodejs nodejs-doc
8.006 0 upgraded, 10 newly installed, 0 to remove and 7 not upgraded.
8.006 Need to get 15.1 MB of archives.
```

**Comment by hughrun** [comment]
Yep I can replicate this:

```
9.407 Installing collected packages: typing-extensions, tomli, platformdirs, pathspec, mypy-extensions, click, black
9.516 Successfully installed black-22.12.0 click-8.1.7 mypy-extensions-1.0.0 pathspec-0.12.1 platformdirs-4.1.0 tomli-2.0.1 typing-extensions-4.9.0
9.554 /bin/sh: 1: npm: not found
------
failed to solve: process "/bin/sh -c apt-get update            &&     apt-get install -y nodejs &&     pip install -r requirements.txt &&     npm install ." did not complete successfully: exit code: 127
```

There's [an issue on the nodesource repository about this](https://github.com/nodesource/distributions/issues/1601#issuecomment-1675839012) with a possible temporary fix, it seems to be specific to Debian Bookworm. @dato do you mind taking a look at this?

**Comment by dato** [comment]
sure I will take a look tomorrow. thanks!

**Comment by dato** [comment]
> Lastly, when executing the command, we can see that `apt` is suggesting the installation of `npm`, but it's not installing it, so perhaps https://deb.nodesource.com/node_18.x no longer includes it?

It does include it, but as can be seen here:

```
Get:4 http://deb.debian.org/debian-security bookworm-security/main amd64 nodejs amd64 18.19.0+dfsg-6~deb12u1 [319 kB]
```

apt is picking the packages from Debian rather than the one from nodesource.

This is fixed by telling apt to prefer nodesource origin over Debian (I've submitted #3175 for this).

Thank you @hughrun for digging up that issue in nodesource/distributions; the apt_preferences fix explained there is indeed the proper fix.

**Comment by ccamara** [comment]
I can confirm that the PR #3175 solves this. Thank you for the quick fix, @dato , and the pointers from @hughrun and @bernaborrero
