### ISSUE TITLE
Ugly hidden overflow on the about page

### ISSUE THREAD

**Issue by joelabrams** [bookwyrm-social/bookwyrm#3178]
**Describe the bug**
At some screen resolutions, on the about page, the row of most beloved/most wanted/most divisive books gets rendered with most of the text overflowing and hidden 

**To Reproduce**
1. Go to https://bookwyrm.social/about
2. Set screen width to between 769 and 1220px

**Expected behavior**
I would expect to be able to read the text next to the thumbnails of the three books.

**Screenshots**

![Screenshot 2024-01-01 at 20-29-59 BookWyrm](https://github.com/bookwyrm-social/bookwyrm/assets/622091/dfdaf1cb-84f2-4637-9970-a9e1efcf2e97)

**Instance**
Both Bookwyrm.social and Bookrastinating

**Additional context**
I know enough CSS to know that the issue is with the .is-one-third rule at the min-width: 769px breakpoint.  There's not enough width to accommodate the content because there's also the left sidebar.  I don;'t know enough CSS to fix this myself, unfortunately.

---

**Desktop (please complete the following information):**
    - OS: Windows
    - Browser: Chrome and Firefox (up-to-date)
 
**Smartphone (please complete the following information):**
    - Device: iPad
    - Browser: Safari

**Comment by bSolt** [comment]
Hm we could move the text

![image](https://github.com/bookwyrm-social/bookwyrm/assets/36494925/4542e632-3011-4ea0-8701-d7b152f0f3b0)

Or change it to two columns before it goes to one?

![image](https://github.com/bookwyrm-social/bookwyrm/assets/36494925/bbf7e925-45b7-4b63-942d-0f4eef89a063)

Maybe we can skip one of the columns at this size?

![image](https://github.com/bookwyrm-social/bookwyrm/assets/36494925/1583d4bd-3f3f-4b48-addd-8dfc6d8930f0)

Thoughts?

**Comment by joelabrams** [comment]
Any is much better, and since you’ve gone ahead and done option 2, I’ll vote for that! Thanks!
