### ISSUE TITLE
"year in the books" should not appear for newly registered users

### ISSUE THREAD

**Issue by hughrun** [bookwyrm-social/bookwyrm#3187]
**Describe the bug**

**To Reproduce**
1. Register a new account during the time "{year} in the books" appears
2. Get a messsage encouraging you to see all the books you read in the year, which will be none.

**Expected behavior**
This should not be displayed for users who have no readthroughs.

**Screenshots**

![Screenshot 2024-01-03 at 11 08 20 am](https://github.com/bookwyrm-social/bookwyrm/assets/17669239/a33d5f2e-a666-4e57-93c3-59a28a62bddd)

**Instance**
dev site

**Comment by rsk2** [comment]
Hi @hughrun, can I work on this?

**Comment by hughrun** [comment]
Plesse do @rsk2! I should note that I _think_ it's a "good first issue" as the logic should be pretty simple to filter this out of the template. But I haven't had a close look at the relevant code so shout out if you need any help.

**Comment by rsk2** [comment]
@hughrun I have created a PR. Please review.
