### ISSUE TITLE
Flower crash : ValueError: Couldn't import 'celerywyrm': Environment variable "DATA_UPLOAD_MAX_MEMORY_SIZE" invalid: Not a valid integer.`

### ISSUE THREAD

**Issue by prolibre** [bookwyrm-social/bookwyrm#3236]
Since updating my .env (following the .env.example) the flower application no longer worked.
Here's a bit of the error :

`master celery[2501464]: ValueError: Couldn't import 'celerywyrm': Environment variable "DATA_UPLOAD_MAX_MEMORY_SIZE" invalid: Not a valid integer.`

I changed :
DATA_UPLOAD_MAX_MEMORY_SIZE = (1024**2 * 100)
to
DATA_UPLOAD_MAX_MEMORY_SIZE = 204800

and it seems to work again

**Comment by hughrun** [comment]
@prolibre are you able to check whether this works if the value is `DATA_UPLOAD_MAX_MEMORY_SIZE=(1024**2 * 100)` (i.e. no spaces around the equals sign)?

**Comment by hughrun** [comment]
hmm don't worry I answered my own question (no).
