### ISSUE TITLE
Non-docker install - Server error when importing - Missing covers thumbnails

### ISSUE THREAD

**Issue by pm3003** [bookwyrm-social/bookwyrm#3240]
**Describe the bug**
Context:
- Non docker install (LXC container)
- updated recently
- static content served staticly and stored locally.

I get a server error on the landing page of the instance most of the time. I get a **server error when importing books** from any source. Mot of the time the books get imported nonetheless, but **the cover thumbnails are not generated** nor imported. They seem to register in the database but are missing. I've tried fiddling with preview image settings and executed image genreation commands in manage.py.

Manually importing the cover yields an error but succeeds. No thubnail is generated in this case either.

Books imported prior to the issue don't have this problem. 
All users seem to have this issue. 

![Screenshot_20240120_175329](https://github.com/bookwyrm-social/bookwyrm/assets/5320421/b7efd55e-65e1-489d-ac5f-18a1c92062b0)

The thumbnail image in the example should be instance.tld/images/thumbnails/covers/55510d2e-0939-4729-b050-d200c9f98bf8/bbda32237f703e9aedad087f04e1a65d.webp  **but the picture doesn't exist on the server**. The full cover displays if I click "click toenlarge" (instance.tld/images/covers/55510d2e-0939-4729-b050-d200c9f98bf8.jpeg)

**To Reproduce**
1. Open instance homepage
2. Search for books in the search box
3. Click "Import book" anywhere
4. Server Error
5. Try to manually upload the picture

**Expected behavior**
- No server error on book import
- Covers thumbnails displayed correctly

**Instance**
Personal instance, will provide details if necessary.

** Server logs **

Import error:
Jan 20 16:40:35 wyrm gunicorn[1263]: Not Found: /api/v1/instance/activity
Jan 20 16:40:35 wyrm gunicorn[1263]: Not Found: /poco
Jan 20 16:40:35 wyrm gunicorn[1263]: Not Found: /api/v1/directory
Jan 20 16:40:34 wyrm gunicorn[1263]: Not Found: /.well-known/x-nodeinfo2
Jan 20 16:35:51 wyrm gunicorn[1263]: AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
Jan 20 16:35:51 wyrm gunicorn[1263]:     img = img.resize((self.width, self.height), Image.ANTIALIAS)
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/pilkit/processors/resize.py", line 24, in process
Jan 20 16:35:51 wyrm gunicorn[1263]:     img = Resize(new_dimensions[0], new_dimensions[1], upscale=self.upscale).process(img)
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/pilkit/processors/resize.py", line 227, in process
Jan 20 16:35:51 wyrm gunicorn[1263]:     img = proc.process(img)
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/pilkit/processors/base.py", line 15, in process
Jan 20 16:35:51 wyrm gunicorn[1263]:     img = ProcessorPipeline(processors or []).process(img)
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/pilkit/utils.py", line 360, in process_image
Jan 20 16:35:51 wyrm gunicorn[1263]:     new_image = process_image(img,
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/specs/__init__.py", line 157, in generate
Jan 20 16:35:51 wyrm gunicorn[1263]:     content = generator.generate()
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/utils.py", line 152, in generate
Jan 20 16:35:51 wyrm gunicorn[1263]:     content = generate(self.generator)
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/cachefiles/__init__.py", line 98, in _generate
Jan 20 16:35:51 wyrm gunicorn[1263]:     file._generate()
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/cachefiles/backends.py", line 96, in generate_now
Jan 20 16:35:51 wyrm gunicorn[1263]:     self.generate_now(file, force=force)
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/cachefiles/backends.py", line 109, in generate
Jan 20 16:35:51 wyrm gunicorn[1263]:     self.cachefile_backend.generate(self, force)
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/cachefiles/__init__.py", line 94, in generate
Jan 20 16:35:51 wyrm gunicorn[1263]:     file.generate()
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/bookwyrm/thumbnail_generation.py", line 16, in on_existence_required
Jan 20 16:35:51 wyrm gunicorn[1263]:     fn(file)
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/utils.py", line 166, in call_strategy_method
Jan 20 16:35:51 wyrm gunicorn[1263]:     call_strategy_method(file, callback)
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/registry.py", line 61, in _receive
Jan 20 16:35:51 wyrm gunicorn[1263]:     self._receive(file, 'on_existence_required')
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/registry.py", line 53, in existence_required_receiver
Jan 20 16:35:51 wyrm gunicorn[1263]:     (receiver, receiver(signal=self, sender=sender, **named))
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
Jan 20 16:35:51 wyrm gunicorn[1263]:     return [
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 180, in send
Jan 20 16:35:51 wyrm gunicorn[1263]:     existence_required.send(sender=self, file=self)
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/cachefiles/__init__.py", line 75, in _storage_attr
Jan 20 16:35:51 wyrm gunicorn[1263]:     return self._storage_attr('url')
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/cachefiles/__init__.py", line 85, in url
Jan 20 16:35:51 wyrm gunicorn[1263]:     return cover_thumbnail.url
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/bookwyrm/templatetags/utilities.py", line 84, in get_book_cover_thumbnail
Jan 20 16:35:51 wyrm gunicorn[1263]:     output = self.func(*resolved_args, **resolved_kwargs)
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/template/library.py", line 192, in render
Jan 20 16:35:51 wyrm gunicorn[1263]:     return self.render(context)
Jan 20 16:35:51 wyrm gunicorn[1263]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jan 20 16:35:51 wyrm gunicorn[1263]:     bit = node.render_annotated(context)

Regular error in the logs:

Jan 20 15:24:56 wyrm celery[450]: Traceback (most recent call last):
Jan 20 15:24:56 wyrm celery[450]: During handling of the above exception, another exception occurred:
Jan 20 15:24:56 wyrm celery[450]: AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
Jan 20 15:24:56 wyrm celery[450]:     img = img.resize((self.width, self.height), Image.ANTIALIAS)
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/pilkit/processors/resize.py", line 24, in process
Jan 20 15:24:56 wyrm celery[450]:     img = Resize(new_dimensions[0], new_dimensions[1], upscale=self.upscale).process(img)
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/pilkit/processors/resize.py", line 227, in process
Jan 20 15:24:56 wyrm celery[450]:     img = proc.process(img)
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/pilkit/processors/base.py", line 15, in process
Jan 20 15:24:56 wyrm celery[450]:     img = ProcessorPipeline(processors or []).process(img)
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/pilkit/utils.py", line 360, in process_image
Jan 20 15:24:56 wyrm celery[450]:     new_image = process_image(img,
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/specs/__init__.py", line 157, in generate
Jan 20 15:24:56 wyrm celery[450]:     content = generator.generate()
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/utils.py", line 152, in generate
Jan 20 15:24:56 wyrm celery[450]:     content = generate(self.generator)
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/cachefiles/__init__.py", line 98, in _generate
Jan 20 15:24:56 wyrm celery[450]:     file._generate()
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/cachefiles/backends.py", line 96, in generate_now
Jan 20 15:24:56 wyrm celery[450]:     self.generate_now(file, force=force)
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/cachefiles/backends.py", line 109, in generate
Jan 20 15:24:56 wyrm celery[450]:     self.cachefile_backend.generate(self, force)
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/cachefiles/__init__.py", line 94, in generate
Jan 20 15:24:56 wyrm celery[450]:     file.generate()
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/bookwyrm/thumbnail_generation.py", line 12, in on_source_saved
Jan 20 15:24:56 wyrm celery[450]:     fn(file)
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/utils.py", line 166, in call_strategy_method
Jan 20 15:24:56 wyrm celery[450]:     call_strategy_method(file, callback_name)
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/registry.py", line 116, in source_group_receiver
Jan 20 15:24:56 wyrm celery[450]:     (receiver, receiver(signal=self, sender=sender, **named))
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
Jan 20 15:24:56 wyrm celery[450]:     return [
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 180, in send
Jan 20 15:24:56 wyrm celery[450]:     signal.send(sender=source_group, source=file)
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/specs/sourcegroups.py", line 124, in dispatch_signal
Jan 20 15:24:56 wyrm celery[450]:     self.dispatch_signal(source_saved, file, sender, instance,
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/specs/sourcegroups.py", line 101, in post_save_receiver
Jan 20 15:24:56 wyrm celery[450]:     fn(self, sender=sender, **kwargs)
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/imagekit/specs/sourcegroups.py", line 33, in receiver
Jan 20 15:24:56 wyrm celery[450]:     (receiver, receiver(signal=self, sender=sender, **named))
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
Jan 20 15:24:56 wyrm celery[450]:     return [
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 180, in send
Jan 20 15:24:56 wyrm celery[450]:     post_save.send(
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/db/models/base.py", line 787, in save_base
Jan 20 15:24:56 wyrm celery[450]:     return original(instance, *args, **kwargs)
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/model_utils/tracker.py", line 375, in inner
Jan 20 15:24:56 wyrm celery[450]:     self.save_base(using=using, force_insert=force_insert,
Jan 20 15:24:56 wyrm celery[450]:   File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
Jan 20 15:24:56 wyrm celery[450]:     super().save(*args, **kwargs)

**Comment by prolibre** [comment]
I think it's the same problem I had a while ago

https://github.com/bookwyrm-social/bookwyrm/issues/3194

**Comment by pm3003** [comment]
@prolibre 
Thank you, it would seem logical. I'll try what you did.
But I don't understand how you fixed the problem permanently (I'm not very familiar with venv). Did you downgrade Pillow in requirements.txt?

**Comment by prolibre** [comment]
@pm3003 

Here's roughly what I did.

I stopped bookwyrm : 
systemctl stop bookwyrm bookwyrm-worker bookwyrm-scheduler

I went into the base directory.
As a precaution : 
mv venv venv-backup

I rebuild my venv

virtualenv venv
. venv/bin/activate
pip install -r requirements.txt

I adjust the rights :
chown -R bookwrym:bookwyrm venv

I restart 
systemctl start bookwyrm bookwyrm-worker bookwyrm-scheduler

Then you can delete the venv-backup :-)

**Comment by pm3003** [comment]
Thanks.
It was indeed the same problem. I don't get why pilkit didn't get upgraded  (if I get the issue right).

**Comment by prolibre** [comment]
> Thanks. It was indeed the same problem. I don't get why pilkit didn't get upgraded (if I get the issue right).

@pm3003 Strange indeed.
