### ISSUE TITLE
Show series name and number after title

### ISSUE THREAD

**Issue by Minnozz** [bookwyrm-social/bookwyrm#3256]
**Is your feature request related to a problem? Please describe.**
I read a lot of book series, and often think of books as "# 4 in that series".

Goodreads shows the series name and number after a book title:
![image](https://github.com/bookwyrm-social/bookwyrm/assets/701386/1ca38453-bb62-431c-be5b-5f751d962aea)

BookWyrm also shows this information, but only on the [book detail page](https://bookwyrm.social/book/177870/s/field-of-dishonor):
![image](https://github.com/bookwyrm-social/bookwyrm/assets/701386/7ac5633f-0ff5-4902-a1ba-4f292504a6cb)

and not, for instance, in the feed:
![image](https://github.com/bookwyrm-social/bookwyrm/assets/701386/cbe6aa76-2ddf-4856-8669-29cdd9589ff0)

**Describe the solution you'd like**
I would like to see the book series and number in more places where currently the book title is shown.

**Describe alternatives you've considered**
- A user setting could be added to configure this behavior. The default could go either way.

**Additional context**
n/a

**Comment by bSolt** [comment]
So something like this? Actually, this might only work on reviews and started to read posts. Maybe it go in the header of the post instead?

Option A

![image](https://github.com/bookwyrm-social/bookwyrm/assets/36494925/7ee92e59-2425-4aac-8e95-72ddbfde4f19)

Option B

This way we can pick and choose which kind of posts to show this on.

![image](https://github.com/bookwyrm-social/bookwyrm/assets/36494925/0198e362-8c75-4dae-a963-6b4625186689)

Maybe we could do both, but that feels a little redundant.

**Comment by Minnozz** [comment]
@bSolt Nice! I would personally be fine with having both.
