### ISSUE TITLE
Cannot clone

### ISSUE THREAD

**Issue by airdogvan** [bookwyrm-social/bookwyrm#3296]
Trying to clone with: 
Get the application code: git clone git@github.com:bookwyrm-social/bookwyrm.git
as per instructions [here](https://docs.joinbookwyrm.com/install-prod.html) and get an error:

```
git clone git@github.com:bookwyrm-social/bookwyrm.git                                                                                                                      ✔ 
Cloning into 'bookwyrm'...
The authenticity of host 'github.com (140.82.112.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Am I doing something wrong?

Thanks

**Comment by Minnozz** [comment]
You probably need to set up an SSH key for your GitHub account: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

**Comment by airdogvan** [comment]
The link should be: 
https://github.com/bookwyrm-social/bookwyrm.git
don't need a key for that.
