### ISSUE TITLE
Moving to a new machine

### ISSUE THREAD

**Issue by OliverPifferi** [bookwyrm-social/bookwyrm#3310]
Hey everyone,

I am planning to move my BookWyrm-instance from a provider-powered VPS to a different one, keeping domain / instance names.

Is there any way to simply make a database-dump, archive the (here) /opt/bookwyrm-directory and move everything to the new server after having installed / met all prerequisites? Or this there anything else I need to take care of?

BR,

Oliver

**Comment by prolibre** [comment]
@OliverPifferi hello.

I think I'll do it this way:
- stop all bookwyrm services
- backup the database
- copy the folder (/opt/bookwyrm-directory) to the new server
- import the database on the new server
- upgrade the conf for connecting to the database
- generate a new "venv" (virtualenv) to match the new configuration.
- start-up and monitoring

**Comment by OliverPifferi** [comment]
Thanks, will check this out - tried the process in the past but didn't generate the new "venv" so I got stuck!
