### ISSUE TITLE
Deletion of Instance

### ISSUE THREAD

**Issue by OliverPifferi** [bookwyrm-social/bookwyrm#3312]
Hey everyone,

is it possible to close down- / de-federate an instance?

Any procedure for this in case I really want to shut down my old instance after having moved on to the new?

Thanks and best regards,

Oliver

**Comment by prolibre** [comment]
If I've understood your message yesterday correctly, you want to change server and migrate your domain name. In this case there's no need to "de-federate" the old instance, requests will automatically switch to the new server. So there's nothing to do.
In any case, there is no procedure for de-federating an instance. To do things properly you would have to migrate or delete each account in the instance.
