### ISSUE TITLE
Characters from icomoon.ttf won't load

### ISSUE THREAD

**Issue by Stoori** [bookwyrm-social/bookwyrm#3319]
**Describe the bug**
Characters from static/css/fonts/icomoon.ttf (eg. rating stars) won't load even though the font file is in the specified directory.

**To Reproduce**
1. Update to latest version (my instance's version shows 0.7.1)
2. Open any page of your instance in private window / incognito mode (to prevent font file loading from browser cache)
3. See that there are now icons that are characters from icomoon.ttf 

**Expected behavior**
All characters from icomoon.ttf would show as normally.

**Screenshots**
https://nx33358.your-storageshare.de/s/26A2zm7cnC3RLob
https://nx33358.your-storageshare.de/s/yRQ3aPWoexAKG2w

**Instance**
https://kirja.casa

**Additional context**
One of our users (using a different system than me) also reported this bug to me, and I could reproduce it after their report.

---

**Desktop (please complete the following information):**
    - OS: macOS 14.2.1
    - Browser: Vivaldi 
    - Version: 6.6.3271.50

**Comment by Minnozz** [comment]
Looks like the same problem as https://github.com/bookwyrm-social/bookwyrm/pull/3284.

Could you try applying https://github.com/bookwyrm-social/bookwyrm/commit/1c587c5e53d3cb8bf3e64b8099d15a7db2eb03a6 (not yet released) to your nginx configuration?

**Comment by Stoori** [comment]
Yes, this solved the issue.
