### ISSUE TITLE
Own posts not shown in my general Feed

### ISSUE THREAD

**Issue by HelmutsCab** [bookwyrm-social/bookwyrm#3340]
My posts appear in my profile, but not in my general feed. Posts are public and appear in Followers feed at Bookworm or e.g. at Friendica.  If a Follower shares my post, then the shared post appears in my general feed.

**To Reproduce**
1. Go to 'my books'
2. choose 'start to read'
3. click on 'post' (official)
4. post appears in Profile but not in general feed

**Expected behavior**
Post should appear in general feed and in the 'discover' feed

<img width="640" alt="Bildschirmfoto 2024-03-29 um 20 33 36" src="https://github.com/bookwyrm-social/bookwyrm/assets/121969129/7c57cbbf-b0aa-4973-8c65-b9f998b681c6">

<img width="1370" alt="Bildschirmfoto 2024-03-29 um 20 34 42" src="https://github.com/bookwyrm-social/bookwyrm/assets/121969129/622bc51f-6bac-4877-a72c-5741634f30a4">

<img width="909" alt="Bildschirmfoto 2024-03-29 um 20 35 24" src="https://github.com/bookwyrm-social/bookwyrm/assets/121969129/b81f3dff-a0af-4b9d-bb9e-1efbc8ad8046">

<img width="656" alt="Bildschirmfoto 2024-03-29 um 20 47 25" src="https://github.com/bookwyrm-social/bookwyrm/assets/121969129/8cd4030b-d2e0-4df7-a887-bfaed248fab3">

Problem encounters on Bookwyrm.social

Post appears about 5-10 minutes later on other instances (e.g. squeet.me/Friendica)

---

**Desktop (please complete the following information):**
    - OS: iOS Sonoma 14.3.1
    - Browser Safari
    - Version 17.3.1

**Comment by prolibre** [comment]
I think a service crashed on bookwryrm.social. (bookwyrm-worker)
You should contact your administrator @mouse-reeve 
Have a nice day.

**Comment by HelmutsCab** [comment]
Thank you for the quick reply! I’ll follow your advice.A nice day for you, too.Am 30.03.2024 um 07:26 schrieb Anthony ***@***.***>:﻿
I think a service crashed on bookwryrm.social. (bookwyrm-worker)
You should contact your administrator @mouse-reeve
Have a nice day.
