### ISSUE TITLE
citation and reading position

### ISSUE THREAD

**Issue by prolibre** [bookwyrm-social/bookwyrm#3352]
Bookwyrm 0.7.3

A user contacted me because he couldn't publish a quote on a book.

For some time now there's been a problem with quotes that I've noticed myself.

If you want to post a extract and only put a page (in the first name=position field) leaving the second empty (name=enposition) then **the citation isn't posted and the user doesn't know why**. 

![SharedScreenshot](https://github.com/bookwyrm-social/bookwyrm/assets/17174902/6fbe24d3-5c44-45aa-9c52-a603b9763758)

I did the test on bookwyrm.social and it's the same thing.

Thank you and have a great week !

**Comment by dato** [comment]
Hi @prolibre! Thank you for your report, indeed this is happening. I've been able to diagnose it, and submitted a fix at #3353. Should be in the next release.
