### ISSUE TITLE
Adding email domain to the block list doesn't affect invite requests

### ISSUE THREAD

**Issue by skobkin** [bookwyrm-social/bookwyrm#3366]
**Describe the bug**
If I add a domain to email block list, it won't work on invite requests.

**To Reproduce**
1. Add domain xxx.tld to the email domain block list
2. Request invite to address on xxx.tld
3. Check invite requests or notifications

**Expected behavior**
Invite requests being automatically ignored or even not created at all.

**Instance**
`b.skobk.in`

**Comment by skobkin** [comment]
I'm not sure if it could be called a bug since I don't know what initial idea behind that list was, but it seems like it'll make sense if it'll work on invites too.

**Comment by skobkin** [comment]
Waited for some time to be able to get some screenshots.

![image](https://github.com/bookwyrm-social/bookwyrm/assets/967576/98ac424d-bd0b-444e-80a4-ce915bd25cb0)

![image](https://github.com/bookwyrm-social/bookwyrm/assets/967576/c79e4c8c-6154-462f-af11-25e4ee6ce5ff)

**Comment by MaggieFero** [comment]
We're having the same issue, and getting large-volume requests from the same domain, on our instance.
