### ISSUE TITLE
"Your books" links are broken when using a subdomain

### ISSUE THREAD

**Issue by MNickelson** [bookwyrm-social/bookwyrm#3368]
**Describe the bug**
When running bookwyrm on a subdomain (bookwyrm.domain.com} the tabs on the Your books page (To Read, Currently Reading, Read, Stopped Reading) all link to domain.com rather than bookwyrm.domain.com which may or may not be on the same host. The "All Books" tab correctly links to bookwyrm.domain.com

**To Reproduce**
1. Go to the Your Books page
2. Click on any of the shelves
3. domain.com loads which may not be the bookwyrm host.

**Expected behavior**
Those tabs should link to bookwyrm.domain.com (or whatever the hostname is in place of bookwyrm). And in fact, if https://bookwyrm is manually added in the address bar, the page loads as expected.

**Instance**
Self hosted private instance for family. Using production docker-compose v0.7.3

---

**Desktop (please complete the following information):**
    - OS: Debian Testing
    - Browser Firefox
    - Version 115.10

**Comment by petz79** [comment]
Doesn't seem to be a default problem, I'm also running docker 0.7.3 on Raspberry Pi OS (Debian) and the shelf links correctly point to the right subdomain. Maybe you missed correcting a domain in the .env config file?

**Comment by MNickelson** [comment]
The only thing I see in .env is line 8. I've tried both {hostname}.{domain} and just {domain} and have the same issue.

The "All books" shelf works fine. And I can see when I hover over the page the link for that (and everything except the other shelves) shows up as https://bookwyrm.{my-domain}.net/user/{me}/books.

But the other shelves, and any shelves I create the link is http://{my-domain}.net/user/{me}/books/{shelf}, so it looks like it's losing the https as well. Switching USE_HTTPS in .env between true and false doesn't seem to change anything.

I'm admittedly, using a non-standard configuration, going through caddy for https, but bypassing that and accessing bookwyrm directly on port 8001 is behaving exactly the same way.

**Comment by MNickelson** [comment]
Alright, well I tried about half a dozen more times or so and I'm not sure exactly what changed, but it seem to be working now.
