### ISSUE TITLE
Account export times out when trying to generate export json

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#3372]
I've tried creating account exports on b.s, even with accounts that are basically empty, and the `create_export_json_task` is taking so long that it times out and fails. It doesn't get to the point of generating a `create_archive_task`. I suspect that there's an inefficiency with the queries in the various data collection functions, but I'm surprised that it's hitting up against this even with essentially empty accounts.

Tagging you @hughrun if you still have any energy left on this ❤️

**Comment by hughrun** [comment]
hmm, that explains why you haven't turned it on yet.

will see what I can find, frustrating we can't get this to work! Is it possible there's something NQR with queues, or it just never gets prioritised?

**Comment by mouse-reeve** [comment]
The `create_export_json_task` is definitely being executed, I just dredged up a stack trace:
```
SoftTimeLimitExceeded: SoftTimeLimitExceeded()
  File "bookwyrm/models/bookwyrm_export_job.py", line 70, in create_export_json_task
    job.export_json = export_json(job.user)
  File "bookwyrm/models/bookwyrm_export_job.py", line 185, in export_json
    data["books"] = export_books(user)
  File "bookwyrm/models/bookwyrm_export_job.py", line 244, in export_books
    return [export_book(user, edition) for edition in editions]
  File "django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "model_utils/managers.py", line 38, in __iter__
    yield from iter
  File "django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/opentelemetry/instrumentation/psycopg2/__init__.py", line 249, in execute
    return _cursor_tracer.traced_execution(
  File "/usr/local/lib/python3.11/site-packages/opentelemetry/instrumentation/dbapi/__init__.py", line 460, in traced_execution
    return query_method(*args, **kwargs)
  File "encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
  File "billiard/pool.py", line 228, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
    ```

It looks to me like the problem is in `get_books_for_user` (https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/models/bookwyrm_export_job.py#L317), and since the users I tried with don't have any associated books but the total number of books is extremely high, I suspect that it's something along the lines of something in there is causing it to try to iterate over all known books.

**Comment by mouse-reeve** [comment]
I wonder if it might fix it just to query those categories separately? I've had queries I've written blow up because I was trying to filter on too many different axes at once.

**Comment by hughrun** [comment]
> It looks to me like the problem is in get_books_for_user

This doesn't surprise me. That's a function I tried to pull out into separate jobs because I could see it has the potential to chew up all available resources. When s3 comes into the picture it becomes a bit harder. We may need to rethink how the export file is created.

**Comment by hughrun** [comment]
Oh wait, I was thinking of something else. Right, we're querying everything, and then we end up splitting it out later anyway. So maybe we need to query each type and then aggregate, instead of aggregating and then splitting.

**Comment by mouse-reeve** [comment]
In this case the problem is the lookup, rather than the write -- if the queries had completed, they would have resulted in an empty queryset.

**Comment by mouse-reeve** [comment]
Oh yeah I just saw your second comment. Hopefully it's a simpler fix since it's a matter of structuring the queries rather than dealing with S3
