### ISSUE TITLE
Trim leading and trailing spaces in search

### ISSUE THREAD

**Issue by Ryuno-Ki** [bookwyrm-social/bookwyrm#3390]
**Describe the bug**
When doing a search and copying over an ISBN from another site, leading and trailing spaces sometimes are picked up, too.

**To Reproduce**
1. Go to https://www.rheinwerk-verlag.de/it-handbuch-fuer-fachinformatiker-der-ausbildungsbegleiter/
2. Copy the ISBN
3. Go to BookWyrm Search page
4. Paste the ISBN and click search
5. See the URL https://bookwyrm.social/search?q=+9783836295918&type=book (leading + in the ISBN)

**Expected behavior**
As a minor tweak I would expect to have no whitespace before or after a non-whitespace character

**Instance**
Noticed on bookwyrm.social.

**Additional context**
It's a cosmetic change, so could be a Good First Issue.

---

**Desktop (please complete the following information):**
    - OS: Debian Bookworm
    - Browser Firefox
    - Version 127.0.1

**Comment by timothyjrogers** [comment]
I've opened a PR for this. The whitespace was already being trimmed off for user queries, but not the other three types.
