### ISSUE TITLE
403 on login

### ISSUE THREAD

**Issue by TrevorMellon** [bookwyrm-social/bookwyrm#3446]
* Updated docker machine from 0.7.1 to 0.7.4 from source
* Applied patch to docker file itemised [here](https://github.com/bookwyrm-social/bookwyrm/issues/3439)
* Can no longer login

Error:

![403-book](https://github.com/user-attachments/assets/d64f97ff-f3b2-4d8b-941d-a2397cb2f6f7)

* Systems Tested: aarch64 -> x86_64
* OS Hosts: Debian Bookwyrm, Arch Rolling
* Browsers: libreWolf, Firefox, Vivaldi

Note: 

* It's behind an nginx proxy which may be the problem seems related to [this issue](https://github.com/bookwyrm-social/bookwyrm/issues/3170) but everything had been working prior to the upgrade, can downgrade if necessary

**Comment by TrevorMellon** [comment]
Update, same error trying to directly connect to the host, so that rules out nginx

**Comment by mouse-reeve** [comment]
I think this might help you? https://github.com/bookwyrm-social/bookwyrm/pull/3388#discussion_r1676695622

**Comment by TrevorMellon** [comment]
Unfortunately it didn't help, it's a remote host, the domain is already correctly set

I did enable debug mode and it seems a variable isn't set


![forbidden](https://github.com/user-attachments/assets/331abc43-4989-41ae-a660-f5119f2bc575)

**Comment by mouse-reeve** [comment]
Do you have your `DOMAIN` variable set in your .env file?

**Comment by TrevorMellon** [comment]
Unfortunately yes, hasn't changed

**Comment by mouse-reeve** [comment]
Well, it was a long shot. I suggest trying the matrix chat, I expect you’ll get more help there than in an issue.

**Comment by TrevorMellon** [comment]
Ok will do, thanks anyhow

**Comment by mouse-reeve** [comment]
I'm so glad to hear it! Thanks for the follow up
