### ISSUE TITLE
Use review subject (or title/author) as CW when federating

### ISSUE THREAD

**Issue by hartsick** [bookwyrm-social/bookwyrm#563]
**Is your feature request related to a problem? Please describe.**
I'm not sure how this information is sent and received via ActivityPub, but I just posted a book review on BookWyrm with a subject and was surprised by how it looked when I saw it federated on Hometown. [Here's the link](https://friend.camp/web/statuses/105634320910174927), which I think you should be able to access!

**Describe the solution you'd like**
I'd like for either the subject provided on BookWyrm or the subject you're constructing for federation (Review of "TITLE" (# stars): SUBJECT) be used as the CW so that the contents are hidden by default.

**Comment by mouse-reeve** [comment]
hmm, this will have to work with reviews that also have content warnings. I guess that can be part of the generated cw though

**Comment by hartsick** [comment]
oh interesting. how can you set content warnings on reviews? I only see the option for "Title" (which I described as "subject" above

**Comment by mouse-reeve** [comment]
<img width="362" alt="Screen Shot 2021-01-28 at 10 21 18 AM" src="https://user-images.githubusercontent.com/1807695/106181656-b792dd00-6152-11eb-9fd1-d3c711af6faa.png">

**Comment by hartsick** [comment]
oh cool! I didn't realize that was a button, though it was an icon to warn folks against posting publicly haha. I can experiment with using that to federate how I want

**Comment by mouse-reeve** [comment]
I'm going through and closing old issues that seem stale or out of date - feel free to reopen with a comment adding some updated context if you feel like it still needs to be addressed ❤️
