### ISSUE TITLE
Sort lists

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#584]
You should be able to sort lists based on rating, default order, etc

**Comment by SavinaRoja** [comment]
One approach would be to render the sort in a full-backend manner with a query param scheme for choosing sort and ordering. Selection of a new sort method would require a new page load.

Another would be use some frontend scripting (and something like this? https://justboil.github.io/bulma-responsive-tables/).

Frontend is not my expertise but I think it makes good sense. I think it would be cool if users who had curation privileges on a list were able to rearrange the default sort rank by drag-and-drop (or if that's too tricky, up-and-down-arrows).

**Comment by mouse-reeve** [comment]
There's actually already a database field on ListItem intended to let the list curator manually order the list! But no functionality to use it.

I prefer to use query params to sort, rather than doing it on the frontend, for one because it's compatible with pagination, and I'm not squeamish about reloading

**Comment by SavinaRoja** [comment]
I've got something in progress.

https://user-images.githubusercontent.com/454944/114041212-55411180-9852-11eb-9404-8c1905cc4e21.mp4

There are still some things to do, like pagination, list re-ordering, sorting by rating and title.

I am planning on setting `order` for `ListItem` as not nullable, and also setting a unique constraint on `(order, book_list_id)`. Is it reasonable to expect that `order` is always null? It might be pretty difficult to write a migration with a guarantee on non-destruction of existing ordering?

Another question about sorting by rating, should that be by the user's rating or should it be by some kind of instance average? The behavior of the stars on the list page appear to operate on the average rounded to half stars.

**Comment by mouse-reeve** [comment]
The preview looks great! I think your plan for the `order` field is sound, and yeah, it should always be null, and even if it isn't the field isn't meaningful in any way, since the list is displayed in order of when the item was added. So there's no meaningful risk of destroying user data with that field. 

I was thinking the average rating, not the user's rating. Just thinking about how _I_ use lists, I'm opening them because I want suggestions of books to read on a topic or theme or whatever, so I'm interested in the community opinion of the book.

**Comment by SavinaRoja** [comment]
This is mostly there: https://github.com/SavinaRoja/bookwyrm/tree/584-sorting-lists

Current blocker is figuring out how to write a Django ORM query to compute the average book rating and get the ordered items. This clause here: https://github.com/SavinaRoja/bookwyrm/blob/05393e19d5372fefff5765d0e9ee8f04905ee2b8/bookwyrm/views/list.py#L154

**Comment by SavinaRoja** [comment]
https://user-images.githubusercontent.com/454944/114177828-da87fd00-990a-11eb-851f-0aa358aabe04.mp4

I originally had the pagination UI using up to 9 list elements but this seemed to break onto two lines in 320p mobile. So I dropped it to 7.

![image](https://user-images.githubusercontent.com/454944/114178290-82052f80-990b-11eb-9835-b18eb121ce08.png)
