### ISSUE TITLE
Consistency and best practices for semantic html

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#589]
as part of the ongoing refactor I'm doing on the markup, I need to review best practices for when to use what html5 tags, rather than just turning divs into section tags willy nilly, and go through the views to ensure things are being used appropriately.

**Comment by greatislander** [comment]
@mouse-reeve I found this article by Bruce Lawson helpful in terms of sorting out where section tags make sense (the key takeaway IMHO is that sections should always have an accessible name (an h2, h3, or the like within or an aria-label). https://www.smashingmagazine.com/2020/01/html5-article-section/

**Comment by mouse-reeve** [comment]
I'm closing this because it's too broad, not because it's not important
