### ISSUE TITLE
re-fetch book info from source

### ISSUE THREAD

**Issue by tofuwabohu** [bookwyrm-social/bookwyrm#591]
**Is your feature request related to a problem? Please describe.**
If additional info is added to the source lib, e.g. Open Library, it won't be accesible in bookwyrm. 

**Describe the solution you'd like**
Have a possiblity to update the book data manually, e.g. by a button "Re-fetch data" next  to the "View on Open Library"-link.

**Describe alternatives you've considered**
Another possibility would be to automatically check for new data periodically but it'd be a lot of request of which most wouldn't do anything.

**Additional context**
Examples:

1. There's a book on bookwyrm that doesn't have a cover, but it does have a cover now on Open Library.
2. There's a book on bookwyrm where the author is missing. It's been corrected on Open Library.

**Comment by louispotok** [comment]
Open library has a "recent changes" [API call](https://openlibrary.org/dev/docs/api/recentchanges), looks like <50 updates/hour. An automated update process doesn't seem crazy either.

**Comment by e-edgren** [comment]
I must say, the documentation at Open Library was quite poor. I mean, "the default value is 100 and the allowed maximum limit is 1000". 1000 calls per... day? Per hour? Per week? Per month? Per year? But if we go after what @louispotok assumes it's less than 50 updates per hour, then you can easily update all data from Open Library that people can use on Bookwyrm once or twice per every 15 minutes via crontab. 1 calls per 15 minutes is 4 calls per hour. 2 calls per 15 minutes is 8 calls per hours which is very good enough :)

**Comment by louispotok** [comment]
@e-edgren I think that's a little unfair. The full quote:
> **limit**: Maximum number of entries in the response. The default value is 100 and the allowed maximum limit is 1000 for performance reasons.

Seems clear to me that 1000 is a maximum value for the `limit` parameter on the API call, whereas I think you are trying to interpret it as a rate limit. I don't see anything about a rate limit in the OL documentation (except for the Covers API).

**Comment by e-edgren** [comment]
Oh! I am sorry, @louispotok 🙈 My mistake.
