### ISSUE TITLE
Group books by series

### ISSUE THREAD

**Issue by tastytea** [bookwyrm-social/bookwyrm#644]
**Is your feature request related to a problem? Please describe.**
When I see a book I might like and notice it has a series after the title, I want to find out what the other books of the series are.

**Describe the solution you'd like**
I'd like to be able to click on the series name and get an ordered list of the complete series.

**Describe alternatives you've considered**
Looking the book up on GoodReads, but that's tedious.

**Comment by mouse-reeve** [comment]
yes! right now series is stored a list of strings in the database on each book, but I think it should be converted into it's own database table, so that it can be a proper relationship between books and can be edited by users
