### ISSUE TITLE
Should we add an option for abandoning a book?

### ISSUE THREAD

**Issue by harrisj** [bookwyrm-social/bookwyrm#646]
**Is your feature request related to a problem? Please describe.**
Currently, when you start reading a book, the only option is to mark it finished. But occasionally, you encounter a book that is like the infamous Dorothy Parker quip: "This is not a novel to be tossed aside lightly. It should be thrown with great force." Should we have a special choice for those options or is that just a `finished` with a bad review?

**Describe the solution you'd like**
Add a menu option for abandoning a book to the choice for finishing a book. Potentially a prompt for why?

**Describe alternatives you've considered**
Abandoning is just another way of finishing reading, but my concern is that it would count in the total of "books I read" in a year of even page count tabulations if I abandon early. But I also have a concern that this might open a Pandora's box of other options like "on hold" and such and we should probably consider what works holistically

**Additional context**
None

**Comment by rkingett** [comment]
I agree with adding this option, but I'd also want to, well, not add any more on holds and stuff like that. I'd want my reasoning for DNF ing a book to be published as a status message, though.

**Comment by mouse-reeve** [comment]
I like this! Thank you both. Would you want DNF to be a shelf (my assumption is no, but worth checking)?

**Comment by rkingett** [comment]
I wouldn't want DNF as a shelf, no. Just a status on a book or a review on a book page.

**Comment by harrisj** [comment]
Me neither. I also agree that the reason for DNF probably makes more sense as a freeform status field rather than other options. Hopefully, DNFs are relatively rare

**Comment by mouse-reeve** [comment]
#821 adds an option to un-shelve a book from the reading status menu. It doesn't keep track of a book as DNF, let you provide context, or update your read-through, all of which might be desirable, but it at least makes it easier to remove a book from your currently-reading list.

**Comment by mouse-reeve** [comment]
I'm going to consider this resolved, but if anyone has ideas or preferences to add to this, feel free to re-open. Thanks all <3
