### ISSUE TITLE
Social media preview images

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#651]
It would be great to have the instance logo or the relevant book cover display in the preview cards generated by sites like twitter. It should be possible to add some logic to the `layout.html` to include this in the meta headers.

**Comment by tofuwabohu** [comment]
In Mastodon, Lemmy and Matrix (Element client), the instance's logo is shown. Maybe this has accidently been done already?

**Comment by mouse-reeve** [comment]
It's partially done, but I'd like to show the book cover instead of the logo on book pages, and improve the compatibility with twitter.

**Comment by mouse-reeve** [comment]
Closed by #1142
