### ISSUE TITLE
Reviews are duplicated when importing more than once

### ISSUE THREAD

**Issue by arkhi** [bookwyrm-social/bookwyrm#679]
This is likely to happen when some book imports are failing and people try again (like I did).

1. [Log in](https://bookwyrm.social/login).
2. Go to the [import page](https://bookwyrm.social/import).
3. Import books with “Include reviews” checked.
4. Repeat the import.
5. Watch reviews appear twice in feeds. (exemple today: https://bookwyrm.social/user/arkhi)

**Expected behavior**

1. [Log in](https://bookwyrm.social/login).
2. Go to the [import page](https://bookwyrm.social/import).
3. Import books with “Include reviews” checked.
4. Repeat the import.
5. Reviews only appear once in feeds.

**Comment by tootbrute** [comment]
So what is the correct thing to do when book imports fail? I don't want to have a thousand duplicate things imported.

I got the TASK FAILED message from my import. Is this what you mean by 'import failed'?

**Comment by mouse-reeve** [comment]
@tootbrute I'll try and figure out why the task failed! That's not the normal "sorry, couldn't find the book" error state. Did any of your items import? If not, you can safely re-run the import without risk of duplicating reviews.

**Comment by tootbrute** [comment]
> @tootbrute I'll try and figure out why the task failed! That's not the normal "sorry, couldn't find the book" error state. Did any of your items import? If not, you can safely re-run the import without risk of duplicating reviews.

Trying not to thread hijack here but...

I'm trying to import a goodreads.csv with 1999 entries in the spreadsheet.
Now it doesn't say TASK FAILED, but it says it's still in progress. It also says 679 failed to import, which is almost half my books :/

![Screenshot from 2021-11-08 18-55-40](https://user-images.githubusercontent.com/47593393/140730497-ce8b7986-a8a1-45bc-bd18-736e8edc2866.png)
 
![Screenshot from 2021-11-08 18-56-08](https://user-images.githubusercontent.com/47593393/140730508-37b8ef28-f761-49d9-bdd4-eea65da3ddb3.png)

1. Is there some documentation to read about how importing works?
2. What happens to the books that failed to import? Do I have to manually input them? If so, that is a major hurdle to jumping over from GoodReads
3. If I re-import the CSV file, will it create duplicate entries?

**Comment by mouse-reeve** [comment]
When your import finishes, there will be an option to re-try only the items that didn't import. I've temporarily disabled imports because it's causing some side issues, but your import data will still be there once it's back and you'll be able to fix the missing entries automatically where possible (which it should be in most cases, those look like common enough books that they should import on their own).
