### ISSUE TITLE
Document BookWyrm ActivityPub format

### ISSUE THREAD

**Issue by WesleyAC** [bookwyrm-social/bookwyrm#684]
**Is your feature request related to a problem? Please describe.**

I'd like to make a page like https://evy.garden/reading/ on my website, and it would be nice if people could subscribe to it via ActivityPub, without me having to set up and manage a whole BookWyrm instance. It seems like you've thought a lot about what a good format is for describing book reviews in ActivityPub, so making my thing conform to that seems good, but I can't find any documentation about what kinds of messages BookWyrm sends out.

**Describe the solution you'd like**

I'd like documentation on what kinds of messages BookWyrm sends, similar to the [PeerTube](https://docs.joinpeertube.org/api-activitypub) and [Mastodon](https://docs.joinmastodon.org/spec/activitypub/) ones.

This will also be useful for developers of other ActivityPub software to make sure that their software works correctly with BookWyrm, etc.

**Comment by mouse-reeve** [comment]
I made a first pass at this, which definitely needs more fleshing out: https://docs.joinbookwyrm.com/activitypub.html

**Comment by mouse-reeve** [comment]
I'm going to close this now that there's a separate documentation repo (https://github.com/bookwyrm-social/documentation)
