### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by Flameborn** [bookwyrm-social/bookwyrm#713]
I am currently running a production Bookwyrm on a Raspberry Pi 3, with both the Postgres database and Bookwyrm being on a hard drive. I'm using Caddy as a web server. My current install is without using Docker.

My feed of about 1000 imported books takes about 10 seconds to open on the local network, the same is true for a user who has about 100 imported books. The page does not have statuses displayed from other users.

I am getting similar results for the status page or a 1000-book import.

My read shelf contains about 600 books or so, this absolutely refuses to load via Safari under MacOS, and in addition, I receive process timeouts and reboots in the logs. My CPU usage is around 1.0, which is about a quarter of the total CPU capacity. Memory also does not seem to be an issue, about 300 MB is used with other services running as well.

If you don't mind sharing, what's the performance of Bookwyrm like on bookwyrm.social?

Would it be possible to improve this experience, e.g. via paging?

**Comment by mouse-reeve** [comment]
Those could and should definitely be paged! I haven't been tracking performance on bookwyrm.social

**Comment by Flameborn** [comment]
The new pagination seems to have sped up loading times quite significantly in most cases.

The feed, however, takes about 20 seconds to load now on a Raspberry Pi 3.

I have as much data as possible on a hard drive, such as the database, Python packages, covers, etc.

As a result, Gunicorn worker processes often time out and restart, resulting in an empty page, when Bookwyrm is opened in Safari for a logged in user.

I'll likely need to investigate how profiling works for Django apps to provide more info on this.

I realize that this issue is partly out of scope, as neither Python or Bookwyrm were designed to run on low-end hardware (an ARM Cortex A53 in this case), so I am only posting updates regarding this, in case some more performance improvements can be made in the future.

**Comment by mouse-reeve** [comment]
yikes! Is that a worse load time than before? there may be some very inefficient queries behind this. 

While it's true that it isn't intended to run on the Pi, performance improvements are improvements for every platform, so I appreciate you keeping an eye on this

**Comment by Flameborn** [comment]
Unfortunately, yes, about double the time of what it used to be.

Profiling this is going to be difficult on a Pi, I've just tried *Cprofile* and *Django Silk*, however, the overhead is so huge that the worker processes keep timing out when I try and access the feeds page, no matter what browser I use.

**Comment by mouse-reeve** [comment]
well, I didn't use any profiling tools but I put some datetime calls in and took a look at what loading each step looks like, my suspicion was confirmed, it's the suggested users query that is taking so long.
```
0:00:00.009479 - querying redis and the database database for the statuses in the feed
0:00:01.064589 - loading suggested users
```

As an experiment, if you replace the call to `... = get_suggested_users(request.user)` with `None` here: https://github.com/mouse-reeve/bookwyrm/blob/main/bookwyrm/views/feed.py#L37, I think you'll see better load times than before. And in the mean time, I will seriously reconsider that query...

**Comment by Flameborn** [comment]
Confirmed, this reduces it locally to about 5 seconds here.

**Comment by mouse-reeve** [comment]
I'm going through and closing old issues that seem stale or out of date - feel free to reopen with a comment adding some updated context if you feel like it still needs to be addressed ❤️

(I think I've addressed most of the low handing fruit for this - if you are still having problems with performance and you'd be down, it would be great if you could open a new issue specific to that. I really appreciate you opening this!)
