### ISSUE TITLE
Unable to Interact With an Account With the Same Username as A Previously Followed Account

### ISSUE THREAD

**Issue by bcj** [bookwyrm-social/bookwyrm#722]
**Describe the bug**

I created my own instance and mutually followed my bookwyrm.social account.
Since resetting instance and recreating an account with the same name, my bookwyrm.social account cannot seem to see any activities (although DMs worked both directions).

I'm seeing nothing in my federated feed so it seems likely it is because the servers have the same name, not because the accounts specifically do (but I'd maybe need to make a second server to fully confirm?). I can see a bookwyrm update I made from my mastodon account, so I know it isn't just my instance not working at all.

**To Reproduce**
1. Create a bookwyrm server
2. Follow an account on it from an account on another server
3. Wipe that server and recreate it.
4. Be unable to send follow requests, see updates from or do anything with an account on that recreated server (except for DMing)

**Expected behavior**

All accounts on instance A should automatically unfollow any accounts on instance B if it appears to be a new server (perhaps with some sort of notification sent to all affected accounts on instance A.

After that point, it should then be possible to interact with the new version of instance B.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser Firefox
 - Version 97.0b9

**Comment by bcj** [comment]
#721 was actually related to me trying to debug this.

I may try to look into this one myself over the weekend and can help debug as necessary (I think you already should be in a weird limbo state with my account)

**Comment by mouse-reeve** [comment]
#979 may have fixed this

**Comment by mouse-reeve** [comment]
I'm closing this in the hope that I was right about that PR fixing it, please feel free to re-open if you see problems continue

**Comment by bcj** [comment]
Oops, yes. I'll have a chance to double-check this week but I think it did.
