### ISSUE TITLE
Display Names/Profiles of Non-Bookwyrm Accounts Never Refresh

### ISSUE THREAD

**Issue by bcj** [bookwyrm-social/bookwyrm#723]
**Describe the bug**

Once profile information from an account on another server (only have tested with mastodon, do not know if this is true of other fediverse accounts or even of other bookwyrm accounts) is loaded, it never updates

**To Reproduce**
1. Search for a fediverse account not already in your bookwyrm instance's database.
2. Have that user change their profile/display name
3. Go to that user's profile on your bookwyrm instance

**Expected behavior**
This information should refresh periodically, and at least after directly interacting with the account.

Some related things that I can break into their own issues if you prefer:
* the profile for that account lists an account creation time that is the time the user was added to the database
* you can work out which remote accounts are in an instance's database by searching their profile page, even when not signed in (e.g., `https://bookwyrm.social/user/bcj@friend.camp` resolves, `https://bookwyrm.social/user/bcj@oulipo.social` currently does not)
 * this is also sort of true of mastodon. if you search `https://INSTANCE_URL/web/accounts/NUMBER` it redirects you to the possibly-external account, even in private browsing mode.

Some of the above might just be how activitypub works but if feels like it is leaking of potentially-sensitive information

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 87.0b9

**Comment by mouse-reeve** [comment]
hm, I think mastodon sends `Update` activities when a user edits their profile, which bookwyrm does (at least in theory) recognize. I wonder if that has stopped working at some point -- @tripofmice@friend.camp does have an up-to-date display name on bookwyrm, and I've definitely changed that a few times since federating with that account.

**Comment by bcj** [comment]
@bcj@friend.camp is at least 2 behind for me but another account I checked isn't. I wonder if this is specific to accounts that select `Opt-out of search engine indexing`?

**Comment by mouse-reeve** [comment]
No, I'm opted out as well. I suspect that I've introduced a bug, probably when I refactored the inbox code.

**Comment by mouse-reeve** [comment]
I just tested this and I'm seeing my mastodon display name get updated correctly in bookwyrm

**Comment by mouse-reeve** [comment]
I suspect that your display name isn't getting updated because no bookwyrm users follow your friend camp account, so friend camp isn't including bookwyrm.social in the servers it broadcasts the changes to.

**Comment by bcj** [comment]
Ah, that makes sense. Thanks

**Comment by tofuwabohu** [comment]
I changed the display name of my old account on .social. In flower, I can see that w.d got the update (following it from my new account), but it didn't change in the w.d database.

Also, my w.d account is not updated on .social (I added pronouns a while ago, while people from .social were following me).

**Comment by mouse-reeve** [comment]
I'm going through and closing old issues that seem stale or out of date - feel free to reopen with a comment adding some updated context if you feel like it still needs to be addressed ❤️
