### ISSUE TITLE
Some books not upating after editing

### ISSUE THREAD

**Issue by LongJohn-Silver** [bookwyrm-social/bookwyrm#741]
**Describe the bug**
Yesterday and the day before it I edited some books and the changes were saved, but after I logged in the next day the books were as if I wouldn't have edited them.

Some examples:

https://www.bookwyrm.social/book/106348 You can see it has the publisher in the title.
https://www.bookwyrm.social/book/106344 It is capitalized in every word even though that formatting is incorrect for Spanish.
https://www.bookwyrm.social/book/106316 It has an English name of the edition in the title even though the edition is not bilingual.

**To Reproduce**
1. Edit a book.
2. Save it.
3. Wait some time?

**Expected behavior**
Edits to be saved.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: elementaryOS
 - Browser: Firefox
 - Version: 86.0

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by mouse-reeve** [comment]
hm, it may be that for some reason these have gotten re-imported and the changes were over-written. I'll take a look.

**Comment by LongJohn-Silver** [comment]
Thanks!
