### ISSUE TITLE
Author is sometimes missing from Open Library-imports

### ISSUE THREAD

**Issue by tastytea** [bookwyrm-social/bookwyrm#850]
**Describe the bug**
When I import a book from Open Library (OL), the author is often missing. This happened with several books, the last one was this: [Open Library](https://openlibrary.org/books/OL32168130M/Der_Fall_Julian_Assange) → [bookwyrm.social](https://bookwyrm.social/book/109395).

This could be only an issue with newly created (in OL) books. I just imported a book that was in OL for a longer time and the author is not missing.

*Edit:* I just imported a book after creating it 17 minutes before in OL and the author is there.

**To Reproduce**
1. Create a book on <https://openlibrary.org/>
2. Import the book in BookWyrm
3. Author is missing

**Comment by mouse-reeve** [comment]
I'm seeing some errors related to fetching authors for editions in the logs, so I'll follow up on those. If you're seeing seeing a book import with no author and then the author magically appears, it's probably just that the data is still being fetched.

**Comment by mouse-reeve** [comment]
I believe this is fixed by #1030
