### ISSUE TITLE
Making deployment easier

### ISSUE THREAD

**Issue by SavinaRoja** [bookwyrm-social/bookwyrm#857]
Right now I think that the story of deploying (and updating a deployment) for bookwyrm is on the difficult side.

I would propose that it would help to maintain the main branch as suitable for both development and deployment.

Alternatively, it could be that the `production` branch be generally maintained as a shallow one-commit branch off of the `main` branch by rebasing it.

Ideally, all critical config local to running a deployment should be out of version control. `.env` qualifies but `nginx/default.conf` does not, I think.

https://github.com/savinaroja/bookwyrm/tree/ease-production shows some experimental effort towards making deployment easier.

**Comment by SavinaRoja** [comment]
Having just `git diff --name-only main production` from this repo, the output is:

```
.env.example
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/black.yml
Dockerfile
bookwyrm/activitystreams.py
bookwyrm/management/commands/populate_streams.py
bookwyrm/settings.py
bw-dev
docker-compose.yml
fr-dev
nginx/default.conf
postgres-docker/Dockerfile
postgres-docker/backup.sh
postgres-docker/cronfile
postgres-docker/tests/Dockerfile
postgres-docker/tests/docker-compose.yaml
postgres-docker/tests/testing-entrypoint.sh
postgres-docker/weed.sh
redis.conf
requirements.txt
```

The treatment of each of these files should be considered.

**Comment by mouse-reeve** [comment]
Thank you! I super agree that deployment and updating could be an easier process. I'm curious to know more about particularly what makes the two branches a pain point for you? I can see how the divergence between the branches makes for more effort in maintaining the codebase, and the production files are harder to find because they only exist on a separate branch, but I'd be interested to know if you thinking is different than that.

I'm not attached to that as a system for separating out the production version of the application from the development version (and having separate .env files has caused issues for me and others, so I appreciate you pointing that out in particular), but there's a few benefits to having separate branches that I really like.

The main win for me is that the shortcuts in `bw-dev` the are available in production vs main are different -- main has tests and destructive commands like `rebuilddb`, which are useful in development but should be very hard to run unintentionally on production. It also means that `main` can act as the bleeding edge and `production` as stable (both are bleeding edge and usually at about the same code point right now), but that might be better handled with user git tools (like release tags).

**Comment by SavinaRoja** [comment]
One pain point I encountered is that when recently applying updates to my local instance, I had to resolve some git merge conflicts, including with my `nginx/default.conf` and `docker-compose.yml` which have local changes. I remember it being a little messy with commit history... I should update again soon and track my process. Maybe there's a piece of git wisdom I am missing.

The general approach I've taken so far is to make the process contextually sensitive to `.env`'s `DOCKER_ENV` var, to conditionally alter behavior. Each of the example env files contains the same variables but with different settings.

I see the merit in making it more difficult to accidentally take destructive action. This perhaps could also be made contextually disabled without modifying the source?

I do also see the point in keeping production stable while in a pre-release stage if main is to be considered non-stable. Though the main branch should generally be at a minimum stability level of "workable, won't crash if you run it" as branches are tested before merge. I do think that release tags is the sensible alternative.

**Comment by tofuwabohu** [comment]
I do fully agree on not having checked in nginx config and docker config files as this could easily break stuff with auto merge. I would like to have a way to see when I change something in my local copies of those, e.g. I broke my redis after the update that introduced a second instance. That could have been seen from the PRs, but it's not obvious for everyone. Luckily @mouse-reeve mentions people who may run an instance currently, when changes are necessary, but that doesn't scale obviously. I think, ideally, `bw-dev update` would tell me "check these new release notes before continuing" or similar, or there would be proper versioning with release notes I can check. I think going through all PRs looking for information is not too practical long term, especially if one doesn't update for a while.

For the branching strategy, idk, for me it's fine in the current way. Maybe main could become the production branch and there would be one for testing with the dangerous tools, but as long as it's documented properly it should not make too much of a difference.

**Comment by SavinaRoja** [comment]
Seems like some straightforward and easy wins would be to get around the common merge conflicts.

For `nginx/default.conf`. One could:

1. `git mv nginx/default.conf nginx/dev.conf`
1. Provide a copy of `nginx/default.conf` from production branch as `nginx/prod.conf`
1. Modify README instructions for development to include a step to `cp nginx/dev.conf nginx/default.conf`
1. Modify README instructions for deploy/production to include a step to `cp nginx/prod.conf nginx/default.conf`
1. Modify `.gitignore` to ignore `nginx/default.conf`

For `docker-compose.yml`. One could:

1. Add a variable to `.env`: `CERTBOT_INIT=false|true`
1. Create a bash script: `./certbot.sh`
    ```bash
    #!/usr/bin/env bash
    source .env;
    if [ "$CERTBOT_INIT" = "true" ]
    then
        certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN} -d www.${DOMAIN}
    else
        renew --webroot --webroot-path /var/www/certbot
    fi
    ```
1. Change the command for certbot in `docker-compose.yml` to `bash ./certbot.sh`
1. Modify README instructions to change `CERTBOT_INIT` to `false` after first run/whenever the initialization for certbot is not required.

**Comment by SavinaRoja** [comment]
@tofuwabohu and @mouse-reeve What is your update process?

Here is what I just did to update my production branch (deploying from my fork, hence the "upstream"):

- `git stash`
- `git checkout main`
- `git pull`
- `git fetch upstream`
- `git merge upstream/main`
- `git checkout production`
- `git merge main`
- `git stash pop`

**Comment by mouse-reeve** [comment]
when I want to add commits to production, I just do:
```
git checkout production
git merge main
```

on bookwyrm.social, I never leave the production branch, so I just `git pull` or stash before and stash pop after if any of the configuration files change

**Comment by tofuwabohu** [comment]
I too just stay on production. I committed all my local changes, so `git pull` tries to auto merge them and sometimes I have to fix conflicts but it's not too much of a hassle usually.

**Comment by SavinaRoja** [comment]
This has reduced the number of steps to deploy for me and also the chance of getting into a merge conflict which is pretty daunting if the person is not familiar with git or the codebase.

I am happy with this so I will close this issue.
