### ISSUE TITLE
Boosts from remote users are shown twice

### ISSUE THREAD

**Issue by tofuwabohu** [bookwyrm-social/bookwyrm#859]
**Describe the bug**
In some cases (maybe all) where a remote user boosts a post, the boost is shown twice.

**Screenshots**
Screenshot where the booster and op are both from a remote instance:
![image](https://user-images.githubusercontent.com/66644064/113485516-2f141e00-94ae-11eb-94ca-312d21d3d8df.png)
Screenshot where the booster is from a remote instance and op is from the local instance:
![image](https://user-images.githubusercontent.com/66644064/113485481-fe33e900-94ad-11eb-90a7-c4d5c76c2bd6.png)

**Additional context**
Liking the post and reloading the page will show the like on both boosts.

**Comment by mouse-reeve** [comment]
interesting! this will probably be fixed by #855

**Comment by mouse-reeve** [comment]
I think this is fixed? I'm hoping it's fixed.

**Comment by tofuwabohu** [comment]
There were no federated boosts so far but I'll keep you posted!

**Comment by mouse-reeve** [comment]
it did not fix it! intriguing. (That the boost is blank has a fix which isn't deployed yet)
<img width="761" alt="Screen Shot 2021-04-06 at 9 13 37 AM" src="https://user-images.githubusercontent.com/1807695/113743372-766dfa80-96b8-11eb-84c8-4e6eabb694dd.png">

**Comment by tofuwabohu** [comment]
I logged into my .social account and in that feed, the post from your screenshot only appears once.

**Comment by mouse-reeve** [comment]
interesting! that's good to know.

**Comment by mouse-reeve** [comment]
I think this is resolved - feel free to re-open if you see it happen again

**Comment by mouse-reeve** [comment]
I jinxed it by saying it was gone! I just replicated it
