### ISSUE TITLE
Only run Actions that are relevant to changes made

### ISSUE THREAD

**Issue by arkhi** [bookwyrm-social/bookwyrm#884]
Not a bug, not a feature, just an improvement (maybe)… :)

At the moment, some Github Actions run every time a commit is pushed to the repository. Maybe this is unnecessary and they could only run if some logic needs to be checked based on the files modified, be it from their location or type?

**Comment by mouse-reeve** [comment]
I'm going through and closing old issues that seem stale or out of date - feel free to reopen with a comment adding some updated context if you feel like it still needs to be addressed ❤️
