### ISSUE TITLE
Ratings don't federate

### ISSUE THREAD

**Issue by tofuwabohu** [bookwyrm-social/bookwyrm#887]
**Describe the bug**
I do follow someone on bookwyrm.social from bookwyrm.social and wyrms.de. I have seen on b.s that they rated some books without reviewing them, but those ratings do not appear on w.d. All other posts federate properly (I think).

**Expeceted behaviour**
The rating should show up on connected instances and ideally also be used on those to calculate the average rating of the book.

Here is one example that's not visible from w.d: https://bookwyrm.social/user/tastytea/reviewrating/21469

**Comment by mouse-reeve** [comment]
I was able to federate a rating just now from my dev instance to b.s. Are you seeing continued problems with ratings, or any errors in flower?

**Comment by tofuwabohu** [comment]
Hm that's funny, there are quite some results including the one from my OP when I filter for "Reviewrating" in flower (with Success), but none of them show up in the federated TL or at the user's profile.

**Comment by mouse-reeve** [comment]
huh! I wonder if they're in the database? If they just weren't showing up in the timelines, that could be a redis issue, but since they aren't showing up on the user page (which doesn't use redis), that suggests that they either aren't getting saved in the database or they're malformed in some way

**Comment by tofuwabohu** [comment]
I don't know how to check the db honestly but will if you could give me a hint.

I just rated a book on wyrms.de but it seems it didn't federate to .social either.
https://wyrms.de/user/tofuwabohu/reviewrating/674
![image](https://user-images.githubusercontent.com/66644064/114055235-dfa86600-9890-11eb-8a3f-a133f946bea0.png)

**Comment by mouse-reeve** [comment]
Oh I wonder if it's a problem with who it's sending to? The status will give you a list of who receives the broadcast --
open the python shell with `./bw-dev shell`, then run:

```python
from bookwrym import models
models.ReviewRating.objects.get(id=674).get_recipients()
```

**Comment by tofuwabohu** [comment]
It's been sent to the following instances:
`['https://bookwyrm.social/inbox', 'https://cybre.space/inbox', 'https://rage.love/inbox', 'https://social.tchncs.de/inbox', 'https://subversive.zone/inbox', 'https://sunbeam.city/inbox', 'https://tabletop.social/inbox']`
So it looks like .social should have it.

**Comment by mouse-reeve** [comment]
okay, definitely not that, then. Thanks for checking!

**Comment by mouse-reeve** [comment]
Okay, I found the corresponding successful inbox task that received your rating, and I'm not seeing the status in the database. That probably means that there was an error serializing some part of the activity which was handled silently. That gives me a foothold to debug it more fully, thankfully

**Comment by tofuwabohu** [comment]
Yay! It's visible on Mastodon if that's of any help.

**Comment by mouse-reeve** [comment]
I haven't been able to reproduce an error with these statuses so far, but I have changed the way that inboxes handle errors (https://github.com/bookwyrm-social/bookwyrm/pull/912/commits/6617cede375f335e9722b09d69afa0a3b666f716) so that when it encounters problems serializing an incoming status, it will throw an error that can be looked up in Flower. I'll keep an eye on my end and see if the culprit shows up.

**Comment by tofuwabohu** [comment]
Found one in the wild:
OP: https://bookwyrm.social/user/tastytea/reviewrating/25129
w.d flower: `Exception | ActivitySerializerError(AttributeError("'Rating' object has no attribute 'name'"))`
``` python
Traceback (most recent call last):
  File "/app/bookwyrm/activitypub/base_activity.py", line 130, in to_model
    field.set_field_from_activity(instance, self)
  File "/app/bookwyrm/models/fields.py", line 69, in set_field_from_activity
    value = getattr(data, self.get_activitypub_field())
AttributeError: 'Rating' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/bookwyrm/views/inbox.py", line 103, in activity_task
    activity.action()
  File "/app/bookwyrm/activitypub/verbs.py", line 22, in action
    self.object.to_model()
  File "/app/bookwyrm/activitypub/base_activity.py", line 132, in to_model
    raise ActivitySerializerError(e)
bookwyrm.activitypub.base_activity.ActivitySerializerError: 'Rating' object has no attribute 'name'
```

Let me know if I can provide more input.
