### ISSUE TITLE
Thumbnails for book covers

### ISSUE THREAD

**Issue by tastytea** [bookwyrm-social/bookwyrm#888]
**Is your feature request related to a problem? Please describe.**
I've added a rather large (718 KiB) cover image to <https://bookwyrm.social/book/102482> and it's loaded everywhere although the required height is 250 pixels at most as far as i can see.

**Describe the solution you'd like**
I think creating thumbnails is a good idea. The thumbnail on a book page could have a hyperlink to the full image.

**Comment by mouse-reeve** [comment]
Yes! there are 3 sizes that covers are displayed at:
- 500 px high
- 250 px high
- 150 px high

**Comment by carbontwelve** [comment]
If I upload a 2MB giant image, I expect the backend to create the resized versions, for example 500px, 250px and 150px high versions each being a fraction of the file size of the original. What currently happens is that giant image is used and sized on the page meaning a lot more bandwidth is needed and the pages load slower.

Unfortunately I don't know Python well enough to implement @tastytea's solution but I certainly agree that the backend should be creating thumbnail versions.

**Comment by mouse-reeve** [comment]
I believe this is closed by #1138
