### ISSUE TITLE
Can't follow user from wyrms.de

### ISSUE THREAD

**Issue by tastytea** [bookwyrm-social/bookwyrm#895]
**Describe the bug**
A user (from wyrms.de) followed me, I followed back. My *followers*-page says I'm following her. My *following*-page doesn't list her. I can see a post from her in the federated feed but not in my home feed. When I go to her profile page, it says I'm following her but I'm not in her followers-list. Her profile page on wyrms.de shows that I follow her.

I unfollowed and followed again. wyrms.de received my first follow activity but the second one doesn't show up in the logs.

**Screenshots**
This is how it looks from wyrms.de:
![e491241f-414d-416b-9e7b-ec8b80fc056a](https://user-images.githubusercontent.com/3681516/113873020-b74b3980-97b4-11eb-81d7-f76be957273b.png)

Her profile page with followers-list, from bookwyrm.social:
![screenshot_2021-04-07T15:24:04](https://user-images.githubusercontent.com/3681516/113873683-4f492300-97b5-11eb-9371-3fe6bb96253a.png)

**Comment by mouse-reeve** [comment]
I see a failed task in the logs on b.s - it looks like part of the transaction was lost, which caused the incoming Accept from wyrms.de to fail. This looks like a transient failure to me, did unfollowing and refollowing resolve it? I think the bigger issue is that activities need to be more resilient to one of the servers temporarily not responding

**Comment by tastytea** [comment]
I unfollowed and refollowed just now, it didn't work.

**Comment by mouse-reeve** [comment]
I was able to replicate this locally! I'll take a close look tomorrow.

**Comment by tastytea** [comment]
I have the same issue with another account on wyrms.de. Is it just me or does anyone else have the same problem?

**Comment by tastytea** [comment]
Not sure if it's the same issue: Bookwyrm un-followed a user from wyrms.de without me doing anything. Re-following doesn't work, like with the other accounts in this thread.

**Comment by mouse-reeve** [comment]
That sounds related! I'm taking a look at this today

**Comment by mouse-reeve** [comment]
Trying again, I haven't been able to replicate the issues with following users, but I am seeing that, according to Flower, your user appears to be editing _Braiding Sweetgrass_ every thirty seconds nonstop for a days. It seems like something has gone haywire with that broadcast action, and it could be that that is preventing other activities from working correctly

**Comment by mouse-reeve** [comment]
Did you edit that book on wyrms.de or on bookwyrm.social?

**Comment by mouse-reeve** [comment]
#979 won't fix whatever issue is causing this in the first place, but it should make it so that it works when you try to re-follow a user

**Comment by Tak** [comment]
I'm having a *very* similar issue trying to follow someone on another instance. I even updated my instance and tried doing a "remote" follow (which reported success, but the symptoms remain the same). Thoughts?

my instance: https://reading.taks.garden
their instance: https://bookwyrm.cincodenada.com

**Comment by mouse-reeve** [comment]
Would you be down to open a new issue? The state of the code has changed a fair amount since this issue was closed, it'll just make it easier for me to keep track of things 😄 

In the meantime, can you check your flower logs (it runs on port 8888) to see if the follow activities are present and if they have produced any errors
