### ISSUE TITLE
Paginator should return a 404 instead of 500 when a user tries to access a nonexistent page

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#902]
Currently, when trying to render a view with a page number that is too high, the app has a 500 error. It should just 404. This should be fixed generally across all the (many) views with pagination, rather than individually in each view.

**Comment by SavinaRoja** [comment]
I checked this on `bookwyrm/views/books:Book.get` and observed that this was the Exception that was occurring.

https://docs.djangoproject.com/en/3.1/ref/paginator/#django.core.paginator.EmptyPage

Seemed like it happened the same for an integer page value `<= 0` as for a page value exceeding the max range.

In my branch for 584, I coerced values to be between 1 and the max page range; the bit for keeping it no lower than 1:

![image](https://user-images.githubusercontent.com/454944/114715223-d855e200-9d00-11eb-9f22-fb87ba1d5e75.png)

Is there a Django friendly way to put some logic like this into a decorator? I did not see anything in the docs for configuring the Paginator class to auto-correct.

**Comment by mouse-reeve** [comment]
I think a decorator could work, I was also thinking of subclassing the paginator

**Comment by SavinaRoja** [comment]
Subclassing would work.

**Comment by SavinaRoja** [comment]
Perhaps we should just use `Paginator.get_page()` instead of `Paginator.page()` https://docs.djangoproject.com/en/3.1/ref/paginator/#django.core.paginator.Paginator.get_page

**Comment by mouse-reeve** [comment]
holy shit. thank you, absolutely yes. I should read the docs more carefully omg

**Comment by SavinaRoja** [comment]
Lol. I was in the middle of re-implementing that in a subclass when I realized I wasn't even changing the behavior...
