### ISSUE TITLE
Allow for Jinja2 templates

### ISSUE THREAD

**Issue by arkhi** [bookwyrm-social/bookwyrm#916]
I’m frustrated with the limitations of Django’s templates; extremely long lines are not very legible and source of bugs, for example.

Django has support for [Jinja2] built-in, an evolution of the Django templates, which allows more control regarding whitespace, among other things.

I tried to implement it but my knowledge with both Python or Django are very limited. It worked but I templates would need to be adapted and there was a couple of mountains I couldn’t climb alone.

Maybe other template systems like nunjucks or twig are possible, I’m not sure how that would work.

### Ressources

- [Jinja2]
- Django documentation about [implementing Jinja2](https://docs.djangoproject.com/en/3.2/topics/templates/#support-for-template-engines)

[jinja2]: https://jinja.palletsprojects.com/en/2.11.x/

**Comment by mouse-reeve** [comment]
I'm going through and closing old issues that seem stale or out of date - feel free to reopen with a comment adding some updated context if you feel like it still needs to be addressed ❤️

**Comment by arkhi** [comment]
I still believe everybody (the project) would benefit from being able to use jinja2 because dealing with the impossibilities of using line-breaks in templates makes them harder to read, more prone to bugs, and also harder to diff.

I don’t know how hard this would be for someone accustomed to Python and Django, though.

**Comment by mouse-reeve** [comment]
I feel you! This is something I would do differently if I was starting again, but at this point it's hard for me to envision taking on the amount of work to make the switch.
