### ISSUE TITLE
Storing images on the cloud

### ISSUE THREAD

**Issue by joachimesque** [bookwyrm-social/bookwyrm#933]
I just installed Bookwyrm on a small server (congrats on the documentation, very straightforward). I don't have a lot of free space, and I expect the database to take a big chunk of it. I'd like to be able to store all the images on a cloud storage service, ideally S3-compatible, as many cloud providers offer storage buckets compatible with AWS's offer.

That feature saved my Mastodon instance when I had severe storage problems.

**Comment by arkhi** [comment]
I find it ironical to create an alternative to Goodreads and host our files on Amazon servers. ;p

I don’t think S3 would go against the license, but still… :)

**Comment by joachimesque** [comment]
You’ll notice I wrote “S3-compatible”, not “AWS S3” 😅

the S3 system has become a de facto industry standard, and is implemented on various other cloud providers… notably on Scaleway, which I use for my Mastodon instance. I personally discourage using AWS infrastructure but I don’t know if there’s any other system as widely used as S3 for Cloud file storage

**Comment by seniorm0ment** [comment]
It could maybe be setup in a way that you can mount another server over SSH for media.
That being said no matter how this is implemented, it would be appreciated to have any remote content proxied through the instance server, instead of served directly to the end users.
