### ISSUE TITLE
Wrong format for import

### ISSUE THREAD

**Issue by joachimesque** [bookwyrm-social/bookwyrm#934]
**The problem**

When importing my Goodreads list from CSV, a lot of books are imported as audio-cd, not as book/ebook version. It's not that big of a problem, except that the ISBN isn't good, the image is square and the voice actor is listed as an author.

**What I'd like to happen**

When I launch an importation, I'd like to be able to have a setting allowing me to look only for printed/ebook versions and not for the audiobook. Or the opposite, if I'm mainly an audiobook reader.

**Comment by mouse-reeve** [comment]
Hm, it ought to match the isbn to the book, which in theory would get the correct edition. Would you mind sharing the csv line that failed, or the correct isbn of the book?

**Comment by joachimesque** [comment]
Ah I see, so after checking the export from Goodreads, here's the lines for some badly imported book:

```
Book Id,Title,Author,Author l-f,Additional Authors,ISBN,ISBN13,My Rating,Average Rating,Publisher,Binding,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Bookshelves with positions,Exclusive Shelf,My Review,Spoiler,Private Notes,Read Count,Recommended For,Recommended By,Owned Copies,Original Purchase Date,Original Purchase Location,Condition,Condition Description,BCID
52360057,"Out Past The Stars (The Farian War, #3)",K.B. Wagers,"Wagers, K.B.",,"=""""","=""""",0,4.17,Orbit,Kindle Edition,320,2021,2021,,2021/02/24,"to-read, tsundoku","to-read (#193), tsundoku (#40)",to-read,,,,0,,,0,,,,,
46017966,Down Among the Dead (The Farian War #2),K.B. Wagers,"Wagers, K.B.",,"=""""","=""""",0,3.98,Orbit,Paperback,432,2019,,,2020/03/07,"to-read, tsundoku","to-read (#122), tsundoku (#29)",to-read,,,,0,,,0,,,,,
36343160,"There Before the Chaos (The Farian War, #1)",K.B. Wagers,"Wagers, K.B.",,"=""""","=""""",0,4.14,Orbit,Paperback,480,2018,2018,,2020/03/07,"to-read, tsundoku","to-read (#121), tsundoku (#28)",to-read,,,,0,,,0,,,,,
42074525,"The City We Became (Great Cities, #1)",N.K. Jemisin,"Jemisin, N.K.",,"=""""","=""""",2,3.98,Orbit,Hardcover,437,2020,2020,,2020/03/08,"tsundoku, currently-reading","tsundoku (#32), currently-reading (#8)",currently-reading,,,,1,,,0,,,,,
```

There's no ISBN or ISBN13 for these books. Here's their Goodreads page (I don't know if it'll help):

- https://www.goodreads.com/book/show/52360057-out-past-the-stars
- https://www.goodreads.com/book/show/46017966-down-among-the-dead
- https://www.goodreads.com/book/show/36343160-there-before-the-chaos
- https://www.goodreads.com/book/show/42074525-the-city-we-became

There's no ISBN for these books on Goodreads, though I don't know why. Too many editions? Multiple formarts?

In the end, I don't think there's a lot of my books that have been affected by this bug, so it might not be too important.

**Comment by mouse-reeve** [comment]
ah yeah, in cases where there isn't an ISBN, the search function tries to pick whatever edition of the book it thinks has the best metadata - so while it prefers print editions, it could be that the audio-cd has more metadata, or had a cover image while the print edition did not. If you go to the page for the edition you want, it will show a "Switch to this edition" button which will replace that entry on your shelves and in your reading history

**Comment by joachimesque** [comment]
I see, thanks!
