### ISSUE TITLE
Potential problem with the "main" version of a book

### ISSUE THREAD

**Issue by joachimesque** [bookwyrm-social/bookwyrm#937]
1. A list of books is imported from a GoodReads export, using the "Import books" feature.
2. Some of these books don't have an ISBN, so all their version are imported, and the one with the most info is used as a "main" edition (sometimes it is the audio cd version instead of print).
3. My imported reviews are applied on the "main" edtion.
4. I go see the list of editions, and switch to a new one.
5. My "Read" shelf displays the new edition (yay).
6. My review appears at the bottom of the page for that new edition.
7. The stars rating does not appear below the cover on that new edition.
8. Adding a rating on the new edition counts as a new review for the book.
9. When looking at an author's page, the list of books shows the old "main" edition, instead of the new one that's in my shelf.

**Expected behavior**

Steps 1-8 seem logical to me. Step 9 seems illogical. Step 4 should perhaps move my review to the new selected edition.

I don't know how the "main" edition is selected as "main", but IMO the list should show the edition that's in the most shelves.

**Screenshots**

On this screenshot you can see that the last item on the list is not the edition that's in my shelves (I'm the only user on my instance, so that edition is in no other shelf). I would prefer to see the edition that's in my shelf (mainly because audio cds have square covers and it's not very harmonious)

![image](https://user-images.githubusercontent.com/1781070/114836312-cf354580-9dd2-11eb-91b1-180697d6567c.png)

**Comment by mouse-reeve** [comment]
Thank you! The star ratings not showing on the new edition should be a straightforward fix.

In search and on the author page, at the moment it isn't taking the user into account when displaying results, but it would make a lot of sense to show the edition the someone has actually interacted with! I'll need to make sure I can implement that in a way that's performant, but I think you're right that it would improve the experience

**Comment by joachimesque** [comment]
I'm not a back-end dev (I'm at the front of the front), so I may be way off:

I kinda undestood there's a `default_edition` for every book. That default could be updated when:

- The book is imported, the "default" is the version with the most info, or the most accurate (looks like it's the case right now)
- A reader interacts with any version of the book
- A reader switches editions (all their previous critiques and ratings are moved to the new version)

In the last two cases, an update is made as to which version is the default, by counting the number of shelves for each edition and/or the number of interactions, critiques, ratings…

Then you wouldn't have to change the rules for displaying the list, the default is always the most popular on the instance. Not really satisfactory for the reader if they have interacted with a non-default version, but performant.

**Comment by mouse-reeve** [comment]
I see what you mean! I don't think there's enough user interaction data at this point to make that the primary metric, but it's a good idea to make it part (and possibly a large part) of the calculation. I'm working on changing how that ranking happens as part of #892, so I'll have a more concrete sense of how to improve this once I get further on that.
