### ISSUE TITLE
Localised date is displayed in a weird format

### ISSUE THREAD

**Issue by arkhi** [bookwyrm-social/bookwyrm#948]
When visiting the [page for a book](https://bookwyrm.social/book/118780), the publication date seems off.

### Steps to reproduce the behavior:

1. Set the preferred language of your browser to French.
1. Go to the book [Le léopard des neiges ](https://bookwyrm.social/book/118780).
2. Search for “Publié”.
4. The string reads _Publié Avr 23rd 1991 par Gallimard._

### Expected behavior:

I would expect to read _Publié le 23 Avril 1991 par Gallimard._

The _le_ part could be solved with the localisation, but the ordinal `rd` and the truncation of the month are not something I would expect in French.

### Screenshots

![image](https://user-images.githubusercontent.com/277773/115110447-c59b1180-9f7b-11eb-9874-340eeeb28b2a.png)

Cc: @joachimesque

**Comment by arkhi** [comment]
The simplified Chinese also has the issue. I think it should read _1991年04月23日_ or simply 1991-04-23? Does @GuDzpoz concur? :)

![image](https://user-images.githubusercontent.com/277773/115110919-faa86380-9f7d-11eb-87bd-7bc8ffb070ec.png)

**Comment by GuDzpoz** [comment]
Yes, either will do but probably not _Apr 23rd 1991_ :P

![image](https://user-images.githubusercontent.com/14026120/115231065-a8457f00-a104-11eb-980d-195889d28042.png)
![image](https://user-images.githubusercontent.com/14026120/115232134-e8f1c800-a105-11eb-8381-42c8bbc7d9ce.png)
By the way, the date under each status doesn't seem yet localized. Could it be of the same problem?

**Comment by mouse-reeve** [comment]
Using Django's `naturalday` filter (https://docs.djangoproject.com/en/3.1/ref/contrib/humanize/) gives me, for example:

`在 Oct. 31, 2016 由 Princeton University Press 出版。` 
`Publié 31 octobre 2016 par Princeton University Press.`

It looks like the month isn't getting localized for Chinese? Which I believe is a bug in Django?

The date on statuses is a separate issue, I wrote a hyper-concise version of the `timesince` filter, but didn't think about localization. I replaced with timesince, and can live with the verbosity for the time being.

**Comment by arkhi** [comment]
> Using Django's `naturalday` filter (https://docs.djangoproject.com/en/3.1/ref/contrib/humanize/) gives me, for example:
> 
> `在 Oct. 31, 2016 由 Princeton University Press 出版。`
> `Publié 31 octobre 2016 par Princeton University Press.`
> 
> It looks like the month isn't getting localized for Chinese? Which I believe is a bug in Django?

There should be a _le_ in French, but I think this can be fixed in the locale directly as it’s consistent across dates, although _le 1 (whatever month)_ will read weird.

Not sure Chinese would write the date this way, even with a _十月_ or _10月_ for “October”. That looks like a _englified_ version. :)

I would propose changing this kind of data consistently across the application to `property: value` entries. I do like lists, as illustrated with this other [comment about a similar topic](https://github.com/bookwyrm-social/bookwyrm/pull/935/files#r618470472). :)

I’m thinking of something like:

> Première publication : **31 octobre 2010** [fake date, I have no idea]
> Publication : **31 octobre 2016**
> Éditeur :     **Princeton University Press**

**Comment by mouse-reeve** [comment]
I'm going through and closing old issues that seem stale or out of date - feel free to reopen with a comment adding some updated context if you feel like it still needs to be addressed ❤️

**Comment by arkhi** [comment]
(not really conjugating, but having to deal with articles and such…)

**Comment by mouse-reeve** [comment]
no, nothing against lists - I think that's a good fix
