### ISSUE TITLE
Menu to move the last Book in a list is cropped

### ISSUE THREAD

**Issue by arkhi** [bookwyrm-social/bookwyrm#949]
### Describe the bug

On the list of Books for a user, the menu to move the last book of the list is cropped.

### Steps to reproduce the behavior

1. Log in BookWyrm.
1. Go to your [Your books](https://bookwyrm.social/user/arkhi/books). (mine for the example)
2. Scroll (or press <kbd>End</kbd>) to reach the last Book listed on the page.
3. Click on the menu “Move book”.
4. The menu is cropped at the limit of the table, as illustrated by the attached picture.

### Expected behavior

The last menu is not cropped.

### Hint

The `.scroll-x` class on an ancestor of those menus is not allowing elements to overflow. It is defined in [bookwyrm.css:24](https://github.com/bookwyrm-social/bookwyrm/blob/797c3a12c87fcfe7167074cbab789711653d0d08/bookwyrm/static/css/bookwyrm.css#L24-L27).

### Resources

![The last “Move Book” menu is cropped](https://user-images.githubusercontent.com/277773/115113072-b373a000-9f88-11eb-9e95-867ea602fbd4.png)

**Comment by arkhi** [comment]
@mouse-reeve: Do you know why the `.scroll-x` class was added to an ancestor?

**Comment by mouse-reeve** [comment]
It's so that if the table is bigger than the screen (which is always the case on mobile), it will add a horizontal scroll bar fjust or the table, rather than making the entire app super wide.

**Comment by arkhi** [comment]
OK, thanks. Do you mind a proposal replacing the table with something more responsive?

**Comment by mouse-reeve** [comment]
Not at all! That page has needed some love for a long time.

**Comment by joachimesque** [comment]
Here's a simple proposal: #974

**Comment by arkhi** [comment]
This has been fixed by #974.
