### ISSUE TITLE
Design: Thinking of the density and hierarchy of feed elements

### ISSUE THREAD

**Issue by joachimesque** [bookwyrm-social/bookwyrm#964]
I was browsing profiles, to discover books and other like-minded readersn and that experience gave me a few remarks:

_("should" is to be taken as "the author of this issue would like if/would find a use in")_

- Feed activities should be filtered by types. I may want to see only comments or critiques.
- Feed activities should be displayed differently depending on the type.      
   Some types ("started reading a book", "finished reading a book") don't need to take much space, while other types ("wrote a comment", "wrote a critique") should be more prevalent (compared to other types), and star ratings can be easily confused with other types due to the lack of text
- Books without a description take up a whole lotta space for nothing

**Here's some rules I set:**

- We should understand the type of update at first sight
- Book previews are most useful where some context is needed: in response to a critique or a comment
- Comments and critiques should not be cut (unless they run _really_ long)
- All the actions should be grouped together

**Here's what I have in mind:**

![Desktop HD](https://user-images.githubusercontent.com/1781070/115273229-92a17b00-a13f-11eb-929f-acc8bf31c3ba.png)

Of course, it's just a very basic proposal, and can be amended. Looking at it, I'm thinking that a "Write a comment" link could be inserted at the end of the critique/comment text, so the "reply" flow is more visible.

If time allows I'll open a PR to better show what I have in mind.

**Comment by tastytea** [comment]
> Comments and critiques should not be cut (unless they run really long)

+1

I'd like [denser started and finished statuses](https://user-images.githubusercontent.com/1807695/115281905-60235e00-a0fe-11eb-84f1-5f839deb0b34.png). I think it's a good idea to [not show the book´s description on quotes and reviews](https://user-images.githubusercontent.com/1807695/115288554-67e70080-a106-11eb-9a44-6460369fe68d.png). I don't like the [book´s description on the right](https://user-images.githubusercontent.com/1807695/115286992-9663dc00-a104-11eb-8959-a1a7ea56450a.png).

**Comment by arkhi** [comment]
Interesting… The CSS logic for covers is something I left for later when documenting and cleaning frontend because covers are everywhere and I wasn’t sure of why what was coded was coded, even if some implementations are currently broken.

I might further wait to see how this Issue is evolving, I would be extremely happy with a more _densified_ version of BookWyrm for sure.

Thanks @joachimesque. :)

**Comment by mouse-reeve** [comment]
I'm interested to know more about
> Comments and critiques should not be cut (unless they run really long)

Do you mean that they should have the "show more"/"show less" buttons? I'm also a little unclear on what constitutes "really long"

**Comment by joachimesque** [comment]
> For me, having the interaction options (like, boost, reply) in the header doesn't make sense with how I read a post. When I've only looked at the header and title, I'm not ready to decide how I want to respond. Since it's an action I would do at the end of reading the post, I think it makes sense for the ui elements to be at the end as well. It's also a standard ui pattern as far as I've seen across various platforms, which makes it more familiar/legible.

Very true. One type of interaction I'd keep on the top side is the "Delete" / "Block" menus though, what do you think?

> And I'm reluctant to get rid of book previews on updates entirely - I get a lot of value from an at-a-glance look at what my friends want to read or have started reading, so seeing a cover and description in the feed is useful to me. But I totally agree that there's no need at all for it to take up the amount of space it does!

I like the compact preview, it's working better than the side card.

> Interesting… The CSS logic for covers is something I left for later when documenting and cleaning frontend because covers are everywhere and I wasn’t sure of why what was coded was coded, even if some implementations are currently broken.

I poked around last week-end, but didn't do anything of note, there are a few use cases that need special sizing rules, but the rest look pretty straightforward.

> > Comments and critiques should not be cut (unless they run really long)
> 
> Do you mean that they should have the "show more"/"show less" buttons? I'm also a little unclear on what constitutes "really long"

Well, the exact length has to be determined, but from what I've seen, most comments and critiques don't run longer than a couple of paragraphs, so a "Read more" button only unfolds a small amount of text. I would remove that click (except when it's running way too long, 4 (long) paragraphs or more).

**Comment by mouse-reeve** [comment]
Thanks all! I implemented the new status styles and made the cutoff for trimming a review much higher. The one thing I couldn't think of a good solution for was displaying user-generated content (https://user-images.githubusercontent.com/1807695/115288554-67e70080-a106-11eb-9a44-6460369fe68d.png) on mobile. I ended up just hiding the cover, which makes me a little sad because I like covers! If anyone has ideas, I'd be very interested to hear them:

<img width="238" alt="Screen Shot 2021-04-20 at 11 11 31 AM" src="https://user-images.githubusercontent.com/1807695/115444275-32efb200-a1c9-11eb-824c-4f1cdb68cd7f.png">

**Comment by arkhi** [comment]
On April 20, 2021 6:12:16 PM UTC, Mouse Reeve ***@***.***> wrote:

> If anyone has ideas, I'd be very interested to hear them

Hello…

My feeling is there is too much going on in those boxes.

I understand the header, body, footer structure, but the ratings and the actions on the book seem too much.

Removing them, I could imagine a cover that is taking the full height of the body (with a max-width to keep it from taking all the width, I guess), with space on the right to display whatever the content is.

Then a click on the link leading to the book allows to interact with the book; a separation of concerns of sort.

This needs pen and paper. :)

**Comment by mouse-reeve** [comment]
I see what you mean about visual clutter, but I think the action button is really handy and an important part of how people interact with books. I feel less strongly about showing the ratings, but I do broadly like having them? I'd be very happy to see drawings :)

**Comment by joachimesque** [comment]
What do you think about that? Denser at the top, and no need for a big huge footer.

![image](https://user-images.githubusercontent.com/1781070/115455290-103db780-a222-11eb-903b-26a4ea4fa2df.png)

**Comment by mouse-reeve** [comment]
I don't have any objection to moving the timestamp and privacy to the header, but I'm not sure there's a benefit, space-wise. As long as there's a footer, the height is the same regardless of whether it just has the interaction buttons, or if it has those plus the other items?

It's possible to remove some of the borders and padding, but I think there's a legibility benefit to have the footer set apart visually.
**Current:**
<img width="650" alt="Screen Shot 2021-04-20 at 1 22 01 PM" src="https://user-images.githubusercontent.com/1807695/115459164-984c9e80-a1db-11eb-8b38-bd504f7f5c3f.png">
**Less padding:**
<img width="656" alt="Screen Shot 2021-04-20 at 1 22 38 PM" src="https://user-images.githubusercontent.com/1807695/115459172-9aaef880-a1db-11eb-91be-1c169cdf70d3.png">

I might be misunderstanding what you're suggesting, or it may just be that the footer doesn't subjectively feel large to me in the way it does to other users?

**Comment by joachimesque** [comment]
The goal of my proposal is to reflect on a better hierarchy of the information.

Currently, we have all these elements at the same exact level:

- main actions
- status date
- privacy info
- supplementary actions

I feel that all these elements don't share the same importance. Some are more important: the main actions (currently as 3 buttons with low affordance and no text). The date and privacy info are not as primordial. The supplementary actions are of importance but less than the main actions.

The header is a good place to place the date and privacy info, smaller than the main card title. The supplementary actions are more "meta" than the main actions, and behind a click, because we think (with reason IMO) that people won't need them as much as the main actions. The main actions are best placed at the end of the content, in order to act upon what the content compels us to: commenting, boosting or adding to favourites are what we expect people to do—and what people expect to be able to do.

I don't think there's a need for a footer, per se. My proposal doesn't densify the header it too much. Here's a little improvement to my previous mockup, to better see how the three small buttons could populate a larger space, without feeling lost.

![image](https://user-images.githubusercontent.com/1781070/115462558-11271700-a22b-11eb-943b-363196302444.png)

By placing the actions at the same level as the content of the status they're less disconnected.

(and re-reading my first message, I don't know if it's wise to group all the actions, but we could add the supplementary actions as fourth button if we wanted to)

What I haven't gotten into, and what I've been thinking about since I opened this issue, is that some feed elements have to appear as cards, while some could be displayed in a more subdued manner, without a card, but still with the same information. The way I see it, cards would be for content-rich updates, non-cards would fit one-line updates: reading activity, etc.

**Comment by mouse-reeve** [comment]
I see! That makes sense. I agree about the privacy and timestamp, but I'm less sure about the "more options," I feel like the same justification for keeping the interaction buttons at the bottom stills applies -- they're things I'd only want to do after having read the status.

**Comment by joachimesque** [comment]
I opened #971 with some of the fixes. Here's what it looks like:

![image](https://user-images.githubusercontent.com/1781070/115581942-c1972880-a2c8-11eb-8a15-63b68b1b8f2f.png)

**Comment by arkhi** [comment]
> I see what you mean about visual clutter, but I think the action button is really handy and an important part of how people interact with books. I feel less strongly about showing the ratings, but I do broadly like having them? I'd be very happy to see drawings :)

I understand the need for interaction.

I was thinking those interactions could be toned-down when the book is not the object being evaluated? Maybe the dropdown could actually be just the arrow with actions, including rating?

**Comment by arkhi** [comment]
> Maybe the dropdown could actually be just the arrow with actions, including rating?

![image](https://user-images.githubusercontent.com/277773/115745580-dbea0880-a393-11eb-915d-aed7df960469.png)

**Comment by mouse-reeve** [comment]
I'm super appreciative of this conversation and all the work that's already come out of it! At this point, I'm finding it a little hard to keep track of all the different proposals and ideas. How would you all feel about considering this issue closed by #971, and starting new, separate issues for additional changes on top of that?

My understanding of what's still up in the air is:
 - Changing how the rating and interactions show up on book previews in the review/commen/quote type status
 - Further de-emphasizing or changing the style of book activity statuses (like "wants to read")

**Comment by arkhi** [comment]
Sure. Next thing I would like to do is have a look at the covers, mostly to understand what has been done CSS wise and how.
