### ISSUE TITLE
Allow book info to include links to personal servers for file sharing

### ISSUE THREAD

**Issue by andpersand** [bookwyrm-social/bookwyrm#97]
It might be useful to have some way for users to find a link to download ebook, audiobook, or PDF files. This could also allow people to more easily share zines and community-made things that might be difficult to find otherwise.

**Comment by mouse-reeve** [comment]
Yes! thank you!

I think this is related to but not a duplicate of #57, wrt integrating with overdriver, openlibrary loans, and internet archive ebooks

**Comment by mouse-reeve** [comment]
also related to #54
