### ISSUE TITLE
More granular reviews and tagging?

### ISSUE THREAD

**Issue by vitorio** [bookwyrm-social/bookwyrm#98]
Following up from a recent newsletter, which writes:

> Right now, you can update your reading progress, tag books, leave comments, and write more traditional reviews with 5 star ratings. 

Books that are collections (fiction collections, poetry collections, cookbooks, non-fiction textbooks, journals, books of plans, etc.) would benefit from being able to tag, review, and comment at the "chapter" or other subdivided content level.

**Comment by mouse-reeve** [comment]
I'm going to close this because I think the page/percent tagging roughly addresses this, and since this issue is nearly two years old, it would make more sense to re-evaluate addition needs around this from a fresh perspective. Thank you for filing!
